import {Router,Request,Response,NextFunction} from "express";
import pool from "../db";import{requireAuth,AuthRequest}from"../middleware/auth";import{ensureHrV2}from"../hr/ensureHrV2";
const router=Router();router.use(requireAuth);const asyncRoute=(fn:(req:any,res:Response)=>Promise<any>)=>(req:Request,res:Response,next:NextFunction)=>fn(req,res).catch(next);
function rolesOf(req:AuthRequest){const raw:any=req.user?.role;if(Array.isArray(raw))return raw.map(String);try{const p=JSON.parse(String(raw||""));return Array.isArray(p)?p.map(String):[String(p)]}catch{return String(raw||"").split(",").map(x=>x.replace(/[\[\]"]/g,"").trim()).filter(Boolean)}}
function adminOnly(req:AuthRequest,res:Response,next:NextFunction){if(rolesOf(req).map(x=>x.toLowerCase()).includes("admin"))return next();return res.status(403).json({error:"Ehhez a művelethez rendszergazdai jogosultság szükséges."})}
router.use(adminOnly);
router.get("/roles",asyncRoute(async(_req,res)=>{await ensureHrV2();const{rows}=await pool.query("SELECT * FROM access_roles ORDER BY level DESC,name");res.json(rows)}));
router.post("/roles",asyncRoute(async(req,res)=>{await ensureHrV2();const b=req.body||{};if(!b.role_key||!b.name)return res.status(400).json({error:"A szerepkör kulcsa és neve kötelező."});const{rows}=await pool.query(`INSERT INTO access_roles(role_key,name,description,level,is_active) VALUES(lower($1),$2,$3,COALESCE($4,10),COALESCE($5,true)) RETURNING *`,[b.role_key,b.name,b.description||null,b.level,b.is_active]);res.status(201).json(rows[0])}));
router.patch("/roles/:id",asyncRoute(async(req,res)=>{await ensureHrV2();const b=req.body||{};const{rows}=await pool.query(`UPDATE access_roles SET name=COALESCE($2,name),description=$3,level=COALESCE($4,level),is_active=COALESCE($5,is_active),updated_at=now() WHERE id=$1 RETURNING *`,[req.params.id,b.name||null,b.description||null,b.level,b.is_active]);res.json(rows[0])}));
router.get("/matrix",asyncRoute(async(_req,res)=>{await ensureHrV2();const[roles,menus,permissions]=await Promise.all([pool.query("SELECT * FROM access_roles WHERE is_active ORDER BY level DESC,name"),pool.query(`SELECT id,code,name,parent_id,route,order_index,feature_key FROM menus WHERE COALESCE(is_active,true) ORDER BY COALESCE(parent_id,0),order_index,id`),pool.query("SELECT * FROM role_menu_permissions")]);res.json({roles:roles.rows,menus:menus.rows,permissions:permissions.rows})}));
router.put("/roles/:roleKey/permissions",asyncRoute(async(req,res)=>{await ensureHrV2();const roleKey=String(req.params.roleKey).toLowerCase();if(roleKey==="admin")return res.status(400).json({error:"A rendszergazdai teljes hozzáférés nem korlátozható."});const updates=Array.isArray(req.body)?req.body:[];const client=await pool.connect();try{await client.query("BEGIN");for(const p of updates)await client.query(`INSERT INTO role_menu_permissions(role_key,menu_id,can_view,can_create,can_edit,can_delete,can_approve,can_export,can_view_financial,can_manage_permissions,scope_type,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,COALESCE($11,'own_location'),now()) ON CONFLICT(role_key,menu_id) DO UPDATE SET can_view=EXCLUDED.can_view,can_create=EXCLUDED.can_create,can_edit=EXCLUDED.can_edit,can_delete=EXCLUDED.can_delete,can_approve=EXCLUDED.can_approve,can_export=EXCLUDED.can_export,can_view_financial=EXCLUDED.can_view_financial,can_manage_permissions=EXCLUDED.can_manage_permissions,scope_type=EXCLUDED.scope_type,updated_at=now()`,[roleKey,p.menu_id,!!p.can_view,!!p.can_create,!!p.can_edit,!!p.can_delete,!!p.can_approve,!!p.can_export,!!p.can_view_financial,!!p.can_manage_permissions,p.scope_type||"own_location"]);await client.query("COMMIT");res.json({success:true})}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}));
export default router;
