import {Router,Request,Response,NextFunction} from "express";
import pool from "../db";
import {requireAuth,AuthRequest}from"../middleware/auth";
import {normalizeRoleKey,parseRoleKeys}from"../security/roles";

const router=Router();router.use(requireAuth);
const asyncRoute=(fn:(req:any,res:Response)=>Promise<any>)=>(req:Request,res:Response,next:NextFunction)=>fn(req,res).catch(next);
const FEATURE_DEFINITIONS=[
 {feature_key:"finance",name:"Pénzügy és pénztár",description:"Pénzügyi lezárás, kassza, fizetések és napi zárás"},
 {feature_key:"product_sale",name:"Termékeladás",description:"Termék értékesítése szolgáltatási munkalap nélkül"},
 {feature_key:"hr",name:"HR adatok",description:"Munkatársak, szerződések, bérezés és HR nyilvántartások"},
 {feature_key:"ai_use",name:"AI Segítő használata",description:"Kleo AI Segítő kérdezése"},{feature_key:"ai_stats",name:"AI statisztika",description:"AI használati és költségstatisztika megtekintése"},
 {feature_key:"staff_chat",name:"Munkatársi chat",description:"Saját belső beszélgetések használata"},{feature_key:"staff_chat_all",name:"Teljes chat felügyelet",description:"Adminisztratív rálátás minden munkatársi beszélgetésre"},
 {feature_key:"inventory",name:"Raktár és készlet",description:"Készlet, mozgások és készletérték kezelése"},{feature_key:"procurement",name:"Beszerzés",description:"Beszállítók, rendelési javaslatok, rendelések és jóváhagyások"},
 {feature_key:"management_dashboard",name:"Vezetői dashboard",description:"Vezetői KPI-k, bevétel és teljesítménymutatók"},{feature_key:"audit",name:"Audit napló",description:"Rendszer- és üzleti eseménynapló megtekintése"}
];
const HOME_ITEMS=[
 {key:'appointments',name:'Időpontnaptár',description:'Naptár, foglalások és érkeztetés',route:'/appointments/calendar',permission:'appointments'},
 {key:'workorders',name:'Munkalapok',description:'Szolgáltatási munkalapok kezelése',route:'/workorders',permission:'workorders'},
 {key:'product_sale',name:'Termékeladás',description:'Termék eladása munkalap nélkül',route:'/finance/product-sale',permission:'product_sale'},
 {key:'clients',name:'Vendégek / CRM',description:'Vendégadatok, címkék és előzmények',route:'/modules/customers/clients',permission:'clients'},
 {key:'cashier',name:'Pénztár',description:'Fizetések és pénztári műveletek',route:'/finance/cashier',permission:'cashier'},
 {key:'staff_chat',name:'Munkatársi chat',description:'Belső kommunikáció',route:'/staff/chat',permission:'staff_chat'},
 {key:'inventory',name:'Raktár és készlet',description:'Készlet és raktári műveletek',route:'/warehouse',permission:'inventory'},
 {key:'finance',name:'Pénzügyek',description:'Pénzügyi központ és kimutatások',route:'/finance',permission:'finance'},
 {key:'reports',name:'Riportok',description:'Vezetői és üzleti riportok',route:'/reports/top-metrics',permission:'reports'},
 {key:'hr',name:'Munkatársak / HR',description:'HR és munkatársi adatok',route:'/employees',permission:'hr'},
 {key:'checklists',name:'Checklisták',description:'Napi és munkaköri ellenőrzőlisták',route:'/knowledge-base/checklists',permission:'checklists'}
];
function rolesOf(req:AuthRequest){return parseRoleKeys(req.user?.role)}function adminOnly(req:AuthRequest,res:Response,next:NextFunction){if(rolesOf(req).includes("admin"))return next();return res.status(403).json({error:"Ehhez a művelethez rendszergazdai jogosultság szükséges."})}
const scopeRank:Record<string,number>={own:0,own_location:1,selected_locations:2,all_locations:3};const strongestScope=(values:string[])=>values.sort((a,b)=>(scopeRank[b]??0)-(scopeRank[a]??0))[0]||"own_location";
async function ensureEmployeeUiSchema(){await pool.query(`CREATE TABLE IF NOT EXISTS employee_ui_permissions(employee_id text NOT NULL,permission_key text NOT NULL,can_use boolean NOT NULL,updated_at timestamptz NOT NULL DEFAULT now(),updated_by text,PRIMARY KEY(employee_id,permission_key));CREATE TABLE IF NOT EXISTS employee_home_items(employee_id text NOT NULL,item_key text NOT NULL,is_visible boolean NOT NULL,sort_order integer NOT NULL DEFAULT 100,updated_at timestamptz NOT NULL DEFAULT now(),updated_by text,PRIMARY KEY(employee_id,item_key));`)}
function simpleRoles(raw:any){try{const p=JSON.parse(String(raw||''));if(Array.isArray(p))return p.map(String).map(x=>x.toLowerCase())}catch{}return String(raw||'').split(',').map(x=>x.replace(/[\[\]"]/g,'').trim().toLowerCase()).filter(Boolean)}
function defaultSimplePermission(rs:string[],key:string){if(rs.includes('admin'))return true;const rec=rs.some(r=>['receptionist','reception','recepciós','recepcios'].includes(r)),mg=rs.some(r=>['manager','location_manager','salon_manager','szalonvezető','szalonvezeto','üzletvezető','uzletvezeto'].includes(r)),emp=rs.some(r=>['employee','staff','munkatárs','munkatars','professional','specialist'].includes(r));if(rec)return ['appointments','workorders','product_sale','clients','cashier','staff_chat','checklists'].includes(key);if(mg)return true;if(emp)return ['appointments','workorders','staff_chat','checklists'].includes(key);return false}
async function employeeRow(id:string){return (await pool.query(`SELECT e.id::text id,COALESCE(NULLIF(to_jsonb(e)->>'full_name',''),NULLIF(to_jsonb(e)->>'name',''),NULLIF(to_jsonb(e)->>'email',''),'Munkatárs') name,to_jsonb(e)->>'email' email,to_jsonb(e)->>'role' role,to_jsonb(e)->>'location_id' location_id,COALESCE(l.name,'') location_name FROM employees e LEFT JOIN locations l ON l.id::text=(to_jsonb(e)->>'location_id') WHERE e.id::text=$1 LIMIT 1`,[id])).rows[0]||null}
async function employeeUiProfile(id:string,rs:string[]){await ensureEmployeeUiSchema();const[ps,hs]=await Promise.all([pool.query(`SELECT permission_key,can_use FROM employee_ui_permissions WHERE employee_id=$1`,[id]),pool.query(`SELECT item_key,is_visible,sort_order FROM employee_home_items WHERE employee_id=$1`,[id])]);const pm=new Map(ps.rows.map((x:any)=>[String(x.permission_key),Boolean(x.can_use)])),hm=new Map(hs.rows.map((x:any)=>[String(x.item_key),x]));const keys=Array.from(new Set(HOME_ITEMS.map(x=>x.permission)));const permissions=keys.map(key=>({key,name:HOME_ITEMS.find(x=>x.permission===key)?.name||key,can_use:pm.has(key)?Boolean(pm.get(key)):defaultSimplePermission(rs,key),overridden:pm.has(key)}));const can=new Map(permissions.map(x=>[x.key,x.can_use]));const items=HOME_ITEMS.map((x,i)=>{const o=hm.get(x.key);return{...x,is_visible:(o?Boolean(o.is_visible):defaultSimplePermission(rs,x.permission))&&Boolean(can.get(x.permission)),sort_order:o?Number(o.sort_order):i*10,overridden:Boolean(o)}}).sort((a,b)=>a.sort_order-b.sort_order);return{permissions,items}}

router.get("/me/features",asyncRoute(async(req:AuthRequest,res)=>{const roles=rolesOf(req);if(roles.includes("admin"))return res.json({admin:true,features:FEATURE_DEFINITIONS.map(f=>({...f,can_use:true,scope_type:"all_locations"}))});const {rows}=await pool.query(`SELECT role_key,feature_key,can_use,scope_type FROM role_feature_permissions WHERE lower(role_key)=ANY($1::text[])`,[roles]);const grouped=new Map<string,any[]>();for(const row of rows){const list=grouped.get(row.feature_key)||[];list.push(row);grouped.set(row.feature_key,list)}res.json({admin:false,features:FEATURE_DEFINITIONS.map(f=>{const list=grouped.get(f.feature_key)||[];const allowed=list.filter(x=>x.can_use);const defaultProduct=f.feature_key==='product_sale'&&roles.some(r=>['receptionist','reception','recepciós','recepcios'].includes(r));return{...f,configured:list.length>0,can_use:allowed.length>0||defaultProduct,scope_type:strongestScope(allowed.map(x=>String(x.scope_type||"own_location")))}})})}));
router.get("/me/ui-profile",asyncRoute(async(req:AuthRequest,res)=>{const id=String(req.user?.id||'');if(!id)return res.status(401).json({error:'Nincs bejelentkezett munkatárs.'});const row=await employeeRow(id);const rs=row?simpleRoles(row.role):rolesOf(req);res.json({employee:row||{id,role:req.user?.role},...(await employeeUiProfile(id,rs))})}));
router.get("/me/capabilities",asyncRoute(async(req:AuthRequest,res)=>{const roles=rolesOf(req),admin=roles.includes("admin"),menus=(await pool.query(`SELECT id,code,name,parent_id,route,feature_key FROM menus WHERE COALESCE(is_active,true)=true ORDER BY order_index,id`)).rows,locations=(await pool.query(`SELECT id,name,city FROM locations WHERE COALESCE(is_active,true)=true ORDER BY city,name`)).rows;if(admin)return res.json({admin:true,roles,allowed_location_ids:locations.map((x:any)=>String(x.id)),features:Object.fromEntries(FEATURE_DEFINITIONS.map(f=>[f.feature_key,{can_use:true,scope_type:"all_locations"}])),menus:Object.fromEntries(menus.map((m:any)=>[m.code,{menu_id:m.id,code:m.code,configured:true,can_view:true,can_create:true,can_edit:true,can_delete:true,can_approve:true,can_export:true,can_view_financial:true,can_manage_permissions:true,scope_type:"all_locations"}]))});const[fp,mp,lp]=await Promise.all([pool.query(`SELECT feature_key,can_use,scope_type FROM role_feature_permissions WHERE lower(role_key)=ANY($1::text[])`,[roles]),pool.query(`SELECT p.*,m.code FROM role_menu_permissions p JOIN menus m ON m.id=p.menu_id WHERE lower(p.role_key)=ANY($1::text[]) AND COALESCE(m.is_active,true)=true`,[roles]),pool.query(`SELECT location_id FROM role_location_permissions WHERE lower(role_key)=ANY($1::text[]) AND can_access=true`,[roles])]);const features:Record<string,any>={};for(const f of FEATURE_DEFINITIONS){const list=fp.rows.filter((x:any)=>x.feature_key===f.feature_key),allowed=list.filter((x:any)=>x.can_use);features[f.feature_key]={configured:list.length>0,can_use:allowed.length>0||(f.feature_key==='product_sale'&&roles.some(r=>['receptionist','reception','recepciós','recepcios'].includes(r))),scope_type:strongestScope(allowed.map((x:any)=>String(x.scope_type||"own_location")))};}const menuCaps:Record<string,any>={};for(const menu of menus){const list=mp.rows.filter((x:any)=>Number(x.menu_id)===Number(menu.id));if(!list.length){menuCaps[menu.code]={menu_id:menu.id,code:menu.code,configured:false,can_view:false,can_create:false,can_edit:false,can_delete:false,can_approve:false,can_export:false,can_view_financial:false,can_manage_permissions:false,scope_type:"own_location"};continue}const keys=["can_view","can_create","can_edit","can_delete","can_approve","can_export","can_view_financial","can_manage_permissions"],cap:any={menu_id:menu.id,code:menu.code,configured:true};for(const key of keys)cap[key]=list.some((x:any)=>x[key]===true);cap.scope_type=strongestScope(list.filter((x:any)=>x.can_view).map((x:any)=>String(x.scope_type||"own_location")));menuCaps[menu.code]=cap}res.json({admin:false,roles,allowed_location_ids:Array.from(new Set(lp.rows.map((x:any)=>String(x.location_id)))),features,menus:menuCaps})}));

router.use(adminOnly);
router.get('/employees-ui',asyncRoute(async(_req,res)=>{await ensureEmployeeUiSchema();const q=await pool.query(`SELECT e.id::text id,COALESCE(NULLIF(to_jsonb(e)->>'full_name',''),NULLIF(to_jsonb(e)->>'name',''),NULLIF(to_jsonb(e)->>'email',''),'Munkatárs') name,to_jsonb(e)->>'email' email,to_jsonb(e)->>'role' role,to_jsonb(e)->>'location_id' location_id,COALESCE(l.name,'') location_name FROM employees e LEFT JOIN locations l ON l.id::text=(to_jsonb(e)->>'location_id') WHERE COALESCE((to_jsonb(e)->>'active')::boolean,true)=true ORDER BY lower(COALESCE(NULLIF(to_jsonb(e)->>'full_name',''),NULLIF(to_jsonb(e)->>'name',''),'')) LIMIT 5000`);res.json({employees:q.rows,items:HOME_ITEMS})}));
router.get('/employees-ui/:id',asyncRoute(async(req,res)=>{const row=await employeeRow(req.params.id);if(!row)return res.status(404).json({error:'A munkatárs nem található.'});res.json({employee:row,...(await employeeUiProfile(String(row.id),simpleRoles(row.role)))})}));
router.put('/employees-ui/:id',asyncRoute(async(req:AuthRequest,res)=>{const row=await employeeRow(req.params.id);if(!row)return res.status(404).json({error:'A munkatárs nem található.'});await ensureEmployeeUiSchema();const c=await pool.connect();try{const permissions=Array.isArray(req.body?.permissions)?req.body.permissions:[],items=Array.isArray(req.body?.items)?req.body.items:[],allowedP=new Set(HOME_ITEMS.map(x=>x.permission)),allowedI=new Set(HOME_ITEMS.map(x=>x.key));await c.query('BEGIN');await c.query(`DELETE FROM employee_ui_permissions WHERE employee_id=$1`,[req.params.id]);for(const p of permissions){const key=String(p?.key||'');if(allowedP.has(key))await c.query(`INSERT INTO employee_ui_permissions(employee_id,permission_key,can_use,updated_by) VALUES($1,$2,$3,$4)`,[req.params.id,key,Boolean(p.can_use),req.user?.email||String(req.user?.id||'')])}await c.query(`DELETE FROM employee_home_items WHERE employee_id=$1`,[req.params.id]);for(let i=0;i<items.length;i++){const x=items[i],key=String(x?.key||'');if(allowedI.has(key))await c.query(`INSERT INTO employee_home_items(employee_id,item_key,is_visible,sort_order,updated_by) VALUES($1,$2,$3,$4,$5)`,[req.params.id,key,Boolean(x.is_visible),Number.isFinite(Number(x.sort_order))?Number(x.sort_order):i*10,req.user?.email||String(req.user?.id||'')])}await c.query('COMMIT');res.json({ok:true,employee:row,...(await employeeUiProfile(req.params.id,simpleRoles(row.role)))})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}));
router.get("/roles",asyncRoute(async(_req,res)=>{const{rows}=await pool.query("SELECT * FROM access_roles ORDER BY level DESC,name");res.json(rows)}));
router.post("/roles",asyncRoute(async(req,res)=>{const b=req.body||{};if(!b.role_key||!b.name)return res.status(400).json({error:"A szerepkör kulcsa és neve kötelező."});const roleKey=normalizeRoleKey(b.role_key);const{rows}=await pool.query(`INSERT INTO access_roles(role_key,name,description,level,is_active) VALUES($1,$2,$3,COALESCE($4,10),COALESCE($5,true)) RETURNING *`,[roleKey,b.name,b.description||null,b.level,b.is_active]);res.status(201).json(rows[0])}));
router.patch("/roles/:id",asyncRoute(async(req,res)=>{const b=req.body||{};const{rows}=await pool.query(`UPDATE access_roles SET name=COALESCE($2,name),description=$3,level=COALESCE($4,level),is_active=COALESCE($5,is_active),updated_at=now() WHERE id=$1 RETURNING *`,[req.params.id,b.name||null,b.description||null,b.level,b.is_active]);res.json(rows[0])}));
router.get("/matrix",asyncRoute(async(_req,res)=>{const[roles,menus,permissions,featurePermissions,locations,locationPermissions]=await Promise.all([pool.query("SELECT * FROM access_roles WHERE is_active ORDER BY level DESC,name"),pool.query(`SELECT id,code,name,parent_id,route,order_index,feature_key FROM menus WHERE COALESCE(is_active,true) ORDER BY COALESCE(parent_id,0),order_index,id`),pool.query("SELECT * FROM role_menu_permissions"),pool.query("SELECT * FROM role_feature_permissions"),pool.query(`SELECT id,name,city,address FROM locations WHERE COALESCE(is_active,true)=true ORDER BY city,name`),pool.query(`SELECT role_key,location_id,can_access FROM role_location_permissions`)]);res.json({roles:roles.rows,menus:menus.rows,permissions:permissions.rows,features:FEATURE_DEFINITIONS,feature_permissions:featurePermissions.rows,locations:locations.rows,location_permissions:locationPermissions.rows})}));
router.put("/roles/:roleKey/permissions",asyncRoute(async(req,res)=>{const roleKey=normalizeRoleKey(req.params.roleKey);if(roleKey==="admin")return res.status(400).json({error:"A rendszergazdai teljes hozzáférés nem korlátozható."});const updates=Array.isArray(req.body)?req.body:[],client=await pool.connect();try{await client.query("BEGIN");for(const p of updates)await client.query(`INSERT INTO role_menu_permissions(role_key,menu_id,can_view,can_create,can_edit,can_delete,can_approve,can_export,can_view_financial,can_manage_permissions,scope_type,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,COALESCE($11,'own_location'),now()) ON CONFLICT(role_key,menu_id) DO UPDATE SET can_view=EXCLUDED.can_view,can_create=EXCLUDED.can_create,can_edit=EXCLUDED.can_edit,can_delete=EXCLUDED.can_delete,can_approve=EXCLUDED.can_approve,can_export=EXCLUDED.can_export,can_view_financial=EXCLUDED.can_view_financial,can_manage_permissions=EXCLUDED.can_manage_permissions,scope_type=EXCLUDED.scope_type,updated_at=now()`,[roleKey,p.menu_id,!!p.can_view,!!p.can_create,!!p.can_edit,!!p.can_delete,!!p.can_approve,!!p.can_export,!!p.can_view_financial,!!p.can_manage_permissions,p.scope_type||"own_location"]);await client.query("COMMIT");res.json({success:true})}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}));
router.put("/roles/:roleKey/features",asyncRoute(async(req,res)=>{const roleKey=normalizeRoleKey(req.params.roleKey);if(roleKey==="admin")return res.status(400).json({error:"A rendszergazdai teljes hozzáférés nem korlátozható."});const updates=Array.isArray(req.body)?req.body:[],allowed=new Set(FEATURE_DEFINITIONS.map(x=>x.feature_key)),client=await pool.connect();try{await client.query("BEGIN");for(const p of updates){const key=String(p.feature_key||"");if(allowed.has(key))await client.query(`INSERT INTO role_feature_permissions(role_key,feature_key,can_use,scope_type,updated_at) VALUES($1,$2,$3,$4,now()) ON CONFLICT(role_key,feature_key) DO UPDATE SET can_use=EXCLUDED.can_use,scope_type=EXCLUDED.scope_type,updated_at=now()`,[roleKey,key,!!p.can_use,p.scope_type||"own_location"])}await client.query("COMMIT");res.json({success:true})}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}));
router.put("/roles/:roleKey/locations",asyncRoute(async(req,res)=>{const roleKey=normalizeRoleKey(req.params.roleKey);if(roleKey==="admin")return res.status(400).json({error:"A rendszergazda minden telephelyhez hozzáfér."});const ids=(Array.isArray(req.body?.location_ids)?req.body.location_ids:[]).map((x:any)=>String(x)).filter(Boolean),client=await pool.connect();try{await client.query("BEGIN");await client.query(`DELETE FROM role_location_permissions WHERE role_key=$1`,[roleKey]);for(const id of ids)await client.query(`INSERT INTO role_location_permissions(role_key,location_id,can_access,updated_at) VALUES($1,$2,true,now()) ON CONFLICT(role_key,location_id) DO UPDATE SET can_access=true,updated_at=now()`,[roleKey,id]);await client.query("COMMIT");res.json({success:true,location_ids:ids})}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}));
export default router;
