import {Router} from"express";
import db from"../db";
import ensureBookingV4 from"../booking/ensureBookingV4";
const publicRouter=Router(),adminRouter=Router();
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const id=(v:any)=>UUID.test(String(v||""))?String(v):null;
async function ensure(){await ensureBookingV4();await db.query(`CREATE TABLE IF NOT EXISTS booking_funnel_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),session_id text NOT NULL,event_name text NOT NULL,location_id uuid REFERENCES locations(id) ON DELETE SET NULL,employee_id uuid REFERENCES employees(id) ON DELETE SET NULL,recommendation_id uuid REFERENCES booking_service_recommendations(id) ON DELETE SET NULL,service_ids jsonb NOT NULL DEFAULT '[]'::jsonb,metadata jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now());CREATE INDEX IF NOT EXISTS idx_booking_funnel_events_created ON booking_funnel_events(created_at DESC);CREATE INDEX IF NOT EXISTS idx_booking_funnel_events_session ON booking_funnel_events(session_id,created_at);`)}
publicRouter.use(async(_q,r,n)=>{try{await ensure();n()}catch(e:any){r.status(500).json({error:"Booking analytics init hiba",detail:e?.message})}});
publicRouter.post("/v4/funnel-event",async(req,res)=>{try{const session=String(req.body?.session_id||"").slice(0,120),event=String(req.body?.event_name||"").slice(0,80);if(!session||!event)return res.status(400).json({error:"session_id és event_name szükséges"});const serviceIds=Array.isArray(req.body?.service_ids)?req.body.service_ids.filter((x:any)=>UUID.test(String(x))).slice(0,12):[];await db.query(`INSERT INTO booking_funnel_events(session_id,event_name,location_id,employee_id,recommendation_id,service_ids,metadata) VALUES($1,$2,$3::uuid,$4::uuid,$5::uuid,$6::jsonb,$7::jsonb)`,[session,event,id(req.body?.location_id),id(req.body?.employee_id),id(req.body?.recommendation_id),JSON.stringify(serviceIds),JSON.stringify(req.body?.metadata||{})]);res.status(204).end()}catch(e:any){res.status(500).json({error:"Esemény mentési hiba",detail:e?.message})}});
adminRouter.use(async(_q,r,n)=>{try{await ensure();n()}catch(e:any){r.status(500).json({error:"Booking growth init hiba",detail:e?.message})}});
adminRouter.get("/growth/analytics",async(req,res)=>{try{const days=Math.max(1,Math.min(365,Number(req.query.days||30))),loc=id(req.query.location_id);const [funnel,recs,opps,taxonomy]=await Promise.all([
 db.query(`SELECT event_name,count(*)::int events,count(DISTINCT session_id)::int sessions FROM booking_funnel_events WHERE created_at>=now()-($2::text||' days')::interval AND ($1::uuid IS NULL OR location_id=$1::uuid) GROUP BY event_name ORDER BY events DESC`,[loc,days]),
 db.query(`SELECT r.id,r.recommendation_type,r.label,s1.name source_service,s2.name recommended_service,l.name location_name,COALESCE(v.views,0)::int views,COALESCE(c.clicks,0)::int clicks,COALESCE(b.bookings,0)::int bookings FROM booking_service_recommendations r JOIN services s1 ON s1.id=r.source_service_id JOIN services s2 ON s2.id=r.recommended_service_id LEFT JOIN locations l ON l.id=r.location_id LEFT JOIN LATERAL(SELECT count(DISTINCT e.session_id) views FROM booking_funnel_events e WHERE e.recommendation_id=r.id AND e.event_name='recommendation_viewed' AND e.created_at>=now()-($2::text||' days')::interval)v ON true LEFT JOIN LATERAL(SELECT count(DISTINCT e.session_id) clicks FROM booking_funnel_events e WHERE e.recommendation_id=r.id AND e.event_name='recommendation_clicked' AND e.created_at>=now()-($2::text||' days')::interval)c ON true LEFT JOIN LATERAL(SELECT count(DISTINCT e.session_id) bookings FROM booking_funnel_events e WHERE e.recommendation_id=r.id AND e.event_name='recommendation_clicked' AND e.created_at>=now()-($2::text||' days')::interval AND EXISTS(SELECT 1 FROM booking_funnel_events bfe WHERE bfe.session_id=e.session_id AND bfe.event_name='booking_completed' AND bfe.created_at>=e.created_at AND bfe.created_at<e.created_at+interval '1 day'))b ON true WHERE ($1::uuid IS NULL OR r.location_id=$1::uuid OR r.location_id IS NULL) ORDER BY views DESC,clicks DESC`,[loc,days]),
 db.query(`SELECT o.location_id,l.name location_name,o.service_id,s.name service_name,count(*)::int open_slots,round(avg(o.discount_percent))::int avg_discount,round(sum(o.original_price))::numeric gross_capacity_value,round(sum(o.original_price-o.offer_price))::numeric discount_cost FROM booking_last_minute_offers o JOIN locations l ON l.id=o.location_id JOIN services s ON s.id=o.service_id WHERE o.status='active' AND o.expires_at>now() AND o.start_time>now() AND ($1::uuid IS NULL OR o.location_id=$1::uuid) GROUP BY o.location_id,l.name,o.service_id,s.name ORDER BY gross_capacity_value DESC`,[loc]),
 db.query(`SELECT CASE WHEN lower(COALESCE(st.name,'')||' '||s.name) ~ '(haj|fodr|balayage|melír|dauer)' THEN 'Fodrászat' WHEN lower(COALESCE(st.name,'')||' '||s.name) ~ '(manik|pedik|köröm|gél ?lakk|kéz|láb)' THEN 'Kéz- és lábápolás' WHEN lower(COALESCE(st.name,'')||' '||s.name) ~ '(masszázs|massage)' THEN 'Masszázs' ELSE 'Kozmetika' END department,COALESCE(st.name,'Egyéb') category,count(*)::int services,jsonb_agg(jsonb_build_object('id',s.id,'name',s.name,'duration',COALESCE(s.duration_minutes,30)) ORDER BY s.name) items FROM services s LEFT JOIN service_types st ON st.id=s.service_type_id WHERE COALESCE(s.is_active,true)=true GROUP BY department,category ORDER BY department,category`)
]);const map:any={};for(const x of funnel.rows)map[x.event_name]=x.sessions;const viewed=Number(map.booking_page_view||0),selected=Number(map.service_selected||0),searched=Number(map.availability_viewed||0),started=Number(map.booking_started||0),completed=Number(map.booking_completed||0);res.json({period_days:days,funnel:{viewed,selected,searched,started,completed,view_to_service:viewed?selected/viewed:0,service_to_search:selected?searched/selected:0,search_to_start:searched?started/searched:0,start_to_complete:started?completed/started:0,overall:viewed?completed/viewed:0},events:funnel.rows,recommendations:recs.rows.map((x:any)=>({...x,ctr:Number(x.views)?Number(x.clicks)/Number(x.views):0,conversion:Number(x.clicks)?Number(x.bookings)/Number(x.clicks):0})),capacity_opportunities:opps.rows,taxonomy:taxonomy.rows})}catch(e:any){res.status(500).json({error:"Growth analytics hiba",detail:e?.message})}});
adminRouter.post("/staff-profiles/:employeeId/portfolio",async(req,res)=>{try{const employee=id(req.params.employeeId),url=String(req.body?.image_url||"").trim();if(!employee||!/^https?:\/\//i.test(url))return res.status(400).json({error:"Érvényes szakember és kép URL szükséges."});const q=await db.query(`INSERT INTO employee_reference_photos(employee_id,image_url,caption,sort_order,is_active) VALUES($1::uuid,$2,$3,$4,true) RETURNING *`,[employee,url,String(req.body?.caption||"").trim()||null,Number(req.body?.sort_order||0)]);res.status(201).json({photo:q.rows[0]})}catch(e:any){res.status(500).json({error:"Referenciafotó mentési hiba",detail:e?.message})}});
adminRouter.delete("/staff-profiles/:employeeId/portfolio/:photoId",async(req,res)=>{try{const employee=id(req.params.employeeId),photo=id(req.params.photoId);if(!employee||!photo)return res.status(400).json({error:"Érvénytelen azonosító."});await db.query(`UPDATE employee_reference_photos SET is_active=false WHERE id=$1::uuid AND employee_id=$2::uuid`,[photo,employee]);res.status(204).end()}catch(e:any){res.status(500).json({error:"Referenciafotó törlési hiba",detail:e?.message})}});
export{publicRouter as bookingV4GrowthPublicRouter,adminRouter as bookingV4GrowthAdminRouter};
