import { Router } from "express";
import db from "../db";

const router=Router();
const num=(v:any)=>Number(v||0);
const actor=(req:any)=>req.user?.email||String(req.user?.id||"");

async function ensureSchema(){
 await db.query(`CREATE EXTENSION IF NOT EXISTS pgcrypto;
 CREATE TABLE IF NOT EXISTS salon_stock_requests(
   id uuid PRIMARY KEY DEFAULT gen_random_uuid(), location_id uuid NOT NULL REFERENCES locations(id), product_id uuid NOT NULL REFERENCES products(id),
   requested_quantity numeric(14,3) NOT NULL CHECK(requested_quantity>0), approved_quantity numeric(14,3), supplied_quantity numeric(14,3) NOT NULL DEFAULT 0,
   status text NOT NULL DEFAULT 'requested' CHECK(status IN('requested','approved','partially_supplied','supplied','cancelled')),
   source text NOT NULL DEFAULT 'manual', source_work_order_id uuid, note text, created_by text, approved_by text, created_at timestamptz NOT NULL DEFAULT now(), approved_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now());
 CREATE INDEX IF NOT EXISTS salon_stock_requests_status_idx ON salon_stock_requests(status,location_id,created_at);
 CREATE TABLE IF NOT EXISTS stock_transfers(
   id uuid PRIMARY KEY DEFAULT gen_random_uuid(), request_id uuid REFERENCES salon_stock_requests(id), product_id uuid NOT NULL REFERENCES products(id), destination_location_id uuid NOT NULL REFERENCES locations(id),
   quantity numeric(14,3) NOT NULL CHECK(quantity>0), status text NOT NULL DEFAULT 'prepared' CHECK(status IN('prepared','dispatched','received','cancelled')),
   dispatched_by text, received_by text, dispatched_at timestamptz, received_at timestamptz, note text, created_at timestamptz NOT NULL DEFAULT now());
 CREATE INDEX IF NOT EXISTS stock_transfers_status_idx ON stock_transfers(status,destination_location_id,created_at);`);
}

router.get('/requests',async(req,res,next)=>{try{await ensureSchema();const loc=String(req.query.location_id||'').trim()||null;const status=String(req.query.status||'').trim()||null;const {rows}=await db.query(`SELECT r.*,l.name location_name,p.name product_name,p.internal_code,
 COALESCE((SELECT quantity FROM product_stock_balances b WHERE b.product_id=r.product_id AND b.location_id IS NULL LIMIT 1),0)::numeric central_quantity,
 COALESCE((SELECT quantity FROM product_stock_balances b WHERE b.product_id=r.product_id AND b.location_id=r.location_id LIMIT 1),0)::numeric salon_quantity
 FROM salon_stock_requests r JOIN locations l ON l.id=r.location_id JOIN products p ON p.id=r.product_id
 WHERE ($1::text IS NULL OR r.location_id::text=$1) AND ($2::text IS NULL OR r.status=$2) ORDER BY r.created_at DESC LIMIT 300`,[loc,status]);res.json(rows)}catch(e){next(e)}});

router.post('/requests',async(req:any,res,next)=>{try{await ensureSchema();const locationId=String(req.body?.location_id||'');const productId=String(req.body?.product_id||'');const qty=num(req.body?.requested_quantity);if(!locationId||!productId||!(qty>0))return res.status(400).json({message:'Telephely, termék és pozitív mennyiség szükséges.'});const open=await db.query(`SELECT id FROM salon_stock_requests WHERE location_id=$1 AND product_id=$2 AND status IN('requested','approved','partially_supplied') LIMIT 1`,[locationId,productId]);if(open.rows[0])return res.status(409).json({message:'Ehhez a termékhez már van nyitott készletigény.',request_id:open.rows[0].id});const {rows}=await db.query(`INSERT INTO salon_stock_requests(location_id,product_id,requested_quantity,source,source_work_order_id,note,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[locationId,productId,qty,String(req.body?.source||'manual'),req.body?.source_work_order_id||null,String(req.body?.note||'').trim()||null,actor(req)]);res.status(201).json(rows[0])}catch(e){next(e)}});

router.post('/requests/:id/approve',async(req:any,res,next)=>{try{await ensureSchema();const qty=num(req.body?.approved_quantity);const q=await db.query(`UPDATE salon_stock_requests SET approved_quantity=CASE WHEN $2>0 THEN LEAST($2,requested_quantity) ELSE requested_quantity END,status='approved',approved_by=$3,approved_at=now(),updated_at=now() WHERE id=$1 AND status='requested' RETURNING *`,[req.params.id,qty,actor(req)]);if(!q.rows[0])return res.status(409).json({message:'Az igény nem jóváhagyható.'});res.json(q.rows[0])}catch(e){next(e)}});

router.post('/requests/:id/allocate',async(req:any,res,next)=>{const cx=await db.connect();try{await ensureSchema();await cx.query('BEGIN');const rr=await cx.query(`SELECT * FROM salon_stock_requests WHERE id=$1 FOR UPDATE`,[req.params.id]);const r=rr.rows[0];if(!r){await cx.query('ROLLBACK');return res.status(404).json({message:'Az igény nem található.'})}if(!['approved','partially_supplied'].includes(r.status)){await cx.query('ROLLBACK');return res.status(409).json({message:'Csak jóváhagyott igény adható ki.'})}const remaining=num(r.approved_quantity||r.requested_quantity)-num(r.supplied_quantity);const requested=num(req.body?.quantity||remaining);const qty=Math.min(remaining,requested);if(!(qty>0)){await cx.query('ROLLBACK');return res.status(400).json({message:'Nincs kiadható mennyiség.'})}const bal=await cx.query(`SELECT * FROM product_stock_balances WHERE product_id=$1 AND location_id IS NULL FOR UPDATE`,[r.product_id]);const current=num(bal.rows[0]?.quantity);if(current+1e-9<qty){await cx.query('ROLLBACK');return res.status(409).json({message:'A központi készlet nem elegendő.',available:current,missing:qty-current})}const {rows}=await cx.query(`INSERT INTO stock_transfers(request_id,product_id,destination_location_id,quantity,note) VALUES($1,$2,$3,$4,$5) RETURNING *`,[r.id,r.product_id,r.location_id,qty,String(req.body?.note||'').trim()||null]);await cx.query('COMMIT');res.status(201).json(rows[0])}catch(e){await cx.query('ROLLBACK');next(e)}finally{cx.release()}});

router.get('/transfers',async(req,res,next)=>{try{await ensureSchema();const loc=String(req.query.location_id||'').trim()||null;const {rows}=await db.query(`SELECT t.*,p.name product_name,l.name destination_name FROM stock_transfers t JOIN products p ON p.id=t.product_id JOIN locations l ON l.id=t.destination_location_id WHERE ($1::text IS NULL OR t.destination_location_id::text=$1) ORDER BY t.created_at DESC LIMIT 300`,[loc]);res.json(rows)}catch(e){next(e)}});

router.post('/transfers/:id/dispatch',async(req:any,res,next)=>{const cx=await db.connect();try{await ensureSchema();await cx.query('BEGIN');const tr=await cx.query(`SELECT * FROM stock_transfers WHERE id=$1 FOR UPDATE`,[req.params.id]);const t=tr.rows[0];if(!t){await cx.query('ROLLBACK');return res.status(404).json({message:'Az átadás nem található.'})}if(t.status!=='prepared'){await cx.query('ROLLBACK');return res.status(409).json({message:'Csak előkészített átadás küldhető el.'})}const b=await cx.query(`SELECT * FROM product_stock_balances WHERE product_id=$1 AND location_id IS NULL FOR UPDATE`,[t.product_id]);const old=num(b.rows[0]?.quantity);if(old+1e-9<num(t.quantity)){await cx.query('ROLLBACK');return res.status(409).json({message:'A központi készlet időközben nem elegendő.'})}const after=old-num(t.quantity);await cx.query(`UPDATE product_stock_balances SET quantity=$2,updated_at=now() WHERE id=$1`,[b.rows[0].id,after]);await cx.query(`INSERT INTO inventory_movements(product_id,location_id,movement_type,quantity,balance_after,unit_cost,stock_value_after,note,created_by) VALUES($1,NULL,'transfer_out',$2,$3,$4,$5,$6,$7)`,[t.product_id,-num(t.quantity),after,num(b.rows[0].unit_cost),after*num(b.rows[0].unit_cost),`Központ → szalon átadás ${t.id}`,actor(req)]);await cx.query(`UPDATE stock_transfers SET status='dispatched',dispatched_by=$2,dispatched_at=now() WHERE id=$1`,[t.id,actor(req)]);await cx.query('COMMIT');res.json({ok:true,status:'dispatched'})}catch(e){await cx.query('ROLLBACK');next(e)}finally{cx.release()}});

router.post('/transfers/:id/receive',async(req:any,res,next)=>{const cx=await db.connect();try{await ensureSchema();await cx.query('BEGIN');const tr=await cx.query(`SELECT * FROM stock_transfers WHERE id=$1 FOR UPDATE`,[req.params.id]);const t=tr.rows[0];if(!t){await cx.query('ROLLBACK');return res.status(404).json({message:'Az átadás nem található.'})}if(t.status!=='dispatched'){await cx.query('ROLLBACK');return res.status(409).json({message:'Csak elküldött átadás érkeztethető.'})}const received=num(req.body?.received_quantity||t.quantity);if(received<0||received>num(t.quantity)){await cx.query('ROLLBACK');return res.status(400).json({message:'Érvénytelen érkeztetett mennyiség.'})}let b=await cx.query(`SELECT * FROM product_stock_balances WHERE product_id=$1 AND location_id=$2 FOR UPDATE`,[t.product_id,t.destination_location_id]);if(!b.rows[0]){await cx.query(`INSERT INTO product_stock_balances(product_id,location_id,quantity,unit_cost,min_quantity,updated_at) VALUES($1,$2,0,0,0,now())`,[t.product_id,t.destination_location_id]);b=await cx.query(`SELECT * FROM product_stock_balances WHERE product_id=$1 AND location_id=$2 FOR UPDATE`,[t.product_id,t.destination_location_id])}const after=num(b.rows[0].quantity)+received;await cx.query(`UPDATE product_stock_balances SET quantity=$2,updated_at=now() WHERE id=$1`,[b.rows[0].id,after]);await cx.query(`INSERT INTO inventory_movements(product_id,location_id,movement_type,quantity,balance_after,unit_cost,stock_value_after,note,created_by) VALUES($1,$2,'transfer_in',$3,$4,$5,$6,$7,$8)`,[t.product_id,t.destination_location_id,received,after,num(b.rows[0].unit_cost),after*num(b.rows[0].unit_cost),`Központi átadás ${t.id}`,actor(req)]);await cx.query(`UPDATE stock_transfers SET status='received',received_by=$2,received_at=now() WHERE id=$1`,[t.id,actor(req)]);if(t.request_id){await cx.query(`UPDATE salon_stock_requests SET supplied_quantity=supplied_quantity+$2,status=CASE WHEN supplied_quantity+$2>=COALESCE(approved_quantity,requested_quantity) THEN 'supplied' ELSE 'partially_supplied' END,updated_at=now() WHERE id=$1`,[t.request_id,received])}await cx.query('COMMIT');res.json({ok:true,status:'received',received_quantity:received,shortage:num(t.quantity)-received})}catch(e){await cx.query('ROLLBACK');next(e)}finally{cx.release()}});

export default router;
