import { Router, Response } from "express";
import db from "../db";
import { requireAuth, type AuthRequest } from "../middleware/auth";
import { requireRoles } from "../middleware/requireRoles";
import { parseRoleKeys } from "../security/roles";

const router=Router();
router.use(requireAuth);
router.use(requireRoles("admin","manager","accounting","bookkeeper","location_manager","salon_manager"));
const GLOBAL=new Set(["admin","manager","accounting","bookkeeper"]);
const PROVIDERS=new Set(["internal","invee_manual","nav_epg","hardware_epg"]);
const NAV_OWNERS=new Set(["vir","external","not_applicable"]);
const text=(v:unknown)=>String(v??"").trim();
const actor=(req:AuthRequest)=>req.user?.email||String(req.user?.id||"");
function globalRole(req:AuthRequest){return parseRoleKeys(req.user?.role).some(r=>GLOBAL.has(r));}
async function ensure(){await db.query(`CREATE EXTENSION IF NOT EXISTS pgcrypto;CREATE TABLE IF NOT EXISTS legal_entity_document_settings(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),legal_entity_id uuid NOT NULL REFERENCES legal_entities(id) ON DELETE CASCADE,location_id uuid REFERENCES locations(id) ON DELETE CASCADE,receipt_provider text NOT NULL DEFAULT 'internal',drive_folder_id text,altegio_location_id text,external_account_ref text,nav_reporting_owner text NOT NULL DEFAULT 'external',active boolean NOT NULL DEFAULT true,updated_by text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CHECK(receipt_provider IN('internal','invee_manual','nav_epg','hardware_epg')),CHECK(nav_reporting_owner IN('vir','external','not_applicable')));CREATE UNIQUE INDEX IF NOT EXISTS uq_legal_entity_document_settings_scope ON legal_entity_document_settings(legal_entity_id,COALESCE(location_id,'00000000-0000-0000-0000-000000000000'::uuid));`)}
async function allowed(req:AuthRequest,entityId:string,locationId:string|null){if(globalRole(req))return true;const own=text(req.user?.location_id);if(!own||(locationId&&locationId!==own))return false;return Boolean((await db.query(`SELECT 1 FROM legal_entity_locations WHERE legal_entity_id=$1::uuid AND location_id::text=$2 AND active=true`,[entityId,own])).rows[0])}
router.put("/settings",async(req:AuthRequest,res:Response)=>{try{await ensure();const entityId=text(req.body?.legal_entity_id),locationId=text(req.body?.location_id)||null;if(!entityId)return res.status(400).json({ok:false,message:"A kibocsátó cég kiválasztása kötelező."});if(!await allowed(req,entityId,locationId))return res.status(403).json({ok:false,message:"Ehhez a céghez vagy telephelyhez nincs jogosultsága."});const provider=PROVIDERS.has(text(req.body?.receipt_provider))?text(req.body.receipt_provider):"internal";const navOwner=NAV_OWNERS.has(text(req.body?.nav_reporting_owner))?text(req.body.nav_reporting_owner):(provider==="internal"?"vir":"external");const values=[entityId,locationId,provider,text(req.body?.drive_folder_id)||null,text(req.body?.altegio_location_id)||null,text(req.body?.external_account_ref)||null,navOwner,req.body?.active!==false,actor(req)];let q=await db.query(`UPDATE legal_entity_document_settings SET receipt_provider=$3,drive_folder_id=$4,altegio_location_id=$5,external_account_ref=$6,nav_reporting_owner=$7,active=$8,updated_by=$9,updated_at=now() WHERE legal_entity_id=$1::uuid AND COALESCE(location_id,'00000000-0000-0000-0000-000000000000'::uuid)=COALESCE($2::uuid,'00000000-0000-0000-0000-000000000000'::uuid) RETURNING *`,values);if(!q.rowCount)q=await db.query(`INSERT INTO legal_entity_document_settings(legal_entity_id,location_id,receipt_provider,drive_folder_id,altegio_location_id,external_account_ref,nav_reporting_owner,active,updated_by) VALUES($1::uuid,$2::uuid,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,values);return res.json({ok:true,settings:q.rows[0]});}catch(e:any){if(e?.code==="23505")return res.status(409).json({ok:false,message:"A beállítás közben párhuzamos módosítás történt. Frissítsd az oldalt és mentsd újra."});return res.status(500).json({ok:false,message:e?.message})}});
export default router;
