import { Router } from "express";
import db from "../db";
import { requireAuth, AuthRequest } from "../middleware/auth";
import { requireFeature } from "../middleware/featureAccess";

const router = Router();
router.use(requireAuth);
router.use(requireFeature("finance"));

const money=(v:unknown)=>{const n=Number(v||0);return Number.isFinite(n)?Math.round(n*100)/100:0};
const actor=(req:AuthRequest)=>req.user?.email||String(req.user?.id||"");

router.get("/workorders/:id/invoice",async(req,res,next)=>{try{const {rows}=await db.query(`SELECT * FROM finance_invoices WHERE direction='outgoing' AND work_order_id=$1 AND status<>'cancelled' ORDER BY created_at DESC LIMIT 1`,[req.params.id]);res.json(rows[0]||null)}catch(err){next(err)}});
router.post("/workorders/:id/invoice/create-or-sync",async(req:AuthRequest,res,next)=>{const client=await db.connect();try{await client.query("BEGIN");const wo=await client.query(`SELECT * FROM work_orders WHERE id=$1 FOR UPDATE`,[req.params.id]);const x=wo.rows[0];if(!x){await client.query("ROLLBACK");return res.status(404).json({message:"A munkalap nem található."})}const gross=money(req.body?.gross_total??x.amount_due??x.gross_total);const vat=money(req.body?.vat_total||0);const net=money(req.body?.net_total??Math.max(0,gross-vat));const invoiceNo=String(req.body?.invoice_no||"").trim()||null;const {rows}=await client.query(`INSERT INTO finance_invoices(location_id,direction,invoice_no,partner_name,partner_tax_no,issue_date,performance_date,due_date,currency,net_total,vat_total,gross_total,status,work_order_id,note,created_by) VALUES($1,'outgoing',$2,$3,$4,COALESCE($5::date,CURRENT_DATE),COALESCE($6::date,CURRENT_DATE),COALESCE($7::date,CURRENT_DATE),COALESCE($8,'HUF'),$9,$10,$11,$12,$13,$14,$15) ON CONFLICT (work_order_id) WHERE direction='outgoing' AND work_order_id IS NOT NULL AND status<>'cancelled' DO UPDATE SET invoice_no=COALESCE(EXCLUDED.invoice_no,finance_invoices.invoice_no),partner_name=EXCLUDED.partner_name,partner_tax_no=COALESCE(EXCLUDED.partner_tax_no,finance_invoices.partner_tax_no),issue_date=EXCLUDED.issue_date,performance_date=EXCLUDED.performance_date,due_date=EXCLUDED.due_date,net_total=EXCLUDED.net_total,vat_total=EXCLUDED.vat_total,gross_total=EXCLUDED.gross_total,note=EXCLUDED.note,updated_at=now() RETURNING *`,[x.location_id,invoiceNo,x.client_name||"Vendég",req.body?.partner_tax_no||null,req.body?.issue_date||null,req.body?.performance_date||x.completed_at||null,req.body?.due_date||null,req.body?.currency||"HUF",net,vat,gross,req.body?.status||"draft",String(x.id),req.body?.note||"Munkalaphoz kapcsolt kimenő számla",actor(req)]);await client.query("COMMIT");res.status(201).json(rows[0])}catch(err){await client.query("ROLLBACK");next(err)}finally{client.release()}});

router.get("/purchase-orders/:id/invoice",async(req,res,next)=>{try{const {rows}=await db.query(`SELECT * FROM finance_invoices WHERE direction='incoming' AND purchase_order_id=$1 AND status<>'cancelled' ORDER BY created_at DESC LIMIT 1`,[req.params.id]);res.json(rows[0]||null)}catch(err){next(err)}});
router.post("/purchase-orders/:id/invoice/create-or-sync",async(req:AuthRequest,res,next)=>{const client=await db.connect();try{await client.query("BEGIN");const po=await client.query(`SELECT * FROM purchase_orders WHERE id=$1 FOR UPDATE`,[req.params.id]);const x=po.rows[0];if(!x){await client.query("ROLLBACK");return res.status(404).json({message:"A beszerzési rendelés nem található."})}const totals=await client.query(`SELECT COALESCE(SUM(received_quantity*COALESCE(actual_unit_cost,unit_cost)),0)::numeric received_total,COALESCE(SUM(ordered_quantity*unit_cost),0)::numeric expected_total FROM purchase_order_items WHERE purchase_order_id=$1`,[x.id]);const base=money(Number(totals.rows[0]?.received_total)>0?totals.rows[0].received_total:totals.rows[0]?.expected_total);const gross=money(req.body?.gross_total??base);const vat=money(req.body?.vat_total||0);const net=money(req.body?.net_total??Math.max(0,gross-vat));const {rows}=await client.query(`INSERT INTO finance_invoices(location_id,direction,invoice_no,partner_name,partner_tax_no,issue_date,performance_date,due_date,currency,net_total,vat_total,gross_total,status,purchase_order_id,note,created_by) VALUES($1,'incoming',$2,$3,$4,COALESCE($5::date,CURRENT_DATE),COALESCE($6::date,CURRENT_DATE),COALESCE($7::date,CURRENT_DATE),COALESCE($8,'HUF'),$9,$10,$11,$12,$13,$14,$15) ON CONFLICT (purchase_order_id) WHERE direction='incoming' AND purchase_order_id IS NOT NULL AND status<>'cancelled' DO UPDATE SET invoice_no=COALESCE(EXCLUDED.invoice_no,finance_invoices.invoice_no),partner_name=EXCLUDED.partner_name,partner_tax_no=COALESCE(EXCLUDED.partner_tax_no,finance_invoices.partner_tax_no),issue_date=EXCLUDED.issue_date,performance_date=EXCLUDED.performance_date,due_date=EXCLUDED.due_date,net_total=EXCLUDED.net_total,vat_total=EXCLUDED.vat_total,gross_total=EXCLUDED.gross_total,note=EXCLUDED.note,updated_at=now() RETURNING *`,[x.location_id,String(req.body?.invoice_no||"").trim()||null,x.supplier_name||"Beszállító",req.body?.partner_tax_no||null,req.body?.issue_date||null,req.body?.performance_date||x.received_at||null,req.body?.due_date||null,req.body?.currency||"HUF",net,vat,gross,req.body?.status||"draft",String(x.id),req.body?.note||"Beszerzési rendeléshez kapcsolt bejövő számla",actor(req)]);await client.query("COMMIT");res.status(201).json(rows[0])}catch(err){await client.query("ROLLBACK");next(err)}finally{client.release()}});

export default router;
