import { Router } from "express";
import db from "../db";
import { requireAuth, type AuthRequest } from "../middleware/auth";
import { requireManagement } from "../middleware/requireRoles";
import { writeSystemAudit } from "../audit/systemAudit";
import { ensureGdprSchema, GDPR_SETTING_KEYS } from "../gdpr/ensureGdpr";

const router=Router();
router.use(requireAuth,requireManagement);
router.use(async(_req,_res,next)=>{try{await ensureGdprSchema();next()}catch(e){next(e)}});

const GUIDE=[
 {key:"principles",title:"Adatkezelési alapelvek",text:"Jogszerűség, tisztességesség, átláthatóság, célhoz kötöttség, adattakarékosság, pontosság, korlátozott tárolhatóság, integritás és elszámoltathatóság.",articles:"GDPR 5. cikk"},
 {key:"records",title:"Adatkezelési nyilvántartás",text:"Minden célhoz rögzíteni kell az érintetteket, adatokat, jogalapot, címzetteket, továbbítást, megőrzést és biztonsági intézkedéseket.",articles:"GDPR 30. cikk"},
 {key:"rights",title:"Érintetti jogok",text:"A kérelmeket azonosítással, felelőssel, határidővel, döntéssel és teljesítési bizonyítékkal kell kezelni. Az alapértelmezett határidő egy hónap.",articles:"GDPR 12–22. cikk"},
 {key:"incidents",title:"Adatvédelmi incidensek",text:"Az eseményt azonnal korlátozni és dokumentálni kell. A bejelentendő incidenst lehetőség szerint a tudomásszerzéstől számított 72 órán belül kell jelezni.",articles:"GDPR 33–34. cikk"},
 {key:"privacy_by_design",title:"Beépített adatvédelem",text:"Az alapértelmezett hozzáférés, adatmezők, exportok és megőrzés csak a célhoz szükséges mértékű lehet.",articles:"GDPR 25. cikk"},
 {key:"security",title:"Adatbiztonság",text:"Kockázatarányos hozzáférés-védelem, titkosítás, helyreállítás, tesztelés és naplózás szükséges.",articles:"GDPR 32. cikk"},
 {key:"processors",title:"Adatfeldolgozók",text:"Csak megfelelő garanciát nyújtó szolgáltató alkalmazható, írásbeli feltételekkel és ellenőrzött alfeldolgozókkal.",articles:"GDPR 28., 44–49. cikk"},
 {key:"dpia",title:"Hatásvizsgálat (DPIA)",text:"Magas kockázatú, különleges adatot, megfigyelést vagy profilalkotást érintő változásnál DPIA-szűrés szükséges.",articles:"GDPR 35–36. cikk"},
];
const t=(v:unknown,max=10000)=>String(v??"").trim().slice(0,max);
const arr=(v:unknown)=>Array.isArray(v)?v.map(x=>t(x,500)).filter(Boolean).slice(0,100):[];
const actor=(req:AuthRequest)=>req.user?.email||String(req.user?.id||"");
const bool=(v:unknown)=>typeof v==="boolean"?v:null;
const reference=(prefix:string)=>`${prefix}-${new Date().toISOString().slice(0,7).replace("-","")}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;
async function getRow(table:string,id:string){return(await db.query(`SELECT * FROM ${table} WHERE id=$1::uuid`,[id])).rows[0]||null}
async function audit(req:AuthRequest,type:string,id:string,action:string,before:any,after:any){await writeSystemAudit(req,{moduleKey:"gdpr",entityType:type,entityId:id,action,severity:action==="create"?"info":"warning",summary:`GDPR ${type}: ${action}`,before,after})}

router.get("/guide",(_req,res)=>res.json({updated_at:"2026-08-16",legal_notice:"A felület működési támogatás, nem helyettesít jogi tanácsadást.",sources:[{title:"GDPR",url:"https://eur-lex.europa.eu/eli/reg/2016/679/oj/hun"},{title:"NAIH incidenskezelés",url:"https://www.naih.hu/tudnivalok-az-adatvedelmi-incidensek-kezeleserol"}],sections:GUIDE}));
router.get("/overview",async(_req,res,next)=>{try{res.json((await db.query(`SELECT
 (SELECT count(*)::int FROM gdpr_processing_activities WHERE status='active') activities,
 (SELECT count(*)::int FROM gdpr_processing_activities WHERE review_at<=CURRENT_DATE AND status<>'archived') reviews_due,
 (SELECT count(*)::int FROM gdpr_data_subject_requests WHERE status NOT IN ('completed','rejected','cancelled')) open_requests,
 (SELECT count(*)::int FROM gdpr_data_subject_requests WHERE due_at<now() AND status NOT IN ('completed','rejected','cancelled')) overdue_requests,
 (SELECT count(*)::int FROM gdpr_incidents WHERE status<>'closed') open_incidents,
 (SELECT count(*)::int FROM gdpr_incidents WHERE authority_notification_required IS NULL AND status<>'closed') incidents_to_assess,
 (SELECT count(*)::int FROM gdpr_retention_policies WHERE enabled) active_retention_policies,
 (SELECT count(*)::int FROM gdpr_processors WHERE status='active') active_processors,
 (SELECT count(*)::int FROM gdpr_notice_versions WHERE status='active') active_notices,
 (SELECT count(*)::int FROM gdpr_dpias WHERE status IN ('screening','assessment','review_due')) open_dpias`)).rows[0])}catch(e){next(e)}});

router.get("/settings",async(_req,res,next)=>{try{res.json((await db.query(`SELECT key,value,updated_by,updated_at FROM gdpr_settings ORDER BY key`)).rows)}catch(e){next(e)}});
router.put("/settings/:key",async(req:AuthRequest,res,next)=>{try{const key=t(req.params.key,100);if(!GDPR_SETTING_KEYS.has(key))return res.status(404).json({message:"Ismeretlen GDPR-beállítás."});const before=(await db.query(`SELECT * FROM gdpr_settings WHERE key=$1`,[key])).rows[0];await db.query(`UPDATE gdpr_settings SET value=$2::jsonb,updated_by=$3,updated_at=now() WHERE key=$1`,[key,JSON.stringify(req.body?.value),actor(req)]);const after=(await db.query(`SELECT * FROM gdpr_settings WHERE key=$1`,[key])).rows[0];await audit(req,"setting",key,"update",before,after);res.json(after)}catch(e){next(e)}});

router.get("/processing-activities",async(_req,res,next)=>{try{res.json((await db.query(`SELECT * FROM gdpr_processing_activities ORDER BY status,lower(name)`)).rows)}catch(e){next(e)}});
router.post("/processing-activities",async(req:AuthRequest,res,next)=>{try{const b=req.body||{};if(!t(b.name)||!t(b.purpose)||!t(b.legal_basis)||!t(b.retention_rule))return res.status(400).json({message:"Név, cél, jogalap és megőrzési szabály kötelező."});const q=await db.query(`INSERT INTO gdpr_processing_activities(name,purpose,data_subjects,data_categories,special_categories,legal_basis,article9_condition,recipients,processors,transfers,retention_rule,security_measures,owner,status,review_at,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$16) RETURNING *`,[t(b.name,300),t(b.purpose),arr(b.data_subjects),arr(b.data_categories),Boolean(b.special_categories),t(b.legal_basis,500),t(b.article9_condition,500)||null,arr(b.recipients),arr(b.processors),t(b.transfers)||null,t(b.retention_rule,2000),t(b.security_measures)||null,t(b.owner,300)||null,["draft","active","review_due","archived"].includes(b.status)?b.status:"draft",b.review_at||null,actor(req)]);await audit(req,"processing_activity",q.rows[0].id,"create",null,q.rows[0]);res.status(201).json(q.rows[0])}catch(e){next(e)}});
router.patch("/processing-activities/:id",async(req:AuthRequest,res,next)=>{try{const before=await getRow("gdpr_processing_activities",req.params.id);if(!before)return res.status(404).json({message:"Az adatkezelési tevékenység nem található."});const b=req.body||{};const q=await db.query(`UPDATE gdpr_processing_activities SET name=COALESCE($2,name),purpose=COALESCE($3,purpose),data_subjects=COALESCE($4,data_subjects),data_categories=COALESCE($5,data_categories),special_categories=COALESCE($6,special_categories),legal_basis=COALESCE($7,legal_basis),article9_condition=COALESCE($8,article9_condition),recipients=COALESCE($9,recipients),processors=COALESCE($10,processors),transfers=COALESCE($11,transfers),retention_rule=COALESCE($12,retention_rule),security_measures=COALESCE($13,security_measures),owner=COALESCE($14,owner),status=COALESCE($15,status),review_at=COALESCE($16,review_at),updated_by=$17,updated_at=now() WHERE id=$1::uuid RETURNING *`,[req.params.id,b.name?t(b.name,300):null,b.purpose?t(b.purpose):null,Array.isArray(b.data_subjects)?arr(b.data_subjects):null,Array.isArray(b.data_categories)?arr(b.data_categories):null,bool(b.special_categories),b.legal_basis?t(b.legal_basis,500):null,b.article9_condition!==undefined?t(b.article9_condition,500):null,Array.isArray(b.recipients)?arr(b.recipients):null,Array.isArray(b.processors)?arr(b.processors):null,b.transfers!==undefined?t(b.transfers):null,b.retention_rule?t(b.retention_rule,2000):null,b.security_measures!==undefined?t(b.security_measures):null,b.owner!==undefined?t(b.owner,300):null,["draft","active","review_due","archived"].includes(b.status)?b.status:null,b.review_at||null,actor(req)]);await audit(req,"processing_activity",req.params.id,"update",before,q.rows[0]);res.json(q.rows[0])}catch(e){next(e)}});

router.get("/retention-policies",async(_req,res,next)=>{try{res.json((await db.query(`SELECT * FROM gdpr_retention_policies ORDER BY enabled DESC,lower(name)`)).rows)}catch(e){next(e)}});
router.post("/retention-policies",async(req:AuthRequest,res,next)=>{try{const b=req.body||{},days=Number(b.retention_days);if(!t(b.name)||!t(b.entity_type)||!t(b.trigger_event)||!Number.isInteger(days)||days<0)return res.status(400).json({message:"Név, adattípus, kezdőesemény és nem negatív napérték kötelező."});const q=await db.query(`INSERT INTO gdpr_retention_policies(name,entity_type,trigger_event,retention_days,action,legal_basis,enabled,legal_hold_supported,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9) RETURNING *`,[t(b.name,300),t(b.entity_type,100),t(b.trigger_event,200),days,["review","anonymize","soft_delete","delete"].includes(b.action)?b.action:"review",t(b.legal_basis,1000)||null,Boolean(b.enabled),b.legal_hold_supported!==false,actor(req)]);await audit(req,"retention_policy",q.rows[0].id,"create",null,q.rows[0]);res.status(201).json(q.rows[0])}catch(e:any){if(e?.code==="23505")return res.status(409).json({message:"Ehhez az adattípushoz és kezdőeseményhez már van szabály."});next(e)}});
router.patch("/retention-policies/:id",async(req:AuthRequest,res,next)=>{try{const before=await getRow("gdpr_retention_policies",req.params.id);if(!before)return res.status(404).json({message:"A megőrzési szabály nem található."});const b=req.body||{};const q=await db.query(`UPDATE gdpr_retention_policies SET name=COALESCE($2,name),retention_days=COALESCE($3,retention_days),action=COALESCE($4,action),legal_basis=COALESCE($5,legal_basis),enabled=COALESCE($6,enabled),legal_hold_supported=COALESCE($7,legal_hold_supported),updated_by=$8,updated_at=now() WHERE id=$1::uuid RETURNING *`,[req.params.id,b.name?t(b.name,300):null,Number.isInteger(Number(b.retention_days))?Number(b.retention_days):null,["review","anonymize","soft_delete","delete"].includes(b.action)?b.action:null,b.legal_basis!==undefined?t(b.legal_basis,1000):null,bool(b.enabled),bool(b.legal_hold_supported),actor(req)]);await audit(req,"retention_policy",req.params.id,"update",before,q.rows[0]);res.json(q.rows[0])}catch(e){next(e)}});

router.get("/requests",async(_req,res,next)=>{try{res.json((await db.query(`SELECT * FROM gdpr_data_subject_requests ORDER BY CASE WHEN status IN ('completed','rejected','cancelled') THEN 1 ELSE 0 END,due_at`)).rows)}catch(e){next(e)}});
router.post("/requests",async(req:AuthRequest,res,next)=>{try{const b=req.body||{};if(!t(b.subject_name))return res.status(400).json({message:"Az érintett neve kötelező."});const days=Number((await db.query(`SELECT value FROM gdpr_settings WHERE key='request_deadline_days'`)).rows[0]?.value||30);const q=await db.query(`INSERT INTO gdpr_data_subject_requests(reference_no,request_type,subject_name,subject_contact,identity_verified,due_at,assigned_to,scope,created_by,updated_by) VALUES($1,$2,$3,$4,$5,now()+($6||' days')::interval,$7,$8,$9,$9) RETURNING *`,[reference("DSR"),["access","rectification","erasure","restriction","portability","objection","consent_withdrawal","other"].includes(b.request_type)?b.request_type:"other",t(b.subject_name,300),t(b.subject_contact,500)||null,Boolean(b.identity_verified),String(days),t(b.assigned_to,300)||null,t(b.scope)||null,actor(req)]);await audit(req,"data_subject_request",q.rows[0].id,"create",null,{...q.rows[0],subject_contact:"[redacted]"});res.status(201).json(q.rows[0])}catch(e){next(e)}});
router.patch("/requests/:id",async(req:AuthRequest,res,next)=>{try{const before=await getRow("gdpr_data_subject_requests",req.params.id);if(!before)return res.status(404).json({message:"A kérelem nem található."});const b=req.body||{},status=["received","identity_check","in_progress","extended","completed","rejected","cancelled"].includes(b.status)?b.status:null;if(status==="extended"&&!t(b.extension_reason)&&!before.extension_reason)return res.status(400).json({message:"A határidő-hosszabbítás indoklása kötelező."});if(status==="completed"&&!t(b.response_evidence)&&!before.response_evidence)return res.status(400).json({message:"A teljesítés bizonyítékának hivatkozása kötelező."});const q=await db.query(`UPDATE gdpr_data_subject_requests SET identity_verified=COALESCE($2,identity_verified),status=COALESCE($3,status),assigned_to=COALESCE($4,assigned_to),scope=COALESCE($5,scope),decision=COALESCE($6,decision),rejection_reason=COALESCE($7,rejection_reason),due_at=COALESCE($8,due_at),extension_reason=COALESCE($9,extension_reason),response_evidence=COALESCE($10,response_evidence),completed_at=CASE WHEN $3='completed' THEN COALESCE(completed_at,now()) ELSE completed_at END,updated_by=$11,updated_at=now() WHERE id=$1::uuid RETURNING *`,[req.params.id,bool(b.identity_verified),status,b.assigned_to!==undefined?t(b.assigned_to,300):null,b.scope!==undefined?t(b.scope):null,b.decision!==undefined?t(b.decision):null,b.rejection_reason!==undefined?t(b.rejection_reason):null,b.due_at||null,b.extension_reason!==undefined?t(b.extension_reason):null,b.response_evidence!==undefined?t(b.response_evidence):null,actor(req)]);await audit(req,"data_subject_request",req.params.id,"update",{...before,subject_contact:"[redacted]"},{...q.rows[0],subject_contact:"[redacted]"});res.json(q.rows[0])}catch(e){next(e)}});

router.get("/incidents",async(_req,res,next)=>{try{res.json((await db.query(`SELECT *,aware_at+interval '72 hours' notification_deadline FROM gdpr_incidents ORDER BY CASE WHEN status='closed' THEN 1 ELSE 0 END,aware_at DESC`)).rows)}catch(e){next(e)}});
router.post("/incidents",async(req:AuthRequest,res,next)=>{try{const b=req.body||{};if(!t(b.title)||!t(b.description))return res.status(400).json({message:"Cím és leírás kötelező."});const now=new Date().toISOString();const q=await db.query(`INSERT INTO gdpr_incidents(reference_no,title,detected_at,aware_at,severity,description,data_categories,approximate_subjects,approximate_records,consequences,containment,risk_to_rights,owner,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$14) RETURNING *,aware_at+interval '72 hours' notification_deadline`,[reference("INC"),t(b.title,300),b.detected_at||now,b.aware_at||now,["low","medium","high","critical"].includes(b.severity)?b.severity:"medium",t(b.description),arr(b.data_categories),Number(b.approximate_subjects)||null,Number(b.approximate_records)||null,t(b.consequences)||null,t(b.containment)||null,t(b.risk_to_rights)||null,t(b.owner,300)||null,actor(req)]);await audit(req,"incident",q.rows[0].id,"create",null,q.rows[0]);res.status(201).json(q.rows[0])}catch(e){next(e)}});
router.patch("/incidents/:id",async(req:AuthRequest,res,next)=>{try{const before=await getRow("gdpr_incidents",req.params.id);if(!before)return res.status(404).json({message:"Az incidens nem található."});const b=req.body||{},status=["open","contained","assessing","notified","closed"].includes(b.status)?b.status:null;const notified=b.authority_notified_at?new Date(b.authority_notified_at):before.authority_notified_at?new Date(before.authority_notified_at):null;const late=notified&&notified.getTime()>new Date(before.aware_at).getTime()+72*3600000;if(late&&!t(b.notification_delay_reason)&&!before.notification_delay_reason)return res.status(400).json({message:"A 72 órán túli bejelentés késedelmi indoka kötelező."});const q=await db.query(`UPDATE gdpr_incidents SET status=COALESCE($2,status),severity=COALESCE($3,severity),description=COALESCE($4,description),data_categories=COALESCE($5,data_categories),consequences=COALESCE($6,consequences),containment=COALESCE($7,containment),risk_to_rights=COALESCE($8,risk_to_rights),authority_notification_required=COALESCE($9,authority_notification_required),authority_notified_at=COALESCE($10,authority_notified_at),subjects_notification_required=COALESCE($11,subjects_notification_required),subjects_notified_at=COALESCE($12,subjects_notified_at),decision_reason=COALESCE($13,decision_reason),owner=COALESCE($14,owner),notification_delay_reason=COALESCE($15,notification_delay_reason),authority_reference=COALESCE($16,authority_reference),closed_at=CASE WHEN $2='closed' THEN COALESCE(closed_at,now()) ELSE closed_at END,updated_by=$17,updated_at=now() WHERE id=$1::uuid RETURNING *,aware_at+interval '72 hours' notification_deadline`,[req.params.id,status,["low","medium","high","critical"].includes(b.severity)?b.severity:null,b.description!==undefined?t(b.description):null,Array.isArray(b.data_categories)?arr(b.data_categories):null,b.consequences!==undefined?t(b.consequences):null,b.containment!==undefined?t(b.containment):null,b.risk_to_rights!==undefined?t(b.risk_to_rights):null,bool(b.authority_notification_required),b.authority_notified_at||null,bool(b.subjects_notification_required),b.subjects_notified_at||null,b.decision_reason!==undefined?t(b.decision_reason):null,b.owner!==undefined?t(b.owner,300):null,b.notification_delay_reason!==undefined?t(b.notification_delay_reason):null,b.authority_reference!==undefined?t(b.authority_reference,500):null,actor(req)]);await audit(req,"incident",req.params.id,"update",before,q.rows[0]);res.json(q.rows[0])}catch(e){next(e)}});

router.get("/processors",async(_req,res,next)=>{try{res.json((await db.query(`SELECT * FROM gdpr_processors ORDER BY status,lower(name)`)).rows)}catch(e){next(e)}});
router.post("/processors",async(req:AuthRequest,res,next)=>{try{const b=req.body||{};if(!t(b.name)||!t(b.service))return res.status(400).json({message:"Név és szolgáltatás kötelező."});const q=await db.query(`INSERT INTO gdpr_processors(name,service,data_categories,processing_locations,subprocessor_url,dpa_signed_at,transfer_mechanism,security_review_at,deletion_verified_at,owner,status,notes,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$13) RETURNING *`,[t(b.name,300),t(b.service,1000),arr(b.data_categories),arr(b.processing_locations),t(b.subprocessor_url,1000)||null,b.dpa_signed_at||null,t(b.transfer_mechanism,1000)||null,b.security_review_at||null,b.deletion_verified_at||null,t(b.owner,300)||null,["planned","active","suspended","terminated"].includes(b.status)?b.status:"active",t(b.notes)||null,actor(req)]);await audit(req,"processor",q.rows[0].id,"create",null,q.rows[0]);res.status(201).json(q.rows[0])}catch(e){next(e)}});
router.patch("/processors/:id",async(req:AuthRequest,res,next)=>{try{const before=await getRow("gdpr_processors",req.params.id);if(!before)return res.status(404).json({message:"Az adatfeldolgozó nem található."});const b=req.body||{};const q=await db.query(`UPDATE gdpr_processors SET name=COALESCE($2,name),service=COALESCE($3,service),data_categories=COALESCE($4,data_categories),processing_locations=COALESCE($5,processing_locations),subprocessor_url=COALESCE($6,subprocessor_url),dpa_signed_at=COALESCE($7,dpa_signed_at),transfer_mechanism=COALESCE($8,transfer_mechanism),security_review_at=COALESCE($9,security_review_at),deletion_verified_at=COALESCE($10,deletion_verified_at),owner=COALESCE($11,owner),status=COALESCE($12,status),notes=COALESCE($13,notes),updated_by=$14,updated_at=now() WHERE id=$1::uuid RETURNING *`,[req.params.id,b.name?t(b.name,300):null,b.service?t(b.service,1000):null,Array.isArray(b.data_categories)?arr(b.data_categories):null,Array.isArray(b.processing_locations)?arr(b.processing_locations):null,b.subprocessor_url!==undefined?t(b.subprocessor_url,1000):null,b.dpa_signed_at||null,b.transfer_mechanism!==undefined?t(b.transfer_mechanism,1000):null,b.security_review_at||null,b.deletion_verified_at||null,b.owner!==undefined?t(b.owner,300):null,["planned","active","suspended","terminated"].includes(b.status)?b.status:null,b.notes!==undefined?t(b.notes):null,actor(req)]);await audit(req,"processor",req.params.id,"update",before,q.rows[0]);res.json(q.rows[0])}catch(e){next(e)}});

router.get("/notices",async(_req,res,next)=>{try{res.json((await db.query(`SELECT * FROM gdpr_notice_versions ORDER BY effective_from DESC`)).rows)}catch(e){next(e)}});
router.post("/notices",async(req:AuthRequest,res,next)=>{try{const b=req.body||{};if(!t(b.version)||!t(b.title)||!t(b.content_hash))return res.status(400).json({message:"Verzió, cím és tartalom-hash kötelező."});const type=["privacy","cookie","employee","applicant","marketing","other"].includes(b.notice_type)?b.notice_type:"other";const status=["draft","active","retired"].includes(b.status)?b.status:"draft";if(status==="active")await db.query(`UPDATE gdpr_notice_versions SET status='retired' WHERE notice_type=$1 AND status='active'`,[type]);const q=await db.query(`INSERT INTO gdpr_notice_versions(notice_type,version,title,url,content_hash,effective_from,status,approved_by,approved_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,CASE WHEN $7='active' THEN now() END,$9) RETURNING *`,[type,t(b.version,100),t(b.title,300),t(b.url,1000)||null,t(b.content_hash,200),b.effective_from||new Date().toISOString(),status,t(b.approved_by,300)||actor(req),actor(req)]);await audit(req,"notice_version",q.rows[0].id,"create",null,q.rows[0]);res.status(201).json(q.rows[0])}catch(e:any){if(e?.code==="23505")return res.status(409).json({message:"Ez a tájékoztató-verzió már létezik."});next(e)}});

router.get("/consents",async(req,res,next)=>{try{const subject=t(req.query.subject,300);res.json((await db.query(`SELECT c.*,n.version notice_version,n.notice_type FROM gdpr_consents c LEFT JOIN gdpr_notice_versions n ON n.id=c.notice_version_id WHERE ($1='' OR c.subject_ref=$1) ORDER BY c.captured_at DESC LIMIT 1000`,[subject])).rows)}catch(e){next(e)}});
router.post("/consents",async(req:AuthRequest,res,next)=>{try{const b=req.body||{};if(!t(b.subject_ref)||!t(b.purpose)||!t(b.source))return res.status(400).json({message:"Érintett-hivatkozás, cél és forrás kötelező."});const status=["granted","withdrawn","refused"].includes(b.status)?b.status:"granted";const q=await db.query(`INSERT INTO gdpr_consents(subject_ref,purpose,notice_version_id,status,captured_at,withdrawn_at,source,evidence,created_by) VALUES($1,$2,$3,$4,$5,CASE WHEN $4='withdrawn' THEN $5::timestamptz END,$6,$7::jsonb,$8) RETURNING *`,[t(b.subject_ref,300),t(b.purpose,500),b.notice_version_id||null,status,b.captured_at||new Date().toISOString(),t(b.source,200),JSON.stringify(b.evidence||{}),actor(req)]);await audit(req,"consent",q.rows[0].id,"create",null,{...q.rows[0],evidence:"[protected]"});res.status(201).json(q.rows[0])}catch(e){next(e)}});

router.get("/dpias",async(_req,res,next)=>{try{res.json((await db.query(`SELECT d.*,p.name processing_activity FROM gdpr_dpias d LEFT JOIN gdpr_processing_activities p ON p.id=d.processing_activity_id ORDER BY d.created_at DESC`)).rows)}catch(e){next(e)}});
router.post("/dpias",async(req:AuthRequest,res,next)=>{try{const b=req.body||{};if(!t(b.title)||!t(b.screening_reason))return res.status(400).json({message:"Cím és szűrési indok kötelező."});const flags=[b.systematic_monitoring,b.special_category_scale,b.vulnerable_subjects,b.new_technology].filter(Boolean).length;const required=b.dpia_required===undefined?flags>=2:Boolean(b.dpia_required);const q=await db.query(`INSERT INTO gdpr_dpias(title,processing_activity_id,screening_reason,systematic_monitoring,special_category_scale,vulnerable_subjects,new_technology,dpia_required,necessity_proportionality,risks,measures,residual_risk,consultation_required,status,owner,review_at,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$17) RETURNING *`,[t(b.title,300),b.processing_activity_id||null,t(b.screening_reason),Boolean(b.systematic_monitoring),Boolean(b.special_category_scale),Boolean(b.vulnerable_subjects),Boolean(b.new_technology),required,t(b.necessity_proportionality)||null,t(b.risks)||null,t(b.measures)||null,t(b.residual_risk)||null,Boolean(b.consultation_required),["screening","assessment","approved","review_due","closed"].includes(b.status)?b.status:"screening",t(b.owner,300)||null,b.review_at||null,actor(req)]);await audit(req,"dpia",q.rows[0].id,"create",null,q.rows[0]);res.status(201).json(q.rows[0])}catch(e){next(e)}});
router.patch("/dpias/:id",async(req:AuthRequest,res,next)=>{try{const before=await getRow("gdpr_dpias",req.params.id);if(!before)return res.status(404).json({message:"A DPIA nem található."});const b=req.body||{};const status=["screening","assessment","approved","review_due","closed"].includes(b.status)?b.status:null;const q=await db.query(`UPDATE gdpr_dpias SET necessity_proportionality=COALESCE($2,necessity_proportionality),risks=COALESCE($3,risks),measures=COALESCE($4,measures),residual_risk=COALESCE($5,residual_risk),consultation_required=COALESCE($6,consultation_required),status=COALESCE($7,status),owner=COALESCE($8,owner),review_at=COALESCE($9,review_at),approved_by=CASE WHEN $7='approved' THEN $10 ELSE approved_by END,approved_at=CASE WHEN $7='approved' THEN now() ELSE approved_at END,updated_by=$10,updated_at=now() WHERE id=$1::uuid RETURNING *`,[req.params.id,b.necessity_proportionality!==undefined?t(b.necessity_proportionality):null,b.risks!==undefined?t(b.risks):null,b.measures!==undefined?t(b.measures):null,b.residual_risk!==undefined?t(b.residual_risk):null,bool(b.consultation_required),status,b.owner!==undefined?t(b.owner,300):null,b.review_at||null,actor(req)]);await audit(req,"dpia",req.params.id,"update",before,q.rows[0]);res.json(q.rows[0])}catch(e){next(e)}});

export default router;
