import{Router}from"express";import db from"../db";import{requireAuth,type AuthRequest}from"../middleware/auth";import{knowledgeSources,materialsForRole,questionsForRole}from"../knowledge/catalog";import{roleKnowledgeSources2026,extraMaterialsForRole2026,extraQuestionsForRole2026}from"../knowledge/catalogRoleTests2026";import{academyKnowledgeSources2026,academyLevels,academyProfessions,academyProfessionByKey,academyProfessionForRole,academyMaterialsForProfession,academyQuestionsForProfession,type AcademyLevel,type AcademyProfession}from"../knowledge/catalogAcademyLevels2026";import virCustomizerRouter from"./virCustomizer";
const router=Router();router.use(requireAuth);
const QUIZ_VERSION="v29";
const allSources=Array.from(new Map([...knowledgeSources,...roleKnowledgeSources2026,...academyKnowledgeSources2026].map(s=>[s.code,s])).values());
const processes=[
 {code:"PROC-01",title:"Nyitási és zárási folyamat",steps:["Helyiség- és biztonsági ellenőrzés","Pénztár és eszközök átvétele","Napi checklist teljesítése","Záráskor nyitott vendégek és munkalapok rendezése","Eltérések naplózása és műszakátadás"]},
 {code:"PROC-02",title:"Foglalástól a lezárt munkalapig",steps:["Vendég és foglalás ellenőrzése","Érkeztetés","Munkalap indítása","Tényleges szolgáltatás és anyag rögzítése","Fizetés","Végleges lezárás és archiválás"]},
 {code:"PROC-03",title:"Panasz és rendkívüli esemény",steps:["Biztonság és sürgősség felmérése","Tények és érintettek rögzítése","Vezető értesítése","Intézkedés és felelős","Vendég visszajelzése","Lezárás és tanulság"]},
 {code:"PROC-04",title:"Adatvédelmi incidens",steps:["Az érintett rendszer vagy küldés megállítása","Az adat további terjedésének megelőzése","Vezető/adatvédelmi felelős azonnali értesítése","Időpont, adatkör és érintettek rögzítése","Kockázatértékelés és szükséges hatósági/érintetti intézkedés"]},
 {code:"PROC-05",title:"Baleset, tűz vagy rosszullét",steps:["Azonnali veszély megszüntetése, ha biztonságos","Segélyhívás vagy elsősegély","Kiürítés az előírt útvonalon","Vezető értesítése","Esemény dokumentálása és kivizsgálása"]},
];
async function ensure(){await db.query(`CREATE TABLE IF NOT EXISTS knowledge_quiz_attempts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),employee_id uuid NOT NULL,position_id text,role_name text,profession_key text,level text NOT NULL DEFAULT 'beginner',quiz_version text NOT NULL DEFAULT 'v29',score numeric NOT NULL,correct_count int NOT NULL,total_count int NOT NULL,answers jsonb NOT NULL,question_ids jsonb NOT NULL DEFAULT '[]'::jsonb,completed_at timestamptz DEFAULT now());ALTER TABLE knowledge_quiz_attempts ADD COLUMN IF NOT EXISTS role_name text;ALTER TABLE knowledge_quiz_attempts ADD COLUMN IF NOT EXISTS profession_key text;ALTER TABLE knowledge_quiz_attempts ADD COLUMN IF NOT EXISTS level text NOT NULL DEFAULT 'beginner';ALTER TABLE knowledge_quiz_attempts ADD COLUMN IF NOT EXISTS quiz_version text NOT NULL DEFAULT 'v27';ALTER TABLE knowledge_quiz_attempts ADD COLUMN IF NOT EXISTS question_ids jsonb NOT NULL DEFAULT '[]'::jsonb;ALTER TABLE hr_employee_evaluations ADD COLUMN IF NOT EXISTS knowledge_score numeric DEFAULT 0;`)}
async function employee(req:AuthRequest){return(await db.query(`SELECT e.id,e.position_id::text,p.name position_name FROM employees e LEFT JOIN hr_positions p ON p.id::text=e.position_id::text WHERE e.id::text=$1 OR lower(COALESCE(e.email,''))=lower($2) LIMIT 1`,[String(req.user?.id||""),String(req.user?.email||"")])).rows[0]}
function sourceMap(){return new Map(allSources.map(s=>[s.code,s]))}
function uniqueBy<T>(items:T[],key:(item:T)=>string){return Array.from(new Map(items.map(item=>[key(item),item])).values())}
function roleKeys(raw:any):string[]{if(Array.isArray(raw))return raw.map(String).map(x=>x.toLowerCase());try{const parsed=JSON.parse(String(raw||""));if(Array.isArray(parsed))return parsed.map(String).map(x=>x.toLowerCase())}catch{}return String(raw||"").split(",").map(x=>x.replace(/[\[\]"]/g,"").trim().toLowerCase()).filter(Boolean)}
function canPreviewAll(req:AuthRequest){return roleKeys(req.user?.role).some(r=>["admin","administrator","superadmin","super_admin","manager","vezető","vezeto"].includes(r))}
function levelFrom(value:unknown):AcademyLevel{const raw=String(value||"beginner");return academyLevels.some(x=>x.key===raw)?raw as AcademyLevel:"beginner"}
function resolveProfession(req:AuthRequest,role:string,body=false):AcademyProfession{const requested=String(body?req.body?.profession:req.query.profession||"").trim();if(requested&&canPreviewAll(req)){const p=academyProfessionByKey(requested);if(p)return p}return academyProfessionForRole(role)}
function roleForProfession(role:string,p:AcademyProfession){const own=academyProfessionForRole(role);return own.key===p.key?role:(p.roles[0]||role)}
function availableProfessions(req:AuthRequest,p:AcademyProfession){const list=canPreviewAll(req)?academyProfessions:[p];return list.map(x=>({key:x.key,label:x.label,category:x.category}))}
function questions(role:string,p:AcademyProfession,level:AcademyLevel){const effective=roleForProfession(role,p),legacy=level==="beginner"?[...questionsForRole(effective),...extraQuestionsForRole2026(effective)]:[];return uniqueBy([...legacy,...academyQuestionsForProfession(p.key,level)],x=>x.id)}
function materials(role:string,p:AcademyProfession){const effective=roleForProfession(role,p);return uniqueBy([...materialsForRole(effective),...extraMaterialsForRole2026(effective),...academyMaterialsForProfession(p.key)],x=>x.code)}
function levelMeta(role:string,p:AcademyProfession){return academyLevels.map(x=>({...x,question_count:questions(role,p,x.key).length,material_count:academyMaterialsForProfession(p.key).filter(m=>m.level===x.key).length}))}
function materialDto(role:string,p:AcademyProfession){const sm=sourceMap();return materials(role,p).map(x=>({...x,level:(x as any).level||"beginner",level_label:(x as any).level_label||"Kezdő",profession:(x as any).profession||p.key,profession_label:(x as any).profession_label||p.label,source:sm.get(x.source_code)}))}
router.get("/",async(req:AuthRequest,res,next)=>{try{await ensure();const e=await employee(req),role=String(e?.position_name||req.user?.role||""),p=resolveProfession(req,role);const attempts=e?(await db.query(`SELECT score,correct_count,total_count,role_name,profession_key,level,quiz_version,completed_at FROM knowledge_quiz_attempts WHERE employee_id=$1 ORDER BY completed_at DESC LIMIT 20`,[e.id])).rows:[];res.json({employee:e,role,profession:{key:p.key,label:p.label,category:p.category},academy_levels:levelMeta(role,p),available_professions:availableProfessions(req,p),materials:materialDto(role,p),processes,attempts,sources:allSources})}catch(e){next(e)}});
router.get("/quiz",async(req:AuthRequest,res,next)=>{try{const e=await employee(req),role=String(e?.position_name||req.user?.role||""),p=resolveProfession(req,role),level=levelFrom(req.query.level),qs=questions(role,p,level);res.json({role,profession:{key:p.key,label:p.label,category:p.category},level,level_label:academyLevels.find(x=>x.key===level)?.label,pass_percent:80,quiz_version:QUIZ_VERSION,available_levels:levelMeta(role,p),available_professions:availableProfessions(req,p),questions:qs.map(({correct,explanation,...q})=>q)})}catch(e){next(e)}});
router.post("/quiz/submit",async(req:AuthRequest,res,next)=>{try{await ensure();const e=await employee(req);if(!e)return res.status(404).json({message:"A belépett felhasználóhoz nincs munkatársi rekord."});const role=String(e.position_name||req.user?.role||""),p=resolveProfession(req,role,true),level=levelFrom(req.body?.level),qs=questions(role,p,level),a=req.body?.answers||{};if(qs.length===0)return res.status(400).json({message:"Ehhez a szakmához és szinthez még nincs tesztkérdés."});if(qs.some(q=>a[q.id]===undefined))return res.status(400).json({message:"Minden kérdésre válaszolni kell."});const correctQs=qs.filter(q=>Number(a[q.id])===q.correct),correct=correctQs.length,score=Math.round(correct/qs.length*100);await db.query(`INSERT INTO knowledge_quiz_attempts(employee_id,position_id,role_name,profession_key,level,quiz_version,score,correct_count,total_count,answers,question_ids)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[e.id,e.position_id,role,p.key,level,QUIZ_VERSION,score,correct,qs.length,a,JSON.stringify(qs.map(q=>q.id))]);const month=new Date().toISOString().slice(0,7)+"-01";const existing=(await db.query(`SELECT id FROM hr_employee_evaluations WHERE employee_id=$1 AND period_start=date_trunc('month',CURRENT_DATE)::date ORDER BY created_at DESC LIMIT 1`,[e.id])).rows[0];if(existing)await db.query(`UPDATE hr_employee_evaluations SET knowledge_score=$2,professional_score=GREATEST(COALESCE(professional_score,0),$2/20),overall_score=(COALESCE(guest_score,0)+COALESCE(sales_score,0)+COALESCE(teamwork_score,0)+COALESCE(hygiene_score,0)+COALESCE(attendance_score,0)+GREATEST(COALESCE(professional_score,0),$2/20))/6 WHERE id=$1`,[existing.id,score]);else await db.query(`INSERT INTO hr_employee_evaluations(employee_id,period_start,period_end,status,professional_score,knowledge_score,overall_score,manager_comment)VALUES($1,$2,(date_trunc('month',CURRENT_DATE)+interval '1 month - 1 day')::date,'draft',$3,$4,$3,'Munkaköri akadémia kvíz eredménye')`,[e.id,month,score/20,score]);const sm=sourceMap();res.json({score,correct,total:qs.length,passed:score>=80,role,profession:{key:p.key,label:p.label},level,level_label:academyLevels.find(x=>x.key===level)?.label,quiz_version:QUIZ_VERSION,review:qs.map(q=>({id:q.id,correct:Number(a[q.id])===q.correct,correct_answer:q.correct,explanation:q.explanation,source:sm.get(q.source_code)}))})}catch(e){next(e)}});
router.get("/sources",(_req,res)=>res.json({sources:allSources}));
router.use('/vir-customizer',virCustomizerRouter);
export default router;
