import {Router} from'express';
import db from'../db';
import{requireAuth,AuthRequest}from'../middleware/auth';
const router=Router();router.use(requireAuth);
const actor=(r:AuthRequest)=>r.user?.email||String(r.user?.id||'');

async function settings(){const r=await db.query(`SELECT * FROM loyalty_automation_settings WHERE active=true ORDER BY location_id NULLS FIRST LIMIT 1`);return r.rows[0]||{pass_expiry_days:14,voucher_expiry_days:14,inactive_guest_days:90,birthday_window_days:7,birthday_discount_percent:10,inactive_discount_percent:10}}

router.get('/summary',async(_req,res,next)=>{try{const s=await settings();const [pass,voucher,points,inactive,bday,suggestions]=await Promise.all([
 db.query(`SELECT COUNT(*)::int count FROM loyalty_passes WHERE status='active' AND valid_until BETWEEN CURRENT_DATE AND CURRENT_DATE+$1::int`,[s.pass_expiry_days]),
 db.query(`SELECT COUNT(*)::int count,COALESCE(SUM(remaining_value),0)::numeric value FROM loyalty_vouchers WHERE status='active' AND remaining_value>0 AND valid_until BETWEEN CURRENT_DATE AND CURRENT_DATE+$1::int`,[s.voucher_expiry_days]),
 db.query(`SELECT COUNT(*)::int count,COALESCE(SUM(points),0)::numeric points FROM loyalty_accounts WHERE status='active' AND points>0 AND points_expires_at BETWEEN CURRENT_DATE AND CURRENT_DATE+30`),
 db.query(`SELECT COUNT(*)::int count FROM crm_guest_profiles WHERE COALESCE(last_visit_at,first_visit_at,updated_at)<now()-($1::text||' days')::interval`,[s.inactive_guest_days]),
 db.query(`SELECT COUNT(*)::int count FROM clients WHERE birth_date IS NOT NULL AND ((to_char(birth_date,'MM-DD')>=to_char(CURRENT_DATE,'MM-DD') AND to_char(birth_date,'MM-DD')<=to_char(CURRENT_DATE+$1::int,'MM-DD')) OR (to_char(CURRENT_DATE,'MM-DD')>to_char(CURRENT_DATE+$1::int,'MM-DD') AND (to_char(birth_date,'MM-DD')>=to_char(CURRENT_DATE,'MM-DD') OR to_char(birth_date,'MM-DD')<=to_char(CURRENT_DATE+$1::int,'MM-DD'))))`,[s.birthday_window_days]).catch(()=>({rows:[{count:0}]} as any)),
 db.query(`SELECT COUNT(*)::int count FROM loyalty_campaign_suggestions WHERE status='suggested'`)
 ]);res.json({settings:s,expiring_passes:Number(pass.rows[0]?.count||0),expiring_vouchers:Number(voucher.rows[0]?.count||0),expiring_voucher_value:Number(voucher.rows[0]?.value||0),expiring_points_accounts:Number(points.rows[0]?.count||0),expiring_points:Number(points.rows[0]?.points||0),inactive_guests:Number(inactive.rows[0]?.count||0),upcoming_birthdays:Number(bday.rows[0]?.count||0),open_suggestions:Number(suggestions.rows[0]?.count||0)})}catch(e){next(e)}});

router.get('/suggestions',async(_req,res,next)=>{try{const{rows}=await db.query(`SELECT * FROM loyalty_campaign_suggestions ORDER BY CASE status WHEN 'suggested' THEN 0 ELSE 1 END,created_at DESC LIMIT 300`);res.json(rows)}catch(e){next(e)}});

router.post('/run',async(req:AuthRequest,res,next)=>{const c=await db.connect();try{await c.query('BEGIN');const s=(await c.query(`SELECT * FROM loyalty_automation_settings WHERE active=true ORDER BY location_id NULLS FIRST LIMIT 1`)).rows[0]||{pass_expiry_days:14,voucher_expiry_days:14,inactive_guest_days:90,birthday_window_days:7,birthday_discount_percent:10,inactive_discount_percent:10};let created=0;
 const passes=(await c.query(`SELECT p.id,p.account_id,p.valid_until,a.customer_id,t.name FROM loyalty_passes p JOIN loyalty_accounts a ON a.id=p.account_id JOIN loyalty_pass_types t ON t.id=p.pass_type_id WHERE p.status='active' AND p.valid_until BETWEEN CURRENT_DATE AND CURRENT_DATE+$1::int`,[s.pass_expiry_days])).rows;for(const x of passes){const k=`pass_expiry:${x.id}:${x.valid_until}`;const r=await c.query(`INSERT INTO loyalty_campaign_suggestions(suggestion_key,customer_id,account_id,suggestion_type,title,detail,recommended_valid_until,payload) VALUES($1,$2,$3,'pass_expiry',$4,$5,$6,$7::jsonb) ON CONFLICT(suggestion_key) DO NOTHING RETURNING id`,[k,String(x.customer_id),x.account_id,`Hamarosan lejáró bérlet: ${x.name}`,`Lejárat: ${x.valid_until}. Javasolt hosszabbítási ajánlat.`,x.valid_until,JSON.stringify({pass_id:x.id,generated_by:actor(req)})]);if(r.rows[0])created++}
 const vouchers=(await c.query(`SELECT id,code,owner_customer_id,remaining_value,valid_until FROM loyalty_vouchers WHERE status='active' AND remaining_value>0 AND valid_until BETWEEN CURRENT_DATE AND CURRENT_DATE+$1::int`,[s.voucher_expiry_days])).rows;for(const x of vouchers){const k=`voucher_expiry:${x.id}:${x.valid_until}`;const r=await c.query(`INSERT INTO loyalty_campaign_suggestions(suggestion_key,customer_id,suggestion_type,title,detail,recommended_valid_until,payload) VALUES($1,$2,'voucher_expiry',$3,$4,$5,$6::jsonb) ON CONFLICT(suggestion_key) DO NOTHING RETURNING id`,[k,x.owner_customer_id||null,`Lejáró ajándékutalvány: ${x.code}`,`Maradványérték: ${Number(x.remaining_value).toLocaleString('hu-HU')} Ft. Lejárat: ${x.valid_until}.`,x.valid_until,JSON.stringify({voucher_id:x.id,generated_by:actor(req)})]);if(r.rows[0])created++}
 const points=(await c.query(`SELECT id,customer_id,points,points_expires_at FROM loyalty_accounts WHERE status='active' AND points>0 AND points_expires_at BETWEEN CURRENT_DATE AND CURRENT_DATE+30`)).rows;for(const x of points){const k=`points_expiry:${x.id}:${x.points_expires_at}`;const r=await c.query(`INSERT INTO loyalty_campaign_suggestions(suggestion_key,customer_id,account_id,suggestion_type,title,detail,recommended_valid_until,payload) VALUES($1,$2,$3,'points_expiry','Hamarosan lejáró hűségpontok',$4,$5,$6::jsonb) ON CONFLICT(suggestion_key) DO NOTHING RETURNING id`,[k,String(x.customer_id),x.id,`${x.points} pont jár le ${x.points_expires_at} napján.`,x.points_expires_at,JSON.stringify({generated_by:actor(req)})]);if(r.rows[0])created++}
 const inactive=(await c.query(`SELECT contact_key,client_name FROM crm_guest_profiles WHERE COALESCE(last_visit_at,first_visit_at,updated_at)<now()-($1::text||' days')::interval ORDER BY COALESCE(last_visit_at,first_visit_at,updated_at) ASC LIMIT 200`,[s.inactive_guest_days])).rows;for(const x of inactive){const k=`inactive_guest:${x.contact_key}:${new Date().toISOString().slice(0,7)}`;const r=await c.query(`INSERT INTO loyalty_campaign_suggestions(suggestion_key,customer_id,suggestion_type,title,detail,discount_type,discount_value,recommended_valid_until,payload) VALUES($1,$2,'inactive_guest',$3,$4,'percent',$5,CURRENT_DATE+14,$6::jsonb) ON CONFLICT(suggestion_key) DO NOTHING RETURNING id`,[k,x.contact_key,`Visszacsábító ajánlat: ${x.client_name||'vendég'}`,`${s.inactive_guest_days}+ napja nem járt a szalonban.`,Number(s.inactive_discount_percent||10),JSON.stringify({generated_by:actor(req)})]);if(r.rows[0])created++}
 await c.query('COMMIT');res.json({ok:true,created})}catch(e){await c.query('ROLLBACK');next(e)}finally{c.release()}});

router.patch('/suggestions/:id',async(req,res,next)=>{try{const status=String(req.body?.status||'');if(!['suggested','approved','dismissed','converted'].includes(status))return res.status(400).json({message:'Érvénytelen státusz.'});const{rows}=await db.query(`UPDATE loyalty_campaign_suggestions SET status=$2,updated_at=now() WHERE id=$1::uuid RETURNING *`,[req.params.id,status]);res.json(rows[0])}catch(e){next(e)}});
export default router;
