import {Router} from 'express';
import db from '../db';
import {requireAuth,AuthRequest} from '../middleware/auth';
import {requireIdempotencyKey} from '../finance/financialIntegrity';
import {recordProtectedWorkOrderPayment} from '../finance/workOrderPaymentIntegrity';
const router=Router();router.use(requireAuth);
const actor=(r:AuthRequest)=>r.user?.email||String(r.user?.id||'');
const money=(v:any)=>Math.round(Number(v||0)*100)/100;
const METHODS=new Set(['cash','card','transfer','other']);

router.get('/workorders/:id/options',async(req,res,next)=>{try{
 const wo=await db.query(`SELECT wo.*,COALESCE(SUM(i.line_total),0)::numeric gross_total FROM work_orders wo LEFT JOIN work_order_items i ON i.work_order_id=wo.id WHERE wo.id=$1 GROUP BY wo.id`,[req.params.id]);
 if(!wo.rows[0])return res.status(404).json({message:'A munkalap nem található.'});
 const items=await db.query(`SELECT item_type,service_id,product_id,item_name,quantity,unit_price,line_total FROM work_order_items WHERE work_order_id=$1 ORDER BY created_at`,[req.params.id]);
 const accounts=await db.query(`SELECT id,customer_id,balance,points,card_identifier FROM loyalty_accounts WHERE status='active' ORDER BY updated_at DESC LIMIT 250`);
 res.json({work_order:wo.rows[0],items:items.rows,accounts:accounts.rows});
}catch(e){next(e)}});

router.post('/workorders/:id/settle',async(req:AuthRequest,res,next)=>{const c=await db.connect();try{
 const settlementKey=requireIdempotencyKey(req,'loyalty-settlement'),requestPayload=JSON.stringify(req.body||{});
 await c.query('BEGIN');
 const operation=(await c.query(`SELECT *,request_payload=$2::jsonb same_payload FROM work_order_settlements WHERE settlement_key=$1 FOR UPDATE`,[settlementKey,requestPayload])).rows[0];
 if(operation){if(String(operation.work_order_id)!==String(req.params.id)||!operation.same_payload){await c.query('ROLLBACK');return res.status(409).json({message:'Az Idempotency-Key már más munkalaphoz vagy eltérő tartalmú hűségpénztári záráshoz lett felhasználva.'})}const previous=(await c.query(`SELECT * FROM loyalty_checkout_settlements WHERE work_order_id=$1`,[req.params.id])).rows[0]||null;await c.query('COMMIT');return res.json({idempotent:true,settlement:previous})}
 const existing=await c.query(`SELECT * FROM loyalty_checkout_settlements WHERE work_order_id=$1 FOR UPDATE`,[req.params.id]);
 if(existing.rows[0]){await c.query('ROLLBACK');return res.status(409).json({message:'A munkalap hűségpénztári zárása már megtörtént; új műveleti kulccsal nem ismételhető.'})}
 const woq=await c.query(`SELECT * FROM work_orders WHERE id=$1 FOR UPDATE`,[req.params.id]);if(!woq.rows[0]){await c.query('ROLLBACK');return res.status(404).json({message:'A munkalap nem található.'})}
 const wo=woq.rows[0];const items=(await c.query(`SELECT item_type,service_id,product_id,item_name,quantity,unit_price,line_total FROM work_order_items WHERE work_order_id=$1`,[req.params.id])).rows;
 await c.query(`INSERT INTO work_order_settlements(work_order_id,settlement_key,request_payload,created_by) VALUES($1,$2,$3::jsonb,$4)`,[req.params.id,settlementKey,requestPayload,actor(req)]);
 const gross=money(items.reduce((s:number,x:any)=>s+Number(x.line_total||0),0));const manualDiscount=Math.max(0,money(req.body?.discount_amount));const tip=Math.max(0,money(req.body?.tip_amount));
 const accountId=String(req.body?.account_id||'').trim()||null;let customerId:String|null=null;let account:any=null;if(accountId){const a=await c.query(`SELECT * FROM loyalty_accounts WHERE id=$1::uuid FOR UPDATE`,[accountId]);if(!a.rows[0])throw new Error('A vendég wallet nem található.');account=a.rows[0];customerId=String(account.customer_id||'')||null}
 const serviceIds=new Set(items.filter((x:any)=>x.item_type==='service'&&x.service_id!=null).map((x:any)=>String(x.service_id)));const productIds=new Set(items.filter((x:any)=>x.item_type==='product'&&x.product_id!=null).map((x:any)=>String(x.product_id)));
 let couponDiscount=0,pointsDiscount=0,pointsSpent=0,walletUsed=0,voucherUsed=0,passValueUsed=0,pointsEarned=0,paymentSequence=0;let discountBase=Math.max(0,gross-manualDiscount);
 if(req.body?.coupon_code){const q=await c.query(`SELECT x.*,cc.discount_type,cc.discount_value,cc.usage_mode,cc.valid_from,cc.valid_until,cc.min_order_value,cc.max_discount_value FROM loyalty_coupons x JOIN loyalty_coupon_campaigns cc ON cc.id=x.campaign_id WHERE upper(x.code)=upper($1) AND x.active=true AND cc.active=true FOR UPDATE`,[String(req.body.coupon_code)]);const x=q.rows[0];if(!x)throw new Error('Kupon nem található.');if((x.valid_from&&new Date(x.valid_from)>new Date())||(x.valid_until&&new Date(x.valid_until)<new Date()))throw new Error('A kupon nem érvényes.');if(x.usage_mode==='single'&&Number(x.usage_count)>0)throw new Error('A kupon már felhasználásra került.');if(x.usage_mode==='once_per_customer'&&customerId){const used=await c.query(`SELECT 1 FROM loyalty_coupon_usages WHERE coupon_id=$1 AND customer_id=$2 LIMIT 1`,[x.id,customerId]);if(used.rows[0])throw new Error('A vendég ezt a kupont már felhasználta.')}if(gross<Number(x.min_order_value||0))throw new Error('A kupon minimum kosárértéke nem teljesül.');const rr=(await c.query(`SELECT target_type,target_id FROM loyalty_coupon_restrictions WHERE campaign_id=$1`,[x.campaign_id])).rows;if(rr.length&&!rr.some((r:any)=>r.target_type==='service'?serviceIds.has(String(r.target_id)):productIds.has(String(r.target_id))))throw new Error('A kupon a munkalap tételeire nem érvényes.');couponDiscount=x.discount_type==='percent'?Math.min(discountBase,discountBase*Number(x.discount_value)/100):Math.min(discountBase,Number(x.discount_value));if(x.max_discount_value!=null)couponDiscount=Math.min(couponDiscount,Number(x.max_discount_value));discountBase=Math.max(0,discountBase-couponDiscount);await c.query(`INSERT INTO loyalty_coupon_usages(coupon_id,customer_id,work_order_id,discount_amount,created_by) VALUES($1,$2,$3,$4,$5)`,[x.id,customerId,req.params.id,couponDiscount,actor(req)]);await c.query(`UPDATE loyalty_coupons SET usage_count=usage_count+1 WHERE id=$1`,[x.id])}
 for(const u of Array.isArray(req.body?.pass_usages)?req.body.pass_usages:[]){const qty=Math.max(1,Number(u.quantity||1));const sid=String(u.service_id||'');if(!u.pass_id||!sid)continue;const b=await c.query(`UPDATE loyalty_pass_balances SET remaining_quantity=remaining_quantity-$3 WHERE pass_id=$1::uuid AND service_id=$2 AND remaining_quantity>=$3 RETURNING *`,[String(u.pass_id),sid,qty]);if(!b.rows[0])throw new Error('A bérleten nincs elegendő felhasználható alkalom.');await c.query(`INSERT INTO loyalty_pass_usages(pass_id,service_id,quantity,work_order_id,created_by) VALUES($1,$2,$3,$4,$5)`,[String(u.pass_id),sid,qty,req.params.id,actor(req)]);const item=items.find((x:any)=>x.item_type==='service'&&String(x.service_id)===sid);passValueUsed+=Math.min(discountBase,Number(item?.unit_price||0)*qty);discountBase=Math.max(0,discountBase-Math.min(discountBase,Number(item?.unit_price||0)*qty))}
 if(account&&Number(req.body?.points_to_spend||0)>0){const rule=(await c.query(`SELECT * FROM loyalty_points_rules WHERE active=true AND (valid_from IS NULL OR valid_from<=CURRENT_DATE) AND (valid_until IS NULL OR valid_until>=CURRENT_DATE) ORDER BY created_at DESC LIMIT 1`)).rows[0];const pointValue=Math.max(.01,Number(rule?.point_value||1));pointsDiscount=Math.min(discountBase,Number(req.body.points_to_spend)*pointValue);pointsSpent=Math.ceil(pointsDiscount/pointValue);const a=await c.query(`UPDATE loyalty_accounts SET points=points-$2,updated_at=now() WHERE id=$1::uuid AND points>=$2 RETURNING *`,[accountId,pointsSpent]);if(!a.rows[0])throw new Error('Nincs elegendő hűségpont.');discountBase=Math.max(0,discountBase-pointsDiscount);await c.query(`INSERT INTO loyalty_transactions(account_id,transaction_type,points,amount,work_order_id,reference_type,reference_id,note,created_by) VALUES($1,'points_spend',$2*-1,$3*-1,$4,'work_order',$4,'Pontbeváltás pénztárban',$5)`,[accountId,pointsSpent,pointsDiscount,req.params.id,actor(req)])}
 const amountDueBeforeTender=Math.max(0,money(gross-manualDiscount-couponDiscount-passValueUsed-pointsDiscount+tip));
 if(account&&Number(req.body?.wallet_amount||0)>0){walletUsed=Math.min(amountDueBeforeTender,Number(req.body.wallet_amount));const a=await c.query(`UPDATE loyalty_accounts SET balance=balance-$2,updated_at=now() WHERE id=$1::uuid AND balance>=$2 RETURNING *`,[accountId,walletUsed]);if(!a.rows[0])throw new Error('Nincs elegendő vendégegyenleg.');await c.query(`INSERT INTO loyalty_transactions(account_id,transaction_type,amount,work_order_id,reference_type,reference_id,note,created_by) VALUES($1,'balance_spend',$2*-1,$3,'work_order',$3,'Wallet fizetés pénztárban',$4)`,[accountId,walletUsed,req.params.id,actor(req)]);if(walletUsed>0)await recordProtectedWorkOrderPayment(c,{workOrder:wo,method:'other',amount:walletUsed,note:'Hűség wallet',actor:actor(req),settlementKey,sequence:paymentSequence++,recognition:'prepaid_redemption'})}
 let afterWallet=Math.max(0,amountDueBeforeTender-walletUsed);
 if(req.body?.voucher_code&&Number(req.body?.voucher_amount||0)>0){const v=(await c.query(`SELECT * FROM loyalty_vouchers WHERE upper(code)=upper($1) AND status='active' AND (valid_until IS NULL OR valid_until>=CURRENT_DATE) FOR UPDATE`,[String(req.body.voucher_code)])).rows[0];if(!v)throw new Error('Az ajándékutalvány nem érvényes.');voucherUsed=Math.min(afterWallet,Number(req.body.voucher_amount),Number(v.remaining_value||0));if(!(voucherUsed>0))throw new Error('Az ajándékutalványon nincs felhasználható egyenleg.');await c.query(`UPDATE loyalty_vouchers SET remaining_value=remaining_value-$2,status=CASE WHEN remaining_value-$2<=0 THEN 'used' ELSE status END WHERE id=$1`,[v.id,voucherUsed]);await c.query(`INSERT INTO loyalty_voucher_usages(voucher_id,customer_id,work_order_id,amount,created_by) VALUES($1,$2,$3,$4,$5)`,[v.id,customerId,req.params.id,voucherUsed,actor(req)]);await recordProtectedWorkOrderPayment(c,{workOrder:wo,method:'voucher',amount:voucherUsed,note:`Ajándékutalvány ${v.code}`,actor:actor(req),settlementKey,sequence:paymentSequence++,recognition:'voucher_redemption'});if(wo.employee_id)await c.query(`INSERT INTO loyalty_commission_events(employee_id,work_order_id,source_type,source_id,base_amount,note) VALUES($1,$2,'voucher_redemption',$3,$4,'Ajándékutalvány beváltás jutalékalap') ON CONFLICT(employee_id,source_type,source_id,work_order_id) DO UPDATE SET base_amount=EXCLUDED.base_amount`,[String(wo.employee_id),req.params.id,String(v.id),voucherUsed])}
 let regularRemaining=Math.max(0,amountDueBeforeTender-walletUsed-voucherUsed);const normalPayments=Array.isArray(req.body?.payments)?req.body.payments:[];for(const p of normalPayments){if(regularRemaining<=0)break;const method=String(p?.payment_method||'').toLowerCase();const requested=money(p?.amount);if(!METHODS.has(method))throw new Error(`Érvénytelen fizetési mód: ${method}`);const amount=Math.min(regularRemaining,Math.max(0,requested));if(amount>0){await recordProtectedWorkOrderPayment(c,{workOrder:wo,method,amount,note:p?.note||null,actor:actor(req),settlementKey,sequence:paymentSequence++,financeAccountId:p?.finance_account_id||null,paymentMethodCode:p?.payment_method_code||method,cashierShiftId:p?.cashier_shift_id||null,feeAmount:money(p?.fee_amount)});regularRemaining=money(regularRemaining-amount)}}
 const paid=money((await c.query(`SELECT COALESCE(SUM(amount),0)::numeric paid FROM work_order_payments WHERE work_order_id=$1`,[req.params.id])).rows[0]?.paid);const discountTotal=money(manualDiscount+couponDiscount+passValueUsed+pointsDiscount);const amountDue=money(gross-discountTotal+tip);const paymentStatus=paid<=0?'unpaid':paid+.009<amountDue?'partial':'paid';const close=Boolean(req.body?.close_financially);if(close&&paymentStatus!=='paid')throw new Error(`A munkalap nem zárható pénzügyileg: még ${money(amountDue-paid)} Ft fizetendő.`);
 if(account){const rule=(await c.query(`SELECT * FROM loyalty_points_rules WHERE active=true AND (valid_from IS NULL OR valid_from<=CURRENT_DATE) AND (valid_until IS NULL OR valid_until>=CURRENT_DATE) ORDER BY created_at DESC LIMIT 1`)).rows[0];if(rule&&Number(rule.spend_amount)>0){const eligible=Math.max(0,gross-manualDiscount-couponDiscount-passValueUsed-pointsDiscount);pointsEarned=Math.floor(eligible/Number(rule.spend_amount))*Number(rule.points_earned||0);if(pointsEarned>0){await c.query(`UPDATE loyalty_accounts SET points=points+$2,updated_at=now() WHERE id=$1::uuid`,[accountId,pointsEarned]);await c.query(`INSERT INTO loyalty_transactions(account_id,transaction_type,points,work_order_id,reference_type,reference_id,note,created_by) VALUES($1,'points_earn',$2,$3,'work_order',$3,'Automatikus pontjóváírás pénzügyi záráskor',$4)`,[accountId,pointsEarned,req.params.id,actor(req)])}}}
 const updated=(await c.query(`UPDATE work_orders SET gross_total=$2,discount_amount=$3,tip_amount=$4,amount_due=$5,amount_paid=$6,payment_status=$7,fully_paid=($7='paid'),invoice_status=$8,financial_closed_at=CASE WHEN $9 THEN COALESCE(financial_closed_at,now()) ELSE financial_closed_at END,financial_closed_by=CASE WHEN $9 THEN COALESCE(financial_closed_by,$10) ELSE financial_closed_by END,updated_at=now() WHERE id=$1 RETURNING *`,[req.params.id,gross,discountTotal,tip,amountDue,paid,paymentStatus,String(req.body?.invoice_status||'not_requested'),close,actor(req)])).rows[0];
 const settlement=(await c.query(`INSERT INTO loyalty_checkout_settlements(work_order_id,account_id,customer_id,coupon_code,coupon_discount,points_spent,points_discount,wallet_used,voucher_code,voucher_used,pass_value_used,cash_due,points_earned,payload,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14::jsonb,$15) RETURNING *`,[req.params.id,accountId,customerId,req.body?.coupon_code||null,couponDiscount,pointsSpent,pointsDiscount,walletUsed,req.body?.voucher_code||null,voucherUsed,passValueUsed,Math.max(0,amountDue-walletUsed-voucherUsed),pointsEarned,JSON.stringify(req.body||{}),actor(req)])).rows[0];
 await c.query(`UPDATE work_order_settlements SET completed_at=now(),result_snapshot=$2::jsonb WHERE settlement_key=$1`,[settlementKey,JSON.stringify({work_order_id:req.params.id,loyalty_settlement_id:settlement.id,payment_status:updated.payment_status,amount_paid:updated.amount_paid,financial_closed_at:updated.financial_closed_at||null})]);
 await c.query('COMMIT');res.json({work_order:updated,settlement});
}catch(e:any){await c.query('ROLLBACK');const m=String(e?.message||'Hűség pénztári lezárási hiba');if(/Kupon|bérlet|pont|wallet|utalvány|fizetési|zárható|Érvénytelen/i.test(m))return res.status(409).json({message:m});next(e)}finally{c.release()}});
export default router;
