import { Router } from 'express';
import db from '../db';
import { requireAuth, AuthRequest } from '../middleware/auth';

const router = Router();
router.use(requireAuth);
const actor=(req:AuthRequest)=>req.user?.email||String(req.user?.id||'');

router.get('/summary', async (_req,res,next)=>{try{
  const {rows}=await db.query(`SELECT
    (SELECT COUNT(*)::int FROM loyalty_accounts WHERE status='active') active_accounts,
    (SELECT COALESCE(SUM(balance),0) FROM loyalty_accounts WHERE status='active') total_balance,
    (SELECT COALESCE(SUM(points),0) FROM loyalty_accounts WHERE status='active') total_points,
    (SELECT COUNT(*)::int FROM loyalty_passes WHERE status='active' AND (valid_until IS NULL OR valid_until>=CURRENT_DATE)) active_passes,
    (SELECT COUNT(*)::int FROM loyalty_coupons WHERE active=true) active_coupons,
    (SELECT COUNT(*)::int FROM loyalty_vouchers WHERE status='active' AND remaining_value>0) active_vouchers`);
  res.json(rows[0]);
}catch(err){next(err)}});

router.get('/accounts', async (req,res,next)=>{try{
  const q=String(req.query.q||'').trim();
  const {rows}=await db.query(`SELECT a.* FROM loyalty_accounts a WHERE ($1='' OR a.customer_id ILIKE '%'||$1||'%' OR COALESCE(a.card_identifier,'') ILIKE '%'||$1||'%') ORDER BY a.updated_at DESC LIMIT 200`,[q]);
  res.json(rows);
}catch(err){next(err)}});

router.post('/accounts', async (req:AuthRequest,res,next)=>{try{
  const customerId=String(req.body?.customer_id||'').trim(); if(!customerId)return res.status(400).json({message:'customer_id kötelező'});
  const {rows}=await db.query(`INSERT INTO loyalty_accounts(customer_id,card_identifier,external_identifier) VALUES($1,$2,$3) ON CONFLICT(customer_id) DO UPDATE SET card_identifier=COALESCE(EXCLUDED.card_identifier,loyalty_accounts.card_identifier), external_identifier=COALESCE(EXCLUDED.external_identifier,loyalty_accounts.external_identifier), updated_at=now() RETURNING *`,[customerId,req.body?.card_identifier||null,req.body?.external_identifier||null]);
  res.status(201).json(rows[0]);
}catch(err){next(err)}});

router.post('/accounts/:id/topup', async (req:AuthRequest,res,next)=>{const client=await db.connect();try{
  const amount=Number(req.body?.amount||0); if(!(amount>0))return res.status(400).json({message:'A feltöltési összeg legyen pozitív.'});
  await client.query('BEGIN');
  const acc=await client.query(`UPDATE loyalty_accounts SET balance=balance+$2,updated_at=now() WHERE id=$1::uuid RETURNING *`,[req.params.id,amount]);
  if(!acc.rows[0]){await client.query('ROLLBACK');return res.status(404).json({message:'Hűségszámla nem található.'})}
  const tx=await client.query(`INSERT INTO loyalty_transactions(account_id,transaction_type,amount,work_order_id,reference_type,reference_id,note,created_by) VALUES($1,'balance_topup',$2,$3,'topup',$4,$5,$6) RETURNING id`,[req.params.id,amount,req.body?.work_order_id||null,req.body?.reference_id||null,req.body?.note||null,actor(req)]);
  await client.query(`INSERT INTO loyalty_sales(sale_type,reference_id,account_id,customer_id,employee_id,work_order_id,gross_amount,commission_base,revenue_recognized,note,created_by) VALUES('wallet_topup',$1,$2,$3,$4,$5,$6,$6,true,$7,$8)`,[String(tx.rows[0].id),req.params.id,acc.rows[0].customer_id,req.body?.employee_id||null,req.body?.work_order_id||null,amount,req.body?.note||null,actor(req)]);
  await client.query('COMMIT'); res.json(acc.rows[0]);
}catch(err){await client.query('ROLLBACK');next(err)}finally{client.release()}});

router.get('/accounts/:id/transactions',async(req,res,next)=>{try{const{rows}=await db.query(`SELECT * FROM loyalty_transactions WHERE account_id=$1::uuid ORDER BY created_at DESC LIMIT 250`,[req.params.id]);res.json(rows)}catch(err){next(err)}});

router.get('/pass-types',async(_req,res,next)=>{try{const{rows}=await db.query(`SELECT p.*,COALESCE(json_agg(json_build_object('service_id',s.service_id,'quantity',s.quantity)) FILTER(WHERE s.id IS NOT NULL),'[]') services FROM loyalty_pass_types p LEFT JOIN loyalty_pass_type_services s ON s.pass_type_id=p.id GROUP BY p.id ORDER BY p.name`);res.json(rows)}catch(err){next(err)}});
router.post('/pass-types',async(req,res,next)=>{const client=await db.connect();try{await client.query('BEGIN');const r=await client.query(`INSERT INTO loyalty_pass_types(name,product_id,valid_days,validity_start_mode,sale_price,renewal_mode,renewal_days) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[req.body?.name,req.body?.product_id||null,req.body?.valid_days||null,req.body?.validity_start_mode||'sale',Number(req.body?.sale_price||0),req.body?.renewal_mode||'extend',req.body?.renewal_days||null]);for(const s of (req.body?.services||[]))await client.query(`INSERT INTO loyalty_pass_type_services(pass_type_id,service_id,quantity) VALUES($1,$2,$3)`,[r.rows[0].id,String(s.service_id),Number(s.quantity||1)]);await client.query('COMMIT');res.status(201).json(r.rows[0])}catch(err){await client.query('ROLLBACK');next(err)}finally{client.release()}});

router.get('/passes',async(_req,res,next)=>{try{const{rows}=await db.query(`SELECT p.*,t.name pass_type_name,t.sale_price,a.customer_id,COALESCE((SELECT SUM(remaining_quantity) FROM loyalty_pass_balances b WHERE b.pass_id=p.id),0) remaining_units FROM loyalty_passes p JOIN loyalty_pass_types t ON t.id=p.pass_type_id JOIN loyalty_accounts a ON a.id=p.account_id ORDER BY p.created_at DESC LIMIT 250`);res.json(rows)}catch(err){next(err)}});
router.post('/passes',async(req:AuthRequest,res,next)=>{const client=await db.connect();try{await client.query('BEGIN');const type=await client.query(`SELECT * FROM loyalty_pass_types WHERE id=$1::uuid`,[req.body?.pass_type_id]);if(!type.rows[0])throw new Error('Bérlettípus nem található');const t=type.rows[0];const from=req.body?.valid_from||new Date().toISOString().slice(0,10);const renew=String(req.body?.renew_existing??'true')!=='false'&&t.renewal_mode==='extend';let pass:any=null;let renewed=false;if(renew){const current=await client.query(`SELECT * FROM loyalty_passes WHERE account_id=$1::uuid AND pass_type_id=$2::uuid AND status='active' ORDER BY COALESCE(valid_until,CURRENT_DATE) DESC LIMIT 1 FOR UPDATE`,[req.body?.account_id,req.body?.pass_type_id]);if(current.rows[0]){pass=current.rows[0];renewed=true;const extraDays=Number(t.renewal_days||t.valid_days||0);await client.query(`UPDATE loyalty_passes SET valid_until=CASE WHEN $2::int>0 THEN GREATEST(COALESCE(valid_until,CURRENT_DATE),CURRENT_DATE)+$2::int ELSE valid_until END,updated_at=now() WHERE id=$1`,[pass.id,extraDays]);await client.query(`UPDATE loyalty_pass_balances b SET original_quantity=b.original_quantity+s.quantity,remaining_quantity=b.remaining_quantity+s.quantity FROM loyalty_pass_type_services s WHERE b.pass_id=$1 AND s.pass_type_id=$2 AND s.service_id=b.service_id`,[pass.id,req.body?.pass_type_id]);}}
if(!pass){const r=await client.query(`INSERT INTO loyalty_passes(account_id,pass_type_id,valid_from,valid_until) VALUES($1::uuid,$2::uuid,$3::date,CASE WHEN $4::int IS NULL THEN NULL ELSE ($3::date + $4::int) END) RETURNING *`,[req.body?.account_id,req.body?.pass_type_id,from,t.valid_days]);pass=r.rows[0];await client.query(`INSERT INTO loyalty_pass_balances(pass_id,service_id,original_quantity,remaining_quantity) SELECT $1,service_id,quantity,quantity FROM loyalty_pass_type_services WHERE pass_type_id=$2`,[pass.id,req.body?.pass_type_id]);}
const account=await client.query(`SELECT customer_id FROM loyalty_accounts WHERE id=$1::uuid`,[req.body?.account_id]);const price=Number(req.body?.sale_price??t.sale_price??0);if(price>0)await client.query(`INSERT INTO loyalty_sales(sale_type,reference_id,account_id,customer_id,employee_id,work_order_id,gross_amount,commission_base,revenue_recognized,note,created_by) VALUES('pass',$1,$2,$3,$4,$5,$6,$6,true,$7,$8)`,[String(pass.id),req.body?.account_id,account.rows[0]?.customer_id||null,req.body?.employee_id||null,req.body?.work_order_id||null,price,renewed?'Bérlet hosszabbítás':'Bérlet értékesítés',actor(req)]);await client.query('COMMIT');res.status(201).json({...pass,renewed})}catch(err){await client.query('ROLLBACK');next(err)}finally{client.release()}});

router.get('/coupon-campaigns',async(_req,res,next)=>{try{const{rows}=await db.query(`SELECT c.*,COUNT(DISTINCT x.id)::int code_count,COALESCE(json_agg(DISTINCT jsonb_build_object('target_type',r.target_type,'target_id',r.target_id)) FILTER(WHERE r.id IS NOT NULL),'[]') restrictions FROM loyalty_coupon_campaigns c LEFT JOIN loyalty_coupons x ON x.campaign_id=c.id LEFT JOIN loyalty_coupon_restrictions r ON r.campaign_id=c.id GROUP BY c.id ORDER BY c.created_at DESC`);res.json(rows)}catch(err){next(err)}});
router.post('/coupon-campaigns',async(req,res,next)=>{const client=await db.connect();try{await client.query('BEGIN');const c=await client.query(`INSERT INTO loyalty_coupon_campaigns(name,discount_type,discount_value,valid_from,valid_until,usage_mode,applies_to_all,min_order_value,max_discount_value) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[req.body?.name,req.body?.discount_type||'percent',Number(req.body?.discount_value||0),req.body?.valid_from||null,req.body?.valid_until||null,req.body?.usage_mode||'single',req.body?.applies_to_all!==false,Number(req.body?.min_order_value||0),req.body?.max_discount_value?Number(req.body.max_discount_value):null]);for(const r of (req.body?.restrictions||[]))if(r?.target_type&&r?.target_id)await client.query(`INSERT INTO loyalty_coupon_restrictions(campaign_id,target_type,target_id) VALUES($1,$2,$3) ON CONFLICT DO NOTHING`,[c.rows[0].id,r.target_type,String(r.target_id)]);const count=Math.max(0,Math.min(1000,Number(req.body?.generate_count||0)));for(let i=0;i<count;i++){const code=`KLEO-${Date.now().toString(36).toUpperCase()}-${i.toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;await client.query(`INSERT INTO loyalty_coupons(campaign_id,code) VALUES($1,$2)`,[c.rows[0].id,code])}if(req.body?.manual_code)await client.query(`INSERT INTO loyalty_coupons(campaign_id,code) VALUES($1,$2)`,[c.rows[0].id,String(req.body.manual_code).trim()]);await client.query('COMMIT');res.status(201).json(c.rows[0])}catch(err){await client.query('ROLLBACK');next(err)}finally{client.release()}});
router.get('/coupons/validate/:code',async(req,res,next)=>{try{const{rows}=await db.query(`SELECT x.*,c.name campaign_name,c.discount_type,c.discount_value,c.valid_from,c.valid_until,c.usage_mode,c.min_order_value,c.max_discount_value,c.applies_to_all FROM loyalty_coupons x JOIN loyalty_coupon_campaigns c ON c.id=x.campaign_id WHERE upper(x.code)=upper($1) AND x.active=true AND c.active=true`,[req.params.code]);const x=rows[0];if(!x)return res.status(404).json({valid:false,message:'Kupon nem található.'});const now=Date.now();const gross=Number(req.query.gross_amount||0);const validDate=(!x.valid_from||new Date(x.valid_from).getTime()<=now)&&(!x.valid_until||new Date(x.valid_until).getTime()>=now);const validUsage=x.usage_mode==='multiple'||Number(x.usage_count||0)===0;const validMin=gross<=0||gross>=Number(x.min_order_value||0);const rr=await db.query(`SELECT target_type,target_id FROM loyalty_coupon_restrictions WHERE campaign_id=$1`,[x.campaign_id]);res.json({valid:validDate&&validUsage&&validMin,coupon:x,restrictions:rr.rows})}catch(err){next(err)}});

router.get('/voucher-types',async(_req,res,next)=>{try{const{rows}=await db.query(`SELECT t.*,COALESCE(json_agg(json_build_object('target_type',r.target_type,'target_id',r.target_id,'quantity',r.quantity)) FILTER(WHERE r.id IS NOT NULL),'[]') restrictions FROM loyalty_voucher_types t LEFT JOIN loyalty_voucher_type_restrictions r ON r.voucher_type_id=t.id GROUP BY t.id ORDER BY t.name`);res.json(rows)}catch(err){next(err)}});
router.post('/voucher-types',async(req,res,next)=>{const client=await db.connect();try{await client.query('BEGIN');const t=await client.query(`INSERT INTO loyalty_voucher_types(name,face_value,valid_days,applies_to_all) VALUES($1,$2,$3,$4) RETURNING *`,[req.body?.name,Number(req.body?.face_value||0),req.body?.valid_days||null,req.body?.applies_to_all!==false]);for(const r of (req.body?.restrictions||[]))if(r?.target_type&&r?.target_id)await client.query(`INSERT INTO loyalty_voucher_type_restrictions(voucher_type_id,target_type,target_id,quantity) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING`,[t.rows[0].id,r.target_type,String(r.target_id),r.quantity?Number(r.quantity):null]);await client.query('COMMIT');res.status(201).json(t.rows[0])}catch(err){await client.query('ROLLBACK');next(err)}finally{client.release()}});
router.get('/vouchers',async(_req,res,next)=>{try{const{rows}=await db.query(`SELECT v.*,t.name voucher_type_name FROM loyalty_vouchers v LEFT JOIN loyalty_voucher_types t ON t.id=v.voucher_type_id ORDER BY v.created_at DESC LIMIT 250`);res.json(rows)}catch(err){next(err)}});
router.post('/vouchers',async(req:AuthRequest,res,next)=>{const client=await db.connect();try{await client.query('BEGIN');let vt=req.body?.voucher_type_id||null;let value=Number(req.body?.value||0),days=req.body?.valid_days||null;if(vt){const t=await client.query(`SELECT * FROM loyalty_voucher_types WHERE id=$1::uuid`,[vt]);if(t.rows[0]){value=Number(t.rows[0].face_value);days=t.rows[0].valid_days}}if(!(value>0)){await client.query('ROLLBACK');return res.status(400).json({message:'Az utalvány értéke kötelező.'})}const code=req.body?.code||`KLEO-GIFT-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;const r=await client.query(`INSERT INTO loyalty_vouchers(voucher_type_id,code,purchaser_customer_id,owner_customer_id,original_value,remaining_value,valid_from,valid_until) VALUES($1,$2,$3,$4,$5,$5,CURRENT_DATE,CASE WHEN $6::int IS NULL THEN NULL ELSE CURRENT_DATE+$6::int END) RETURNING *`,[vt,code,req.body?.purchaser_customer_id||null,req.body?.owner_customer_id||null,value,days]);await client.query(`INSERT INTO loyalty_sales(sale_type,reference_id,customer_id,employee_id,work_order_id,gross_amount,commission_base,revenue_recognized,finance_reference,note,created_by) VALUES('voucher',$1,$2,$3,$4,$5,$5,true,$6,$7,$8)`,[String(r.rows[0].id),req.body?.purchaser_customer_id||null,req.body?.employee_id||null,req.body?.work_order_id||null,value,req.body?.finance_reference||null,'Ajándékutalvány értékesítés',actor(req)]);await client.query('COMMIT');res.status(201).json(r.rows[0])}catch(err){await client.query('ROLLBACK');next(err)}finally{client.release()}});

router.get('/sales',async(req,res,next)=>{try{const type=String(req.query.type||'').trim();const{rows}=await db.query(`SELECT * FROM loyalty_sales WHERE ($1='' OR sale_type=$1) ORDER BY created_at DESC LIMIT 300`,[type]);res.json(rows)}catch(err){next(err)}});
router.get('/commission-events',async(req,res,next)=>{try{const employee=String(req.query.employee_id||'').trim();const{rows}=await db.query(`SELECT * FROM loyalty_commission_events WHERE ($1='' OR employee_id=$1) ORDER BY created_at DESC LIMIT 300`,[employee]);res.json(rows)}catch(err){next(err)}});

export default router;
