import {Router} from "express";
import db from "../db";
import type {AuthRequest} from "../middleware/auth";
import {resolveTenantIdentity,locationBelongsToTenant} from "../saas/tenantAccess";
import ensureManagementImprovement from "../management/ensureManagementImprovement";

const router=Router();
const statuses=new Set(['draft','active','review','approved','closed','cancelled']);
const priorities=new Set(['low','normal','high','critical']);
const actionTypes=new Set(['correction','corrective','preventive','improvement']);
const actionStatuses=new Set(['open','in_progress','completed','verified','cancelled']);
const directions=new Set(['higher_better','lower_better','target']);
const text=(v:any)=>String(v??'').trim();
const actor=(req:AuthRequest)=>text(req.user?.email)||text(req.user?.id)||'manager';
const actorId=(req:AuthRequest)=>text(req.user?.id)||null;
const ip=(req:AuthRequest)=>text(req.ip||req.socket?.remoteAddress)||null;
const roles=(req:AuthRequest)=>{const r=req.user?.role;return (Array.isArray(r)?r:String(r??'').split(',')).map(String).map(x=>x.toLowerCase().trim())};
const isAdmin=(req:AuthRequest)=>roles(req).some(r=>['admin','administrator','superadmin','super_admin','rendszergazda'].includes(r));

async function tenantId(req:AuthRequest){
  const resolved=await resolveTenantIdentity(req);
  if(!resolved)throw Object.assign(new Error('A tenant nem azonosítható.'),{status:403});
  return resolved.id;
}
async function ensureLocation(req:AuthRequest,tenant:string,locationId:any){
  const value=text(locationId);if(!value)return null;
  if(!(await locationBelongsToTenant(value,tenant)))throw Object.assign(new Error('A kiválasztott telephely nem tartozik ehhez a tenanthez.'),{status:403});
  return value;
}
function projectCode(){const d=new Date();const stamp=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;return `CI-${stamp}-${Math.random().toString(36).slice(2,6).toUpperCase()}`}
async function audit(client:any,req:AuthRequest,tenant:string,projectId:string,entityType:string,entityId:string,action:string,changes:any={}){
  await client.query(`INSERT INTO management_improvement_audit(project_id,tenant_id,entity_type,entity_id,action,actor_user_id,actor,changes,request_ip) VALUES($1,$2::bigint,$3,$4,$5,$6,$7,$8::jsonb,$9)`,[projectId,tenant,entityType,entityId,action,actorId(req),actor(req),JSON.stringify(changes||{}),ip(req)]);
}
async function projectRow(client:any,tenant:string,id:string){return (await client.query(`SELECT p.*,
  (SELECT count(*)::int FROM management_improvement_actions a WHERE a.project_id=p.id AND a.status NOT IN ('verified','cancelled')) open_actions,
  (SELECT count(*)::int FROM management_improvement_actions a WHERE a.project_id=p.id AND a.action_type IN ('correction','corrective','preventive')) capa_actions,
  (SELECT count(*)::int FROM management_improvement_kpis k WHERE k.project_id=p.id) kpi_count
 FROM management_improvement_projects p WHERE p.id=$1::uuid AND p.tenant_id=$2::bigint`,[id,tenant])).rows[0]}
function fail(res:any,error:any){const status=Number(error?.status||500);return res.status(status>=400&&status<600?status:500).json({message:String(error?.message||'A művelet sikertelen.')})}

router.use(async(_req,_res,next)=>{try{await ensureManagementImprovement();next()}catch(e){next(e)}});

router.get('/employees',async(req:AuthRequest,res)=>{try{const tenant=await tenantId(req);const rows=(await db.query(`SELECT e.id::text id,COALESCE(e.full_name,concat_ws(' ',e.first_name,e.last_name)) full_name,e.position_id::text position_id,COALESCE(to_jsonb(e)->>'location_id','') location_id FROM employees e LEFT JOIN locations l ON l.id::text=(to_jsonb(e)->>'location_id') WHERE COALESCE(e.active,true)=true AND (l.tenant_id=$1::bigint OR $1::bigint=(SELECT tenant_id FROM locations WHERE id::text=$2 LIMIT 1)) ORDER BY 2`,[tenant,text(req.user?.location_id)])).rows;res.json(rows)}catch(e){return fail(res,e)}});

router.get('/projects',async(req:AuthRequest,res)=>{try{const tenant=await tenantId(req);const status=text(req.query.status),location=text(req.query.location_id);if(location)await ensureLocation(req,tenant,location);const params:any[]=[tenant];let where='p.tenant_id=$1::bigint';if(status){params.push(status);where+=` AND p.status=$${params.length}`}if(location){params.push(location);where+=` AND p.location_id=$${params.length}`}const rows=(await db.query(`SELECT p.*,
 (SELECT count(*)::int FROM management_improvement_actions a WHERE a.project_id=p.id AND a.status NOT IN ('verified','cancelled')) open_actions,
 (SELECT count(*)::int FROM management_improvement_actions a WHERE a.project_id=p.id AND a.action_type IN ('correction','corrective','preventive')) capa_actions,
 (SELECT count(*)::int FROM management_improvement_kpis k WHERE k.project_id=p.id) kpi_count,
 (SELECT count(*)::int FROM management_improvement_actions a WHERE a.project_id=p.id AND a.due_date<CURRENT_DATE AND a.status NOT IN ('verified','completed','cancelled')) overdue_actions
 FROM management_improvement_projects p WHERE ${where} ORDER BY CASE p.priority WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'normal' THEN 3 ELSE 4 END,p.due_date NULLS LAST,p.updated_at DESC`,params)).rows;res.json(rows)}catch(e){return fail(res,e)}});

router.post('/projects',async(req:AuthRequest,res)=>{const client=await db.connect();try{await client.query('BEGIN');const tenant=await tenantId(req);const b=req.body||{};const title=text(b.title);if(!title)throw Object.assign(new Error('A projekt megnevezése kötelező.'),{status:400});const location=await ensureLocation(req,tenant,b.location_id);const priority=priorities.has(text(b.priority))?text(b.priority):'normal';const status=statuses.has(text(b.status))?text(b.status):'draft';const ownerId=text(b.owner_employee_id)||null;let ownerName=text(b.owner_name)||null;if(ownerId){const employee=(await client.query(`SELECT COALESCE(full_name,concat_ws(' ',first_name,last_name)) full_name FROM employees WHERE id::text=$1 AND COALESCE(active,true)=true`,[ownerId])).rows[0];if(!employee)throw Object.assign(new Error('A felelős munkatárs nem található.'),{status:400});ownerName=ownerName||employee.full_name}const code=text(b.code)||projectCode();const row=(await client.query(`INSERT INTO management_improvement_projects(tenant_id,location_id,code,title,problem_statement,objective,methodology,analysis_data,owner_employee_id,owner_name,priority,status,start_date,due_date,created_by) VALUES($1::bigint,$2,$3,$4,$5,$6,$7::text[],$8::jsonb,$9,$10,$11,$12,COALESCE($13::date,CURRENT_DATE),$14::date,$15) RETURNING *`,[tenant,location,code,title,text(b.problem_statement)||null,text(b.objective)||null,Array.isArray(b.methodology)?b.methodology.map(String):[],JSON.stringify(b.analysis_data||{}),ownerId,ownerName,priority,status,b.start_date||null,b.due_date||null,actor(req)])).rows[0];await audit(client,req,tenant,row.id,'project',row.id,'project.created',{after:row});await client.query('COMMIT');res.status(201).json(row)}catch(e){await client.query('ROLLBACK');return fail(res,e)}finally{client.release()}});

router.get('/projects/:id',async(req:AuthRequest,res)=>{try{const tenant=await tenantId(req);const project=await projectRow(db,tenant,req.params.id);if(!project)return res.status(404).json({message:'A fejlesztési projekt nem található.'});const [actions,kpis,approvals,auditRows]=await Promise.all([
 db.query(`SELECT * FROM management_improvement_actions WHERE project_id=$1::uuid AND tenant_id=$2::bigint ORDER BY CASE status WHEN 'open' THEN 1 WHEN 'in_progress' THEN 2 WHEN 'completed' THEN 3 WHEN 'verified' THEN 4 ELSE 5 END,due_date NULLS LAST,created_at`,[project.id,tenant]),
 db.query(`SELECT *,CASE WHEN before_value IS NULL OR after_value IS NULL THEN NULL WHEN direction='lower_better' THEN before_value-after_value WHEN direction='higher_better' THEN after_value-before_value ELSE -abs(COALESCE(target_value,after_value)-after_value) END improvement_value FROM management_improvement_kpis WHERE project_id=$1::uuid AND tenant_id=$2::bigint ORDER BY created_at`,[project.id,tenant]),
 db.query(`SELECT * FROM management_improvement_approvals WHERE project_id=$1::uuid AND tenant_id=$2::bigint ORDER BY requested_at DESC`,[project.id,tenant]),
 db.query(`SELECT * FROM management_improvement_audit WHERE project_id=$1::uuid AND tenant_id=$2::bigint ORDER BY created_at DESC,id DESC LIMIT 250`,[project.id,tenant])]);res.json({project,actions:actions.rows,kpis:kpis.rows,approvals:approvals.rows,audit:auditRows.rows})}catch(e){return fail(res,e)}});

router.patch('/projects/:id',async(req:AuthRequest,res)=>{const client=await db.connect();try{await client.query('BEGIN');const tenant=await tenantId(req),b=req.body||{};const current=await projectRow(client,tenant,req.params.id);if(!current)throw Object.assign(new Error('A projekt nem található.'),{status:404});if(current.status==='closed')throw Object.assign(new Error('Lezárt projekt nem módosítható.'),{status:409});const location=b.location_id===undefined?current.location_id:await ensureLocation(req,tenant,b.location_id);const nextStatus=b.status===undefined?current.status:text(b.status);if(!statuses.has(nextStatus))throw Object.assign(new Error('Érvénytelen projektállapot.'),{status:400});const priority=b.priority===undefined?current.priority:text(b.priority);if(!priorities.has(priority))throw Object.assign(new Error('Érvénytelen prioritás.'),{status:400});const ownerId=b.owner_employee_id===undefined?current.owner_employee_id:(text(b.owner_employee_id)||null);let ownerName=b.owner_name===undefined?current.owner_name:(text(b.owner_name)||null);if(ownerId&&ownerId!==current.owner_employee_id){const employee=(await client.query(`SELECT COALESCE(full_name,concat_ws(' ',first_name,last_name)) full_name FROM employees WHERE id::text=$1 AND COALESCE(active,true)=true`,[ownerId])).rows[0];if(!employee)throw Object.assign(new Error('A felelős munkatárs nem található.'),{status:400});ownerName=ownerName||employee.full_name}const row=(await client.query(`UPDATE management_improvement_projects SET location_id=$3,title=$4,problem_statement=$5,objective=$6,methodology=$7::text[],analysis_data=$8::jsonb,owner_employee_id=$9,owner_name=$10,priority=$11,status=$12,start_date=$13::date,due_date=$14::date,updated_at=now() WHERE id=$1::uuid AND tenant_id=$2::bigint RETURNING *`,[current.id,tenant,location,b.title===undefined?current.title:text(b.title),b.problem_statement===undefined?current.problem_statement:text(b.problem_statement)||null,b.objective===undefined?current.objective:text(b.objective)||null,b.methodology===undefined?current.methodology:(Array.isArray(b.methodology)?b.methodology.map(String):[]),JSON.stringify(b.analysis_data===undefined?current.analysis_data:(b.analysis_data||{})),ownerId,ownerName,priority,nextStatus,b.start_date===undefined?current.start_date:(b.start_date||null),b.due_date===undefined?current.due_date:(b.due_date||null)])).rows[0];await audit(client,req,tenant,row.id,'project',row.id,'project.updated',{before:current,after:row});await client.query('COMMIT');res.json(row)}catch(e){await client.query('ROLLBACK');return fail(res,e)}finally{client.release()}});

router.post('/projects/:id/actions',async(req:AuthRequest,res)=>{const client=await db.connect();try{await client.query('BEGIN');const tenant=await tenantId(req),project=await projectRow(client,tenant,req.params.id),b=req.body||{};if(!project)throw Object.assign(new Error('A projekt nem található.'),{status:404});const title=text(b.title);if(!title)throw Object.assign(new Error('Az intézkedés megnevezése kötelező.'),{status:400});const type=actionTypes.has(text(b.action_type))?text(b.action_type):'improvement';const ownerId=text(b.owner_employee_id)||null;let ownerName=text(b.owner_name)||null;if(ownerId){const e=(await client.query(`SELECT COALESCE(full_name,concat_ws(' ',first_name,last_name)) full_name FROM employees WHERE id::text=$1 AND COALESCE(active,true)=true`,[ownerId])).rows[0];if(!e)throw Object.assign(new Error('A felelős munkatárs nem található.'),{status:400});ownerName=ownerName||e.full_name}const row=(await client.query(`INSERT INTO management_improvement_actions(project_id,tenant_id,action_type,title,description,root_cause,owner_employee_id,owner_name,due_date,status,effectiveness_criteria,created_by) VALUES($1::uuid,$2::bigint,$3,$4,$5,$6,$7,$8,$9::date,'open',$10,$11) RETURNING *`,[project.id,tenant,type,title,text(b.description)||null,text(b.root_cause)||null,ownerId,ownerName,b.due_date||null,text(b.effectiveness_criteria)||null,actor(req)])).rows[0];await client.query(`UPDATE management_improvement_projects SET status=CASE WHEN status='draft' THEN 'active' ELSE status END,updated_at=now() WHERE id=$1`,[project.id]);await audit(client,req,tenant,project.id,'action',row.id,'action.created',{after:row});await client.query('COMMIT');res.status(201).json(row)}catch(e){await client.query('ROLLBACK');return fail(res,e)}finally{client.release()}});

router.patch('/projects/:id/actions/:actionId',async(req:AuthRequest,res)=>{const client=await db.connect();try{await client.query('BEGIN');const tenant=await tenantId(req),b=req.body||{};const current=(await client.query(`SELECT * FROM management_improvement_actions WHERE id=$1::uuid AND project_id=$2::uuid AND tenant_id=$3::bigint`,[req.params.actionId,req.params.id,tenant])).rows[0];if(!current)throw Object.assign(new Error('Az intézkedés nem található.'),{status:404});const status=b.status===undefined?current.status:text(b.status);if(!actionStatuses.has(status))throw Object.assign(new Error('Érvénytelen intézkedésállapot.'),{status:400});if(status==='verified'&&!text(b.effectiveness_result)&&!current.effectiveness_result)throw Object.assign(new Error('Ellenőrzéshez az eredményesség értékelése kötelező.'),{status:409});const row=(await client.query(`UPDATE management_improvement_actions SET title=$4,description=$5,root_cause=$6,owner_employee_id=$7,owner_name=$8,due_date=$9::date,status=$10,effectiveness_criteria=$11,effectiveness_result=$12,completed_at=CASE WHEN $10='completed' AND completed_at IS NULL THEN now() WHEN $10 IN ('open','in_progress') THEN NULL ELSE completed_at END,verified_by=CASE WHEN $10='verified' THEN $13 WHEN $10<>'verified' THEN NULL ELSE verified_by END,verified_at=CASE WHEN $10='verified' THEN now() WHEN $10<>'verified' THEN NULL ELSE verified_at END,updated_at=now() WHERE id=$1::uuid AND project_id=$2::uuid AND tenant_id=$3::bigint RETURNING *`,[current.id,req.params.id,tenant,b.title===undefined?current.title:text(b.title),b.description===undefined?current.description:text(b.description)||null,b.root_cause===undefined?current.root_cause:text(b.root_cause)||null,b.owner_employee_id===undefined?current.owner_employee_id:(text(b.owner_employee_id)||null),b.owner_name===undefined?current.owner_name:(text(b.owner_name)||null),b.due_date===undefined?current.due_date:(b.due_date||null),status,b.effectiveness_criteria===undefined?current.effectiveness_criteria:text(b.effectiveness_criteria)||null,b.effectiveness_result===undefined?current.effectiveness_result:text(b.effectiveness_result)||null,actor(req)])).rows[0];await audit(client,req,tenant,req.params.id,'action',row.id,'action.updated',{before:current,after:row});await client.query('COMMIT');res.json(row)}catch(e){await client.query('ROLLBACK');return fail(res,e)}finally{client.release()}});

router.delete('/projects/:id/actions/:actionId',async(req:AuthRequest,res)=>{const client=await db.connect();try{await client.query('BEGIN');const tenant=await tenantId(req);const row=(await client.query(`DELETE FROM management_improvement_actions WHERE id=$1::uuid AND project_id=$2::uuid AND tenant_id=$3::bigint RETURNING *`,[req.params.actionId,req.params.id,tenant])).rows[0];if(!row)throw Object.assign(new Error('Az intézkedés nem található.'),{status:404});await audit(client,req,tenant,req.params.id,'action',row.id,'action.deleted',{before:row});await client.query('COMMIT');res.json({ok:true})}catch(e){await client.query('ROLLBACK');return fail(res,e)}finally{client.release()}});

router.post('/projects/:id/kpis',async(req:AuthRequest,res)=>{const client=await db.connect();try{await client.query('BEGIN');const tenant=await tenantId(req),project=await projectRow(client,tenant,req.params.id),b=req.body||{};if(!project)throw Object.assign(new Error('A projekt nem található.'),{status:404});const name=text(b.name);if(!name)throw Object.assign(new Error('A KPI megnevezése kötelező.'),{status:400});const direction=directions.has(text(b.direction))?text(b.direction):'higher_better';const row=(await client.query(`INSERT INTO management_improvement_kpis(project_id,tenant_id,metric_key,name,unit,direction,before_value,target_value,after_value,before_at,after_at,source,notes,created_by) VALUES($1::uuid,$2::bigint,$3,$4,$5,$6,$7::numeric,$8::numeric,$9::numeric,$10::timestamptz,$11::timestamptz,$12,$13,$14) RETURNING *`,[project.id,tenant,text(b.metric_key)||null,name,text(b.unit)||null,direction,b.before_value??null,b.target_value??null,b.after_value??null,b.before_at||null,b.after_at||null,text(b.source)||null,text(b.notes)||null,actor(req)])).rows[0];await audit(client,req,tenant,project.id,'kpi',row.id,'kpi.created',{after:row});await client.query('COMMIT');res.status(201).json(row)}catch(e){await client.query('ROLLBACK');return fail(res,e)}finally{client.release()}});

router.patch('/projects/:id/kpis/:kpiId',async(req:AuthRequest,res)=>{const client=await db.connect();try{await client.query('BEGIN');const tenant=await tenantId(req),b=req.body||{};const current=(await client.query(`SELECT * FROM management_improvement_kpis WHERE id=$1::uuid AND project_id=$2::uuid AND tenant_id=$3::bigint`,[req.params.kpiId,req.params.id,tenant])).rows[0];if(!current)throw Object.assign(new Error('A KPI nem található.'),{status:404});const direction=b.direction===undefined?current.direction:text(b.direction);if(!directions.has(direction))throw Object.assign(new Error('Érvénytelen KPI irány.'),{status:400});const row=(await client.query(`UPDATE management_improvement_kpis SET metric_key=$4,name=$5,unit=$6,direction=$7,before_value=$8::numeric,target_value=$9::numeric,after_value=$10::numeric,before_at=$11::timestamptz,after_at=$12::timestamptz,source=$13,notes=$14,updated_at=now() WHERE id=$1::uuid AND project_id=$2::uuid AND tenant_id=$3::bigint RETURNING *`,[current.id,req.params.id,tenant,b.metric_key===undefined?current.metric_key:text(b.metric_key)||null,b.name===undefined?current.name:text(b.name),b.unit===undefined?current.unit:text(b.unit)||null,direction,b.before_value===undefined?current.before_value:b.before_value,b.target_value===undefined?current.target_value:b.target_value,b.after_value===undefined?current.after_value:b.after_value,b.before_at===undefined?current.before_at:(b.before_at||null),b.after_at===undefined?current.after_at:(b.after_at||null),b.source===undefined?current.source:text(b.source)||null,b.notes===undefined?current.notes:text(b.notes)||null])).rows[0];await audit(client,req,tenant,req.params.id,'kpi',row.id,'kpi.updated',{before:current,after:row});await client.query('COMMIT');res.json(row)}catch(e){await client.query('ROLLBACK');return fail(res,e)}finally{client.release()}});

router.delete('/projects/:id/kpis/:kpiId',async(req:AuthRequest,res)=>{const client=await db.connect();try{await client.query('BEGIN');const tenant=await tenantId(req);const row=(await client.query(`DELETE FROM management_improvement_kpis WHERE id=$1::uuid AND project_id=$2::uuid AND tenant_id=$3::bigint RETURNING *`,[req.params.kpiId,req.params.id,tenant])).rows[0];if(!row)throw Object.assign(new Error('A KPI nem található.'),{status:404});await audit(client,req,tenant,req.params.id,'kpi',row.id,'kpi.deleted',{before:row});await client.query('COMMIT');res.json({ok:true})}catch(e){await client.query('ROLLBACK');return fail(res,e)}finally{client.release()}});

router.post('/projects/:id/request-approval',async(req:AuthRequest,res)=>{const client=await db.connect();try{await client.query('BEGIN');const tenant=await tenantId(req),project=await projectRow(client,tenant,req.params.id);if(!project)throw Object.assign(new Error('A projekt nem található.'),{status:404});if(['closed','cancelled'].includes(project.status))throw Object.assign(new Error('Lezárt vagy megszakított projekt nem küldhető jóváhagyásra.'),{status:409});const open=(await client.query(`SELECT count(*)::int c FROM management_improvement_actions WHERE project_id=$1 AND tenant_id=$2::bigint AND status NOT IN ('completed','verified','cancelled')`,[project.id,tenant])).rows[0]?.c||0;if(open>0)throw Object.assign(new Error(`Jóváhagyás előtt ${open} nyitott intézkedést le kell zárni.`),{status:409});const kpi=(await client.query(`SELECT count(*)::int c FROM management_improvement_kpis WHERE project_id=$1 AND tenant_id=$2::bigint AND before_value IS NOT NULL AND after_value IS NOT NULL`,[project.id,tenant])).rows[0]?.c||0;if(kpi<1)throw Object.assign(new Error('Jóváhagyás előtt legalább egy előtte/utána KPI rögzítése kötelező.'),{status:409});await client.query(`UPDATE management_improvement_approvals SET decision='withdrawn',decided_at=now(),decided_by=$3,comment='Új jóváhagyási kör indult.' WHERE project_id=$1 AND tenant_id=$2::bigint AND decision='pending'`,[project.id,tenant,actor(req)]);const approval=(await client.query(`INSERT INTO management_improvement_approvals(project_id,tenant_id,requested_by,comment) VALUES($1,$2::bigint,$3,$4) RETURNING *`,[project.id,tenant,actor(req),text(req.body?.comment)||null])).rows[0];const updated=(await client.query(`UPDATE management_improvement_projects SET status='review',approval_state='pending',approval_requested_by=$3,approval_requested_at=now(),approved_by=NULL,approved_at=NULL,rejected_by=NULL,rejected_at=NULL,approval_comment=$4,updated_at=now() WHERE id=$1 AND tenant_id=$2::bigint RETURNING *`,[project.id,tenant,actor(req),text(req.body?.comment)||null])).rows[0];await audit(client,req,tenant,project.id,'approval',approval.id,'approval.requested',{approval,project:updated});await client.query('COMMIT');res.json({project:updated,approval})}catch(e){await client.query('ROLLBACK');return fail(res,e)}finally{client.release()}});

router.post('/projects/:id/approve',async(req:AuthRequest,res)=>{const client=await db.connect();try{await client.query('BEGIN');const tenant=await tenantId(req),project=await projectRow(client,tenant,req.params.id);if(!project)throw Object.assign(new Error('A projekt nem található.'),{status:404});if(project.approval_state!=='pending')throw Object.assign(new Error('Nincs függő jóváhagyási kérelem.'),{status:409});const own=actor(req)===text(project.approval_requested_by);if(own&&!isAdmin(req))throw Object.assign(new Error('A kérelmező nem hagyhatja jóvá a saját projektjét.'),{status:403});if(own&&isAdmin(req)&&!text(req.body?.override_reason))throw Object.assign(new Error('Saját projekt adminisztrátori jóváhagyásához indoklás kötelező.'),{status:409});const comment=text(req.body?.comment)||text(req.body?.override_reason)||null;const approval=(await client.query(`UPDATE management_improvement_approvals SET decision='approved',decided_by=$3,decided_at=now(),comment=COALESCE($4,comment) WHERE id=(SELECT id FROM management_improvement_approvals WHERE project_id=$1 AND tenant_id=$2::bigint AND decision='pending' ORDER BY requested_at DESC LIMIT 1) RETURNING *`,[project.id,tenant,actor(req),comment])).rows[0];const updated=(await client.query(`UPDATE management_improvement_projects SET status='approved',approval_state='approved',approved_by=$3,approved_at=now(),rejected_by=NULL,rejected_at=NULL,approval_comment=$4,updated_at=now() WHERE id=$1 AND tenant_id=$2::bigint RETURNING *`,[project.id,tenant,actor(req),comment])).rows[0];await audit(client,req,tenant,project.id,'approval',approval?.id||project.id,'approval.approved',{comment,self_approval_override:own&&isAdmin(req)});await client.query('COMMIT');res.json({project:updated,approval})}catch(e){await client.query('ROLLBACK');return fail(res,e)}finally{client.release()}});

router.post('/projects/:id/reject',async(req:AuthRequest,res)=>{const client=await db.connect();try{await client.query('BEGIN');const tenant=await tenantId(req),project=await projectRow(client,tenant,req.params.id),comment=text(req.body?.comment);if(!project)throw Object.assign(new Error('A projekt nem található.'),{status:404});if(project.approval_state!=='pending')throw Object.assign(new Error('Nincs függő jóváhagyási kérelem.'),{status:409});if(!comment)throw Object.assign(new Error('Elutasításkor indoklás kötelező.'),{status:400});const approval=(await client.query(`UPDATE management_improvement_approvals SET decision='rejected',decided_by=$3,decided_at=now(),comment=$4 WHERE id=(SELECT id FROM management_improvement_approvals WHERE project_id=$1 AND tenant_id=$2::bigint AND decision='pending' ORDER BY requested_at DESC LIMIT 1) RETURNING *`,[project.id,tenant,actor(req),comment])).rows[0];const updated=(await client.query(`UPDATE management_improvement_projects SET status='active',approval_state='rejected',rejected_by=$3,rejected_at=now(),approved_by=NULL,approved_at=NULL,approval_comment=$4,updated_at=now() WHERE id=$1 AND tenant_id=$2::bigint RETURNING *`,[project.id,tenant,actor(req),comment])).rows[0];await audit(client,req,tenant,project.id,'approval',approval?.id||project.id,'approval.rejected',{comment});await client.query('COMMIT');res.json({project:updated,approval})}catch(e){await client.query('ROLLBACK');return fail(res,e)}finally{client.release()}});

router.post('/projects/:id/close',async(req:AuthRequest,res)=>{const client=await db.connect();try{await client.query('BEGIN');const tenant=await tenantId(req),project=await projectRow(client,tenant,req.params.id);if(!project)throw Object.assign(new Error('A projekt nem található.'),{status:404});if(project.approval_state!=='approved')throw Object.assign(new Error('A projekt csak jóváhagyás után zárható le.'),{status:409});const unverified=(await client.query(`SELECT count(*)::int c FROM management_improvement_actions WHERE project_id=$1 AND tenant_id=$2::bigint AND action_type IN ('correction','corrective','preventive') AND status NOT IN ('verified','cancelled')`,[project.id,tenant])).rows[0]?.c||0;if(unverified>0)throw Object.assign(new Error(`Lezárás előtt ${unverified} CAPA intézkedés eredményességét igazolni kell.`),{status:409});const updated=(await client.query(`UPDATE management_improvement_projects SET status='closed',closed_at=now(),updated_at=now() WHERE id=$1 AND tenant_id=$2::bigint RETURNING *`,[project.id,tenant])).rows[0];await audit(client,req,tenant,project.id,'project',project.id,'project.closed',{after:updated});await client.query('COMMIT');res.json(updated)}catch(e){await client.query('ROLLBACK');return fail(res,e)}finally{client.release()}});

router.get('/projects/:id/audit',async(req:AuthRequest,res)=>{try{const tenant=await tenantId(req);const project=await projectRow(db,tenant,req.params.id);if(!project)return res.status(404).json({message:'A projekt nem található.'});const rows=(await db.query(`SELECT * FROM management_improvement_audit WHERE project_id=$1::uuid AND tenant_id=$2::bigint ORDER BY created_at DESC,id DESC LIMIT 500`,[project.id,tenant])).rows;res.json(rows)}catch(e){return fail(res,e)}});

router.get('/dashboard',async(req:AuthRequest,res)=>{try{const tenant=await tenantId(req);const rows=(await db.query(`SELECT count(*)::int total,count(*) FILTER(WHERE status IN ('active','review'))::int active,count(*) FILTER(WHERE approval_state='pending')::int awaiting_approval,count(*) FILTER(WHERE due_date<CURRENT_DATE AND status NOT IN ('closed','cancelled'))::int overdue,count(*) FILTER(WHERE status='closed')::int closed FROM management_improvement_projects WHERE tenant_id=$1::bigint`,[tenant])).rows[0];const actions=(await db.query(`SELECT count(*) FILTER(WHERE action_type IN ('correction','corrective','preventive') AND status NOT IN ('verified','cancelled'))::int open_capa,count(*) FILTER(WHERE due_date<CURRENT_DATE AND status NOT IN ('completed','verified','cancelled'))::int overdue_actions FROM management_improvement_actions WHERE tenant_id=$1::bigint`,[tenant])).rows[0];res.json({...rows,...actions})}catch(e){return fail(res,e)}});

export default router;
