import {Router} from 'express';
import db from '../db';
import {requireAuth,AuthRequest} from '../middleware/auth';

const router=Router();router.use(requireAuth);
const roles=(raw:any):string[]=>{if(Array.isArray(raw))return raw.map(String).map(x=>x.toLowerCase());try{const p=JSON.parse(String(raw||''));if(Array.isArray(p))return p.map(String).map(x=>x.toLowerCase());if(p!=null)return[String(p).toLowerCase()]}catch{}return String(raw||'').split(',').map(x=>x.replace(/[\[\]"]/g,'').trim().toLowerCase()).filter(Boolean)};
router.use((req:AuthRequest,res,next)=>{if(!roles(req.user?.role).some(r=>['admin','administrator','rendszergazda','superadmin','super_admin'].includes(r)))return res.status(403).json({message:'A NAV Online Számla technikai beállításait csak adminisztrátor kezelheti.'});next()});
function publicSettings(row:any){if(!row)return null;const secret=(envKey:string,value:any)=>process.env[envKey]?'ENVIRONMENT':value?'********':null;return {...row,technical_login:process.env.NAV_TECHNICAL_LOGIN?'ENVIRONMENT':row.technical_login||null,technical_password:secret('NAV_TECHNICAL_PASSWORD',row.technical_password),signing_key:secret('NAV_SIGNING_KEY',row.signing_key),exchange_key:secret('NAV_EXCHANGE_KEY',row.exchange_key),technical_password_configured:Boolean(process.env.NAV_TECHNICAL_PASSWORD||row.technical_password),signing_key_configured:Boolean(process.env.NAV_SIGNING_KEY||row.signing_key),exchange_key_configured:Boolean(process.env.NAV_EXCHANGE_KEY||row.exchange_key)};}
router.get('/settings',async(req:AuthRequest,res,next)=>{try{const locationId=String(req.query.location_id||req.user?.location_id||'').trim();const q=await db.query(`SELECT * FROM nav_online_invoice_settings WHERE active=true AND ($1::text='' OR location_id::text=$1 OR location_id IS NULL) ORDER BY CASE WHEN location_id::text=$1 THEN 0 ELSE 1 END,updated_at DESC LIMIT 1`,[locationId]);res.json(publicSettings(q.rows[0]||null))}catch(e){next(e)}});
router.put('/settings',async(req:AuthRequest,res,next)=>{try{const b=req.body||{},locationId=String(b.location_id||'').trim()||null;const environment=String(b.environment||'test').toLowerCase();if(!['test','live'].includes(environment))return res.status(400).json({message:'A NAV környezet test vagy live lehet.'});const supplierName=String(b.supplier_name||'').trim(),tax=String(b.supplier_tax_number||'').replace(/\D/g,'');if(!supplierName)return res.status(400).json({message:'A kibocsátó neve kötelező.'});if(tax.length<8||tax.length>11)return res.status(400).json({message:'A kibocsátó adószáma 8–11 számjegy legyen.'});for(const [key,label] of [['supplier_postal_code','Irányítószám'],['supplier_city','Város'],['supplier_address','Cím']] as const)if(!String(b[key]||'').trim())return res.status(400).json({message:`${label} megadása kötelező.`});const rateRaw=Number(b.default_vat_rate??0.27),rate=rateRaw>1?rateRaw/100:rateRaw;if(!(rate>=0&&rate<=1))return res.status(400).json({message:'Az alapértelmezett ÁFA kulcs hibás.'});const existing=await db.query(`SELECT id FROM nav_online_invoice_settings WHERE location_id IS NOT DISTINCT FROM $1::uuid ORDER BY updated_at DESC LIMIT 1`,[locationId]);const values=[environment,supplierName,tax,String(b.supplier_group_member_tax_number||'').trim()||null,String(b.supplier_bank_account||'').trim()||null,String(b.supplier_country_code||'HU').trim().toUpperCase(),String(b.supplier_postal_code).trim(),String(b.supplier_city).trim(),String(b.supplier_address).trim(),String(b.invoice_prefix||'KLEO').trim(),rate,String(b.currency||'HUF').trim().toUpperCase(),String(b.technical_login||'').trim(),String(b.technical_password||'').trim(),String(b.signing_key||'').trim(),String(b.exchange_key||'').trim(),String(b.software_id||'KLEOSZALONVIR0001').trim(),String(b.software_name||'Kleoszalon VIR').trim(),String(b.software_operation||'ONLINE_SERVICE').trim(),String(b.software_main_version||'1.0').trim(),String(b.software_dev_name||'Kleoszalon Kft.').trim(),String(b.software_dev_contact||'').trim()||null,String(b.software_dev_country_code||'HU').trim().toUpperCase()];let row:any;
if(existing.rows[0]){row=(await db.query(`UPDATE nav_online_invoice_settings SET active=true,environment=$2,supplier_name=$3,supplier_tax_number=$4,supplier_group_member_tax_number=$5,supplier_bank_account=$6,supplier_country_code=$7,supplier_postal_code=$8,supplier_city=$9,supplier_address=$10,invoice_prefix=$11,default_vat_rate=$12,currency=$13,technical_login=CASE WHEN $14 IN ('','********','ENVIRONMENT') THEN technical_login ELSE $14 END,technical_password=CASE WHEN $15 IN ('','********','ENVIRONMENT') THEN technical_password ELSE $15 END,signing_key=CASE WHEN $16 IN ('','********','ENVIRONMENT') THEN signing_key ELSE $16 END,exchange_key=CASE WHEN $17 IN ('','********','ENVIRONMENT') THEN exchange_key ELSE $17 END,software_id=$18,software_name=$19,software_operation=$20,software_main_version=$21,software_dev_name=$22,software_dev_contact=$23,software_dev_country_code=$24,updated_at=now() WHERE id=$1::uuid RETURNING *`,[existing.rows[0].id,...values])).rows[0]}else{row=(await db.query(`INSERT INTO nav_online_invoice_settings(location_id,active,environment,supplier_name,supplier_tax_number,supplier_group_member_tax_number,supplier_bank_account,supplier_country_code,supplier_postal_code,supplier_city,supplier_address,invoice_prefix,default_vat_rate,currency,technical_login,technical_password,signing_key,exchange_key,software_id,software_name,software_operation,software_main_version,software_dev_name,software_dev_contact,software_dev_country_code) VALUES($1::uuid,true,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,NULLIF($14,''),NULLIF($15,''),NULLIF($16,''),NULLIF($17,''),$18,$19,$20,$21,$22,$23,$24) RETURNING *`,[locationId,...values])).rows[0]}res.json(publicSettings(row));}catch(e:any){if(e?.code==='22P02')return res.status(400).json({message:'Érvénytelen telephely-azonosító.'});next(e)}});
export default router;
