import { Router } from "express";
import legacyNotificationsRouter from "./notificationsLegacy";
import alertRuleAdminRouter from "./alertRuleAdmin";
import observabilityRouter from "./observability";
import businessReconciliationRouter from "./businessReconciliation";
import exceptionCommandCenterRouter from "./exceptionCommandCenter";
import { requireManagement } from "../middleware/requireRoles";
import { startAlertRuleScheduler } from "../services/alertRuleEngine";
import { startObservabilityWorker } from "../services/observabilityApm";
import { ensureTransactionTraceForensicsSchema } from "../services/transactionTraceForensics";
import { ensureExceptionCommandCenterSchema, startExceptionCommandCenterScheduler } from "../services/exceptionCommandCenter";

const router=Router();
startAlertRuleScheduler();
startObservabilityWorker();
startExceptionCommandCenterScheduler();
void ensureTransactionTraceForensicsSchema().catch(error=>console.error('[transaction-trace] startup forensic schema bootstrap failed',error));
void ensureExceptionCommandCenterSchema().catch(error=>console.error('[exception-center] startup schema bootstrap failed',error));
router.use("/observability",requireManagement,observabilityRouter);
router.use("/reconciliation",requireManagement,businessReconciliationRouter);
router.use("/exceptions",requireManagement,exceptionCommandCenterRouter);
router.use("/alert-rules",alertRuleAdminRouter);
router.use("/",legacyNotificationsRouter);
export default router;
