import{Router}from"express";import db from"../db";const router=Router();
async function ensure(){await db.query(`CREATE TABLE IF NOT EXISTS operations_quality_records(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),module_key text NOT NULL,title text NOT NULL,description text,location_name text,department text,assignee text,priority text DEFAULT 'normal',status text NOT NULL DEFAULT 'open',due_at timestamptz,recurrence text,requires_approval boolean DEFAULT false,metadata jsonb DEFAULT '{}'::jsonb,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());CREATE INDEX IF NOT EXISTS operations_quality_module_idx ON operations_quality_records(module_key,status,due_at);
INSERT INTO operations_quality_records(module_key,title,description,department,assignee,priority,status,due_at,recurrence,requires_approval,metadata) VALUES
('tasks','Nyitás előtti higiéniai ellenőrzés','Munkafelületek, mosók, fertőtlenítők és vendégtér ellenőrzése.','Minden részleg','Délelőttös műszak','high','open',date_trunc('day',now())+interval '8 hour','naponta',true,'{"shift":"délelőtt","checklist":["felületek","eszközök","fertőtlenítő","vendégtér"]}'),
('tasks','Napi zárási ellenőrzés','Pénztár, munkalapok, készleteltérések és zárási takarítás.','Recepció','Délutános műszak','high','open',date_trunc('day',now())+interval '20 hour','naponta',true,'{"shift":"délután"}'),
('tasks','Heti készletszint mintavétel','Részlegenként véletlenszerű termékminta tényleges készletének rögzítése.','Raktár','Részlegvezető','normal','assigned',date_trunc('week',now())+interval '5 day 12 hour','hetente',true,'{"stock_check":true,"sample_size":10}'),
('maintenance','Hajszárítók éves érintésvédelmi vizsgálata','Biztonságtechnikai felülvizsgálat és jegyzőkönyv csatolása.','Fodrászat','Műszaki partner','high','scheduled',now()+interval '21 day','évente',true,'{"asset":"Hajszárítók","warning_days":30}'),
('maintenance','Kozmetikai gép időszakos szervize','Szűrők, kábelek, kezelőfejek és kalibráció ellenőrzése.','Kozmetika','Szervizpartner','normal','scheduled',now()+interval '45 day','félévente',false,'{"asset":"Kozmetikai kezelőgép","warning_days":30}'),
('documents','Panaszkezelési szabályzat','Aktuális, dolgozók számára elérhető szabályzat.','Központ','Minőségügyi vezető','high','valid',now()+interval '365 day','évente',true,'{"category":"szabályzat","version":"1.0"}'),
('documents','Munkavédelmi oktatási jegyzőkönyv','Éves oktatás igazolása és jelenléti íve.','Minden részleg','HR','high','expiring',now()+interval '60 day','évente',true,'{"category":"igazolás"}'),
('internal-email','Havi vezetői működési összefoglaló','KPI, eltérések, panaszok és intézkedések havi összefoglalója.','Központ','Üzletvezetők','normal','draft',now()+interval '5 day','havonta',true,'{"recipient_group":"vezetők"}'),
('complaints','Várakozási idő kivizsgálása','Vendégjelzés a megnövekedett várakozási idő miatt.','Recepció','Üzletvezető','high','investigating',now()+interval '2 day',NULL,true,'{"subject":"várakozás miatt","source":"személyes","sla_days":5}'),
('audits','Havi szalonminőségi audit','Higiénia, vendégélmény, dokumentáció, pénztár és készlet ellenőrzése.','Minden részleg','Üzletvezető','high','planned',date_trunc('month',now())+interval '25 day','havonta',true,'{"checklist":["higiénia","vendégélmény","munkalap","pénztár","készlet"],"target_score":90}'),
('incidents','Munkahelyi és szolgáltatási eltérések naplója','Baleset, eszközhiba, adatvédelmi vagy szolgáltatásminőségi eltérés rögzítése.','Minden részleg','Üzletvezető','high','open',now()+interval '1 day',NULL,true,'{"category":"minőségi eltérés","root_cause_required":true}');`)}
router.use(async(_q,_s,n)=>{try{await ensure();n()}catch(e){n(e)}});
router.get('/overview',async(_q,res,n)=>{try{const{rows}=await db.query(`SELECT * FROM operations_quality_records ORDER BY CASE priority WHEN 'critical' THEN 1 WHEN 'high' THEN 2 ELSE 3 END,due_at NULLS LAST,created_at DESC`);res.json({records:rows,summary:{open:rows.filter(x=>!['approved','resolved','archived','valid','sent'].includes(x.status)).length,overdue:rows.filter(x=>x.due_at&&new Date(x.due_at)<new Date()&&!['approved','resolved','archived','valid','sent'].includes(x.status)).length,approval:rows.filter(x=>x.requires_approval&&['completed','review','investigating'].includes(x.status)).length}})}catch(e){n(e)}});
router.post('/records',async(req,res,n)=>{try{const b=req.body;if(!b.module_key||!b.title?.trim())return res.status(400).json({message:'A modul és a megnevezés kötelező.'});const{rows}=await db.query(`INSERT INTO operations_quality_records(module_key,title,description,location_name,department,assignee,priority,status,due_at,recurrence,requires_approval,metadata)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)RETURNING *`,[b.module_key,b.title.trim(),b.description||null,b.location_name||null,b.department||null,b.assignee||null,b.priority||'normal',b.status||'open',b.due_at||null,b.recurrence||null,!!b.requires_approval,b.metadata||{}]);res.status(201).json(rows[0])}catch(e){n(e)}});
router.patch('/records/:id',async(req,res,n)=>{try{const b=req.body,{rows}=await db.query(`UPDATE operations_quality_records SET status=COALESCE($2,status),assignee=COALESCE($3,assignee),description=COALESCE($4,description),metadata=metadata||COALESCE($5::jsonb,'{}'::jsonb),updated_at=now() WHERE id=$1::uuid RETURNING *`,[req.params.id,b.status||null,b.assignee||null,b.description||null,JSON.stringify(b.metadata||{})]);if(!rows[0])return res.status(404).json({message:'A tétel nem található.'});res.json(rows[0])}catch(e){n(e)}});export default router;
