import {Router,Response,NextFunction} from 'express';
import pool from '../db';
import {requireAuth,AuthRequest} from '../middleware/auth';
import {ensureHrV2} from '../hr/ensureHrV2';

const router=Router();router.use(requireAuth);
const num=(v:any)=>Number(v||0);const round=(v:number)=>Math.round((v+Number.EPSILON)*100)/100;
const asyncRoute=(fn:(req:any,res:Response)=>Promise<any>)=>(req:any,res:Response,next:NextFunction)=>fn(req,res).catch(next);
const ADMIN=new Set(['admin','administrator','rendszergazda','superadmin','super_admin']);
const MANAGER=new Set(['location_manager','üzletvezető','uzletvezeto','store_manager','branch_manager']);
const roleList=(raw:any):string[]=>{if(Array.isArray(raw))return raw.map(String).map(x=>x.toLowerCase());try{const p=JSON.parse(String(raw||''));if(Array.isArray(p))return p.map(String).map(x=>x.toLowerCase())}catch{}return String(raw||'').replace(/[\[\]"]/g,'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean)};
function scope(req:AuthRequest,requested:any){const roles=roleList(req.user?.role);if(roles.some(r=>ADMIN.has(r)))return{admin:true,location:String(requested||'').trim()||null};if(roles.some(r=>MANAGER.has(r))){const own=req.user?.location_id?String(req.user.location_id):'';if(!own)throw Object.assign(new Error('A felhasználóhoz nincs szalon rendelve.'),{status:403});return{admin:false,location:own}}throw Object.assign(new Error('A bérszámfejtéshez adminisztrátori vagy üzletvezetői jogosultság szükséges.'),{status:403})}

async function ensureIntegrationSchema(c:any=pool){await ensureHrV2();await c.query(`
 CREATE EXTENSION IF NOT EXISTS pgcrypto;
 CREATE TABLE IF NOT EXISTS work_order_commission_events(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),work_order_id uuid NOT NULL REFERENCES work_orders(id),employee_id uuid NOT NULL REFERENCES employees(id),
  base_amount numeric(14,2) NOT NULL DEFAULT 0,tip_amount numeric(14,2) NOT NULL DEFAULT 0,source_type text NOT NULL DEFAULT 'work_order_finalization',
  status text NOT NULL DEFAULT 'open',note text,created_at timestamptz NOT NULL DEFAULT now(),created_by text,UNIQUE(work_order_id,employee_id,source_type));
 CREATE TABLE IF NOT EXISTS payroll_commission_links(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),payroll_run_id uuid NOT NULL REFERENCES payroll_runs(id) ON DELETE CASCADE,
  commission_event_id uuid NOT NULL REFERENCES work_order_commission_events(id) ON DELETE CASCADE,employee_id uuid NOT NULL REFERENCES employees(id),
  created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(commission_event_id),UNIQUE(payroll_run_id,commission_event_id));
 CREATE INDEX IF NOT EXISTS payroll_commission_links_run_idx ON payroll_commission_links(payroll_run_id,employee_id);
 `)}

async function settingsFor(location:string|null,override:any={}){const q=await pool.query(`SELECT * FROM payroll_settings WHERE (($1::uuid IS NULL AND location_id IS NULL) OR location_id=$1::uuid) AND is_active ORDER BY location_id NULLS LAST LIMIT 1`,[location]);return{include_draft_timesheets:false,pay_paid_leave:true,calculate_service_commission:true,calculate_product_commission:true,calculate_revenue_commission:true,calculate_overtime:true,calculate_weekend_extra:true,calculate_evening_extra:true,calculate_attendance_bonus:true,calculate_target_bonus:true,standard_daily_minutes:480,tax_percent:0,social_contribution_percent:0,default_deduction:0,...q.rows[0],...override}}

type CalculateOptions={runId?:string|null};
async function calculate(c:any,from:string,to:string,location:string|null,settings:any,options:CalculateOptions={}){
 const runId=options.runId||null;
 const {rows}=await c.query(`WITH
 ts AS(
  SELECT employee_id,SUM(regular_minutes)::int regular_minutes,SUM(overtime_minutes)::int overtime_minutes,COUNT(*)::int worked_days,
   SUM(CASE WHEN EXTRACT(ISODOW FROM work_date)>=6 THEN regular_minutes ELSE 0 END)::int weekend_minutes,
   SUM(CASE WHEN clock_in IS NOT NULL AND clock_out IS NOT NULL THEN GREATEST(0,EXTRACT(EPOCH FROM (clock_out-GREATEST(clock_in,work_date::timestamp+interval '18 hour')))/60) ELSE 0 END)::int evening_minutes
  FROM timesheets WHERE work_date BETWEEN $1::date AND $2::date AND ($3::uuid IS NULL OR location_id=$3::uuid) AND (status='approved' OR $4::boolean) GROUP BY employee_id),
 paid_leave AS(
  SELECT r.employee_id,COALESCE(SUM(CASE WHEN lt.is_paid AND EXTRACT(ISODOW FROM d.day)<6 THEN COALESCE(r.minutes_per_day,$6::int) ELSE 0 END),0)::int paid_leave_minutes
  FROM leave_requests r JOIN leave_types lt ON lt.id=r.leave_type_id
  CROSS JOIN LATERAL generate_series(GREATEST(r.date_from,$1::date),LEAST(r.date_to,$2::date),interval '1 day') d(day)
  WHERE r.status='approved' AND r.date_from<=$2::date AND r.date_to>=$1::date GROUP BY r.employee_id),
 eligible AS(
  SELECT ce.id event_id,ce.work_order_id,ce.employee_id,COALESCE(ce.tip_amount,0)::numeric tip_amount
  FROM work_order_commission_events ce JOIN work_orders w ON w.id=ce.work_order_id
  LEFT JOIN payroll_commission_links pcl ON pcl.commission_event_id=ce.id
  WHERE ce.created_at::date BETWEEN $1::date AND $2::date AND ($3::uuid IS NULL OR w.location_id=$3::uuid)
    AND (($5::uuid IS NULL AND ce.status='open' AND pcl.id IS NULL) OR ($5::uuid IS NOT NULL AND pcl.payroll_run_id=$5::uuid))),
 rev AS(
  SELECT e.employee_id,
   COALESCE(SUM((SELECT COALESCE(SUM(i.line_total),0) FROM work_order_items i WHERE i.work_order_id=e.work_order_id AND i.item_type='service')),0)::numeric service_revenue,
   COALESCE(SUM((SELECT COALESCE(SUM(i.line_total),0) FROM work_order_items i WHERE i.work_order_id=e.work_order_id AND i.item_type='product')),0)::numeric product_revenue,
   COALESCE(SUM(e.tip_amount),0)::numeric tip_amount,COUNT(*)::int completed_workorders
  FROM eligible e GROUP BY e.employee_id)
 SELECT e.id employee_id,e.full_name,e.position_id,h.name position_name,e.location_id,
  COALESCE(ts.regular_minutes,0)::int regular_minutes,COALESCE(ts.overtime_minutes,0)::int overtime_minutes,COALESCE(ts.worked_days,0)::int worked_days,
  COALESCE(ts.weekend_minutes,0)::int weekend_minutes,COALESCE(ts.evening_minutes,0)::int evening_minutes,COALESCE(pl.paid_leave_minutes,0)::int paid_leave_minutes,
  COALESCE(rev.service_revenue,0)::numeric service_revenue,COALESCE(rev.product_revenue,0)::numeric product_revenue,COALESCE(rev.tip_amount,0)::numeric tip_amount,COALESCE(rev.completed_workorders,0)::int completed_workorders,
  a.compensation_plan_id,COALESCE(a.monthly_base,p.monthly_base,0) monthly_base,COALESCE(a.hourly_rate,p.hourly_rate,0) hourly_rate,COALESCE(a.daily_rate,p.daily_rate,0) daily_rate,
  COALESCE(p.shift_rate,0) shift_rate,COALESCE(a.service_commission_percent,p.service_commission_percent,0) service_pct,COALESCE(a.product_commission_percent,p.product_commission_percent,0) product_pct,
  COALESCE(a.revenue_commission_percent,p.revenue_commission_percent,0) revenue_pct,COALESCE(p.attendance_bonus,0) attendance_bonus,COALESCE(p.target_bonus,0) target_bonus,COALESCE(p.monthly_target,0) monthly_target,
  COALESCE(p.overtime_multiplier,1.5) overtime_multiplier,COALESCE(p.weekend_multiplier,1) weekend_multiplier,COALESCE(p.evening_multiplier,1) evening_multiplier,COALESCE(p.paid_leave_multiplier,1) paid_leave_multiplier,
  COALESCE(p.minimum_guarantee,0) minimum_guarantee,p.maximum_gross,COALESCE(p.calculation_mode,'monthly_plus_variable') calculation_mode
 FROM employees e LEFT JOIN ts ON ts.employee_id=e.id LEFT JOIN paid_leave pl ON pl.employee_id=e.id LEFT JOIN rev ON rev.employee_id=e.id
 LEFT JOIN employee_compensation_assignments a ON a.employee_id=e.id AND a.is_active LEFT JOIN compensation_plans p ON p.id=a.compensation_plan_id LEFT JOIN hr_positions h ON h.id=e.position_id
 WHERE COALESCE(e.active,true) AND ($3::uuid IS NULL OR e.location_id=$3::uuid) ORDER BY e.full_name`,[from,to,location,Boolean(settings.include_draft_timesheets),runId,Number(settings.standard_daily_minutes||480)]);
 return rows.map((r:any)=>{const hourly=num(r.hourly_rate),regHours=num(r.regular_minutes)/60,otHours=num(r.overtime_minutes)/60,weekendHours=num(r.weekend_minutes)/60,eveningHours=num(r.evening_minutes)/60,leaveHours=num(r.paid_leave_minutes)/60,totalRev=num(r.service_revenue)+num(r.product_revenue);let base=0;switch(r.calculation_mode){case'hourly_only':base=regHours*hourly;break;case'daily_only':base=num(r.worked_days)*num(r.daily_rate);break;case'shift_only':base=num(r.worked_days)*num(r.shift_rate);break;case'higher_of':base=Math.max(num(r.monthly_base),regHours*hourly,num(r.worked_days)*num(r.daily_rate));break;default:base=num(r.monthly_base)||regHours*hourly}
  let paidLeave=0;if(settings.pay_paid_leave&&num(r.paid_leave_minutes)>0&&num(r.monthly_base)<=0){paidLeave=r.calculation_mode==='daily_only'?(num(r.paid_leave_minutes)/num(settings.standard_daily_minutes||480))*num(r.daily_rate)*num(r.paid_leave_multiplier):leaveHours*hourly*num(r.paid_leave_multiplier)}
  base+=paidLeave;const overtime=settings.calculate_overtime?otHours*hourly*num(r.overtime_multiplier):0;const weekend=settings.calculate_weekend_extra?weekendHours*hourly*Math.max(0,num(r.weekend_multiplier)-1):0;const evening=settings.calculate_evening_extra?eveningHours*hourly*Math.max(0,num(r.evening_multiplier)-1):0;
  const svc=settings.calculate_service_commission?num(r.service_revenue)*num(r.service_pct)/100:0;const prod=settings.calculate_product_commission?num(r.product_revenue)*num(r.product_pct)/100:0;const revenue=settings.calculate_revenue_commission?totalRev*num(r.revenue_pct)/100:0;const tips=num(r.tip_amount);
  const attendance=settings.calculate_attendance_bonus&&num(r.worked_days)>0?num(r.attendance_bonus):0;const target=settings.calculate_target_bonus&&num(r.monthly_target)>0&&totalRev>=num(r.monthly_target)?num(r.target_bonus):0;
  let gross=Math.max(num(r.minimum_guarantee),base+overtime+weekend+evening+svc+prod+revenue+tips+attendance+target);if(r.maximum_gross!=null)gross=Math.min(gross,num(r.maximum_gross));const deductions=num(settings.default_deduction)+gross*(num(settings.tax_percent)+num(settings.social_contribution_percent))/100;
  return{...r,total_revenue:round(totalRev),base_pay:round(base),paid_leave_pay:round(paidLeave),overtime_pay:round(overtime),weekend_pay:round(weekend),evening_pay:round(evening),service_commission:round(svc),product_commission:round(prod),revenue_commission:round(revenue),tip_pay:round(tips),attendance_bonus_pay:round(attendance),target_bonus_pay:round(target),deductions:round(deductions),gross_pay:round(gross),net_pay:round(Math.max(0,gross-deductions))}})
}

async function readiness(from:string,to:string,location:string|null){const params=[from,to,location];const [staff,attendance,leave,commission]=await Promise.all([
 pool.query(`SELECT COUNT(*)::int active_employees,COUNT(*) FILTER(WHERE c.id IS NULL)::int missing_contract,COUNT(*) FILTER(WHERE ca.id IS NULL)::int missing_compensation FROM employees e LEFT JOIN LATERAL(SELECT id FROM employment_contracts c WHERE c.employee_id=e.id AND c.is_active LIMIT 1)c ON true LEFT JOIN LATERAL(SELECT id FROM employee_compensation_assignments a WHERE a.employee_id=e.id AND a.is_active LIMIT 1)ca ON true WHERE COALESCE(e.active,true) AND ($3::uuid IS NULL OR e.location_id=$3::uuid)`,params),
 pool.query(`SELECT COUNT(*) FILTER(WHERE t.status<>'approved')::int unapproved_timesheets,COUNT(*) FILTER(WHERE t.status='approved')::int approved_timesheets,COALESCE(SUM(t.overtime_minutes) FILTER(WHERE t.status='approved'),0)::int approved_overtime_minutes FROM timesheets t WHERE t.work_date BETWEEN $1::date AND $2::date AND ($3::uuid IS NULL OR t.location_id=$3::uuid)`,params),
 pool.query(`SELECT COUNT(*) FILTER(WHERE r.status='pending')::int pending_leave,COUNT(*) FILTER(WHERE r.status='approved' AND lt.is_paid)::int approved_paid_leave FROM leave_requests r JOIN leave_types lt ON lt.id=r.leave_type_id JOIN employees e ON e.id=r.employee_id WHERE r.date_from<=$2::date AND r.date_to>=$1::date AND ($3::uuid IS NULL OR e.location_id=$3::uuid)`,params),
 pool.query(`SELECT COUNT(*) FILTER(WHERE ce.status='open')::int open_commissions,COUNT(*) FILTER(WHERE ce.status='included')::int included_commissions,COUNT(*) FILTER(WHERE ce.status='paid')::int paid_commissions,COALESCE(SUM(ce.base_amount) FILTER(WHERE ce.status='open'),0)::numeric open_commission_base,COALESCE(SUM(ce.tip_amount) FILTER(WHERE ce.status='open'),0)::numeric open_tips FROM work_order_commission_events ce JOIN work_orders w ON w.id=ce.work_order_id WHERE ce.created_at::date BETWEEN $1::date AND $2::date AND ($3::uuid IS NULL OR w.location_id=$3::uuid)`,params)
 ]);const x={...staff.rows[0],...attendance.rows[0],...leave.rows[0],...commission.rows[0]};return{...x,ready:Number(x.missing_contract||0)===0&&Number(x.missing_compensation||0)===0&&Number(x.unapproved_timesheets||0)===0&&Number(x.pending_leave||0)===0}}

router.get('/readiness',asyncRoute(async(req:AuthRequest,res)=>{await ensureIntegrationSchema();const s=scope(req,req.query.location_id);const from=String(req.query.from||new Date().toISOString().slice(0,8)+'01'),to=String(req.query.to||new Date().toISOString().slice(0,10));res.json({from,to,scope:s,...await readiness(from,to,s.location)})}));
router.post('/preview',asyncRoute(async(req:AuthRequest,res)=>{await ensureIntegrationSchema();const b=req.body||{};if(!b.from||!b.to)return res.status(400).json({error:'Az időszak kötelező.'});const s=scope(req,b.location_id);const settings=await settingsFor(s.location,b.settings||{});const items=await calculate(pool,b.from,b.to,s.location,settings);const totals={gross:round(items.reduce((a:number,x:any)=>a+num(x.gross_pay),0)),deductions:round(items.reduce((a:number,x:any)=>a+num(x.deductions),0)),net:round(items.reduce((a:number,x:any)=>a+num(x.net_pay),0)),tips:round(items.reduce((a:number,x:any)=>a+num(x.tip_pay),0)),commission:round(items.reduce((a:number,x:any)=>a+num(x.service_commission)+num(x.product_commission)+num(x.revenue_commission),0))};res.json({settings,items,totals,readiness:await readiness(b.from,b.to,s.location),scope:s})}));

router.post('/runs',asyncRoute(async(req:AuthRequest,res)=>{await ensureIntegrationSchema();const b=req.body||{};if(!b.from||!b.to)return res.status(400).json({error:'Az időszak kötelező.'});const s=scope(req,b.location_id);const settings=await settingsFor(s.location);const c=await pool.connect();try{await c.query('BEGIN');const duplicate=await c.query(`SELECT id,status,title,period_from,period_to,location_id FROM payroll_runs WHERE status<>'cancelled' AND period_from<=$2::date AND period_to>=$1::date AND ($3::uuid IS NULL OR location_id IS NULL OR location_id=$3::uuid) ORDER BY created_at DESC LIMIT 1 FOR UPDATE`,[b.from,b.to,s.location]);if(duplicate.rows[0]){await c.query('ROLLBACK');return res.status(409).json({error:'Az időszakra már létezik átfedő aktív számfejtési futás, ezért duplikált bér vagy jutalék keletkezhetne.',run:duplicate.rows[0]})}const run=(await c.query(`INSERT INTO payroll_runs(location_id,period_from,period_to,title,status,settings_snapshot,gross_total,deduction_total,net_total,created_by) VALUES($1,$2,$3,$4,'draft',$5::jsonb,0,0,0,$6) RETURNING *`,[s.location,b.from,b.to,b.title||`${b.from} – ${b.to} számfejtés`,JSON.stringify(settings),String(req.user?.id??'')])).rows[0];
 await c.query(`INSERT INTO payroll_commission_links(payroll_run_id,commission_event_id,employee_id) SELECT $1::uuid,ce.id,ce.employee_id FROM work_order_commission_events ce JOIN work_orders w ON w.id=ce.work_order_id LEFT JOIN payroll_commission_links old ON old.commission_event_id=ce.id WHERE ce.status='open' AND old.id IS NULL AND ce.created_at::date BETWEEN $2::date AND $3::date AND ($4::uuid IS NULL OR w.location_id=$4::uuid) ON CONFLICT(commission_event_id) DO NOTHING`,[run.id,b.from,b.to,s.location]);
 await c.query(`UPDATE work_order_commission_events ce SET status='included' FROM payroll_commission_links l WHERE l.payroll_run_id=$1::uuid AND l.commission_event_id=ce.id`,[run.id]);
 const items=await calculate(c,b.from,b.to,s.location,settings,{runId:run.id});const totals={gross:round(items.reduce((a:number,x:any)=>a+num(x.gross_pay),0)),deductions:round(items.reduce((a:number,x:any)=>a+num(x.deductions),0)),net:round(items.reduce((a:number,x:any)=>a+num(x.net_pay),0))};for(const x of items)await c.query(`INSERT INTO payroll_items(payroll_run_id,employee_id,compensation_plan_id,regular_minutes,overtime_minutes,worked_days,shifts,service_revenue,product_revenue,total_revenue,base_pay,overtime_pay,weekend_pay,evening_pay,service_commission,product_commission,revenue_commission,attendance_bonus,target_bonus,deductions,gross_pay,net_pay,calculation_details) VALUES($1,$2,$3,$4,$5,$6,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22::jsonb)`,[run.id,x.employee_id,x.compensation_plan_id,x.regular_minutes,x.overtime_minutes,x.worked_days,x.service_revenue,x.product_revenue,x.total_revenue,x.base_pay,x.overtime_pay,x.weekend_pay,x.evening_pay,x.service_commission,x.product_commission,x.revenue_commission,x.attendance_bonus_pay,x.target_bonus_pay,x.deductions,x.gross_pay,x.net_pay,JSON.stringify(x)]);const updated=(await c.query(`UPDATE payroll_runs SET gross_total=$2,deduction_total=$3,net_total=$4,updated_at=now() WHERE id=$1 RETURNING *`,[run.id,totals.gross,totals.deductions,totals.net])).rows[0];await c.query('COMMIT');res.status(201).json({...updated,items,totals,readiness:await readiness(b.from,b.to,s.location)})}catch(e){await c.query('ROLLBACK').catch(()=>undefined);throw e}finally{c.release()}}));

router.get('/runs',asyncRoute(async(req:AuthRequest,res)=>{await ensureIntegrationSchema();const s=scope(req,req.query.location_id);const {rows}=await pool.query(`SELECT r.*,COUNT(DISTINCT i.id)::int employee_count,COUNT(DISTINCT l.id)::int commission_event_count FROM payroll_runs r LEFT JOIN payroll_items i ON i.payroll_run_id=r.id LEFT JOIN payroll_commission_links l ON l.payroll_run_id=r.id WHERE ($1::uuid IS NULL OR r.location_id=$1::uuid) GROUP BY r.id ORDER BY r.period_from DESC,r.created_at DESC`,[s.location]);res.json(rows)}));

router.patch('/runs/:id/status',asyncRoute(async(req:AuthRequest,res)=>{await ensureIntegrationSchema();const requested=String(req.body?.status||'');if(!['draft','calculated','approved','paid','cancelled'].includes(requested))return res.status(400).json({error:'Érvénytelen státusz.'});const s=scope(req,req.body?.location_id);const c=await pool.connect();try{await c.query('BEGIN');const current=(await c.query(`SELECT * FROM payroll_runs WHERE id=$1::uuid AND ($2::uuid IS NULL OR location_id=$2::uuid) FOR UPDATE`,[req.params.id,s.location])).rows[0];if(!current){await c.query('ROLLBACK');return res.status(404).json({error:'A számfejtési futás nem található.'})}if(['paid','cancelled'].includes(String(current.status))&&requested!==current.status){await c.query('ROLLBACK');return res.status(409).json({error:'Kifizetett vagy törölt számfejtési futás státusza már nem módosítható.'})}if(requested==='cancelled'){await c.query(`UPDATE work_order_commission_events ce SET status='open' FROM payroll_commission_links l WHERE l.payroll_run_id=$1::uuid AND l.commission_event_id=ce.id AND ce.status='included'`,[current.id]);await c.query(`DELETE FROM payroll_commission_links WHERE payroll_run_id=$1::uuid`,[current.id])}else if(requested==='paid'){await c.query(`UPDATE work_order_commission_events ce SET status='paid' FROM payroll_commission_links l WHERE l.payroll_run_id=$1::uuid AND l.commission_event_id=ce.id`,[current.id])}else{await c.query(`UPDATE work_order_commission_events ce SET status='included' FROM payroll_commission_links l WHERE l.payroll_run_id=$1::uuid AND l.commission_event_id=ce.id AND ce.status='open'`,[current.id])}
 const row=(await c.query(`UPDATE payroll_runs SET status=$2,approved_by=CASE WHEN $2='approved' THEN $3 ELSE approved_by END,approved_at=CASE WHEN $2='approved' THEN COALESCE(approved_at,now()) ELSE approved_at END,updated_at=now() WHERE id=$1 RETURNING *`,[current.id,requested,String(req.user?.id??'')])).rows[0];await c.query('COMMIT');res.json(row)}catch(e){await c.query('ROLLBACK').catch(()=>undefined);throw e}finally{c.release()}}));

router.use((err:any,_req:any,res:Response,next:NextFunction)=>{if(!err)return next();if(err.status)return res.status(err.status).json({error:err.message});next(err)});
export default router;
