import crypto from 'crypto';
import {Router,Response} from 'express';
import db from '../db';
import {requireAuth,type AuthRequest} from '../middleware/auth';
import {requireRoles} from '../middleware/requireRoles';
import {parseRoleKeys} from '../security/roles';
import {sendEmail} from '../mailer';
import {generateReceiptPdf,type ReceiptPdfDocument,type ReceiptPdfLine} from '../services/receiptDocumentPdf';
import {ensureFinanceNav} from '../finance/ensureFinanceNav';

const router=Router();
router.use(requireAuth);
router.use(requireRoles('admin','manager','accounting','bookkeeper','location_manager','salon_manager','receptionist'));
const GLOBAL=new Set(['admin','manager','accounting','bookkeeper']);
const money=(v:any)=>Math.round(Number(v||0)*100)/100;
const pct=(v:any,f=27)=>{let n=Number(v);if(!Number.isFinite(n))n=f;if(n>0&&n<=1)n*=100;return Math.round(n*1000)/1000};
const category=(r:number,raw?:any)=>{const c=String(raw||'').trim().toUpperCase();if(['AAM','TAM','VAT_27','VAT_18','VAT_5','VAT_0','OTHER'].includes(c))return c;if(Math.abs(r-27)<.001)return'VAT_27';if(Math.abs(r-18)<.001)return'VAT_18';if(Math.abs(r-5)<.001)return'VAT_5';if(Math.abs(r)<.001)return'VAT_0';return'OTHER'};
const vat=(gross:any,rate:any,cat?:any)=>{const g=money(gross),r=pct(rate),c=category(r,cat),exempt=c==='AAM'||c==='TAM',net=exempt?g:money(g/(1+r/100));return{vat_rate_percent:r,vat_category:c,gross:g,net,vat:money(g-net)}};
const mergeVat=(rows:any[])=>{const m=new Map<string,any>();for(const x of rows){const k=`${x.vat_category}|${x.vat_rate_percent}`,z=m.get(k)||{...x,gross:0,net:0,vat:0};z.gross=money(z.gross+x.gross);z.net=money(z.net+x.net);z.vat=money(z.vat+x.vat);m.set(k,z)}return[...m.values()]};
const actor=(req:AuthRequest)=>req.user?.email||String(req.user?.id||'');
function scope(req:AuthRequest,res:Response,explicit?:any){const requested=String(explicit??'').trim(),roles=parseRoleKeys(req.user?.role);if(roles.some(r=>GLOBAL.has(r)))return requested||null;const own=String(req.user?.location_id||'').trim();if(!own){res.status(403).json({message:'A felhasználóhoz nincs szalon rendelve.'});return undefined}if(requested&&requested!==own){res.status(403).json({message:'Másik szalon nyugtája nem állítható ki.'});return undefined}return own}

async function ensure(){
 await ensureFinanceNav();
 await db.query(`CREATE TABLE IF NOT EXISTS vir_receipt_sequences(sequence_key text PRIMARY KEY,last_no bigint NOT NULL DEFAULT 0,updated_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE IF NOT EXISTS vir_receipts(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),location_id text,legal_entity_id uuid REFERENCES legal_entities(id) ON DELETE RESTRICT,source_type text NOT NULL,source_id text NOT NULL,source_number text,receipt_number text NOT NULL UNIQUE,document_type text NOT NULL DEFAULT 'SALE',status text NOT NULL DEFAULT 'ISSUED',original_receipt_id uuid REFERENCES vir_receipts(id) ON DELETE RESTRICT,original_receipt_number text,issued_at timestamptz NOT NULL DEFAULT now(),issuer_name text NOT NULL,issuer_tax_number text NOT NULL,issuer_address text NOT NULL,currency text NOT NULL DEFAULT 'HUF',gross_total numeric(14,2) NOT NULL,vat_breakdown jsonb NOT NULL DEFAULT '[]'::jsonb,line_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb,customer_name text,customer_email text,correction_reason text,document_hash text NOT NULL,pdf_sha256 text NOT NULL,pdf_data bytea NOT NULL,email_sent_at timestamptz,email_message_id text,created_by text,created_at timestamptz NOT NULL DEFAULT now(),voided_at timestamptz,voided_by text,void_reason text);
 ALTER TABLE vir_receipts ADD COLUMN IF NOT EXISTS legal_entity_id uuid REFERENCES legal_entities(id) ON DELETE RESTRICT;
 CREATE UNIQUE INDEX IF NOT EXISTS vir_receipts_sale_source_uq ON vir_receipts(source_type,source_id) WHERE document_type='SALE';
 CREATE TABLE IF NOT EXISTS vir_receipt_events(id bigserial PRIMARY KEY,receipt_id uuid NOT NULL REFERENCES vir_receipts(id) ON DELETE RESTRICT,event_type text NOT NULL,actor text,payload jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now());`);
}
async function issuer(c:any,id:string,locationId:string|null){const e=(await c.query(`SELECT e.* FROM legal_entities e JOIN legal_entity_locations el ON el.legal_entity_id=e.id WHERE e.id=$1::uuid AND e.active=true AND el.active=true AND ($2::text IS NULL OR el.location_id::text=$2) LIMIT 1`,[id,locationId])).rows[0];if(!e)throw Object.assign(new Error('A munkalapon kiválasztott cég nem aktív ebben a szalonban.'),{status:409});return{id:String(e.id),name:String(e.legal_name),tax:String(e.tax_number),address:[e.registered_postal_code,e.registered_city,e.registered_address_line].filter(Boolean).join(' '),currency:String(e.currency||'HUF'),defaultVat:Number(e.default_vat_rate||27),prefix:String(e.receipt_prefix||'KLEO-NY').replace(/[^A-Za-z0-9_-]/g,'').slice(0,24)||'KLEO-NY'};}
async function nextNumber(c:any,e:any){const year=new Date().getFullYear(),key=`${e.id}:${e.prefix}:${year}`;await c.query(`INSERT INTO vir_receipt_sequences(sequence_key,last_no) VALUES($1,0) ON CONFLICT(sequence_key) DO NOTHING`,[key]);const no=Number((await c.query(`UPDATE vir_receipt_sequences SET last_no=last_no+1,updated_at=now() WHERE sequence_key=$1 RETURNING last_no`,[key])).rows[0].last_no);return`${e.prefix}-${year}-${String(no).padStart(6,'0')}`;}
async function source(c:any,type:string,id:string){
 if(type==='WORK_ORDER'){
  const w=(await c.query(`SELECT w.*,to_jsonb(w) j FROM work_orders w WHERE w.id::text=$1 FOR UPDATE`,[id])).rows[0];if(!w)throw Object.assign(new Error('A munkalap nem található.'),{status:404});const j=w.j||w;if(!j.legal_entity_id)throw Object.assign(new Error('A munkalaphoz nincs kibocsátó cég kiválasztva.'),{status:409});if(String(j.payment_status||'')!=='paid'&&!j.fully_paid)throw Object.assign(new Error('Nyugta csak teljesen kifizetett munkalapból állítható ki.'),{status:409});if(['requested','issued','invoiced','invoice_requested','sent','submitted'].includes(String(j.invoice_status||'').toLowerCase()))throw Object.assign(new Error('A munkalaphoz számla tartozik; nyugta nem állítható ki.'),{status:409});const rows=(await c.query(`SELECT wi.*,to_jsonb(wi) j,to_jsonb(p) p,to_jsonb(s) s FROM work_order_items wi LEFT JOIN products p ON p.id::text=NULLIF(to_jsonb(wi)->>'product_id','') LEFT JOIN services s ON s.id::text=NULLIF(to_jsonb(wi)->>'service_id','') WHERE wi.work_order_id::text=$1 ORDER BY wi.created_at,wi.id`,[id])).rows;if(!rows.length)throw Object.assign(new Error('A munkalapon nincs nyugtázható tétel.'),{status:409});return{location_id:String(j.location_id||'')||null,legal_entity_id:String(j.legal_entity_id),source_number:String(j.work_order_number||w.id),customer_name:String(j.client_name||'')||null,customer_email:String(j.client_email||'')||null,gross_total:money(j.gross_total||rows.reduce((a:number,r:any)=>a+Number(r.line_total||0),0)-Number(j.discount_amount||0)),rows,discount:money(j.discount_amount||0)};
 }
 if(type==='RETAIL_SALE'){
  const s=(await c.query(`SELECT r.*,to_jsonb(r) j FROM retail_sales r WHERE r.id::text=$1 FOR UPDATE`,[id])).rows[0];if(!s)throw Object.assign(new Error('A termékeladás nem található.'),{status:404});const j=s.j||s;if(!j.legal_entity_id)throw Object.assign(new Error('A termékeladáshoz nincs kibocsátó cég kiválasztva.'),{status:409});if(j.invoice_requested||j.finance_invoice_id)throw Object.assign(new Error('A termékeladáshoz számla tartozik; nyugta nem állítható ki.'),{status:409});const rows=(await c.query(`SELECT i.*,to_jsonb(i) j,to_jsonb(p) p FROM retail_sale_items i LEFT JOIN products p ON p.id::text=i.product_id::text WHERE i.sale_id::text=$1 ORDER BY i.created_at,i.id`,[id])).rows;return{location_id:String(j.location_id||'')||null,legal_entity_id:String(j.legal_entity_id),source_number:String(j.sale_number||s.id),customer_name:String(j.customer_name||'')||null,customer_email:String(j.customer_email||'')||null,gross_total:money(j.gross_total),rows,discount:0};
 }
 throw Object.assign(new Error('Érvénytelen nyugtaforrás.'),{status:400});
}
function makeLines(src:any,defaultVat:number){const raw=src.rows.map((r:any)=>{const x=r.j||r,p=r.p||{},sv=r.s||{};const gross=money(x.line_total??x.gross_amount??0),rate=pct(x.vat_rate??p.vat_rate??sv.vat_rate,defaultVat);return{description:String(x.item_name||x.product_name||p.name||sv.name||'Tétel'),quantity:Number(x.quantity||1),gross,rate,cat:x.vat_category??p.vat_category??sv.vat_category}});const rawTotal=money(raw.reduce((a:number,x:any)=>a+x.gross,0)),target=money(src.gross_total),scale=rawTotal?target/rawTotal:1;return raw.map((x:any)=>({...x,gross:money(x.gross*scale)}));}
async function mail(receipt:any,pdf:Buffer,to:string){return sendEmail({to,subject:`Kleopátra – nyugta ${receipt.receipt_number}`,text:`Kedves Vendég!\n\nCsatolva küldjük a ${receipt.receipt_number} számú nyugta PDF példányát.\n\nÜdvözlettel:\n${receipt.issuer_name}`,html:`<p>Kedves Vendég!</p><p>Csatolva küldjük a <b>${receipt.receipt_number}</b> számú nyugta PDF példányát.</p><p>Üdvözlettel:<br/>${receipt.issuer_name}</p>`,attachments:[{filename:`${receipt.receipt_number}.pdf`,content:pdf,contentType:'application/pdf'}]});}

router.post('/documents/issue',async(req:AuthRequest,res:Response)=>{const c=await db.connect();let receipt:any=null,pdf:Buffer|null=null;try{
 await ensure();const type=String(req.body?.source_type||'').toUpperCase(),id=String(req.body?.source_id||'').trim();if(!['WORK_ORDER','RETAIL_SALE'].includes(type)||!id)return res.status(400).json({message:'A nyugtaforrás kötelező.'});const requestedScope=scope(req,res,req.body?.location_id);if(requestedScope===undefined)return;await c.query('BEGIN');const existing=(await c.query(`SELECT id::text FROM vir_receipts WHERE source_type=$1 AND source_id=$2 AND document_type='SALE' FOR UPDATE`,[type,id])).rows[0];if(existing){await c.query('COMMIT');const row=(await db.query(`SELECT id,location_id,legal_entity_id,source_type,source_id,source_number,receipt_number,document_type,status,issued_at,issuer_name,issuer_tax_number,issuer_address,currency,gross_total,customer_name,customer_email,email_sent_at FROM vir_receipts WHERE id=$1::uuid`,[existing.id])).rows[0];return res.json({ok:true,receipt:row,idempotent:true})}
 const src=await source(c,type,id);if(requestedScope&&src.location_id&&requestedScope!==src.location_id)throw Object.assign(new Error('A forrás másik szalonhoz tartozik.'),{status:403});const e=await issuer(c,src.legal_entity_id,src.location_id||requestedScope),receiptNumber=await nextNumber(c,e),issuedAt=new Date().toISOString(),lines=makeLines(src,e.defaultVat),vatBreakdown=mergeVat(lines.map((x:any)=>vat(x.gross,x.rate,x.cat))),pdfLines:ReceiptPdfLine[]=lines.map((x:any)=>({description:x.description,quantity:x.quantity,gross:x.gross,vat_rate_percent:x.rate,vat_category:category(x.rate,x.cat)}));const base={source_type:type,source_id:id,source_number:src.source_number,receipt_number:receiptNumber,document_type:'SALE' as const,issued_at:issuedAt,issuer_name:e.name,issuer_tax_number:e.tax,issuer_address:e.address,currency:e.currency,gross_total:money(src.gross_total),vat_breakdown:vatBreakdown,lines:pdfLines,customer_name:src.customer_name,customer_email:String(req.body?.customer_email||src.customer_email||'').trim()||null,original_receipt_number:null,correction_reason:null};const documentHash=crypto.createHash('sha256').update(JSON.stringify(base)).digest('hex');pdf=await generateReceiptPdf({...base,document_hash:documentHash} as ReceiptPdfDocument);const pdfHash=crypto.createHash('sha256').update(pdf).digest('hex');receipt=(await c.query(`INSERT INTO vir_receipts(location_id,legal_entity_id,source_type,source_id,source_number,receipt_number,document_type,status,issued_at,issuer_name,issuer_tax_number,issuer_address,currency,gross_total,vat_breakdown,line_snapshot,customer_name,customer_email,document_hash,pdf_sha256,pdf_data,created_by) VALUES($1,$2::uuid,$3,$4,$5,$6,'SALE','ISSUED',$7,$8,$9,$10,$11,$12,$13::jsonb,$14::jsonb,$15,$16,$17,$18,$19,$20) RETURNING id::text,location_id,legal_entity_id,source_type,source_id,source_number,receipt_number,document_type,status,issued_at,issuer_name,issuer_tax_number,issuer_address,currency,gross_total,customer_name,customer_email,email_sent_at`,[src.location_id||requestedScope,e.id,type,id,src.source_number,receiptNumber,issuedAt,e.name,e.tax,e.address,e.currency,src.gross_total,JSON.stringify(vatBreakdown),JSON.stringify(pdfLines),src.customer_name,base.customer_email,documentHash,pdfHash,pdf,actor(req)])).rows[0];await c.query(`INSERT INTO vir_receipt_events(receipt_id,event_type,actor,payload) VALUES($1,'ISSUED',$2,$3::jsonb)`,[receipt.id,actor(req),JSON.stringify({source_type:type,source_id:id,legal_entity_id:e.id,pdf_sha256:pdfHash})]);if(type==='WORK_ORDER')await c.query(`UPDATE work_orders SET receipt_status='issued',receipt_id=$2::uuid WHERE id::text=$1`,[id,receipt.id]).catch(()=>undefined);else await c.query(`UPDATE retail_sales SET receipt_status='issued',receipt_id=$2::uuid WHERE id::text=$1`,[id,receipt.id]).catch(()=>undefined);await c.query('COMMIT');
 const sendNow=req.body?.send_email===true&&receipt.customer_email;if(sendNow&&pdf){const info=await mail(receipt,pdf,String(receipt.customer_email));await db.query(`UPDATE vir_receipts SET email_sent_at=CASE WHEN $2::boolean THEN now() ELSE email_sent_at END,email_message_id=COALESCE($3,email_message_id) WHERE id=$1::uuid`,[receipt.id,Boolean((info as any)?.sent),(info as any)?.messageId||null]);await db.query(`INSERT INTO vir_receipt_events(receipt_id,event_type,actor,payload) VALUES($1,$2,$3,$4::jsonb)`,[receipt.id,(info as any)?.sent?'EMAIL_SENT':'EMAIL_LOGGED',actor(req),JSON.stringify({to:receipt.customer_email,message_id:(info as any)?.messageId||null})]);receipt.email_sent_at=(info as any)?.sent?new Date().toISOString():null}
 return res.status(201).json({ok:true,receipt,legal_entity:{id:e.id,legal_name:e.name,tax_number:e.tax},email_requested:Boolean(sendNow)});
 }catch(err:any){await c.query('ROLLBACK').catch(()=>undefined);return res.status(Number(err?.status||500)).json({message:err?.message||'A nyugta nem állítható ki.'})}finally{c.release()}});

export default router;
