import { NextFunction, Response, Router } from "express";
import db from "../db";
import { requireTenantRole, TenantAuthRequest } from "../middleware/tenantContext";
import { createStripeCheckout, createStripePortal, processStripeEvent, retrieveStripeEvent, runRevenueDunningCycle, stripeBillingReadiness } from "../saas/stripeBilling";

const router=Router();
export const saasRevenuePublicRouter=Router();
const manage=requireTenantRole("owner","admin");

export async function ensureRevenueSchema(){
 await db.query(`
  ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS annual_price numeric(14,2);
  ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS onboarding_fee numeric(14,2) NOT NULL DEFAULT 0;
  ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS trial_days integer NOT NULL DEFAULT 0;
  ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS recommended boolean NOT NULL DEFAULT false;
  ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS public_visible boolean NOT NULL DEFAULT false;
  ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS booking_commission_percent numeric(6,3) NOT NULL DEFAULT 0;
  ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS addons jsonb NOT NULL DEFAULT '{}'::jsonb;
  ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS billing_interval text NOT NULL DEFAULT 'month';
  ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS next_retry_at timestamptz;
  ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS dunning_step integer NOT NULL DEFAULT 0;
  ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS payment_method_status text;
  CREATE TABLE IF NOT EXISTS billing_checkout_sessions(
    id bigserial PRIMARY KEY,tenant_id bigint NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,subscription_id bigint REFERENCES subscriptions(id) ON DELETE SET NULL,
    provider text NOT NULL,external_session_id text NOT NULL,plan_code text NOT NULL,billing_interval text NOT NULL,status text NOT NULL DEFAULT 'created',amount numeric(14,2) NOT NULL DEFAULT 0,currency text NOT NULL DEFAULT 'HUF',coupon_code text,checkout_url text,expires_at timestamptz,created_by text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(provider,external_session_id));
  CREATE INDEX IF NOT EXISTS billing_checkout_tenant_idx ON billing_checkout_sessions(tenant_id,created_at DESC);
  CREATE TABLE IF NOT EXISTS subscription_coupons(
    id bigserial PRIMARY KEY,code text NOT NULL UNIQUE,description text,percent_off numeric(6,2) NOT NULL CHECK(percent_off>0 AND percent_off<=100),valid_from timestamptz NOT NULL DEFAULT now(),valid_until timestamptz,max_redemptions integer,redemption_count integer NOT NULL DEFAULT 0,active boolean NOT NULL DEFAULT true,plan_codes jsonb NOT NULL DEFAULT '[]'::jsonb,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
  CREATE TABLE IF NOT EXISTS subscription_coupon_redemptions(
    id bigserial PRIMARY KEY,coupon_id bigint NOT NULL REFERENCES subscription_coupons(id),tenant_id bigint NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,subscription_id bigint REFERENCES subscriptions(id) ON DELETE SET NULL,external_session_id text,redeemed_at timestamptz NOT NULL DEFAULT now(),UNIQUE(coupon_id,tenant_id));
  UPDATE subscription_plans SET annual_price=299000,onboarding_fee=49900,trial_days=14,recommended=false,public_visible=true,booking_commission_percent=0,monthly_price=29900,max_locations=1,max_users=5,
    addons='{"extra_location_monthly":19900,"ai_plus_monthly":9900,"white_label_monthly":39900,"branded_app_monthly":49900}'::jsonb WHERE code='start';
  UPDATE subscription_plans SET annual_price=599000,onboarding_fee=99900,trial_days=14,recommended=true,public_visible=true,booking_commission_percent=0,monthly_price=59900,max_locations=1,max_users=15,
    addons='{"extra_location_monthly":19900,"ai_plus_monthly":9900,"white_label_monthly":39900,"branded_app_monthly":49900}'::jsonb WHERE code='pro';
  UPDATE subscription_plans SET annual_price=1499000,onboarding_fee=299000,trial_days=0,recommended=false,public_visible=true,booking_commission_percent=0,monthly_price=149900,max_locations=5,max_users=50 WHERE code='franchise';
  UPDATE subscription_plans SET annual_price=2999000,onboarding_fee=0,trial_days=0,recommended=false,public_visible=true,booking_commission_percent=0,monthly_price=299900 WHERE code='enterprise';
 `);
}

router.use(async(_req,_res,next:NextFunction)=>{try{await ensureRevenueSchema();next();}catch(error){next(error);}});

router.get("/config",async(_req,res)=>res.json({ok:true,provider:"stripe",...stripeBillingReadiness()}));
router.get("/catalog",async(_req,res)=>{try{const{rows}=await db.query(`SELECT code,name,monthly_price,annual_price,onboarding_fee,currency,max_locations,max_users,features,trial_days,recommended,booking_commission_percent,addons FROM subscription_plans WHERE active=true AND public_visible=true AND code<>'internal' ORDER BY monthly_price`);return res.json({ok:true,rows});}catch(error){return res.status(500).json({ok:false,error:"A SaaS árkatalógus nem tölthető be."});}});
router.get("/summary",async(req:TenantAuthRequest,res:Response)=>{try{const sub=await db.query(`SELECT s.id::text,s.status,s.billing_provider,s.billing_interval,s.external_customer_id,s.external_subscription_id,s.current_period_end,s.trial_ends_at,s.grace_period_end,s.next_retry_at,s.dunning_step,s.payment_method_status,s.last_payment_status,s.last_payment_at,sp.code plan_code,sp.name plan_name,sp.monthly_price,sp.annual_price,sp.currency FROM subscriptions s JOIN subscription_plans sp ON sp.id=s.plan_id WHERE s.tenant_id=$1::bigint ORDER BY CASE WHEN s.status IN('trial','active','past_due','suspended') THEN 0 ELSE 1 END,s.created_at DESC LIMIT 1`,[req.tenant!.id]);const checkouts=await db.query(`SELECT id::text,provider,external_session_id,plan_code,billing_interval,status,amount,currency,coupon_code,expires_at,created_at FROM billing_checkout_sessions WHERE tenant_id=$1::bigint ORDER BY created_at DESC LIMIT 10`,[req.tenant!.id]);const invoices=await db.query(`SELECT id::text,status,period_start,period_end,currency,net_amount,tax_amount,gross_amount,due_at,paid_at,external_invoice_id,created_at FROM subscription_invoices WHERE tenant_id=$1::bigint ORDER BY created_at DESC LIMIT 24`,[req.tenant!.id]);return res.json({ok:true,provider:stripeBillingReadiness(),subscription:sub.rows[0]||null,checkouts:checkouts.rows,invoices:invoices.rows});}catch(error){return res.status(500).json({ok:false,error:"A Revenue Engine állapota nem tölthető be."});}});

async function couponFor(code:string,planCode:string){if(!code)return null;const result=await db.query(`SELECT * FROM subscription_coupons WHERE lower(code)=lower($1) AND active=true AND valid_from<=now() AND (valid_until IS NULL OR valid_until>now()) AND (max_redemptions IS NULL OR redemption_count<max_redemptions) LIMIT 1`,[code]);const coupon=result.rows[0];if(!coupon)return null;const plans=Array.isArray(coupon.plan_codes)?coupon.plan_codes:[];if(plans.length&&!plans.map(String).includes(planCode))return null;return coupon;}
router.post("/coupons/validate",manage,async(req:TenantAuthRequest,res:Response)=>{const code=String(req.body?.code||"").trim(),planCode=String(req.body?.plan_code||"").trim().toLowerCase();if(!code||!planCode)return res.status(400).json({ok:false,error:"A kuponkód és csomag kötelező."});try{const coupon=await couponFor(code,planCode);if(!coupon)return res.status(404).json({ok:false,error:"A kupon nem érvényes ehhez a csomaghoz."});const used=await db.query(`SELECT 1 FROM subscription_coupon_redemptions WHERE coupon_id=$1 AND tenant_id=$2::bigint`,[coupon.id,req.tenant!.id]);if(used.rowCount)return res.status(409).json({ok:false,error:"Ezt a kupont ez a tenant már felhasználta."});return res.json({ok:true,coupon:{code:coupon.code,description:coupon.description,percent_off:Number(coupon.percent_off)}});}catch(error){return res.status(500).json({ok:false,error:"A kupon nem ellenőrizhető."});}});

router.post("/checkout",manage,async(req:TenantAuthRequest,res:Response)=>{const planCode=String(req.body?.plan_code||"").trim().toLowerCase(),billingInterval=req.body?.billing_interval==="year"?"year":"month",couponCode=String(req.body?.coupon_code||"").trim();if(!planCode||planCode==="internal")return res.status(400).json({ok:false,error:"Érvényes publikus csomag szükséges."});try{const readiness=stripeBillingReadiness();if(!readiness.configured)return res.status(503).json({ok:false,code:"STRIPE_NOT_CONFIGURED",error:"A fizetési szolgáltató még nincs konfigurálva."});const plan=(await db.query(`SELECT id,code,name,monthly_price,annual_price,currency FROM subscription_plans WHERE code=$1 AND active=true AND public_visible=true LIMIT 1`,[planCode])).rows[0];if(!plan)return res.status(404).json({ok:false,error:"A csomag nem található."});const subscription=(await db.query(`SELECT * FROM subscriptions WHERE tenant_id=$1::bigint ORDER BY CASE WHEN status IN('trial','active','past_due','suspended') THEN 0 ELSE 1 END,created_at DESC LIMIT 1`,[req.tenant!.id])).rows[0];if(subscription?.external_subscription_id)return res.status(409).json({ok:false,code:"USE_BILLING_PORTAL",error:"A meglévő Stripe előfizetést a számlázási portálon lehet módosítani."});const tenant=(await db.query(`SELECT name,billing_email FROM tenants WHERE id=$1::bigint`,[req.tenant!.id])).rows[0]||{};let coupon:any=null;if(couponCode){coupon=await couponFor(couponCode,planCode);if(!coupon)return res.status(400).json({ok:false,error:"Érvénytelen kupon."});const used=await db.query(`SELECT 1 FROM subscription_coupon_redemptions WHERE coupon_id=$1 AND tenant_id=$2::bigint`,[coupon.id,req.tenant!.id]);if(used.rowCount)return res.status(409).json({ok:false,error:"A kupon már fel lett használva."});}
 const checkout=await createStripeCheckout({tenantId:String(req.tenant!.id),tenantName:tenant.name||"KleoSaaS",billingEmail:tenant.billing_email||null,externalCustomerId:subscription?.external_customer_id||null,plan,billingInterval,couponPercent:coupon?Number(coupon.percent_off):null});const amount=billingInterval==="year"?Number(plan.annual_price||0):Number(plan.monthly_price||0);await db.query(`INSERT INTO billing_checkout_sessions(tenant_id,subscription_id,provider,external_session_id,plan_code,billing_interval,status,amount,currency,coupon_code,checkout_url,expires_at,created_by) VALUES($1::bigint,$2,'stripe',$3,$4,$5,'created',$6,$7,$8,$9,to_timestamp($10),$11)`,[req.tenant!.id,subscription?.id||null,checkout.id,planCode,billingInterval,amount,String(plan.currency||"HUF").toUpperCase(),coupon?.code||null,checkout.url||null,checkout.expires_at||null,String(req.user?.id||req.user?.email||"")]);return res.status(201).json({ok:true,provider:"stripe",session_id:checkout.id,url:checkout.url,expires_at:checkout.expires_at||null});}catch(error:any){console.error("[SAAS REVENUE] checkout",error?.code||"",error?.message||error);const status=error?.code==="STRIPE_TAX_NOT_CONFIGURED"?503:500;return res.status(status).json({ok:false,code:error?.code||"CHECKOUT_FAILED",error:error?.message||"A fizetés nem indítható."});}});

router.post("/portal",manage,async(req:TenantAuthRequest,res:Response)=>{try{const sub=(await db.query(`SELECT external_customer_id FROM subscriptions WHERE tenant_id=$1::bigint AND billing_provider='stripe' ORDER BY created_at DESC LIMIT 1`,[req.tenant!.id])).rows[0];if(!sub?.external_customer_id)return res.status(409).json({ok:false,code:"STRIPE_CUSTOMER_MISSING",error:"Ehhez a tenanthoz még nincs Stripe számlázási profil."});const portal=await createStripePortal(String(sub.external_customer_id));return res.json({ok:true,url:portal.url});}catch(error:any){return res.status(500).json({ok:false,code:error?.code||"PORTAL_FAILED",error:error?.message||"A számlázási portál nem nyitható meg."});}});
router.post("/dunning/run",manage,async(_req,res)=>{try{return res.json({ok:true,...await runRevenueDunningCycle()});}catch(error){return res.status(500).json({ok:false,error:"A dunning ciklus nem futtatható."});}});

async function finalizeCheckout(event:any){const session=event?.data?.object||{};const sessionId=String(session?.id||"");if(!sessionId)return;const client=await db.connect();try{await client.query("BEGIN");const updated=await client.query(`UPDATE billing_checkout_sessions SET status='completed',updated_at=now() WHERE provider='stripe' AND external_session_id=$1 AND status<>'completed' RETURNING tenant_id,subscription_id,coupon_code`,[sessionId]);const row=updated.rows[0];if(row?.coupon_code){const coupon=await client.query(`SELECT id FROM subscription_coupons WHERE lower(code)=lower($1) LIMIT 1`,[row.coupon_code]);if(coupon.rows[0]){const redeemed=await client.query(`INSERT INTO subscription_coupon_redemptions(coupon_id,tenant_id,subscription_id,external_session_id) VALUES($1,$2,$3,$4) ON CONFLICT(coupon_id,tenant_id) DO NOTHING RETURNING id`,[coupon.rows[0].id,row.tenant_id,row.subscription_id,sessionId]);if(redeemed.rowCount)await client.query(`UPDATE subscription_coupons SET redemption_count=redemption_count+1,updated_at=now() WHERE id=$1`,[coupon.rows[0].id]);}}await client.query("COMMIT");}catch(error){await client.query("ROLLBACK").catch(()=>{});throw error;}finally{client.release();}}
saasRevenuePublicRouter.post("/webhook/stripe",async(req,res)=>{const eventId=String(req.body?.id||"").trim();if(!eventId)return res.status(400).json({ok:false,error:"Stripe event id szükséges."});try{const canonicalEvent=await retrieveStripeEvent(eventId);const result=await processStripeEvent(canonicalEvent);if(canonicalEvent?.type==="checkout.session.completed")await finalizeCheckout(canonicalEvent);if(canonicalEvent?.type==="checkout.session.expired")await db.query(`UPDATE billing_checkout_sessions SET status='expired',updated_at=now() WHERE provider='stripe' AND external_session_id=$1`,[String(canonicalEvent?.data?.object?.id||"")]);return res.json(result);}catch(error:any){console.error("[SAAS REVENUE] webhook",error?.code||"",error?.message||error);return res.status(error?.status===404?400:500).json({ok:false,code:error?.code||"WEBHOOK_FAILED",error:"A Stripe webhook nem hitelesíthető vagy nem dolgozható fel."});}});

export default router;