import express,{NextFunction,Request,Response} from "express";
import inventoryRouter from "./inventory";
import aiSupportRouter from "./aiSupport";
import collaborationChatRouter from "./collaborationChat";
import cashierRouter from "./cashier";
import financeOperationsRouter from "./financeOperations";
import financeLinkingRouter from "./financeLinking";
import financeControlRouter from "./financeControl";
import systemHealthRouter from "./systemHealth";
import uatTestCenterRouter from "./uatTestCenter";
import uatIssuesRouter from "./uatIssues";
import loyaltyRouter from "./loyalty";
import loyaltyAnalyticsRouter from "./loyaltyAnalytics";
import loyaltyOperationsRouter from "./loyaltyOperations";
import loyaltyPassLookupRouter from "./loyaltyPassLookup";
import loyaltyCommissionRouter from "./loyaltyCommission";
import loyaltyCustomerFinanceRouter from "./loyaltyCustomerFinance";
import loyaltyCashierRouter from "./loyaltyCashier";
import loyaltyAutomationRouter from "./loyaltyAutomation";
import workOrderFinalizationRouter from "./workOrderFinalization";
import workOrderInvoiceChainRouter from "./workOrderInvoiceChain";
import navOnlineInvoiceSettingsRouter from "./navOnlineInvoiceSettings";
import navOnlineInvoiceRouter from "./navOnlineInvoice";
import navOnlineInvoiceStatusRouter from "./navOnlineInvoiceStatus";
import navInvoiceLifecycleRouter from "./navInvoiceLifecycle";
import notificationsRouter from "./notifications";
import managementSummaryRouter from "./managementSummary";
import dashboardSettingsRouter from "./dashboardSettings";
import auditLogRouter from "./auditLog";
import purchaseOrdersRouter from "./purchaseOrders";
import suppliersRouter from "./suppliers";
import procurementWorkflowRouter from "./procurementWorkflow";
import bookingOperationsRouter from "./bookingOperations";
import bookingCommunicationsRouter from "./bookingCommunications";
import { requirePurchaseOrderAccess, requireProcurementWorkflowAccess } from "../middleware/procurementAccess";
import { requireMenuPermission, requireMenuPermissionByMethod } from "../middleware/menuPermission";
import { requireFeature } from "../middleware/featureAccess";
import {ensureFinanceNav} from "../finance/ensureFinanceNav";
import type {AuthRequest} from "../middleware/auth";
const router=express.Router();
const ensureFinanceReady=async(_req:Request,res:Response,next:NextFunction)=>{try{await ensureFinanceNav();next()}catch(error:any){console.error('Finance/NAV schema bootstrap hiba:',error?.message||error);res.status(503).json({ok:false,error:'finance_schema_unavailable',message:'A pénzügyi/NAV adatbázis séma jelenleg nem kész. A rendszer automatikusan újrapróbálja.',detail:process.env.NODE_ENV==='development'?String(error?.message||error):undefined})}};
const navAdminOnly=(req:AuthRequest,res:Response,next:NextFunction)=>{const raw:any=req.user?.role;const rs=(Array.isArray(raw)?raw:String(raw||'').replace(/[\[\]"]/g,'').split(',')).map((x:any)=>String(x).trim().toLowerCase()).filter(Boolean);if(rs.some((r:string)=>['admin','administrator','rendszergazda','superadmin','super_admin'].includes(r)))return next();return res.status(403).json({message:'A NAV Online Számla modul csak adminisztrátor számára érhető el.'})};
router.get("/",(_req,res)=>res.json([{id:1,type:"income",amount:10000}]));
router.use("/inventory",requireFeature("inventory"),requireMenuPermissionByMethod("inventory"),inventoryRouter);
router.use("/procurement",requirePurchaseOrderAccess,purchaseOrdersRouter);
router.use("/procurement-workflow",requireProcurementWorkflowAccess,procurementWorkflowRouter);
router.use("/suppliers",requireFeature("procurement"),requireMenuPermissionByMethod("procurement.suppliers"),suppliersRouter);
router.use("/ai-support",aiSupportRouter);router.use("/staff-chat",collaborationChatRouter);
router.use("/booking-operations",bookingOperationsRouter);router.use("/booking-communications",bookingCommunicationsRouter);
router.use("/cashier",ensureFinanceReady,requireFeature("finance"),requireMenuPermissionByMethod("finance.checkout"),cashierRouter);
router.use("/finance-operations",ensureFinanceReady,requireFeature("finance"),requireMenuPermissionByMethod("finance"),financeOperationsRouter);
router.use("/finance-linking",ensureFinanceReady,requireFeature("finance"),requireMenuPermissionByMethod("finance"),financeLinkingRouter);
router.use("/finance-control",ensureFinanceReady,requireFeature("finance"),requireMenuPermissionByMethod("finance"),financeControlRouter);
router.use("/loyalty",loyaltyRouter);
router.use("/loyalty-analytics",loyaltyAnalyticsRouter);
router.use("/loyalty-operations",loyaltyPassLookupRouter);
router.use("/loyalty-operations",loyaltyOperationsRouter);
router.use("/loyalty-commission",loyaltyCommissionRouter);
router.use("/loyalty-v4",loyaltyCustomerFinanceRouter);
router.use("/loyalty-cashier",ensureFinanceReady,requireFeature("finance"),requireMenuPermissionByMethod("finance.checkout"),loyaltyCashierRouter);
router.use("/workorder-finalization",ensureFinanceReady,requireFeature("finance"),requireMenuPermissionByMethod("finance.checkout"),workOrderFinalizationRouter);
router.use("/workorder-invoice",ensureFinanceReady,requireFeature("finance"),requireMenuPermissionByMethod("finance"),workOrderInvoiceChainRouter);
router.use("/nav-online-invoice",ensureFinanceReady,requireFeature("finance"),navAdminOnly,navOnlineInvoiceSettingsRouter);
router.use("/nav-online-invoice",ensureFinanceReady,requireFeature("finance"),navAdminOnly,requireMenuPermissionByMethod("finance"),navOnlineInvoiceRouter);
router.use("/nav-online-invoice",ensureFinanceReady,requireFeature("finance"),navAdminOnly,requireMenuPermissionByMethod("finance"),navOnlineInvoiceStatusRouter);
router.use("/nav-online-invoice",ensureFinanceReady,requireFeature("finance"),navAdminOnly,requireMenuPermissionByMethod("finance"),navInvoiceLifecycleRouter);
router.use("/loyalty-automation",loyaltyAutomationRouter);
router.use("/system-health",ensureFinanceReady,systemHealthRouter);
router.use("/uat",uatTestCenterRouter);
router.use("/uat-issues",uatIssuesRouter);
router.use("/cashier/management-summary",ensureFinanceReady,requireFeature("management_dashboard"),requireMenuPermission("finance","can_view_financial"),managementSummaryRouter);
router.use("/management",requireFeature("management_dashboard"),requireMenuPermission("analytics","can_view_financial"),managementSummaryRouter);
router.use("/dashboard-settings",requireFeature("management_dashboard"),dashboardSettingsRouter);
router.use("/notifications",notificationsRouter);router.use("/audit",requireFeature("audit"),requireMenuPermission("settings.audit","can_view"),auditLogRouter);
export default router;
