import { Router } from "express";
import db from "../db";
import { requireAuth, AuthRequest } from "../middleware/auth";

const router=Router();
router.use(requireAuth);
const actor=(req:AuthRequest)=>req.user?.email||String(req.user?.id||"");

router.get("/",async(req,res,next)=>{try{const runId=String(req.query.run_id||"").trim();const status=String(req.query.status||"").trim();const{rows}=await db.query(`SELECT i.*,c.code test_code,c.title test_title,r.status result_status FROM uat_issues i LEFT JOIN uat_test_cases c ON c.id=i.test_case_id LEFT JOIN uat_test_results r ON r.id=i.result_id WHERE ($1::text='' OR i.run_id::text=$1) AND ($2::text='' OR i.status=$2) ORDER BY CASE i.priority WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 ELSE 4 END,i.created_at DESC`,[runId,status]);res.json(rows)}catch(err){next(err)}});

router.post("/sync/:runId",async(req:AuthRequest,res,next)=>{const client=await db.connect();try{await client.query("BEGIN");const runId=req.params.runId;const failed=await client.query(`SELECT x.id result_id,x.test_case_id,x.status,x.note,c.code,c.title,c.critical FROM uat_test_results x JOIN uat_test_cases c ON c.id=x.test_case_id WHERE x.run_id=$1::uuid AND x.status IN ('failed','blocked')`,[runId]);let created=0;for(const x of failed.rows){const priority=x.critical?'critical':x.status==='failed'?'high':'medium';const code=`ISS-${x.code}-${String(x.result_id).slice(0,8)}`;const q=await client.query(`INSERT INTO uat_issues(run_id,result_id,test_case_id,code,title,description,priority,status,reporter,retest_required,retest_status) VALUES($1::uuid,$2::uuid,$3::uuid,$4,$5,$6,$7,'open',$8,true,'pending') ON CONFLICT DO NOTHING RETURNING id`,[runId,x.result_id,x.test_case_id,code,`${x.code} · ${x.title}`,x.note||`UAT eredmény: ${x.status}`,priority,actor(req)]);created+=q.rowCount||0}await client.query("COMMIT");res.json({ok:true,created,total_failed_or_blocked:failed.rowCount||0})}catch(err){await client.query("ROLLBACK");next(err)}finally{client.release()}});

router.patch("/:id",async(req:AuthRequest,res,next)=>{try{const allowedStatus=['open','in_progress','fixed','retest','closed','rejected'];const allowedPriority=['critical','high','medium','low'];const status=req.body?.status?String(req.body.status):null;const priority=req.body?.priority?String(req.body.priority):null;if(status&&!allowedStatus.includes(status))return res.status(400).json({message:'Érvénytelen hibajegy státusz.'});if(priority&&!allowedPriority.includes(priority))return res.status(400).json({message:'Érvénytelen prioritás.'});const{rows}=await db.query(`UPDATE uat_issues SET status=COALESCE($2,status),priority=COALESCE($3,priority),assignee=COALESCE($4,assignee),description=COALESCE($5,description),resolution=COALESCE($6,resolution),updated_at=now(),resolved_at=CASE WHEN $2 IN ('fixed','retest','closed') THEN COALESCE(resolved_at,now()) ELSE resolved_at END,closed_at=CASE WHEN $2='closed' THEN now() ELSE closed_at END WHERE id=$1::uuid RETURNING *`,[req.params.id,status,priority,req.body?.assignee??null,req.body?.description??null,req.body?.resolution??null]);if(!rows[0])return res.status(404).json({message:'A hibajegy nem található.'});res.json(rows[0])}catch(err){next(err)}});

router.post("/:id/retest",async(req:AuthRequest,res,next)=>{const client=await db.connect();try{await client.query("BEGIN");const issue=await client.query(`SELECT * FROM uat_issues WHERE id=$1::uuid FOR UPDATE`,[req.params.id]);const i=issue.rows[0];if(!i){await client.query("ROLLBACK");return res.status(404).json({message:'A hibajegy nem található.'})}const passed=Boolean(req.body?.passed);const note=String(req.body?.note||'').trim();await client.query(`UPDATE uat_issues SET status=$2,retest_status=$3,resolution=COALESCE(NULLIF($4,''),resolution),updated_at=now(),closed_at=CASE WHEN $3='passed' THEN now() ELSE NULL END WHERE id=$1::uuid`,[req.params.id,passed?'closed':'in_progress',passed?'passed':'failed',note]);if(i.result_id){await client.query(`UPDATE uat_test_results SET status=$2,tester=$3,tested_at=now(),note=COALESCE(NULLIF($4,''),note),updated_at=now() WHERE id=$1::uuid`,[i.result_id,passed?'passed':'failed',actor(req),note])}await client.query("COMMIT");res.json({ok:true,status:passed?'closed':'in_progress',retest_status:passed?'passed':'failed'})}catch(err){await client.query("ROLLBACK");next(err)}finally{client.release()}});

router.get("/summary/:runId",async(req,res,next)=>{try{const{rows}=await db.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status NOT IN ('closed','rejected'))::int open,COUNT(*) FILTER(WHERE priority='critical' AND status NOT IN ('closed','rejected'))::int critical_open,COUNT(*) FILTER(WHERE retest_status='pending')::int retest_pending,COUNT(*) FILTER(WHERE retest_status='failed')::int retest_failed FROM uat_issues WHERE run_id=$1::uuid`,[req.params.runId]);res.json(rows[0]||{total:0,open:0,critical_open:0,retest_pending:0,retest_failed:0})}catch(err){next(err)}});
export default router;
