import { Router } from "express";
import db from "../db";
import { requireAuth, AuthRequest } from "../middleware/auth";

const router=Router();
router.use(requireAuth);
const actor=(req:AuthRequest)=>req.user?.email||String(req.user?.id||"");

router.get("/cases",async(_req,res,next)=>{try{const{rows}=await db.query(`SELECT * FROM uat_test_cases WHERE active=true ORDER BY order_index,code`);res.json(rows)}catch(err){next(err)}});
router.get("/runs",async(req:AuthRequest,res,next)=>{try{const locationId=String(req.query.location_id||"").trim();const{rows}=await db.query(`SELECT r.*,COUNT(x.id)::int total,COUNT(*) FILTER(WHERE x.status='passed')::int passed,COUNT(*) FILTER(WHERE x.status='failed')::int failed,COUNT(*) FILTER(WHERE x.status='blocked')::int blocked,COUNT(*) FILTER(WHERE x.status='not_tested')::int not_tested FROM uat_test_runs r LEFT JOIN uat_test_results x ON x.run_id=r.id WHERE ($1::text='' OR r.location_id::text=$1 OR r.location_id IS NULL) GROUP BY r.id ORDER BY r.started_at DESC LIMIT 50`,[locationId]);res.json(rows)}catch(err){next(err)}});
router.post("/runs",async(req:AuthRequest,res,next)=>{const client=await db.connect();try{await client.query("BEGIN");const locationId=String(req.body?.location_id||"").trim()||null;const name=String(req.body?.name||`UAT ${new Date().toISOString().slice(0,10)}`).trim();const run=await client.query(`INSERT INTO uat_test_runs(name,location_id,status,started_by,note) VALUES($1,$2::uuid,'open',$3,$4) RETURNING *`,[name,locationId,actor(req),req.body?.note||null]);await client.query(`INSERT INTO uat_test_results(run_id,test_case_id,status) SELECT $1,id,'not_tested' FROM uat_test_cases WHERE active=true ON CONFLICT DO NOTHING`,[run.rows[0].id]);await client.query("COMMIT");res.status(201).json(run.rows[0])}catch(err){await client.query("ROLLBACK");next(err)}finally{client.release()}});
router.post("/seed-and-start",async(req:AuthRequest,res,next)=>{const client=await db.connect();try{await client.query("BEGIN");const requested=String(req.body?.location_id||"").trim();let locationId=requested||null;if(!locationId){const l=await client.query(`SELECT id::text FROM locations ORDER BY id LIMIT 1`);locationId=l.rows[0]?.id||null}if(!locationId){await client.query("ROLLBACK");return res.status(409).json({message:"Nincs telephely. Előbb hozz létre legalább egy telephelyet."})}const stamp=Date.now().toString().slice(-8);const email=`uat.${stamp}@kleopatra.test`;let customerId:string|null=null;const customerTable=await client.query(`SELECT to_regclass('public.customers') IS NOT NULL ok`);if(customerTable.rows[0]?.ok){const cols=await client.query(`SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name='customers'`);const c=new Set(cols.rows.map((x:any)=>x.column_name));if(c.has('name')&&c.has('email')){const q=await client.query(`INSERT INTO customers(name,email${c.has('phone')?',phone':''}) VALUES($1,$2${c.has('phone')?',$3':''}) RETURNING id::text`,c.has('phone')?[`UAT Teszt Vendég ${stamp}`,email,'+3610000000']:[`UAT Teszt Vendég ${stamp}`,email]);customerId=q.rows[0]?.id||null}}
const run=await client.query(`INSERT INTO uat_test_runs(name,location_id,status,started_by,note) VALUES($1,$2::uuid,'open',$3,$4) RETURNING *`,[`Automatikus UAT ${new Date().toISOString().slice(0,10)} #${stamp}`,locationId,actor(req),`Automatikusan létrehozott tesztkörnyezet. Teszt vendég: ${email}`]);await client.query(`INSERT INTO uat_test_results(run_id,test_case_id,status,note) SELECT $1,id,'not_tested','Automatikus UAT tesztadat-készlet létrehozva.' FROM uat_test_cases WHERE active=true ON CONFLICT DO NOTHING`,[run.rows[0].id]);await client.query("COMMIT");res.status(201).json({run:run.rows[0],seed:{location_id:locationId,customer_id:customerId,customer_email:email,tag:`UAT-${stamp}`},message:"Tesztadat-készlet és UAT futás létrehozva. A generált rekordok UAT jelölésűek."})}catch(err){await client.query("ROLLBACK");next(err)}finally{client.release()}});
router.get("/runs/:id",async(req,res,next)=>{try{const run=await db.query(`SELECT * FROM uat_test_runs WHERE id=$1::uuid`,[req.params.id]);if(!run.rows[0])return res.status(404).json({message:"A tesztfutás nem található."});const results=await db.query(`SELECT x.*,c.code,c.module_key,c.title,c.description,c.expected_result,c.route,c.order_index,c.critical FROM uat_test_results x JOIN uat_test_cases c ON c.id=x.test_case_id WHERE x.run_id=$1::uuid ORDER BY c.order_index,c.code`,[req.params.id]);res.json({...run.rows[0],results:results.rows})}catch(err){next(err)}});
router.patch("/runs/:runId/results/:resultId",async(req:AuthRequest,res,next)=>{try{const status=String(req.body?.status||"");if(!['not_tested','passed','failed','blocked','skipped'].includes(status))return res.status(400).json({message:"Érvénytelen UAT státusz."});const{rows}=await db.query(`UPDATE uat_test_results SET status=$3,tester=$4,tested_at=CASE WHEN $3='not_tested' THEN NULL ELSE now() END,note=$5,evidence=$6,updated_at=now() WHERE id=$2::uuid AND run_id=$1::uuid RETURNING *`,[req.params.runId,req.params.resultId,status,actor(req),req.body?.note||null,req.body?.evidence||null]);if(!rows[0])return res.status(404).json({message:"A teszteredmény nem található."});res.json(rows[0])}catch(err){next(err)}});
router.post("/runs/:id/complete",async(req:AuthRequest,res,next)=>{try{const stats=await db.query(`SELECT COUNT(*) FILTER(WHERE status IN ('failed','blocked'))::int blockers,COUNT(*) FILTER(WHERE status='not_tested')::int pending FROM uat_test_results WHERE run_id=$1::uuid`,[req.params.id]);if(Number(stats.rows[0]?.blockers)>0&&!req.body?.force)return res.status(409).json({message:"A futásban hibás vagy blokkolt tesztek vannak.",...stats.rows[0]});if(Number(stats.rows[0]?.pending)>0&&!req.body?.force)return res.status(409).json({message:"Még vannak nem tesztelt esetek.",...stats.rows[0]});const{rows}=await db.query(`UPDATE uat_test_runs SET status='completed',completed_at=now(),note=COALESCE($2,note) WHERE id=$1::uuid RETURNING *`,[req.params.id,req.body?.note||null]);res.json(rows[0])}catch(err){next(err)}});
router.get("/readiness",async(_req,res,next)=>{try{const last=await db.query(`SELECT r.*,COUNT(x.id)::int total,COUNT(*) FILTER(WHERE x.status='passed')::int passed,COUNT(*) FILTER(WHERE x.status='failed')::int failed,COUNT(*) FILTER(WHERE x.status='blocked')::int blocked,COUNT(*) FILTER(WHERE x.status='not_tested')::int not_tested,COUNT(*) FILTER(WHERE c.critical AND x.status<>'passed')::int critical_not_passed FROM uat_test_runs r LEFT JOIN uat_test_results x ON x.run_id=r.id LEFT JOIN uat_test_cases c ON c.id=x.test_case_id GROUP BY r.id ORDER BY r.started_at DESC LIMIT 1`);const x=last.rows[0];if(!x)return res.json({status:'not_started',message:'Még nem indult UAT futás.'});const ready=Number(x.failed||0)===0&&Number(x.blocked||0)===0&&Number(x.critical_not_passed||0)===0&&Number(x.not_tested||0)===0;res.json({status:ready?'ready':'not_ready',run:x})}catch(err){next(err)}});
export default router;
