import {Router,Response} from 'express';
import pool from '../db';
import type {AuthRequest} from '../middleware/auth';
import {requireManagement} from '../middleware/requireRoles';
const r=Router();r.use(requireManagement);const n=(v:unknown)=>String(v||'').trim();
async function tenant(req:AuthRequest,res:Response){const t=n(req.user?.tenant_id);if(!t){res.status(403).json({ok:false,error:'tenant_missing'});return null}return t}
r.get('/status',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;const q=(await pool.query(`SELECT COUNT(*) FILTER(WHERE start_time>=date_trunc('day',now()) AND start_time<date_trunc('day',now())+interval '1 day' AND status NOT IN ('cancelled','no_show'))::int appointments_today,COUNT(DISTINCT employee_id) FILTER(WHERE start_time>=date_trunc('day',now()) AND start_time<date_trunc('day',now())+interval '1 day' AND status NOT IN ('cancelled','no_show'))::int booked_staff_today FROM appointments WHERE tenant_id=$1::uuid`,[t])).rows[0];res.json({ok:true,layer:'operations_workforce_autopilot_v4',automatic_shift_write:false,automatic_roster_change:false,capabilities:{workforce_pressure:true,capacity_gap_detection:true,shift_plan_preview:true,service_bottlenecks:true},counts:q})});
r.get('/workforce-pressure',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;const rows=(await pool.query(`SELECT e.id::text employee_id,e.full_name,COUNT(DISTINCT a.id)::int appointments,COALESCE(SUM(COALESCE(s.duration_minutes,30)),0)::int booked_minutes FROM employees e LEFT JOIN appointments a ON a.employee_id=e.id AND a.tenant_id=$1::uuid AND a.start_time>=date_trunc('day',now()) AND a.start_time<date_trunc('day',now())+interval '7 days' AND a.status NOT IN ('cancelled','no_show') LEFT JOIN appointment_services aps ON aps.appointment_id=a.id LEFT JOIN services s ON s.id=aps.service_id WHERE COALESCE(e.active,true)=true GROUP BY e.id,e.full_name HAVING COUNT(a.id)>0 ORDER BY booked_minutes DESC LIMIT 250`,[t])).rows.map((x:any)=>({...x,pressure:Number(x.booked_minutes)>=1800?'HIGH':Number(x.booked_minutes)>=1200?'MEDIUM':'NORMAL'}));res.json({ok:true,model:'workforce_pressure_v4',window_days:7,items:rows})});
r.get('/capacity-gaps',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;const rows=(await pool.query(`SELECT date_trunc('day',start_time)::date day,COUNT(*)::int bookings,COUNT(DISTINCT employee_id)::int booked_staff,COUNT(*) FILTER(WHERE status='cancelled')::int cancellations,COUNT(*) FILTER(WHERE status='no_show')::int no_shows FROM appointments WHERE tenant_id=$1::uuid AND start_time>=date_trunc('day',now()) AND start_time<date_trunc('day',now())+interval '14 days' GROUP BY 1 ORDER BY 1`,[t])).rows.map((x:any)=>({...x,capacity_signal:Number(x.bookings)>=40?'PRESSURE':Number(x.bookings)<=8?'UNDERUSED':'BALANCED'}));res.json({ok:true,model:'capacity_gap_detection_v4',items:rows,automatic_reallocation:false})});
r.get('/service-bottlenecks',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;const rows=(await pool.query(`SELECT s.id::text service_id,s.name,COUNT(*)::int bookings_30d,COALESCE(AVG(COALESCE(s.duration_minutes,30)),30)::numeric avg_duration_minutes,COUNT(DISTINCT a.employee_id)::int providers FROM appointment_services aps JOIN appointments a ON a.id=aps.appointment_id JOIN services s ON s.id=aps.service_id WHERE a.tenant_id=$1::uuid AND a.start_time>now()-interval '30 days' AND a.status NOT IN ('cancelled','no_show') GROUP BY s.id,s.name ORDER BY bookings_30d DESC LIMIT 100`,[t])).rows.map((x:any)=>({...x,bottleneck_risk:Number(x.bookings_30d)>=30&&Number(x.providers)<=2?'HIGH':Number(x.bookings_30d)>=20&&Number(x.providers)<=3?'MEDIUM':'NORMAL'}));res.json({ok:true,model:'service_bottleneck_v4',items:rows})});
r.post('/shift-plan/preview',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;const days=Math.min(30,Math.max(1,Number(req.body?.days)||7));const rows=(await pool.query(`SELECT date_trunc('day',start_time)::date day,COUNT(*) FILTER(WHERE status NOT IN ('cancelled','no_show'))::int demand,COUNT(DISTINCT employee_id) FILTER(WHERE status NOT IN ('cancelled','no_show'))::int booked_staff FROM appointments WHERE tenant_id=$1::uuid AND start_time>=date_trunc('day',now()) AND start_time<date_trunc('day',now())+($2::int||' days')::interval GROUP BY 1 ORDER BY 1`,[t,days])).rows.map((x:any)=>({...x,suggested_extra_staff:Math.max(0,Math.ceil(Number(x.demand)/8)-Number(x.booked_staff))}));res.json({ok:true,model:'shift_plan_preview_v4',days,preview:rows,write_enabled:false,automatic_roster_change:false,approval_required:true})});
export default r;
