import { Router, Response } from "express";
import pool from "../db";
import type { AuthRequest } from "../middleware/auth";
import { requireManagement } from "../middleware/requireRoles";

const router = Router();
router.use(requireManagement);
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
type Scope={tenantId:string;locationId:string|null};
async function scope(req:AuthRequest,res:Response):Promise<Scope|undefined>{const tenantId=String(req.user?.tenant_id||"").trim();if(!tenantId){res.status(403).json({ok:false,error:"A felhasználóhoz nincs tenant rendelve."});return}const requested=String(req.query.locationId||req.body?.locationId||"").trim();if(!requested)return{tenantId,locationId:null};if(!UUID.test(requested)){res.status(400).json({ok:false,error:"Érvénytelen telephelyazonosító."});return}const owned=(await pool.query(`SELECT id FROM locations WHERE id=$1::uuid AND tenant_id=$2::uuid`,[requested,tenantId])).rows[0];if(!owned){res.status(403).json({ok:false,error:"A telephely nem tartozik a tenantjához."});return}return{tenantId,locationId:requested}}
async function ensureSchema(){await pool.query(`
CREATE TABLE IF NOT EXISTS vir_client_channel_identities(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,client_id uuid,channel text NOT NULL,external_id text NOT NULL,display_name text,verified boolean NOT NULL DEFAULT false,transactional_consent boolean NOT NULL DEFAULT false,marketing_consent boolean NOT NULL DEFAULT false,last_activity_at timestamptz,metadata jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,channel,external_id));
ALTER TABLE vir_client_channel_identities ADD COLUMN IF NOT EXISTS active boolean NOT NULL DEFAULT true;
CREATE TABLE IF NOT EXISTS vir_conversations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,location_id uuid,client_id uuid,channel text NOT NULL,external_thread_id text,status text NOT NULL DEFAULT 'open',assigned_user_id uuid,last_message_at timestamptz,ai_handoff_required boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS vir_conversation_messages(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,conversation_id uuid NOT NULL,direction text NOT NULL,provider_message_id text,body text NOT NULL DEFAULT '',sent_at timestamptz NOT NULL DEFAULT now(),delivery_status text NOT NULL DEFAULT 'received',attribution_touch_id uuid,metadata jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS vir_ai_handoffs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,location_id uuid,client_id uuid,conversation_id uuid,reason text NOT NULL,summary text NOT NULL,status text NOT NULL DEFAULT 'open',created_by uuid,created_at timestamptz NOT NULL DEFAULT now(),closed_at timestamptz);
CREATE TABLE IF NOT EXISTS vir_ai_reception_sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,location_id uuid,client_id uuid,conversation_id uuid,intent text,status text NOT NULL DEFAULT 'preview',request_text text NOT NULL,structured_request jsonb NOT NULL DEFAULT '{}'::jsonb,booking_preview jsonb NOT NULL DEFAULT '{}'::jsonb,human_approval_required boolean NOT NULL DEFAULT true,created_by uuid,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS vir_ai_reception_scope_idx ON vir_ai_reception_sessions(tenant_id,created_at DESC);
CREATE TABLE IF NOT EXISTS vir_complaint_cases(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,location_id uuid,client_id uuid,conversation_id uuid,work_order_id uuid,category text NOT NULL DEFAULT 'OTHER',severity text NOT NULL DEFAULT 'normal',summary text NOT NULL,evidence jsonb NOT NULL DEFAULT '{}'::jsonb,recommended_resolution jsonb NOT NULL DEFAULT '{}'::jsonb,status text NOT NULL DEFAULT 'open',compensation_approval_required boolean NOT NULL DEFAULT true,created_by uuid,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS vir_complaint_scope_idx ON vir_complaint_cases(tenant_id,status,created_at DESC);
`)}
const normalize=(v:unknown)=>String(v||'').trim();
function inferIntent(text:string){const t=text.toLowerCase();if(/panasz|reklam|rossz|elégedetlen|vissza/.test(t))return'COMPLAINT';if(/lemond|töröl/.test(t))return'CANCEL';if(/módos|átrak|másik idő/.test(t))return'RESCHEDULE';if(/foglal|időpont|szeretnék/.test(t))return'BOOK';return'GENERAL';}
async function servicesForScope(locationId:string|null){if(locationId)return(await pool.query(`SELECT s.id::text,s.name,COALESCE(s.duration_minutes,30)::int duration_minutes,COALESCE(s.promo_price,s.list_price,s.base_price,0)::numeric price FROM services s WHERE COALESCE(s.is_active,true)=true AND (NOT EXISTS(SELECT 1 FROM service_locations sl WHERE sl.service_id=s.id) OR EXISTS(SELECT 1 FROM service_locations sl WHERE sl.service_id=s.id AND sl.location_id=$1::uuid)) ORDER BY s.name LIMIT 400`,[locationId])).rows;return(await pool.query(`SELECT s.id::text,s.name,COALESCE(s.duration_minutes,30)::int duration_minutes,COALESCE(s.promo_price,s.list_price,s.base_price,0)::numeric price FROM services s WHERE COALESCE(s.is_active,true)=true ORDER BY s.name LIMIT 400`)).rows}

router.get('/status',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const counts=(await pool.query(`SELECT (SELECT count(*) FROM vir_ai_reception_sessions WHERE tenant_id=$1::uuid)::int sessions,(SELECT count(*) FROM vir_conversations WHERE tenant_id=$1::uuid AND status='open')::int open_conversations,(SELECT count(*) FROM vir_ai_handoffs WHERE tenant_id=$1::uuid AND status='open')::int open_handoffs,(SELECT count(*) FROM vir_complaint_cases WHERE tenant_id=$1::uuid AND status='open')::int open_complaints`,[s.tenantId])).rows[0];res.json({ok:true,layer:'ai_reception_customer_journey_v3',automatic_booking:false,automatic_compensation:false,human_approval_boundary:true,capabilities:{full_ai_receptionist:true,conversation_memory:true,complaint_assistant:true},counts})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'p11_status_failed'})}});

router.post('/receptionist/preview',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const text=normalize(req.body?.text);if(!text)return res.status(400).json({ok:false,error:'text szükséges.'});const clientId=normalize(req.body?.client_id)||null,conversationId=normalize(req.body?.conversation_id)||null;if((clientId&&!UUID.test(clientId))||(conversationId&&!UUID.test(conversationId)))return res.status(400).json({ok:false,error:'Érvénytelen azonosító.'});const intent=inferIntent(text);const services=await servicesForScope(s.locationId);const tokens=text.toLocaleLowerCase('hu-HU').split(/[^\p{L}\p{N}]+/u).filter((x:string)=>x.length>3);const matched=services.map((x:any)=>({...x,match_score:tokens.reduce((score:number,t:string)=>score+(String(x.name||'').toLocaleLowerCase('hu-HU').includes(t)?2:0),0)})).filter((x:any)=>x.match_score>0).sort((a:any,b:any)=>b.match_score-a.match_score).slice(0,8);const preview={intent,service_candidates:matched,location_id:s.locationId,requested_text:text,requires_guest_confirmation:true,write_enabled:false};const row=(await pool.query(`INSERT INTO vir_ai_reception_sessions(tenant_id,location_id,client_id,conversation_id,intent,request_text,structured_request,booking_preview,human_approval_required,created_by) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,true,$9) RETURNING id,created_at`,[s.tenantId,s.locationId,clientId,conversationId,intent,text,JSON.stringify({tokens}),JSON.stringify(preview),req.user?.id||null])).rows[0];res.status(201).json({ok:true,model:'ai_receptionist_v3_preview',session_id:row.id,automatic_booking:false,approval_required:true,preview})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'reception_preview_failed'})}});

router.get('/conversation-memory/:clientId',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const clientId=normalize(req.params.clientId);if(!UUID.test(clientId))return res.status(400).json({ok:false,error:'Érvénytelen clientId.'});const owns=(await pool.query(`SELECT 1 FROM appointments WHERE tenant_id=$1::uuid AND client_id=$2::uuid LIMIT 1`,[s.tenantId,clientId])).rowCount;if(!owns)return res.status(403).json({ok:false,error:'A vendég nem igazolt a tenantban.'});const client=(await pool.query(`SELECT id::text,full_name,email,phone FROM clients WHERE id=$1::uuid`,[clientId])).rows[0];const conversations=(await pool.query(`SELECT c.id::text,c.channel,c.status,c.last_message_at,(SELECT body FROM vir_conversation_messages m WHERE m.tenant_id=c.tenant_id AND m.conversation_id=c.id ORDER BY m.sent_at DESC LIMIT 1) last_message FROM vir_conversations c WHERE c.tenant_id=$1::uuid AND c.client_id=$2::uuid ORDER BY c.last_message_at DESC NULLS LAST LIMIT 20`,[s.tenantId,clientId])).rows;const visits=(await pool.query(`SELECT a.id::text,a.start_time,a.status,e.full_name employee_name,string_agg(DISTINCT sv.name,', ' ORDER BY sv.name) services FROM appointments a LEFT JOIN employees e ON e.id=a.employee_id LEFT JOIN appointment_services aps ON aps.appointment_id=a.id LEFT JOIN services sv ON sv.id=aps.service_id WHERE a.tenant_id=$1::uuid AND a.client_id=$2::uuid GROUP BY a.id,a.start_time,a.status,e.full_name ORDER BY a.start_time DESC LIMIT 20`,[s.tenantId,clientId])).rows;const identities=(await pool.query(`SELECT channel,verified,transactional_consent,marketing_consent,last_activity_at FROM vir_client_channel_identities WHERE tenant_id=$1::uuid AND client_id=$2::uuid AND active=true ORDER BY last_activity_at DESC NULLS LAST`,[s.tenantId,clientId])).rows;res.json({ok:true,model:'conversation_memory_v3',client,communication_identities:identities,recent_conversations:conversations,recent_visits:visits,memory_policy:{source:'first_party_operational_history',sensitive_inference:false,automatic_profile_mutation:false}})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'conversation_memory_failed'})}});

router.post('/complaints/analyze',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const summary=normalize(req.body?.summary),clientId=normalize(req.body?.client_id)||null,conversationId=normalize(req.body?.conversation_id)||null,workOrderId=normalize(req.body?.work_order_id)||null;if(!summary)return res.status(400).json({ok:false,error:'summary szükséges.'});for(const id of [clientId,conversationId,workOrderId])if(id&&!UUID.test(id))return res.status(400).json({ok:false,error:'Érvénytelen azonosító.'});const low=summary.toLowerCase();const category=/pénz|visszatér|refund|számla/.test(low)?'PAYMENT':/fáj|sérül|allerg|égés/.test(low)?'SERVICE_SAFETY':/kés|várako/.test(low)?'WAIT_TIME':'SERVICE_QUALITY';const severity=category==='SERVICE_SAFETY'?'high':/nagyon|azonnal|felhábor/.test(low)?'high':'normal';let evidence:any={};if(workOrderId){evidence=(await pool.query(`SELECT w.id::text,w.status,w.location_id,COALESCE(SUM(wp.amount),0)::numeric paid_amount FROM work_orders w LEFT JOIN work_order_payments wp ON wp.work_order_id=w.id WHERE w.id=$1::uuid AND w.tenant_id=$2::uuid GROUP BY w.id,w.status,w.location_id`,[workOrderId,s.tenantId])).rows[0]||{}}const recommended={action:severity==='high'?'IMMEDIATE_HUMAN_REVIEW':'HUMAN_REVIEW',refund_or_compensation:'NOT_AUTOMATIC',contact_client:true,collect_evidence:true};const row=(await pool.query(`INSERT INTO vir_complaint_cases(tenant_id,location_id,client_id,conversation_id,work_order_id,category,severity,summary,evidence,recommended_resolution,compensation_approval_required,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10::jsonb,true,$11) RETURNING *`,[s.tenantId,s.locationId,clientId,conversationId,workOrderId,category,severity,summary,JSON.stringify(evidence),JSON.stringify(recommended),req.user?.id||null])).rows[0];await pool.query(`INSERT INTO vir_ai_handoffs(tenant_id,location_id,client_id,conversation_id,reason,summary,created_by) VALUES($1,$2,$3,$4,'COMPLAINT_REVIEW',$5,$6)`,[s.tenantId,s.locationId,clientId,conversationId,summary,req.user?.id||null]);res.status(201).json({ok:true,model:'ai_complaint_assistant_v3',automatic_refund:false,automatic_compensation:false,human_review_required:true,item:row})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'complaint_analysis_failed'})}});

router.get('/complaints',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const rows=(await pool.query(`SELECT cc.*,COALESCE(c.full_name,'Ismeretlen vendég') client_name FROM vir_complaint_cases cc LEFT JOIN clients c ON c.id=cc.client_id WHERE cc.tenant_id=$1::uuid AND ($2::uuid IS NULL OR cc.location_id=$2::uuid) ORDER BY cc.created_at DESC LIMIT 250`,[s.tenantId,s.locationId])).rows;res.json({ok:true,items:rows})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'complaints_failed'})}});

export default router;
