import { Router, Response } from "express";
import pool from "../db";
import type { AuthRequest } from "../middleware/auth";
import { requireManagement } from "../middleware/requireRoles";
import { locationBelongsToTenant } from "../saas/tenantAccess";

const router=Router();
router.use(requireManagement);
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

function tenantId(req:AuthRequest,res:Response):string|undefined{const value=String(req.user?.tenant_id??"").trim();if(!/^\d+$/.test(value)||Number(value)<=0){res.status(403).json({ok:false,error:"tenant_context_required"});return;}return value;}
function actorId(req:AuthRequest):string{return String(req.user?.id??req.user?.employee_id??"system");}
async function validateLocation(value:unknown,tenant:string,res:Response):Promise<string|null|undefined>{const id=String(value??"").trim();if(!id)return null;if(!UUID.test(id)){res.status(400).json({ok:false,error:"invalid_location_id"});return;}if(!(await locationBelongsToTenant(id,tenant))){res.status(403).json({ok:false,error:"tenant_location_mismatch"});return;}return id;}
function horizon(value:unknown):7|30|90{const n=Number(value);return n===30?30:n===90?90:7;}
function clamp(n:number,min:number,max:number){return Math.max(min,Math.min(max,n));}
function average(values:number[]):number{return values.length?values.reduce((a,b)=>a+b,0)/values.length:0;}
async function safeRows(sql:string,args:any[]=[]):Promise<any[]>{try{return (await pool.query(sql,args)).rows;}catch{return [];}}

async function buildForecast(tenant:string,location:string|null,days:7|30|90){
  const series=await safeRows(`SELECT date_trunc('day',a.start_time)::date day,COUNT(DISTINCT a.id)::int bookings,COALESCE(SUM(COALESCE(aps.price,0)),0)::numeric revenue FROM appointments a LEFT JOIN appointment_services aps ON aps.appointment_id=a.id WHERE a.tenant_id::text=$1 AND ($2::uuid IS NULL OR a.location_id=$2::uuid) AND a.start_time>=now()-interval '90 days' AND a.start_time<now() AND a.status NOT IN ('cancelled','no_show') GROUP BY 1 ORDER BY 1`,[tenant,location]);
  const recent=series.slice(-14),previous=series.slice(-28,-14);const recentRevenue=recent.map(x=>Number(x.revenue||0)),previousRevenue=previous.map(x=>Number(x.revenue||0)),recentBookings=recent.map(x=>Number(x.bookings||0)),previousBookings=previous.map(x=>Number(x.bookings||0));
  const baseRevenue=average(recentRevenue),prevRevenue=average(previousRevenue),baseBookings=average(recentBookings),prevBookings=average(previousBookings);
  const revenueTrend=prevRevenue>0?clamp((baseRevenue-prevRevenue)/prevRevenue,-0.35,0.35):0;const bookingTrend=prevBookings>0?clamp((baseBookings-prevBookings)/prevBookings,-0.35,0.35):0;
  const trendWeight=days===7?0.75:days===30?0.45:0.25;
  const revenueForecast=Math.max(0,baseRevenue*days*(1+revenueTrend*trendWeight));const bookingForecast=Math.max(0,Math.round(baseBookings*days*(1+bookingTrend*trendWeight)));
  const risk=(await safeRows(`SELECT COUNT(*) FILTER(WHERE status='no_show')::int no_shows,COUNT(*)::int total FROM appointments WHERE tenant_id::text=$1 AND ($2::uuid IS NULL OR location_id=$2::uuid) AND start_time>=now()-interval '30 days' AND start_time<now()`,[tenant,location]))[0]||{no_shows:0,total:0};
  const capacity=(await safeRows(`SELECT COUNT(*) FILTER(WHERE start_time>=now() AND start_time<now()+interval '7 days' AND status NOT IN ('cancelled','no_show'))::int future_bookings_7d,COUNT(DISTINCT employee_id) FILTER(WHERE start_time>=now() AND start_time<now()+interval '7 days' AND status NOT IN ('cancelled','no_show'))::int booked_staff_7d FROM appointments WHERE tenant_id::text=$1 AND ($2::uuid IS NULL OR location_id=$2::uuid)`,[tenant,location]))[0]||{future_bookings_7d:0,booked_staff_7d:0};
  const noShowRisk=Number(risk.total||0)>0?Number(risk.no_shows||0)/Number(risk.total)*100:0;const staff=Math.max(1,Number(capacity.booked_staff_7d||0)),load=Number(capacity.future_bookings_7d||0)/(staff*8);const capacityPressure=load>=1.6?"critical":load>=1.2?"high":load<0.45?"low":"normal";
  const confidence=clamp(0.45+Math.min(series.length,60)/120+(recent.length>=10?0.08:0),0.45,0.9);
  return {model:"deterministic_trend_v1",horizon_days:days,confidence:Number(confidence.toFixed(4)),revenue_forecast:Number(revenueForecast.toFixed(2)),booking_forecast:bookingForecast,no_show_risk_percent:Number(noShowRisk.toFixed(3)),capacity_pressure:capacityPressure,drivers:{history_days:series.length,recent_daily_revenue:Number(baseRevenue.toFixed(2)),previous_daily_revenue:Number(prevRevenue.toFixed(2)),revenue_trend_percent:Number((revenueTrend*100).toFixed(2)),recent_daily_bookings:Number(baseBookings.toFixed(2)),booking_trend_percent:Number((bookingTrend*100).toFixed(2)),future_bookings_7d:Number(capacity.future_bookings_7d||0),booked_staff_7d:Number(capacity.booked_staff_7d||0)},limitations:["deterministic trend model","not a guarantee of future revenue","external execution disabled"]};
}

router.get("/status",async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;try{const counts=(await pool.query(`SELECT COUNT(*)::int snapshots,MAX(created_at) last_snapshot_at FROM vir_p19_forecast_snapshots WHERE tenant_id=$1::bigint`,[tenant])).rows[0];return res.json({ok:true,model:"predictive_executive_intelligence_v1",supported_horizons:[7,30,90],automatic_execution:false,counts});}catch(error:any){return res.status(500).json({ok:false,error:error?.message||"p19_status_failed"});}});

router.get("/forecast",async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;const location=await validateLocation(req.query.locationId,tenant,res);if(location===undefined)return;try{return res.json({ok:true,forecast:await buildForecast(tenant,location,horizon(req.query.days))});}catch(error:any){return res.status(500).json({ok:false,error:error?.message||"p19_forecast_failed"});}});

router.post("/snapshot",async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;const location=await validateLocation(req.body?.locationId,tenant,res);if(location===undefined)return;try{const days=horizon(req.body?.days),forecast=await buildForecast(tenant,location,days);const row=(await pool.query(`INSERT INTO vir_p19_forecast_snapshots(tenant_id,location_id,horizon_days,model_key,confidence,revenue_forecast,booking_forecast,no_show_risk_percent,capacity_pressure,inputs,forecast,created_by) VALUES($1::bigint,$2::uuid,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11::jsonb,$12) RETURNING *`,[tenant,location,days,forecast.model,forecast.confidence,forecast.revenue_forecast,forecast.booking_forecast,forecast.no_show_risk_percent,forecast.capacity_pressure,JSON.stringify(forecast.drivers),JSON.stringify(forecast),actorId(req)])).rows[0];return res.status(201).json({ok:true,item:row,forecast});}catch(error:any){return res.status(500).json({ok:false,error:error?.message||"p19_snapshot_failed"});}});

router.get("/snapshots",async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;try{const rows=(await pool.query(`SELECT * FROM vir_p19_forecast_snapshots WHERE tenant_id=$1::bigint ORDER BY created_at DESC LIMIT 100`,[tenant])).rows;return res.json({ok:true,items:rows});}catch(error:any){return res.status(500).json({ok:false,error:error?.message||"p19_snapshots_failed"});}});

router.get("/executive-brief",async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;const location=await validateLocation(req.query.locationId,tenant,res);if(location===undefined)return;try{const [f7,f30,p17,p18]=await Promise.all([buildForecast(tenant,location,7),buildForecast(tenant,location,30),safeRows(`SELECT COUNT(*) FILTER(WHERE status='pending_approval')::int pending_approval,COUNT(*) FILTER(WHERE status='executed')::int executed_unverified FROM vir_p17_operations WHERE tenant_id=$1::bigint`,[tenant]),safeRows(`SELECT COUNT(*) FILTER(WHERE status='proposed')::int proposed,COUNT(*) FILTER(WHERE status='promoted')::int promoted FROM vir_p18_proposals WHERE tenant_id=$1::bigint`,[tenant])]);const a=p17[0]||{},b=p18[0]||{};const alerts:any[]=[];if(f7.capacity_pressure==="critical"||f7.capacity_pressure==="high")alerts.push({priority:"high",title:"Kapacitásnyomás várható",reason:`7 napos terhelési szint: ${f7.capacity_pressure}.`});if(f7.no_show_risk_percent>=8)alerts.push({priority:"high",title:"Emelkedett no-show kockázat",reason:`30 napos no-show arány: ${f7.no_show_risk_percent}%.`});if(Number(a.pending_approval||0)>=5)alerts.push({priority:"medium",title:"P17 jóváhagyási torlódás",reason:`${a.pending_approval} művelet vár jóváhagyásra.`});return res.json({ok:true,model:"predictive_executive_brief_v1",generated_at:new Date().toISOString(),headline:alerts.length?`${alerts.length} előrejelzett vezetői figyelmeztetés igényel figyelmet.`:"Nincs kiemelt prediktív riasztás.",forecast_7d:f7,forecast_30d:f30,governance:{p17_pending_approval:Number(a.pending_approval||0),p17_executed_unverified:Number(a.executed_unverified||0),p18_proposed:Number(b.proposed||0),p18_promoted:Number(b.promoted||0),automatic_execution:false},alerts});}catch(error:any){return res.status(500).json({ok:false,error:error?.message||"p19_brief_failed"});}});

export default router;
