import {Router,Response} from 'express';
import pool from '../db';
import type {AuthRequest} from '../middleware/auth';
import {requireManagement} from '../middleware/requireRoles';
const r=Router();r.use(requireManagement);
const n=(v:unknown)=>String(v??'').trim();
async function tenant(req:AuthRequest,res:Response){const t=n(req.user?.tenant_id);if(!t){res.status(403).json({ok:false,error:'tenant_missing'});return null}return t}
async function ensureSchema(){await pool.query(`CREATE TABLE IF NOT EXISTS vir_p16_decisions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,location_id uuid,decision_key text NOT NULL,title text NOT NULL,area text NOT NULL,priority text NOT NULL,reason text NOT NULL,evidence jsonb NOT NULL DEFAULT '{}'::jsonb,recommended_action jsonb NOT NULL DEFAULT '{}'::jsonb,status text NOT NULL DEFAULT 'open',created_by uuid,decided_by uuid,created_at timestamptz NOT NULL DEFAULT now(),decided_at timestamptz,UNIQUE(tenant_id,decision_key,status));CREATE INDEX IF NOT EXISTS vir_p16_decisions_scope_idx ON vir_p16_decisions(tenant_id,status,priority,created_at DESC);`)}
async function signals(t:string){const [revenue,journey,ops,actions]=await Promise.all([
 pool.query(`SELECT COUNT(*) FILTER(WHERE status='no_show' AND start_time>now()-interval '30 days')::int no_shows_30d,COUNT(*) FILTER(WHERE status='cancelled' AND start_time>now()-interval '30 days')::int cancellations_30d,COUNT(*) FILTER(WHERE start_time>now() AND start_time<now()+interval '7 days' AND status NOT IN ('cancelled','no_show'))::int future_bookings_7d FROM appointments WHERE tenant_id=$1::uuid`,[t]),
 pool.query(`SELECT (SELECT count(*) FROM vir_ai_handoffs WHERE tenant_id=$1::uuid AND status='open')::int open_handoffs,(SELECT count(*) FROM vir_complaint_cases WHERE tenant_id=$1::uuid AND status='open')::int open_complaints`,[t]),
 pool.query(`SELECT COUNT(*) FILTER(WHERE start_time>=date_trunc('day',now()) AND start_time<date_trunc('day',now())+interval '7 days' AND status NOT IN ('cancelled','no_show'))::int bookings_7d,COUNT(DISTINCT employee_id) FILTER(WHERE start_time>=date_trunc('day',now()) AND start_time<date_trunc('day',now())+interval '7 days' AND status NOT IN ('cancelled','no_show'))::int booked_staff_7d FROM appointments WHERE tenant_id=$1::uuid`,[t]),
 pool.query(`SELECT COUNT(*) FILTER(WHERE status='OPEN')::int open_actions,COUNT(*) FILTER(WHERE status='WAITING_APPROVAL')::int approvals,COUNT(*) FILTER(WHERE priority='CRITICAL' AND status NOT IN ('DONE'))::int critical_actions FROM vir_management_actions WHERE tenant_id=$1::uuid`,[t]).catch(()=>({rows:[{open_actions:0,approvals:0,critical_actions:0}]} as any))
 ]);return {revenue:revenue.rows[0],journey:journey.rows[0],operations:ops.rows[0],actions:actions.rows[0]}}
function decisionsFrom(s:any){const out:any[]=[];if(Number(s.journey.open_complaints)>0)out.push({key:'open_complaints',title:'Nyitott vendégpanaszok kezelése',area:'CUSTOMER',priority:'CRITICAL',reason:`${s.journey.open_complaints} nyitott panasz vár vezetői döntésre.`,action:{type:'SERVICE_RECOVERY_REVIEW'}});if(Number(s.revenue.no_shows_30d)>=5)out.push({key:'no_show_pressure',title:'No-show bevételvédelem',area:'REVENUE',priority:'HIGH',reason:`${s.revenue.no_shows_30d} no-show történt 30 nap alatt.`,action:{type:'REVIEW_DEPOSIT_POLICY'}});if(Number(s.operations.bookings_7d)>Math.max(1,Number(s.operations.booked_staff_7d))*8)out.push({key:'capacity_pressure',title:'Kapacitáshiány várható',area:'OPERATIONS',priority:'HIGH',reason:`${s.operations.bookings_7d} foglalás / ${s.operations.booked_staff_7d} foglalt munkatárs a következő 7 napra.`,action:{type:'OPEN_P14_SHIFT_PREVIEW'}});if(Number(s.actions.approvals)>0)out.push({key:'approval_backlog',title:'Jóváhagyási torlódás',area:'GOVERNANCE',priority:'MEDIUM',reason:`${s.actions.approvals} akció vár jóváhagyásra.`,action:{type:'OPEN_ACTION_CENTER'}});return out}
r.get('/status',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;await ensureSchema();const counts=(await pool.query(`SELECT COUNT(*) FILTER(WHERE status='open')::int open,COUNT(*) FILTER(WHERE status='accepted')::int accepted,COUNT(*) FILTER(WHERE status='dismissed')::int dismissed FROM vir_p16_decisions WHERE tenant_id=$1::uuid`,[t])).rows[0];res.json({ok:true,layer:'executive_intelligence_v2',exception_driven:true,automatic_execution:false,human_decision_required:true,counts})});
r.get('/exception-brief',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;const s=await signals(t);const decisions=decisionsFrom(s);res.json({ok:true,model:'exception_brief_v2',summary:{decision_count:decisions.length,critical:decisions.filter(x=>x.priority==='CRITICAL').length,high:decisions.filter(x=>x.priority==='HIGH').length},signals:s,decisions,automatic_execution:false})});
r.post('/decision-inbox/sync',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;await ensureSchema();const s=await signals(t);const items=decisionsFrom(s);let created=0;for(const d of items){const q=await pool.query(`INSERT INTO vir_p16_decisions(tenant_id,decision_key,title,area,priority,reason,evidence,recommended_action,created_by) VALUES($1::uuid,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9) ON CONFLICT(tenant_id,decision_key,status) DO NOTHING`,[t,d.key,d.title,d.area,d.priority,d.reason,JSON.stringify(s),JSON.stringify(d.action),req.user?.id||null]);created+=q.rowCount||0}res.json({ok:true,created,automatic_execution:false})});
r.get('/decision-inbox',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;await ensureSchema();const rows=(await pool.query(`SELECT * FROM vir_p16_decisions WHERE tenant_id=$1::uuid ORDER BY CASE priority WHEN 'CRITICAL' THEN 1 WHEN 'HIGH' THEN 2 WHEN 'MEDIUM' THEN 3 ELSE 4 END,created_at DESC LIMIT 250`,[t])).rows;res.json({ok:true,items:rows})});
r.post('/decision-inbox/:id/decide',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;await ensureSchema();const status=n(req.body?.status).toLowerCase();if(!['accepted','dismissed'].includes(status))return res.status(400).json({ok:false,error:'status must be accepted or dismissed'});const row=(await pool.query(`UPDATE vir_p16_decisions SET status=$3,decided_by=$4,decided_at=now() WHERE id=$1::uuid AND tenant_id=$2::uuid AND status='open' RETURNING *`,[req.params.id,t,status,req.user?.id||null])).rows[0];if(!row)return res.status(404).json({ok:false,error:'decision_not_found_or_closed'});res.json({ok:true,item:row,execution_enabled:false,note:'A vezetői döntés rögzítése nem hajt végre automatikus üzleti műveletet.'})});
r.get('/morning-brief',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;const s=await signals(t);const d=decisionsFrom(s);res.json({ok:true,model:'executive_morning_brief_v2',generated_at:new Date().toISOString(),headline:d.length?`Ma ${d.length} vezetői döntés igényel figyelmet.`:'Nincs kiemelt vezetői kivétel.',top_decisions:d.slice(0,5),signals:s,automatic_execution:false})});
export default r;
