import {Router,Response} from 'express';
import pool from '../db';
import type {AuthRequest} from '../middleware/auth';
import {requireManagement} from '../middleware/requireRoles';
import {actorId,clamp,tenantId,UUID,validateLocation} from './virP20P22Shared';
import {buildDigitalTwin,candidateScore,insertP17FromOptimization,normalizedWeights,simulateScenario} from './virP23P25Shared';

const router=Router();router.use(requireManagement);
function constraints(v:any){const x=v&&typeof v==='object'?v:{};return{max_price_change_percent:clamp(Number(x.max_price_change_percent??10),0,20),max_discount_percent:clamp(Number(x.max_discount_percent??15),0,25),max_staff_change_percent:clamp(Number(x.max_staff_change_percent??20),0,25),min_margin_percent:clamp(Number(x.min_margin_percent??20),0,70)};}
router.get('/status',async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;try{const counts=(await pool.query(`SELECT COUNT(*)::int runs,COUNT(*) FILTER(WHERE status='recommended')::int recommended,COUNT(*) FILTER(WHERE status='promoted')::int promoted,MAX(created_at) last_run_at FROM vir_p25_optimization_runs WHERE tenant_id=$1::bigint`,[tenant])).rows[0];return res.json({ok:true,model:'multi_objective_business_optimizer_v1',approval_layer:'P17',direct_execution:false,counts});}catch(e:any){return res.status(500).json({ok:false,error:e?.message||'p25_status_failed'});}});
router.post('/optimize',async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;const location=await validateLocation(req.body?.locationId,tenant,res);if(location===undefined)return;try{const weights=normalizedWeights(req.body?.objective_weights),limits=constraints(req.body?.constraints),twin=await buildDigitalTwin(tenant,location);const price=[-5,0,5,10,15].filter(n=>Math.abs(n)<=limits.max_price_change_percent),staff=[-10,0,10,20].filter(n=>Math.abs(n)<=limits.max_staff_change_percent),discount=[0,5,10,15,20].filter(n=>n<=limits.max_discount_percent),noShow=[0,10,20,30],stock=[0,10],candidates:any[]=[];for(const p of price)for(const s of staff)for(const d of discount)for(const n of noShow)for(const st of stock){const sim=simulateScenario(twin,{price_delta_percent:p,staff_hours_delta_percent:s,promotion_discount_percent:d,no_show_reduction_percent:n,stock_availability_delta_percent:st,demand_delta_percent:0});if(sim.result.margin_percent<limits.min_margin_percent)continue;const score=candidateScore(sim,weights,twin);candidates.push({score,levers:sim.levers,result:sim.result,delta:sim.delta,confidence:sim.confidence});}candidates.sort((a,b)=>b.score-a.score||b.result.profit-a.result.profit);if(!candidates.length)return res.status(422).json({ok:false,error:'no_feasible_candidate',constraints:limits});const champion=candidates[0],alternatives=candidates.slice(1,6),row=(await pool.query(`INSERT INTO vir_p25_optimization_runs(tenant_id,location_id,objective_weights,constraints,candidate_count,champion,alternatives,score,status,created_by) VALUES($1::bigint,$2::uuid,$3::jsonb,$4::jsonb,$5,$6::jsonb,$7::jsonb,$8,'recommended',$9) RETURNING *`,[tenant,location,JSON.stringify(weights),JSON.stringify(limits),candidates.length,JSON.stringify(champion),JSON.stringify(alternatives),champion.score,actorId(req)])).rows[0];return res.status(201).json({ok:true,item:row,optimizer:{model:'multi_objective_business_optimizer_v1',weights,constraints:limits,candidate_count:candidates.length,champion,alternatives,governance:{direct_execution:false,approval_required:true,approval_layer:'P17'}}});}catch(e:any){return res.status(500).json({ok:false,error:e?.message||'p25_optimize_failed'});}});
router.get('/runs',async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;try{return res.json({ok:true,items:(await pool.query(`SELECT * FROM vir_p25_optimization_runs WHERE tenant_id=$1::bigint ORDER BY created_at DESC LIMIT 100`,[tenant])).rows});}catch(e:any){return res.status(500).json({ok:false,error:e?.message||'p25_runs_failed'});}});
router.post('/runs/:id/promote',async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;const id=String(req.params.id||'');if(!UUID.test(id))return res.status(400).json({ok:false,error:'invalid_optimizer_run_id'});try{const run=(await pool.query(`SELECT * FROM vir_p25_optimization_runs WHERE id=$1::uuid AND tenant_id=$2::bigint`,[id,tenant])).rows[0];if(!run)return res.status(404).json({ok:false,error:'optimizer_run_not_found'});if(run.status==='dismissed')return res.status(409).json({ok:false,error:'optimizer_run_dismissed'});const operationId=await insertP17FromOptimization(tenant,run.location_id?String(run.location_id):null,run,actorId(req));return res.json({ok:true,optimizer_run_id:id,promoted_operation_id:operationId,status:'promoted',direct_execution:false,approval_required:true});}catch(e:any){return res.status(500).json({ok:false,error:e?.message||'p25_promote_failed'});}});
router.post('/runs/:id/dismiss',async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;const id=String(req.params.id||'');if(!UUID.test(id))return res.status(400).json({ok:false,error:'invalid_optimizer_run_id'});try{const item=(await pool.query(`UPDATE vir_p25_optimization_runs SET status='dismissed',updated_at=now() WHERE id=$1::uuid AND tenant_id=$2::bigint AND status='recommended' RETURNING *`,[id,tenant])).rows[0];if(!item)return res.status(404).json({ok:false,error:'optimizer_run_not_found_or_not_recommended'});return res.json({ok:true,item});}catch(e:any){return res.status(500).json({ok:false,error:e?.message||'p25_dismiss_failed'});}});
export default router;