import { Router, Response } from "express";
import pool from "../db";
import type { AuthRequest } from "../middleware/auth";
import { requireManagement } from "../middleware/requireRoles";
import { buildP20Forecast } from "./virP20";
import { UUID,actorId,clamp,readKpis,safeRows,tenantId,validateLocation } from "./virP20P22Shared";

const router=Router();
router.use(requireManagement);

type Candidate={operation_type:string;title:string;rationale:string;baseScore:number;expected:Record<string,unknown>;evidence:Record<string,unknown>;alternatives:string[];risks:string[]};
function priority(score:number){return score>=90?"critical":score>=72?"high":score>=50?"medium":"low";}
async function learnedAdjustment(tenant:string,operationType:string){
  const row=(await safeRows(`SELECT COUNT(*)::int samples,COALESCE(AVG(optimization_score),0)::numeric avg_score,COUNT(*) FILTER(WHERE outcome_class='positive')::int positive FROM vir_p22_cycles WHERE tenant_id=$1::bigint AND operation_type=$2 AND status='evaluated'`,[tenant,operationType]))[0]||{};
  const samples=Number(row.samples||0),avg=Number(row.avg_score||0),positive=Number(row.positive||0),adjustment=samples?clamp(avg*0.25,-15,15):0;
  return {samples,avg_score:Number(avg.toFixed(3)),positive_rate:samples?Number((positive/samples).toFixed(4)):0.5,adjustment:Number(adjustment.toFixed(3))};
}
async function generateCandidates(tenant:string,location:string|null):Promise<Candidate[]>{
  const [f7,f30,kpis,capacityRows]=await Promise.all([buildP20Forecast(tenant,location,7),buildP20Forecast(tenant,location,30),readKpis(tenant,location,30),safeRows(`SELECT COUNT(DISTINCT a.id)::int future_bookings_7d,COUNT(DISTINCT a.employee_id)::int booked_staff_7d FROM appointments a WHERE a.tenant_id::text=$1 AND ($2::uuid IS NULL OR a.location_id=$2::uuid) AND a.start_time>=now() AND a.start_time<now()+interval '7 days' AND a.status NOT IN ('cancelled','no_show')`,[tenant,location])]);
  const cap=capacityRows[0]||{},future=Number(cap.future_bookings_7d||0),staff=Math.max(1,Number(cap.booked_staff_7d||0)),load=future/(staff*8),rm=Number(f30.metrics?.revenue_momentum||1),bm=Number(f30.metrics?.booking_momentum||1),mape=Number(f30.metrics?.mape_percent||100),out:Candidate[]=[];
  if(load>=1.2||bm>=1.08)out.push({operation_type:"staffing_review",title:"Kapacitás és műszakbeosztás felülvizsgálata",rationale:`A 7 napos előjegyzett terhelés ${load.toFixed(2)} egység/fő, a foglalási momentum ${(bm*100-100).toFixed(1)}%.`,baseScore:load>=1.6?88:74,expected:{goal:"reduce_capacity_pressure",forecast_bookings_7d:f7.booking_forecast},evidence:{load,future_bookings_7d:future,booked_staff_7d:staff,booking_momentum:bm},alternatives:["idősávok újraosztása","önkéntes extra műszak","kereslet átterelése más telephelyre"],risks:["túlóra-költség","túlzott kapacitás, ha a kereslet nem realizálódik"]});
  if(rm<0.96)out.push({operation_type:"revenue_review",title:"Bevétel-visszaesési akcióterv",rationale:`A 30 napos modell bevételi momentuma ${(rm*100-100).toFixed(1)}%, ezért célzott bevételi beavatkozás indokolt.`,baseScore:rm<0.90?86:68,expected:{goal:"restore_revenue_momentum",forecast_revenue_30d:f30.revenue_forecast},evidence:{revenue_momentum:rm,revenue_forecast_30d:f30.revenue_forecast,confidence:f30.confidence},alternatives:["szolgáltatás-mix optimalizálás","üres idősávok célzott feltöltése","árengedmény nélküli upsell"],risks:["téves jel gyenge adatminta esetén","marginromlás rosszul választott kedvezménnyel"]});
  if(kpis.no_show_percent>=8)out.push({operation_type:"customer_retention_review",title:"No-show kockázat csökkentése",rationale:`Az elmúlt 30 nap no-show aránya ${kpis.no_show_percent}%, ezért vendégmegtartási és emlékeztetési kontroll szükséges.`,baseScore:kpis.no_show_percent>=12?84:70,expected:{goal:"reduce_no_show",baseline_percent:kpis.no_show_percent},evidence:kpis,alternatives:["megerősítő emlékeztető","várólista aktiválása","kockázati szegmens külön kezelése"],risks:["túl sok kommunikáció","vendégélmény-romlás túl szigorú szabály esetén"]});
  if(mape>=35)out.push({operation_type:"manual_task",title:"Prediktív adatminőség felülvizsgálata",rationale:`A P20 holdout MAPE ${mape.toFixed(1)}%, ezért a modell döntési súlyát adatminőség-ellenőrzésig csökkenteni kell.`,baseScore:76,expected:{goal:"improve_model_reliability",current_mape:mape},evidence:{mape_percent:mape,history_days:f30.history_days},alternatives:["státuszadatok tisztítása","ár-adatok ellenőrzése","ritka események kizárása"],risks:["túl kevés történeti adat","szezonális törés"]});
  if(!out.length)out.push({operation_type:"capacity_review",title:"Stabil működés fenntartása",rationale:"A prediktív jelek nem mutatnak kritikus eltérést; preventív kapacitáskontroll javasolt.",baseScore:48,expected:{goal:"maintain_stability"},evidence:{load,revenue_momentum:rm,booking_momentum:bm,mape_percent:mape},alternatives:["nincs beavatkozás","heti újraértékelés"],risks:["rejtett lokális eltérés"]});
  return out;
}

router.get("/status",async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;try{const counts=(await pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='proposed')::int proposed,COUNT(*) FILTER(WHERE status='promoted')::int promoted,COUNT(*) FILTER(WHERE status='dismissed')::int dismissed FROM vir_p21_decisions WHERE tenant_id=$1::bigint`,[tenant])).rows[0];return res.json({ok:true,model:"explainable_ai_decision_support_v1",uses_p20_predictions:true,uses_p22_feedback:true,requires_p17_approval:true,direct_external_execution:false,counts});}catch(error:any){return res.status(500).json({ok:false,error:error?.message||"p21_status_failed"});}});
router.get("/decisions",async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;try{return res.json({ok:true,items:(await pool.query(`SELECT * FROM vir_p21_decisions WHERE tenant_id=$1::bigint ORDER BY created_at DESC LIMIT 200`,[tenant])).rows});}catch(error:any){return res.status(500).json({ok:false,error:error?.message||"p21_list_failed"});}});
router.post("/generate",async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;const location=await validateLocation(req.body?.locationId,tenant,res);if(location===undefined)return;try{const candidates=await generateCandidates(tenant,location),created=[] as any[];for(const c of candidates){const learning=await learnedAdjustment(tenant,c.operation_type),score=clamp(c.baseScore+learning.adjustment,0,100),confidence=clamp(0.48+score/250+(learning.samples?0.08:0),0.45,0.94),key=`${c.operation_type}:${location||"all"}:${new Date().toISOString().slice(0,10)}`;const row=(await pool.query(`INSERT INTO vir_p21_decisions(tenant_id,location_id,decision_key,operation_type,title,rationale,priority,confidence,score,expected_impact,evidence,alternatives,risks,learning,created_by) VALUES($1::bigint,$2::uuid,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11::jsonb,$12::jsonb,$13::jsonb,$14::jsonb,$15) ON CONFLICT (tenant_id,decision_key) WHERE status='proposed' DO UPDATE SET title=EXCLUDED.title,rationale=EXCLUDED.rationale,priority=EXCLUDED.priority,confidence=EXCLUDED.confidence,score=EXCLUDED.score,expected_impact=EXCLUDED.expected_impact,evidence=EXCLUDED.evidence,alternatives=EXCLUDED.alternatives,risks=EXCLUDED.risks,learning=EXCLUDED.learning,updated_at=now() RETURNING *`,[tenant,location,key,c.operation_type,c.title,c.rationale,priority(score),confidence,score,JSON.stringify(c.expected),JSON.stringify(c.evidence),JSON.stringify(c.alternatives),JSON.stringify(c.risks),JSON.stringify(learning),actorId(req)])).rows[0];created.push(row);}return res.status(201).json({ok:true,model:"explainable_ai_decision_support_v1",items:created,direct_external_execution:false});}catch(error:any){return res.status(500).json({ok:false,error:error?.message||"p21_generate_failed"});}});
router.post("/decisions/:id/promote",async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;const id=String(req.params.id||"");if(!UUID.test(id))return res.status(400).json({ok:false,error:"invalid_decision_id"});const client=await pool.connect();try{await client.query("BEGIN");const d=(await client.query(`SELECT * FROM vir_p21_decisions WHERE id=$1::uuid AND tenant_id=$2::bigint FOR UPDATE`,[id,tenant])).rows[0];if(!d){await client.query("ROLLBACK");return res.status(404).json({ok:false,error:"decision_not_found"});}if(d.status==='promoted'&&d.promoted_operation_id){await client.query("COMMIT");return res.json({ok:true,operation_id:d.promoted_operation_id,already_promoted:true});}if(d.status!=='proposed'){await client.query("ROLLBACK");return res.status(409).json({ok:false,error:"decision_not_promotable",status:d.status});}const preview={source:"p21_ai",decision_id:d.id,score:Number(d.score),confidence:Number(d.confidence),rationale:d.rationale,expected_impact:d.expected_impact,evidence:d.evidence,alternatives:d.alternatives,risks:d.risks,learning:d.learning,no_direct_external_execution:true};const op=(await client.query(`INSERT INTO vir_p17_operations(tenant_id,location_id,operation_type,title,status,execution_mode,approval_required,risk_level,source_layer,source_ref,idempotency_key,preview_payload,created_by) VALUES($1::bigint,$2::uuid,$3,$4,'pending_approval','controlled_manual',true,$5,'p21_ai',$6,$7,$8::jsonb,$9) RETURNING *`,[tenant,d.location_id,d.operation_type,d.title,d.priority==='critical'?'high':d.priority==='high'?'high':'medium',d.id,`p21:${d.id}`,JSON.stringify(preview),actorId(req)])).rows[0];await client.query(`INSERT INTO vir_p17_operation_events(tenant_id,operation_id,event_type,actor_id,payload) VALUES($1::bigint,$2::uuid,'promoted_from_p21',$3,$4::jsonb)`,[tenant,op.id,actorId(req),JSON.stringify({decision_id:d.id,score:d.score})]);await client.query(`UPDATE vir_p21_decisions SET status='promoted',promoted_operation_id=$3::uuid,decided_by=$4,decided_at=now(),updated_at=now() WHERE id=$1::uuid AND tenant_id=$2::bigint`,[id,tenant,op.id,actorId(req)]);await client.query("COMMIT");return res.status(201).json({ok:true,operation:op,requires_p17_approval:true,direct_external_execution:false});}catch(error:any){await client.query("ROLLBACK").catch(()=>undefined);return res.status(500).json({ok:false,error:error?.message||"p21_promote_failed"});}finally{client.release();}});
router.post("/decisions/:id/dismiss",async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;const id=String(req.params.id||"");if(!UUID.test(id))return res.status(400).json({ok:false,error:"invalid_decision_id"});try{const row=(await pool.query(`UPDATE vir_p21_decisions SET status='dismissed',decided_by=$3,decided_at=now(),updated_at=now() WHERE id=$1::uuid AND tenant_id=$2::bigint AND status='proposed' RETURNING *`,[id,tenant,actorId(req)])).rows[0];if(!row)return res.status(404).json({ok:false,error:"decision_not_found_or_decided"});return res.json({ok:true,item:row});}catch(error:any){return res.status(500).json({ok:false,error:error?.message||"p21_dismiss_failed"});}});

export default router;
