import {Router,Response} from 'express';
import pool from '../db';
import type {AuthRequest} from '../middleware/auth';
import {requireManagement} from '../middleware/requireRoles';
const r=Router();r.use(requireManagement);const UUID=/^[0-9a-f]{8}-[0-9a-f-]{27}$/i;const n=(v:unknown)=>String(v||'').trim();
async function tenant(req:AuthRequest,res:Response){const t=n(req.user?.tenant_id);if(!t){res.status(403).json({ok:false,error:'tenant_missing'});return null}return t}
async function owns(t:string,id:string){return Number((await pool.query('SELECT 1 FROM appointments WHERE tenant_id=$1::uuid AND client_id=$2::uuid LIMIT 1',[t,id])).rowCount||0)>0}
r.get('/status',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;const q=(await pool.query(`SELECT (SELECT count(*) FROM vir_conversations WHERE tenant_id=$1::uuid AND status='open')::int open_conversations,(SELECT count(*) FROM vir_ai_handoffs WHERE tenant_id=$1::uuid AND status='open')::int open_handoffs,(SELECT count(*) FROM vir_complaint_cases WHERE tenant_id=$1::uuid AND status='open')::int open_complaints`,[t])).rows[0];res.json({ok:true,layer:'customer_journey_orchestration_v4',automatic_customer_mutation:false,capabilities:{journey_timeline:true,next_best_step:true,recovery_queue:true},counts:q})});
r.get('/journey/:clientId',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;const id=n(req.params.clientId);if(!UUID.test(id)||!await owns(t,id))return res.status(403).json({ok:false,error:'client_not_in_tenant'});const visits=(await pool.query(`SELECT 'APPOINTMENT' type,a.id::text id,a.start_time at,a.status label,COALESCE(string_agg(DISTINCT s.name,', '),'') detail FROM appointments a LEFT JOIN appointment_services aps ON aps.appointment_id=a.id LEFT JOIN services s ON s.id=aps.service_id WHERE a.tenant_id=$1::uuid AND a.client_id=$2::uuid GROUP BY a.id,a.start_time,a.status ORDER BY a.start_time DESC LIMIT 40`,[t,id])).rows;const conv=(await pool.query(`SELECT 'CONVERSATION' type,id::text,last_message_at at,status label,channel detail FROM vir_conversations WHERE tenant_id=$1::uuid AND client_id=$2::uuid ORDER BY last_message_at DESC NULLS LAST LIMIT 30`,[t,id])).rows;const complaints=(await pool.query(`SELECT 'COMPLAINT' type,id::text,created_at at,status label,category||' / '||severity detail FROM vir_complaint_cases WHERE tenant_id=$1::uuid AND client_id=$2::uuid ORDER BY created_at DESC LIMIT 20`,[t,id])).rows;res.json({ok:true,model:'journey_timeline_v4',items:[...visits,...conv,...complaints].sort((a:any,b:any)=>String(b.at||'').localeCompare(String(a.at||''))).slice(0,80)})});
r.get('/next-step/:clientId',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;const id=n(req.params.clientId);if(!UUID.test(id)||!await owns(t,id))return res.status(403).json({ok:false,error:'client_not_in_tenant'});const row=(await pool.query(`SELECT EXISTS(SELECT 1 FROM vir_complaint_cases WHERE tenant_id=$1::uuid AND client_id=$2::uuid AND status='open') complaint,EXISTS(SELECT 1 FROM appointments WHERE tenant_id=$1::uuid AND client_id=$2::uuid AND start_time>now() AND status NOT IN ('cancelled','no_show')) future_booking,COALESCE((SELECT max(start_time) FROM appointments WHERE tenant_id=$1::uuid AND client_id=$2::uuid AND start_time<=now()),now()-interval '365 days') last_visit`,[t,id])).rows[0];const action=row.complaint?'SERVICE_RECOVERY':!row.future_booking?'REBOOK':'FOLLOW_UP';res.json({ok:true,model:'next_best_step_v4',recommendation:{action,priority:row.complaint?'high':'normal',reason:row.complaint?'Nyitott panasz miatt emberi visszahívás szükséges.':!row.future_booking?'Nincs jövőbeli foglalás.':'Van aktív jövőbeli foglalás.',last_visit:row.last_visit},execution_enabled:false,approval_required:true})});
r.get('/recovery-queue',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;const rows=(await pool.query(`SELECT c.id::text client_id,c.full_name,COUNT(*) FILTER(WHERE a.status='no_show' AND a.start_time>now()-interval '90 days')::int no_shows_90d,MAX(a.start_time) FILTER(WHERE a.start_time<=now()) last_visit,EXISTS(SELECT 1 FROM vir_complaint_cases cc WHERE cc.tenant_id=$1::uuid AND cc.client_id=c.id AND cc.status='open') open_complaint FROM clients c JOIN appointments a ON a.client_id=c.id AND a.tenant_id=$1::uuid GROUP BY c.id,c.full_name HAVING COUNT(*) FILTER(WHERE a.status='no_show' AND a.start_time>now()-interval '90 days')>0 OR MAX(a.start_time) FILTER(WHERE a.start_time<=now())<now()-interval '120 days' OR EXISTS(SELECT 1 FROM vir_complaint_cases cc WHERE cc.tenant_id=$1::uuid AND cc.client_id=c.id AND cc.status='open') ORDER BY open_complaint DESC,no_shows_90d DESC,last_visit ASC NULLS FIRST LIMIT 250`,[t])).rows;res.json({ok:true,model:'journey_recovery_queue_v4',automatic_outreach:false,items:rows})});
export default r;
