import {Router,Response} from "express";
import pool from "../db";
import type {AuthRequest} from "../middleware/auth";
import {requireManagement} from "../middleware/requireRoles";
import {findCalendarGaps,matchWaitlist} from "../booking/virWave1Engine";

const router=Router();router.use(requireManagement);
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const CHANNELS=["email","sms","viber","messenger","whatsapp","push","webchat","voice"] as const;
const n=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
type Scope={tenantId:string;locationId:string|null};
async function scope(req:AuthRequest,res:Response):Promise<Scope|undefined>{const tenantId=String(req.user?.tenant_id||"").trim();if(!tenantId){res.status(403).json({ok:false,error:"A felhasználóhoz nincs tenant rendelve."});return}const requested=String(req.query.locationId||req.body?.locationId||req.query.location_id||req.body?.location_id||"").trim();if(!requested)return{tenantId,locationId:null};if(!UUID.test(requested)){res.status(400).json({ok:false,error:"Érvénytelen telephelyazonosító."});return}const owned=(await pool.query(`SELECT id FROM locations WHERE id=$1::uuid AND tenant_id=$2::uuid`,[requested,tenantId])).rows[0];if(!owned){res.status(403).json({ok:false,error:"A telephely nem tartozik a tenantjához."});return}return{tenantId,locationId:requested}}
async function ensureSchema(){await pool.query(`
CREATE TABLE IF NOT EXISTS vir_client_channel_identities(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,client_id uuid NOT NULL,channel text NOT NULL,external_id text NOT NULL,display_name text,verified boolean NOT NULL DEFAULT false,transactional_consent boolean NOT NULL DEFAULT false,marketing_consent boolean NOT NULL DEFAULT false,last_activity_at timestamptz,metadata jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,channel,external_id));
CREATE INDEX IF NOT EXISTS vir_client_channel_identity_client_idx ON vir_client_channel_identities(tenant_id,client_id,channel);
CREATE TABLE IF NOT EXISTS vir_conversations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,location_id uuid,client_id uuid,channel text NOT NULL,external_thread_id text,status text NOT NULL DEFAULT 'open',assigned_user_id uuid,last_message_at timestamptz,ai_handoff_required boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS vir_conversations_scope_idx ON vir_conversations(tenant_id,status,last_message_at DESC);
CREATE TABLE IF NOT EXISTS vir_conversation_messages(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,conversation_id uuid NOT NULL,direction text NOT NULL,provider_message_id text,body text NOT NULL DEFAULT '',sent_at timestamptz NOT NULL DEFAULT now(),delivery_status text NOT NULL DEFAULT 'received',attribution_touch_id uuid,metadata jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE INDEX IF NOT EXISTS vir_conversation_messages_thread_idx ON vir_conversation_messages(tenant_id,conversation_id,sent_at DESC);
CREATE TABLE IF NOT EXISTS vir_communication_touches(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,location_id uuid,client_id uuid,channel text NOT NULL,campaign_key text,purpose text NOT NULL DEFAULT 'transactional',status text NOT NULL DEFAULT 'queued',cost_amount numeric(12,4) NOT NULL DEFAULT 0,currency text NOT NULL DEFAULT 'HUF',sent_at timestamptz,delivered_at timestamptz,clicked_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS vir_communication_touches_scope_idx ON vir_communication_touches(tenant_id,client_id,created_at DESC);
CREATE TABLE IF NOT EXISTS vir_ai_handoffs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,location_id uuid,client_id uuid,conversation_id uuid,reason text NOT NULL,summary text NOT NULL,status text NOT NULL DEFAULT 'open',created_by uuid,created_at timestamptz NOT NULL DEFAULT now(),closed_at timestamptz);
`)}
async function tenantLocations(s:Scope){if(s.locationId)return(await pool.query(`SELECT id::text,name FROM locations WHERE tenant_id=$1::uuid AND id=$2::uuid`,[s.tenantId,s.locationId])).rows;return(await pool.query(`SELECT id::text,name FROM locations WHERE tenant_id=$1::uuid AND active IS DISTINCT FROM false ORDER BY name`,[s.tenantId])).rows}

router.get('/layer-status',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const counts=(await pool.query(`SELECT (SELECT count(*) FROM vir_client_channel_identities WHERE tenant_id=$1::uuid)::int identities,(SELECT count(*) FROM vir_conversations WHERE tenant_id=$1::uuid AND status='open')::int open_conversations,(SELECT count(*) FROM vir_ai_handoffs WHERE tenant_id=$1::uuid AND status='open')::int open_handoffs`,[s.tenantId])).rows[0];return res.json({ok:true,layer:'communication_revenue_automation_v1',tenant_scoped:true,consent_aware:true,approval_boundary:true,capabilities:{identity_hub:true,universal_inbox:true,ai_handoff:true,empty_slot_recovery:true,channel_optimizer:true,revenue_attribution:true},counts})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'p8_status_failed'})}});

router.get('/identity-hub',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const clientId=String(req.query.clientId||'').trim();const params:any[]=[s.tenantId];let extra='';if(clientId){if(!UUID.test(clientId))return res.status(400).json({ok:false,error:'Érvénytelen clientId.'});params.push(clientId);extra=' AND i.client_id=$2::uuid'}const rows=(await pool.query(`SELECT i.*,COALESCE(c.full_name,'Vendég') client_name FROM vir_client_channel_identities i LEFT JOIN clients c ON c.id=i.client_id WHERE i.tenant_id=$1::uuid${extra} ORDER BY i.client_id,i.channel`,params)).rows;return res.json({ok:true,model:'omnichannel_identity_hub_v1',channels:CHANNELS,items:rows})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'identity_hub_failed'})}});
router.post('/identity-hub',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const clientId=String(req.body?.client_id||'').trim(),channel=String(req.body?.channel||'').toLowerCase(),externalId=String(req.body?.external_id||'').trim();if(!UUID.test(clientId)||!CHANNELS.includes(channel as any)||!externalId)return res.status(400).json({ok:false,error:'client_id, támogatott channel és external_id szükséges.'});const owns=(await pool.query(`SELECT 1 FROM appointments WHERE tenant_id=$1::uuid AND client_id=$2::uuid LIMIT 1`,[s.tenantId,clientId])).rowCount;if(!owns)return res.status(403).json({ok:false,error:'A vendég nem igazolt a tenantban.'});const row=(await pool.query(`INSERT INTO vir_client_channel_identities(tenant_id,client_id,channel,external_id,display_name,verified,transactional_consent,marketing_consent,last_activity_at,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,now(),$9::jsonb) ON CONFLICT(tenant_id,channel,external_id) DO UPDATE SET client_id=EXCLUDED.client_id,display_name=EXCLUDED.display_name,verified=EXCLUDED.verified,transactional_consent=EXCLUDED.transactional_consent,marketing_consent=EXCLUDED.marketing_consent,last_activity_at=now(),metadata=EXCLUDED.metadata,updated_at=now() RETURNING *`,[s.tenantId,clientId,channel,externalId,String(req.body?.display_name||'')||null,Boolean(req.body?.verified),Boolean(req.body?.transactional_consent),Boolean(req.body?.marketing_consent),JSON.stringify(req.body?.metadata||{})])).rows[0];return res.status(201).json({ok:true,item:row})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'identity_upsert_failed'})}});

router.get('/inbox',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const rows=(await pool.query(`SELECT c.*,COALESCE(cl.full_name,'Ismeretlen vendég') client_name,(SELECT body FROM vir_conversation_messages m WHERE m.conversation_id=c.id AND m.tenant_id=c.tenant_id ORDER BY sent_at DESC LIMIT 1) last_message FROM vir_conversations c LEFT JOIN clients cl ON cl.id=c.client_id WHERE c.tenant_id=$1::uuid AND ($2::uuid IS NULL OR c.location_id=$2::uuid) ORDER BY c.last_message_at DESC NULLS LAST,c.created_at DESC LIMIT 250`,[s.tenantId,s.locationId])).rows;return res.json({ok:true,model:'universal_inbox_v1',items:rows})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'inbox_failed'})}});
router.post('/inbox/ingest',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const channel=String(req.body?.channel||'').toLowerCase(),externalId=String(req.body?.external_id||'').trim(),body=String(req.body?.body||'').trim();if(!CHANNELS.includes(channel as any)||!externalId||!body)return res.status(400).json({ok:false,error:'channel, external_id és body szükséges.'});const ident=(await pool.query(`SELECT client_id FROM vir_client_channel_identities WHERE tenant_id=$1::uuid AND channel=$2 AND external_id=$3`,[s.tenantId,channel,externalId])).rows[0];let conv=(await pool.query(`SELECT * FROM vir_conversations WHERE tenant_id=$1::uuid AND channel=$2 AND external_thread_id=$3 AND status='open' ORDER BY created_at DESC LIMIT 1`,[s.tenantId,channel,externalId])).rows[0];if(!conv)conv=(await pool.query(`INSERT INTO vir_conversations(tenant_id,location_id,client_id,channel,external_thread_id,last_message_at) VALUES($1,$2,$3,$4,$5,now()) RETURNING *`,[s.tenantId,s.locationId,ident?.client_id||null,channel,externalId])).rows[0];await pool.query(`INSERT INTO vir_conversation_messages(tenant_id,conversation_id,direction,provider_message_id,body,delivery_status,metadata) VALUES($1,$2,'inbound',$3,$4,'received',$5::jsonb)`,[s.tenantId,conv.id,String(req.body?.provider_message_id||'')||null,body,JSON.stringify(req.body?.metadata||{})]);await pool.query(`UPDATE vir_conversations SET client_id=COALESCE(client_id,$3),last_message_at=now(),updated_at=now() WHERE id=$1 AND tenant_id=$2`,[conv.id,s.tenantId,ident?.client_id||null]);return res.status(201).json({ok:true,conversation_id:conv.id,client_resolved:Boolean(ident?.client_id)})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'inbox_ingest_failed'})}});

router.post('/ai-receptionist/handoff',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const summary=String(req.body?.summary||'').trim(),reason=String(req.body?.reason||'AI_UNCERTAIN').slice(0,120);if(!summary)return res.status(400).json({ok:false,error:'summary szükséges.'});const convId=String(req.body?.conversation_id||'').trim()||null,clientId=String(req.body?.client_id||'').trim()||null;if(convId&&!UUID.test(convId)||clientId&&!UUID.test(clientId))return res.status(400).json({ok:false,error:'Érvénytelen azonosító.'});const row=(await pool.query(`INSERT INTO vir_ai_handoffs(tenant_id,location_id,client_id,conversation_id,reason,summary,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[s.tenantId,s.locationId,clientId,convId,reason,summary,req.user?.id||null])).rows[0];if(convId)await pool.query(`UPDATE vir_conversations SET ai_handoff_required=true,updated_at=now() WHERE id=$1 AND tenant_id=$2`,[convId,s.tenantId]);return res.status(201).json({ok:true,human_review_required:true,automatic_resolution:false,item:row})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'handoff_failed'})}});

router.get('/empty-slot-recovery',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;const days=Math.max(1,Math.min(14,Math.round(n(req.query.days)||7)));const locs=await tenantLocations(s);const items:any[]=[];for(const loc of locs){const gaps=await findCalendarGaps(String(loc.id),days);const matches=await matchWaitlist(String(loc.id),gaps);for(const g of gaps){const m=matches.find((x:any)=>x.employee_id===g.employee_id&&x.gap_start===g.start);if(m)items.push({location_id:loc.id,location_name:loc.name,gap:g,match:m,estimated_recovered_value:n(m.estimated_value)||n(g.estimated_value),recommended_channel:'BEST_AVAILABLE',approval_required:true})}}items.sort((a,b)=>n(b.estimated_recovered_value)-n(a.estimated_recovered_value));return res.json({ok:true,model:'empty_slot_revenue_recovery_v2',automatic_outreach:false,automatic_rebooking:false,summary:{opportunities:items.length,estimated_recoverable_value:items.reduce((a,x)=>a+n(x.estimated_recovered_value),0)},items:items.slice(0,200)})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'empty_slot_recovery_failed'})}});

router.get('/channel-optimizer',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const days=Math.max(30,Math.min(365,Math.round(n(req.query.days)||90)));const rows=(await pool.query(`SELECT i.client_id::text,COALESCE(c.full_name,'Vendég') client_name,i.channel,i.transactional_consent,i.marketing_consent,COUNT(t.id)::int touches,COUNT(t.delivered_at)::int delivered,COUNT(t.clicked_at)::int clicked,COALESCE(SUM(t.cost_amount),0)::numeric cost FROM vir_client_channel_identities i LEFT JOIN clients c ON c.id=i.client_id LEFT JOIN vir_communication_touches t ON t.tenant_id=i.tenant_id AND t.client_id=i.client_id AND t.channel=i.channel AND t.created_at>=now()-($2::text||' days')::interval WHERE i.tenant_id=$1::uuid GROUP BY i.client_id,c.full_name,i.channel,i.transactional_consent,i.marketing_consent ORDER BY i.client_id,i.channel`,[s.tenantId,days])).rows;const byClient=new Map<string,any>();for(const r of rows){const key=r.client_id;const x=byClient.get(key)||{client_id:key,client_name:r.client_name,channels:[]};const score=(r.transactional_consent||r.marketing_consent)?Math.round((n(r.clicked)*8+n(r.delivered)*2+Math.max(0,10-n(r.cost)))*10)/10:0;x.channels.push({...r,score});byClient.set(key,x)}const items=[...byClient.values()].map(x=>({...x,recommended_channel:[...x.channels].sort((a:any,b:any)=>b.score-a.score)[0]?.channel||null}));return res.json({ok:true,model:'consent_cost_response_channel_optimizer_v1',days,automatic_send:false,items})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'channel_optimizer_failed'})}});

router.get('/revenue-attribution',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const days=Math.max(7,Math.min(365,Math.round(n(req.query.days)||90)));const rows=(await pool.query(`SELECT t.channel,COUNT(DISTINCT t.id)::int touches,COUNT(DISTINCT a.id)::int attributed_bookings,COALESCE(SUM(aps.price),0)::numeric booked_value,COALESCE(SUM(t.cost_amount),0)::numeric communication_cost FROM vir_communication_touches t LEFT JOIN LATERAL (SELECT a.* FROM appointments a WHERE a.tenant_id=t.tenant_id AND a.client_id=t.client_id AND a.start_time>=COALESCE(t.sent_at,t.created_at) AND a.start_time<COALESCE(t.sent_at,t.created_at)+interval '14 days' AND ($2::uuid IS NULL OR a.location_id=$2::uuid) ORDER BY a.start_time LIMIT 1) a ON true LEFT JOIN appointment_services aps ON aps.appointment_id=a.id WHERE t.tenant_id=$1::uuid AND t.created_at>=now()-($3::text||' days')::interval GROUP BY t.channel ORDER BY booked_value DESC`,[s.tenantId,s.locationId,days])).rows;const items=rows.map((r:any)=>({...r,roi_proxy:n(r.communication_cost)>0?Math.round((n(r.booked_value)/n(r.communication_cost))*100)/100:null}));return res.json({ok:true,model:'last_touch_booking_value_attribution_v1',days,paid_revenue_supported:false,causality_claim:false,attribution_window_days:14,items})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'attribution_failed'})}});

export default router;
