import {Router,Response} from "express";
import pool from "../db";
import type {AuthRequest} from "../middleware/auth";
import {requireManagement} from "../middleware/requireRoles";
import {profitEngine} from "../services/virWave2Engine";
import {collectExecutiveSignals,currentBudapestDate} from "../services/executiveAiAssistant";

const router=Router();
router.use(requireManagement);
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const num=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
const clamp=(v:number,min:number,max:number)=>Math.min(max,Math.max(min,v));
type Scope={tenantId:string;locationId:string|null};
async function scope(req:AuthRequest,res:Response):Promise<Scope|undefined>{const tenantId=String(req.user?.tenant_id||"").trim();if(!tenantId){res.status(403).json({ok:false,error:"A felhasználóhoz nincs tenant rendelve."});return}const requested=String(req.query.locationId||req.body?.locationId||req.query.location_id||req.body?.location_id||"").trim();if(!requested)return{tenantId,locationId:null};if(!UUID.test(requested)){res.status(400).json({ok:false,error:"Érvénytelen telephelyazonosító."});return}const owned=(await pool.query(`SELECT id FROM locations WHERE id=$1::uuid AND tenant_id=$2::uuid`,[requested,tenantId])).rows[0];if(!owned){res.status(403).json({ok:false,error:"A telephely nem tartozik a tenantjához."});return}return{tenantId,locationId:requested}}
async function locations(s:Scope){return(await pool.query(`SELECT id::text,name FROM locations WHERE tenant_id=$1::uuid AND active IS DISTINCT FROM false AND ($2::uuid IS NULL OR id=$2::uuid) ORDER BY name`,[s.tenantId,s.locationId])).rows}

router.get("/digital-twin",async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;const revenue=clamp(num(req.query.revenue_change),-50,100),price=clamp(num(req.query.price_change),-30,50),util=clamp(num(req.query.utilization_change),-50,100),wage=clamp(num(req.query.wage_change),-30,50),material=clamp(num(req.query.material_change),-30,50);const locs=await locations(s);const items=[] as any[];for(const loc of locs){const p=await profitEngine({locationId:String(loc.id)});const b:any=p.summary||{};const baseRevenue=num(b.revenue),baseMaterial=num(b.material_cost),baseLabor=num(b.labor_cost),baseCommission=num(b.commission_cost),baseProfit=num(b.gross_profit);const revenueMultiplier=(1+revenue/100)*(1+price/100)*(1+util/100);const scenarioRevenue=baseRevenue*revenueMultiplier,scenarioMaterial=baseMaterial*(1+material/100)*(1+revenue/100)*(1+util/100),scenarioLabor=baseLabor*(1+wage/100)*(1+util/100),scenarioCommission=baseRevenue?baseCommission*(scenarioRevenue/baseRevenue):0,scenarioProfit=scenarioRevenue-scenarioMaterial-scenarioLabor-scenarioCommission;items.push({location_id:loc.id,location_name:loc.name,baseline:{revenue:Math.round(baseRevenue),gross_profit:Math.round(baseProfit),margin_percent:baseRevenue?Math.round(baseProfit/baseRevenue*10000)/100:0},scenario:{revenue:Math.round(scenarioRevenue),gross_profit:Math.round(scenarioProfit),margin_percent:scenarioRevenue?Math.round(scenarioProfit/scenarioRevenue*10000)/100:0},delta:{revenue:Math.round(scenarioRevenue-baseRevenue),gross_profit:Math.round(scenarioProfit-baseProfit)}})}return res.json({ok:true,model:"vir_digital_twin_deterministic_v1",inputs:{revenue_change:revenue,price_change:price,utilization_change:util,wage_change:wage,material_change:material},simulation_only:true,automatic_writes:false,items});}catch(e:any){res.status(500).json({ok:false,error:e?.message||"digital_twin_failed"})}});

router.post("/goal-action",async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;const goal=String(req.body?.goal||"revenue_growth");const target=clamp(num(req.body?.target_percent)||10,1,100),horizon=clamp(Math.round(num(req.body?.horizon_days)||30),7,180);const locs=await locations(s);const actions=[] as any[];for(const loc of locs){const signals=await collectExecutiveSignals(currentBudapestDate(),String(loc.id));const warning=signals.filter(x=>x.severity==='critical'||x.severity==='warning').slice(0,4);const p=await profitEngine({locationId:String(loc.id)});const margin=num((p.summary as any)?.margin_percent);const candidates:any[]=[];if(warning.some(x=>String(x.key).includes('capacity')))candidates.push({type:"CAPACITY",priority:"HIGH",action:"Nyiss célzott kapacitást a csúcsidősávokban.",evidence:warning.find(x=>String(x.key).includes('capacity'))?.headline});if(warning.some(x=>String(x.key).includes('no_show')))candidates.push({type:"NO_SHOW",priority:"HIGH",action:"Erősítsd a megerősítési és várólista folyamatot.",evidence:warning.find(x=>String(x.key).includes('no_show'))?.headline});if(margin<20)candidates.push({type:"MARGIN",priority:"HIGH",action:"Vizsgáld felül az alacsony marzsú szolgáltatásokat és anyagfelhasználást.",evidence:`Jelenlegi becsült margin: ${Math.round(margin*10)/10}%`});if(!candidates.length)candidates.push({type:"GROWTH",priority:"MEDIUM",action:"Növeld az újrafoglalást és a kihasználtságot a legerősebb szolgáltatásoknál.",evidence:"Nincs kritikus operatív jelzés."});actions.push({location_id:loc.id,location_name:loc.name,goal,target_percent:target,horizon_days:horizon,actions:candidates.slice(0,5)})}return res.json({ok:true,model:"goal_to_action_deterministic_v1",goal,target_percent:target,horizon_days:horizon,ai_execution:false,approval_required:true,automatic_actions:false,items:actions});}catch(e:any){res.status(500).json({ok:false,error:e?.message||"goal_action_failed"})}});

router.post("/action-preview",async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;const actionType=String(req.body?.action_type||"CAPACITY").toUpperCase();const impact=clamp(num(req.body?.expected_revenue_change_percent)||5,-50,100),cost=clamp(num(req.body?.expected_cost_change_percent)||2,-50,100);const locs=await locations(s);const previews=[] as any[];for(const loc of locs){const p=await profitEngine({locationId:String(loc.id)});const b:any=p.summary||{};const baseRevenue=num(b.revenue),baseProfit=num(b.gross_profit),baseCost=Math.max(0,baseRevenue-baseProfit);const afterRevenue=baseRevenue*(1+impact/100),afterCost=baseCost*(1+cost/100),afterProfit=afterRevenue-afterCost;previews.push({location_id:loc.id,location_name:loc.name,action_type:actionType,before:{revenue:Math.round(baseRevenue),gross_profit:Math.round(baseProfit)},preview_after:{revenue:Math.round(afterRevenue),gross_profit:Math.round(afterProfit)},delta:{revenue:Math.round(afterRevenue-baseRevenue),gross_profit:Math.round(afterProfit-baseProfit)},risk:Math.abs(cost)>15||Math.abs(impact)>30?"HIGH":"NORMAL"})}return res.json({ok:true,model:"autonomous_action_preview_v1",preview_only:true,approval_required:true,execution_enabled:false,automatic_writes:false,previews});}catch(e:any){res.status(500).json({ok:false,error:e?.message||"action_preview_failed"})}});

router.get("/competitor-intelligence",async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;const days=clamp(Math.round(num(req.query.days)||30),7,90);const rows=(await pool.query(`WITH x AS (SELECT l.id,l.name,COUNT(DISTINCT a.id)::int appointments,COUNT(DISTINCT a.client_id)::int clients,COALESCE(SUM(COALESCE(aps.price,0)),0)::numeric revenue FROM locations l LEFT JOIN appointments a ON a.location_id=l.id AND a.tenant_id=$1::uuid AND a.start_time>=now()-($3::text||' days')::interval LEFT JOIN appointment_services aps ON aps.appointment_id=a.id WHERE l.tenant_id=$1::uuid GROUP BY l.id,l.name) SELECT * FROM x WHERE ($2::uuid IS NULL OR id=$2::uuid) ORDER BY revenue DESC`,[s.tenantId,s.locationId,days])).rows;const all=(await pool.query(`SELECT l.id::text,l.name,COUNT(DISTINCT a.id)::int appointments,COALESCE(SUM(COALESCE(aps.price,0)),0)::numeric revenue FROM locations l LEFT JOIN appointments a ON a.location_id=l.id AND a.tenant_id=$1::uuid AND a.start_time>=now()-($2::text||' days')::interval LEFT JOIN appointment_services aps ON aps.appointment_id=a.id WHERE l.tenant_id=$1::uuid GROUP BY l.id,l.name`,[s.tenantId,days])).rows;const avgRev=all.length?all.reduce((a:number,r:any)=>a+num(r.revenue),0)/all.length:0,avgAppt=all.length?all.reduce((a:number,r:any)=>a+num(r.appointments),0)/all.length:0;const items=rows.map((r:any)=>({location_id:String(r.id),location_name:r.name,appointments:num(r.appointments),clients:num(r.clients),revenue:num(r.revenue),revenue_vs_peer_pct:avgRev?Math.round((num(r.revenue)-avgRev)/avgRev*1000)/10:0,appointments_vs_peer_pct:avgAppt?Math.round((num(r.appointments)-avgAppt)/avgAppt*1000)/10:0,competitive_position:num(r.revenue)>=avgRev*1.15?"LEADING":num(r.revenue)<=avgRev*.85?"DEFENSIVE":"PARITY"}));return res.json({ok:true,days,model:"internal_peer_competitor_proxy_v1",external_competitor_data:false,data_source:"internal_network_proxy_only",warning:"Külső versenytársi adatfeed nincs bekötve; ez belső hálózati benchmark, nem piaci tényadat.",peer_average:{revenue:Math.round(avgRev),appointments:Math.round(avgAppt)},items});}catch(e:any){res.status(500).json({ok:false,error:e?.message||"competitor_intelligence_failed"})}});

router.get("/location-expansion",async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;const candidate=String(req.query.candidate_name||"Új telephely");const expectedAppointments=Math.max(0,num(req.query.expected_monthly_appointments)||300),avgTicket=Math.max(0,num(req.query.avg_ticket)||12000),monthlyRent=Math.max(0,num(req.query.monthly_rent)||1200000),startupCost=Math.max(0,num(req.query.startup_cost)||25000000);const rows=(await pool.query(`SELECT l.id::text,l.name,COUNT(DISTINCT a.id)::numeric/GREATEST(COUNT(DISTINCT date_trunc('month',a.start_time)),1) monthly_appointments,COALESCE(SUM(COALESCE(aps.price,0)),0)::numeric/GREATEST(COUNT(DISTINCT date_trunc('month',a.start_time)),1) monthly_revenue FROM locations l LEFT JOIN appointments a ON a.location_id=l.id AND a.tenant_id=$1::uuid AND a.start_time>=now()-interval '180 days' LEFT JOIN appointment_services aps ON aps.appointment_id=a.id WHERE l.tenant_id=$1::uuid GROUP BY l.id,l.name`,[s.tenantId])).rows;const avgMonthlyRevenue=rows.length?rows.reduce((a:number,r:any)=>a+num(r.monthly_revenue),0)/rows.length:0,avgMonthlyAppointments=rows.length?rows.reduce((a:number,r:any)=>a+num(r.monthly_appointments),0)/rows.length:0;const projectedRevenue=expectedAppointments*avgTicket;const rentRatio=projectedRevenue?monthlyRent/projectedRevenue:1;const simplePaybackMonths=Math.max(1,Math.round(startupCost/Math.max(1,projectedRevenue-monthlyRent)));let score=50;if(projectedRevenue>avgMonthlyRevenue)score+=15;if(expectedAppointments>avgMonthlyAppointments)score+=10;if(rentRatio<.12)score+=15;else if(rentRatio>.2)score-=20;if(simplePaybackMonths<=24)score+=10;else if(simplePaybackMonths>48)score-=15;score=clamp(Math.round(score),0,100);return res.json({ok:true,model:"location_expansion_unit_economics_v1",decision_support_only:true,automatic_commitment:false,external_market_data:false,candidate:{name:candidate,expected_monthly_appointments:expectedAppointments,avg_ticket:avgTicket,monthly_rent:monthlyRent,startup_cost:startupCost,projected_monthly_revenue:projectedRevenue,rent_to_revenue_percent:Math.round(rentRatio*1000)/10,simple_payback_months:simplePaybackMonths,expansion_score:score,recommendation:score>=75?"PROCEED_TO_DUE_DILIGENCE":score>=55?"INVESTIGATE":"HOLD"},network_baseline:{locations:rows.length,avg_monthly_revenue:Math.round(avgMonthlyRevenue),avg_monthly_appointments:Math.round(avgMonthlyAppointments)},warning:"Külső demográfia, gyalogosforgalom, versenytársi ár és ingatlanpiaci adat nincs automatikusan bekötve; végső helyszíndöntéshez due diligence szükséges."});}catch(e:any){res.status(500).json({ok:false,error:e?.message||"location_expansion_failed"})}});

export default router;
