import {Router,Response} from 'express';
import pool from '../db';
import type {AuthRequest} from '../middleware/auth';
import {requireManagement} from '../middleware/requireRoles';
const r=Router();r.use(requireManagement);const UUID=/^[0-9a-f]{8}-[0-9a-f-]{27}$/i;const n=(v:unknown)=>String(v||'').trim();
async function tenant(req:AuthRequest,res:Response){const t=n(req.user?.tenant_id);if(!t){res.status(403).json({ok:false,error:'tenant_missing'});return null}return t}
async function schema(){await pool.query(`CREATE TABLE IF NOT EXISTS vir_p15_action_plans(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,location_id uuid,title text NOT NULL,reason text NOT NULL,action_type text NOT NULL,proposal jsonb NOT NULL DEFAULT '{}'::jsonb,status text NOT NULL DEFAULT 'preview',approval_required boolean NOT NULL DEFAULT true,execution_enabled boolean NOT NULL DEFAULT false,created_by uuid,approved_by uuid,created_at timestamptz NOT NULL DEFAULT now(),approved_at timestamptz);CREATE INDEX IF NOT EXISTS vir_p15_action_plan_scope_idx ON vir_p15_action_plans(tenant_id,status,created_at DESC);`)}
r.get('/status',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;await schema();const q=(await pool.query(`SELECT COUNT(*) FILTER(WHERE status='preview')::int preview_plans,COUNT(*) FILTER(WHERE status='approved')::int approved_plans FROM vir_p15_action_plans WHERE tenant_id=$1::uuid`,[t])).rows[0];res.json({ok:true,layer:'executive_autopilot_governance_v4',execution_enabled:false,human_approval_boundary:true,capabilities:{command_center:true,controlled_action_plans:true,approval_register:true,governance_audit:true},counts:q})});
r.get('/command-center',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;await schema();const revenue=(await pool.query(`SELECT COUNT(*) FILTER(WHERE status='no_show' AND start_time>now()-interval '30 days')::int no_shows_30d,COUNT(*) FILTER(WHERE status='cancelled' AND start_time>now()-interval '30 days')::int cancellations_30d,COUNT(*) FILTER(WHERE start_time>now() AND status NOT IN ('cancelled','no_show'))::int future_bookings FROM appointments WHERE tenant_id=$1::uuid`,[t])).rows[0];const journey=(await pool.query(`SELECT (SELECT count(*) FROM vir_ai_handoffs WHERE tenant_id=$1::uuid AND status='open')::int open_handoffs,(SELECT count(*) FROM vir_complaint_cases WHERE tenant_id=$1::uuid AND status='open')::int open_complaints`,[t])).rows[0];const operations=(await pool.query(`SELECT COUNT(*) FILTER(WHERE start_time>=date_trunc('day',now()) AND start_time<date_trunc('day',now())+interval '7 days' AND status NOT IN ('cancelled','no_show'))::int bookings_7d,COUNT(DISTINCT employee_id) FILTER(WHERE start_time>=date_trunc('day',now()) AND start_time<date_trunc('day',now())+interval '7 days' AND status NOT IN ('cancelled','no_show'))::int booked_staff_7d FROM appointments WHERE tenant_id=$1::uuid`,[t])).rows[0];const plans=(await pool.query(`SELECT COUNT(*) FILTER(WHERE status='preview')::int preview,COUNT(*) FILTER(WHERE status='approved')::int approved FROM vir_p15_action_plans WHERE tenant_id=$1::uuid`,[t])).rows[0];const alerts:any[]=[];if(Number(journey.open_complaints)>0)alerts.push({area:'CUSTOMER',priority:'HIGH',signal:'OPEN_COMPLAINTS',value:journey.open_complaints});if(Number(revenue.no_shows_30d)>=5)alerts.push({area:'REVENUE',priority:'HIGH',signal:'NO_SHOWS_30D',value:revenue.no_shows_30d});if(Number(operations.bookings_7d)>Number(operations.booked_staff_7d)*8)alerts.push({area:'OPERATIONS',priority:'MEDIUM',signal:'CAPACITY_PRESSURE',value:operations.bookings_7d});res.json({ok:true,model:'executive_command_center_v4',signals:{revenue,journey,operations,plans},alerts,execution_enabled:false})});
r.post('/action-plans/preview',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;await schema();const title=n(req.body?.title),reason=n(req.body?.reason),actionType=n(req.body?.action_type).toUpperCase();if(!title||!reason||!actionType)return res.status(400).json({ok:false,error:'title, reason és action_type szükséges'});const allowed=['CUSTOMER_RECOVERY','REVENUE_PROTECTION','CAPACITY_ADJUSTMENT','MANAGEMENT_FOLLOWUP'];if(!allowed.includes(actionType))return res.status(400).json({ok:false,error:'unsupported_action_type'});const proposal={...req.body?.proposal,source:'P15_PREVIEW',automatic_execution:false};const row=(await pool.query(`INSERT INTO vir_p15_action_plans(tenant_id,location_id,title,reason,action_type,proposal,approval_required,execution_enabled,created_by) VALUES($1,$2,$3,$4,$5,$6::jsonb,true,false,$7) RETURNING *`,[t,n(req.body?.location_id)||null,title,reason,actionType,JSON.stringify(proposal),req.user?.id||null])).rows[0];res.status(201).json({ok:true,model:'controlled_action_plan_v4',item:row,execution_enabled:false,approval_required:true})});
r.get('/action-plans',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;await schema();const rows=(await pool.query(`SELECT * FROM vir_p15_action_plans WHERE tenant_id=$1::uuid ORDER BY created_at DESC LIMIT 250`,[t])).rows;res.json({ok:true,items:rows})});
r.post('/action-plans/:id/approve',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;await schema();const id=n(req.params.id);if(!UUID.test(id))return res.status(400).json({ok:false,error:'invalid_id'});const row=(await pool.query(`UPDATE vir_p15_action_plans SET status='approved',approved_by=$3,approved_at=now() WHERE id=$1::uuid AND tenant_id=$2::uuid AND status='preview' RETURNING *`,[id,t,req.user?.id||null])).rows[0];if(!row)return res.status(404).json({ok:false,error:'plan_not_found_or_not_preview'});res.json({ok:true,item:row,execution_enabled:false,note:'A jóváhagyás nem hajtja végre az operatív műveletet.'})});
export default r;
