import {Router,Response} from 'express';
import pool from '../db';
import type {AuthRequest} from '../middleware/auth';
import {requireManagement} from '../middleware/requireRoles';
import {actorId,tenantId,UUID,validateLocation} from './virP20P22Shared';
import {buildDigitalTwin,simulateScenario} from './virP23P25Shared';

const router=Router();router.use(requireManagement);
router.get('/status',async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;try{const counts=(await pool.query(`SELECT COUNT(*)::int runs,MAX(created_at) last_run_at FROM vir_p24_scenario_runs WHERE tenant_id=$1::bigint`,[tenant])).rows[0];return res.json({ok:true,model:'what_if_simulator_v1',production_mutation:false,bounded_levers:true,counts});}catch(e:any){return res.status(500).json({ok:false,error:e?.message||'p24_status_failed'});}});
router.post('/simulate',async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;const location=await validateLocation(req.body?.locationId,tenant,res);if(location===undefined)return;try{let twin:any,snapshotId:string|null=null;const requested=String(req.body?.twin_snapshot_id||'').trim();if(requested){if(!UUID.test(requested))return res.status(400).json({ok:false,error:'invalid_twin_snapshot_id'});const row=(await pool.query(`SELECT id,snapshot FROM vir_p23_twin_snapshots WHERE id=$1::uuid AND tenant_id=$2::bigint`,[requested,tenant])).rows[0];if(!row)return res.status(404).json({ok:false,error:'twin_snapshot_not_found'});snapshotId=String(row.id);twin=row.snapshot;}else twin=await buildDigitalTwin(tenant,location);const sim=simulateScenario(twin,req.body?.levers),name=String(req.body?.scenario_name||'Vezetői mi lenne, ha szcenárió').trim().slice(0,180)||'Scenario';const row=(await pool.query(`INSERT INTO vir_p24_scenario_runs(tenant_id,location_id,twin_snapshot_id,scenario_name,levers,baseline,result,confidence,created_by) VALUES($1::bigint,$2::uuid,$3::uuid,$4,$5::jsonb,$6::jsonb,$7::jsonb,$8,$9) RETURNING *`,[tenant,location,snapshotId,name,JSON.stringify(sim.levers),JSON.stringify(sim.baseline),JSON.stringify({...sim.result,delta:sim.delta,assumptions:sim.assumptions}),sim.confidence,actorId(req)])).rows[0];return res.status(201).json({ok:true,item:row,simulation:sim,production_mutation:false});}catch(e:any){return res.status(500).json({ok:false,error:e?.message||'p24_simulation_failed'});}});
router.get('/runs',async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;try{return res.json({ok:true,items:(await pool.query(`SELECT * FROM vir_p24_scenario_runs WHERE tenant_id=$1::bigint ORDER BY created_at DESC LIMIT 100`,[tenant])).rows});}catch(e:any){return res.status(500).json({ok:false,error:e?.message||'p24_runs_failed'});}});
router.get('/runs/:id',async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;const id=String(req.params.id||'');if(!UUID.test(id))return res.status(400).json({ok:false,error:'invalid_scenario_id'});try{const item=(await pool.query(`SELECT * FROM vir_p24_scenario_runs WHERE id=$1::uuid AND tenant_id=$2::bigint`,[id,tenant])).rows[0];if(!item)return res.status(404).json({ok:false,error:'scenario_not_found'});return res.json({ok:true,item});}catch(e:any){return res.status(500).json({ok:false,error:e?.message||'p24_run_failed'});}});
export default router;