import {Router,Response} from "express";
import pool from "../db";
import type {AuthRequest} from "../middleware/auth";
import {requireManagement} from "../middleware/requireRoles";
import {findCalendarGaps,matchWaitlist,upcomingRiskCandidates} from "../booking/virWave1Engine";

const router=Router();
router.use(requireManagement);
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const n=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
const clamp=(v:number,min:number,max:number)=>Math.min(max,Math.max(min,v));
type Scope={tenantId:string;locationId:string|null};

async function scope(req:AuthRequest,res:Response):Promise<Scope|undefined>{const tenantId=String(req.user?.tenant_id||"").trim();if(!tenantId){res.status(403).json({ok:false,error:"A felhasználóhoz nincs tenant rendelve."});return}const requested=String(req.query.locationId||req.body?.locationId||req.query.location_id||req.body?.location_id||"").trim();if(!requested)return{tenantId,locationId:null};if(!UUID.test(requested)){res.status(400).json({ok:false,error:"Érvénytelen telephelyazonosító."});return}const owned=(await pool.query(`SELECT id FROM locations WHERE id=$1::uuid AND tenant_id=$2::uuid`,[requested,tenantId])).rows[0];if(!owned){res.status(403).json({ok:false,error:"A telephely nem tartozik a tenantjához."});return}return{tenantId,locationId:requested}}
async function locations(s:Scope){if(s.locationId)return(await pool.query(`SELECT id::text,name FROM locations WHERE id=$1::uuid AND tenant_id=$2::uuid`,[s.locationId,s.tenantId])).rows;return(await pool.query(`SELECT id::text,name FROM locations WHERE tenant_id=$1::uuid AND active IS DISTINCT FROM false ORDER BY name`,[s.tenantId])).rows}
async function servicesForLocation(locationId:string){return(await pool.query(`SELECT s.id::text,s.name,COALESCE(s.duration_minutes,30)::int duration_minutes,COALESCE(s.promo_price,s.list_price,s.base_price,0)::numeric price FROM services s WHERE COALESCE(s.is_active,true)=true AND (NOT EXISTS(SELECT 1 FROM service_locations sl WHERE sl.service_id=s.id) OR EXISTS(SELECT 1 FROM service_locations sl WHERE sl.service_id=s.id AND sl.location_id=$1::uuid)) ORDER BY s.name`,[locationId])).rows}
function lexicalScore(text:string,name:string){const words=text.toLocaleLowerCase("hu-HU").split(/[^\p{L}\p{N}]+/u).filter(x=>x.length>=3);const target=name.toLocaleLowerCase("hu-HU");return words.reduce((s,w)=>s+(target.includes(w)?2:0),target.includes(text.toLocaleLowerCase("hu-HU").trim())?5:0)}

router.post("/ai-receptionist/preview",async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;const message=String(req.body?.message||"").trim();if(!message)return res.status(400).json({ok:false,error:"Az üzenet nem lehet üres."});const locs=await locations(s);const results=[] as any[];for(const loc of locs.slice(0,8)){const services=await servicesForLocation(String(loc.id));const ranked=services.map((x:any)=>({...x,match_score:lexicalScore(message,String(x.name))})).sort((a:any,b:any)=>b.match_score-a.match_score||n(b.price)-n(a.price)).slice(0,6);const gaps=(await findCalendarGaps(String(loc.id),7)).slice(0,12);results.push({location_id:loc.id,location_name:loc.name,service_candidates:ranked,availability:gaps.map(g=>({employee_id:g.employee_id,employee_name:g.employee_name,start:g.start,end:g.end,minutes:g.minutes,estimated_value:g.estimated_value})).slice(0,8)})}return res.json({ok:true,model:"ai_receptionist_intent_preview_v1",message,channels:{webchat:true,kiosk:true,mobile:true,voice_provider_connected:false,sms_provider_connected:false},preview_only:true,booking_write_enabled:false,automatic_messages:false,results,response_hint:results.length?"Találtam szolgáltatás- és időpontjelölteket. A végleges foglalás előtt vendég- és szolgáltatásmegerősítés szükséges.":"Nem találtam megfelelő jelöltet."});}catch(e:any){res.status(500).json({ok:false,error:e?.message||"ai_receptionist_preview_failed"})}});

router.get("/intelligent-scheduling",async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;const horizon=clamp(Math.round(n(req.query.days)||14),1,31);const locs=await locations(s);const items=[] as any[];for(const loc of locs){const gaps=await findCalendarGaps(String(loc.id),horizon);for(const g of gaps.slice(0,80))items.push({...g,location_name:loc.name,recommendation:g.estimated_value>=20000?"FILL_PRIORITY":g.minutes>=120?"CONSOLIDATE_OR_FILL":"FILL_IF_MATCH",confidence:g.schedule_source==='published_shifts'?"HIGH":"MEDIUM"})}items.sort((a,b)=>n(b.estimated_value)-n(a.estimated_value));return res.json({ok:true,model:"intelligent_scheduling_gap_value_v2",horizon_days:horizon,granularity:"calendar_gap",skill_aware_candidate_stage:true,automatic_schedule_write:false,decision_support_only:true,summary:{opportunities:items.length,estimated_open_capacity_value:items.reduce((a,x)=>a+n(x.estimated_value),0),published_shift_based:items.filter(x=>x.schedule_source==='published_shifts').length},items:items.slice(0,250)});}catch(e:any){res.status(500).json({ok:false,error:e?.message||"intelligent_scheduling_failed"})}});

router.get("/booking-recovery",async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;const days=clamp(Math.round(n(req.query.days)||14),1,31);const locs=await locations(s);const opportunities=[] as any[],risks=[] as any[];for(const loc of locs){const gaps=await findCalendarGaps(String(loc.id),days);const matches=await matchWaitlist(String(loc.id),gaps);for(const g of gaps){const m=matches.find((x:any)=>x.employee_id===g.employee_id&&x.gap_start===g.start);if(m)opportunities.push({location_id:loc.id,location_name:loc.name,gap:g,match:m,recovery_type:"WAITLIST_FILL",estimated_recovered_value:n(m.estimated_value)||n(g.estimated_value)});}for(const r of await upcomingRiskCandidates(String(loc.id),days))risks.push({...r,location_id:loc.id,location_name:loc.name,recovery_type:"NO_SHOW_PREVENTION"});}opportunities.sort((a,b)=>n(b.estimated_recovered_value)-n(a.estimated_recovered_value));risks.sort((a,b)=>n(b.score)-n(a.score));return res.json({ok:true,model:"booking_recovery_waitlist_risk_v1",days,automatic_outreach:false,automatic_rebooking:false,approval_required:true,summary:{waitlist_recovery_opportunities:opportunities.length,estimated_recoverable_value:opportunities.reduce((a,x)=>a+n(x.estimated_recovered_value),0),elevated_no_show_risks:risks.length},opportunities:opportunities.slice(0,150),risk_candidates:risks.slice(0,150)});}catch(e:any){res.status(500).json({ok:false,error:e?.message||"booking_recovery_failed"})}});

router.get("/agent-gateway/capabilities",async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;const locs=await locations(s);return res.json({ok:true,gateway:"kleopatra_booking_agent_gateway_v1",protocol_stage:"authenticated_internal_preview",external_agent_auth_ready:false,public_endpoint_enabled:false,booking_write_enabled:false,capabilities:["list_locations","list_services","read_availability","quote_estimated_value"],future_capabilities:["create_booking","modify_booking","cancel_booking"],locations:locs});}catch(e:any){res.status(500).json({ok:false,error:e?.message||"agent_gateway_failed"})}});
router.get("/agent-gateway/availability",async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;if(!s.locationId)return res.status(400).json({ok:false,error:"Az availability lekérdezéshez locationId szükséges."});const horizon=clamp(Math.round(n(req.query.days)||7),1,14);const services=await servicesForLocation(s.locationId);const gaps=await findCalendarGaps(s.locationId,horizon);return res.json({ok:true,gateway:"kleopatra_booking_agent_gateway_v1",read_only:true,location_id:s.locationId,services:services.slice(0,250),availability:gaps.slice(0,160)});}catch(e:any){res.status(500).json({ok:false,error:e?.message||"agent_availability_failed"})}});

router.get("/external-competitor-intelligence",async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;const exists=Boolean((await pool.query(`SELECT to_regclass('public.vir_external_competitor_observations') IS NOT NULL ok`)).rows[0]?.ok);if(!exists)return res.json({ok:true,model:"external_competitor_adapter_v1",external_data_connected:false,synthetic_data_used:false,items:[],required_fields:["competitor_name","location_text","service_name","price","rating","review_count","observed_at","source_url"],warning:"Külső adatforrás nincs bekötve; a VIR nem gyárt versenytársi tényadatot."});const rows=(await pool.query(`SELECT * FROM vir_external_competitor_observations WHERE tenant_id=$1::uuid AND ($2::uuid IS NULL OR location_id=$2::uuid) ORDER BY observed_at DESC LIMIT 300`,[s.tenantId,s.locationId])).rows;return res.json({ok:true,model:"external_competitor_adapter_v1",external_data_connected:true,synthetic_data_used:false,items:rows});}catch(e:any){res.status(500).json({ok:false,error:e?.message||"external_competitor_failed"})}});

router.post("/consultation/preview",async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;if(!s.locationId)return res.status(400).json({ok:false,error:"A konzultációhoz locationId szükséges."});const concern=String(req.body?.concern||req.body?.style||"").trim();if(!concern)return res.status(400).json({ok:false,error:"Add meg a kívánt stílust vagy kezelési célt."});const services=await servicesForLocation(s.locationId);const suggestions=services.map((x:any)=>({...x,match_score:lexicalScore(concern,String(x.name))})).sort((a:any,b:any)=>b.match_score-a.match_score||n(b.price)-n(a.price)).slice(0,10);return res.json({ok:true,model:"beauty_consultation_catalog_match_v1",concern,medical_advice:false,visualizer:{provider_connected:false,image_generation_enabled:false,consent_required:true,retention_policy_required:true},booking_handoff_ready:true,suggestions,disclaimer:"A javaslat szolgáltatáskatalógus-egyezés, nem diagnózis és nem garantált vizuális eredmény."});}catch(e:any){res.status(500).json({ok:false,error:e?.message||"consultation_preview_failed"})}});

export default router;
