import { Router, Response } from "express";
import pool from "../db";
import type { AuthRequest } from "../middleware/auth";
import { requireManagement } from "../middleware/requireRoles";
import { findCalendarGaps } from "../booking/virWave1Engine";

const router = Router();
router.use(requireManagement);
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const n=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
type Scope={tenantId:string;locationId:string|null};
async function scope(req:AuthRequest,res:Response):Promise<Scope|undefined>{const tenantId=String(req.user?.tenant_id||"").trim();if(!tenantId){res.status(403).json({ok:false,error:"A felhasználóhoz nincs tenant rendelve."});return}const requested=String(req.query.locationId||req.body?.locationId||"").trim();if(!requested)return{tenantId,locationId:null};if(!UUID.test(requested)){res.status(400).json({ok:false,error:"Érvénytelen telephelyazonosító."});return}const owned=(await pool.query(`SELECT id FROM locations WHERE id=$1::uuid AND tenant_id=$2::uuid`,[requested,tenantId])).rows[0];if(!owned){res.status(403).json({ok:false,error:"A telephely nem tartozik a tenantjához."});return}return{tenantId,locationId:requested}}

router.get('/dynamic-offers',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;const rows=(await pool.query(`SELECT c.id::text client_id,COALESCE(c.full_name,'Vendég') client_name,MAX(a.start_time) last_visit,COUNT(DISTINCT a.id)::int visits,COALESCE(SUM(wp.amount),0)::numeric paid_revenue FROM clients c JOIN appointments a ON a.client_id=c.id AND a.tenant_id=$1::uuid LEFT JOIN work_orders w ON w.appointment_id=a.id LEFT JOIN work_order_payments wp ON wp.work_order_id=w.id WHERE ($2::uuid IS NULL OR a.location_id=$2::uuid) GROUP BY c.id,c.full_name ORDER BY last_visit ASC LIMIT 500`,[s.tenantId,s.locationId])).rows;const items=rows.map((r:any)=>{const days=Math.max(0,Math.floor((Date.now()-new Date(r.last_visit).getTime())/86400000));const visits=n(r.visits),revenue=n(r.paid_revenue);const avg=visits?revenue/visits:0;let discount=0,reason='HOLD_PRICE';if(days>=120)discount=15;else if(days>=90)discount=10;else if(days>=60)discount=5;if(visits>=12||avg>=25000)discount=Math.min(discount,5);return{...r,days_since_visit:days,recommended_discount_percent:discount,offer_type:discount?'WIN_BACK':'VALUE_ADD',reason,guardrail:'loyal/high-value clients receive smaller discounts'}});res.json({ok:true,model:'margin_guarded_dynamic_offer_v1',automatic_discount:false,approval_required:true,items})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'dynamic_offer_failed'})}});

router.get('/empty-slot-autopilot',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;if(!s.locationId)return res.status(400).json({ok:false,error:'locationId szükséges.'});const gaps=await findCalendarGaps(s.locationId,2);const reachable=(await pool.query(`SELECT channel,COUNT(DISTINCT client_id)::int clients FROM vir_client_channel_identities WHERE tenant_id=$1::uuid AND location_id=$2::uuid AND active=true AND marketing_consent=true AND opted_out_at IS NULL AND communication_blocked=false GROUP BY channel`,[s.tenantId,s.locationId])).rows;const items=gaps.slice(0,40).map((g:any,i:number)=>({...g,priority_score:Math.max(1,100-i*2),recommended_action:'WAITLIST_THEN_TARGETED_MESSAGE',approval_required:true,automatic_booking:false}));res.json({ok:true,model:'empty_slot_revenue_autopilot_v2',reachable_by_channel:reachable,automatic_send:false,automatic_booking:false,items})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'empty_slot_autopilot_failed'})}});

router.get('/revenue-guard',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;const appt=(await pool.query(`SELECT COUNT(DISTINCT a.id)::int appointments,COALESCE(SUM(aps.price),0)::numeric exposed_value FROM appointments a LEFT JOIN appointment_services aps ON aps.appointment_id=a.id WHERE a.tenant_id=$1::uuid AND a.start_time BETWEEN now() AND now()+interval '14 days' AND ($2::uuid IS NULL OR a.location_id=$2::uuid)`,[s.tenantId,s.locationId])).rows[0];const comm=(await pool.query(`SELECT COALESCE(SUM(cost_amount),0)::numeric communication_cost,COUNT(*)::int touches FROM vir_communication_touches WHERE tenant_id=$1::uuid AND created_at>=now()-interval '30 days' AND ($2::uuid IS NULL OR location_id=$2::uuid)`,[s.tenantId,s.locationId])).rows[0];const paid=(await pool.query(`SELECT COALESCE(SUM(wp.amount),0)::numeric paid_revenue FROM work_order_payments wp JOIN work_orders w ON w.id=wp.work_order_id WHERE w.tenant_id=$1::uuid AND wp.paid_at>=now()-interval '30 days' AND ($2::uuid IS NULL OR w.location_id=$2::uuid)`,[s.tenantId,s.locationId])).rows[0];const cost=n(comm.communication_cost),rev=n(paid.paid_revenue);const alerts:any[]=[];if(cost>0&&rev/cost<3)alerts.push({severity:'warning',type:'COMMUNICATION_ROI',message:'Az elmúlt 30 nap kommunikációs bevétel/költség aránya 3x alatt van.'});if(n(appt.exposed_value)>0)alerts.push({severity:'info',type:'UPCOMING_REVENUE_EXPOSURE',message:`A következő 14 nap foglalási értéke ${Math.round(n(appt.exposed_value))} Ft; no-show és üresedés figyelése javasolt.`});res.json({ok:true,model:'revenue_guard_v1',automatic_intervention:false,summary:{paid_revenue_30d:rev,communication_cost_30d:cost,communication_roas:cost?Math.round(rev/cost*100)/100:null,upcoming_booking_value:n(appt.exposed_value)},alerts})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'revenue_guard_failed'})}});

router.get('/next-best-offers',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;const rows=(await pool.query(`SELECT c.id::text client_id,COALESCE(c.full_name,'Vendég') client_name,MAX(a.start_time) last_visit,COUNT(DISTINCT a.id)::int visits,COALESCE(SUM(wp.amount),0)::numeric paid_revenue FROM clients c JOIN appointments a ON a.client_id=c.id AND a.tenant_id=$1::uuid LEFT JOIN work_orders w ON w.appointment_id=a.id LEFT JOIN work_order_payments wp ON wp.work_order_id=w.id WHERE ($2::uuid IS NULL OR a.location_id=$2::uuid) GROUP BY c.id,c.full_name ORDER BY last_visit ASC LIMIT 300`,[s.tenantId,s.locationId])).rows;const items=[] as any[];for(const r of rows){const identity=(await pool.query(`SELECT channel FROM vir_client_channel_identities WHERE tenant_id=$1::uuid AND client_id=$2::uuid AND active=true AND marketing_consent=true AND opted_out_at IS NULL AND communication_blocked=false ORDER BY last_activity_at DESC NULLS LAST LIMIT 1`,[s.tenantId,r.client_id])).rows[0];const days=Math.floor((Date.now()-new Date(r.last_visit).getTime())/86400000);items.push({...r,days_since_visit:days,recommended_channel:identity?.channel||null,next_best_offer:days>=90?'WIN_BACK_10':days>=45?'REBOOK_VALUE_ADD':'NO_DISCOUNT',timing:days>=90?'today':'next optimal window',approval_required:true,automatic_send:false})}res.json({ok:true,model:'next_best_offer_v1',items})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'next_best_offer_failed'})}});

router.post('/promotion-simulator',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;const audience=Math.max(0,Math.min(100000,Math.round(n(req.body?.audience)||100)));const response=Math.max(0,Math.min(100,n(req.body?.expected_response_percent)||8));const avgTicket=Math.max(0,n(req.body?.avg_ticket)||15000);const discount=Math.max(0,Math.min(80,n(req.body?.discount_percent)||10));const commCost=Math.max(0,n(req.body?.communication_cost)||0);const incrementalBookings=audience*response/100;const grossRevenue=incrementalBookings*avgTicket;const discountCost=grossRevenue*discount/100;const netRevenue=grossRevenue-discountCost-commCost;res.json({ok:true,model:'promotion_profit_simulator_v1',simulation_only:true,automatic_campaign:false,inputs:{audience,expected_response_percent:response,avg_ticket:avgTicket,discount_percent:discount,communication_cost:commCost},result:{incremental_bookings:Math.round(incrementalBookings*10)/10,gross_revenue:Math.round(grossRevenue),discount_cost:Math.round(discountCost),net_revenue_before_variable_service_cost:Math.round(netRevenue)},warning:'Ez bevételi what-if, nem teljes fedezet/EBITDA modell.'})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'promotion_simulator_failed'})}});

export default router;
