import {Router,Response} from "express";
import pool from "../db";
import type {AuthRequest} from "../middleware/auth";
import {requireManagement} from "../middleware/requireRoles";
const router=Router();router.use(requireManagement);const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
async function ensureQueue(){await pool.query(`CREATE TABLE IF NOT EXISTS vir_guest_action_queue(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,location_id uuid,kind text NOT NULL,status text NOT NULL DEFAULT 'pending',payload jsonb NOT NULL DEFAULT '{}'::jsonb,created_by uuid,approved_by uuid,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())`)}
async function resolve(req:AuthRequest,res:Response){const tenantId=String(req.user?.tenant_id||'').trim(),locationId=String(req.body?.locationId||req.query.locationId||'').trim();if(!tenantId){res.status(403).json({ok:false,error:'Tenant hiányzik.'});return null}if(locationId&&!UUID.test(locationId)){res.status(400).json({ok:false,error:'Érvénytelen locationId.'});return null}if(locationId){const row=(await pool.query(`SELECT id FROM locations WHERE id=$1::uuid AND tenant_id=$2::uuid`,[locationId,tenantId])).rows[0];if(!row){res.status(403).json({ok:false,error:'A telephely nem tartozik a tenantjához.'});return null}}return{tenantId,locationId:locationId||null}}
router.get('/integration-status',async(req:AuthRequest,res:Response)=>{const s=await resolve(req,res);if(!s)return;return res.json({ok:true,p6_bound:true,booking_handoff:true,guest_action_queue:true,providers:{email:Boolean(process.env.SMTP_HOST||process.env.RESEND_API_KEY),sms:Boolean(process.env.TWILIO_ACCOUNT_SID||process.env.SMS_PROVIDER_URL),whatsapp:Boolean(process.env.WHATSAPP_ACCESS_TOKEN),voice:Boolean(process.env.TWILIO_ACCOUNT_SID||process.env.VOICE_PROVIDER_URL),competitor_feed:Boolean(process.env.COMPETITOR_FEED_URL),visualizer:Boolean(process.env.BEAUTY_VISUALIZER_URL)},external_execution_requires_provider:true,automatic_booking_write:false})});
router.post('/booking-handoff',async(req:AuthRequest,res:Response)=>{try{const s=await resolve(req,res);if(!s)return;await ensureQueue();const payload=req.body?.payload||{};const kind=String(req.body?.kind||'P6_BOOKING_HANDOFF');const row=(await pool.query(`INSERT INTO vir_guest_action_queue(tenant_id,location_id,kind,status,payload,created_by) VALUES($1::uuid,$2::uuid,$3,'pending',$4::jsonb,$5::uuid) RETURNING *`,[s.tenantId,s.locationId,kind,JSON.stringify(payload),req.user?.id||null])).rows[0];return res.status(201).json({ok:true,p6_bound:true,approval_required:true,booking_created:false,handoff:row})}catch(e:any){return res.status(500).json({ok:false,error:e?.message||'p6_handoff_failed'})}});
export default router;
