import {Router,Response} from 'express';
import pool from '../db';
import type {AuthRequest} from '../middleware/auth';
import {requireManagement} from '../middleware/requireRoles';
const r=Router();r.use(requireManagement);const UUID=/^[0-9a-f]{8}-[0-9a-f-]{27}$/i;const n=(v:unknown)=>String(v||'').trim();
async function tenant(req:AuthRequest,res:Response){const t=n(req.user?.tenant_id);if(!t){res.status(403).json({ok:false,error:'tenant_missing'});return null}return t}
async function owns(t:string,id:string){return Number((await pool.query('SELECT 1 FROM appointments WHERE tenant_id=$1::uuid AND client_id=$2::uuid LIMIT 1',[t,id])).rowCount||0)>0}
r.get('/status',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;const q=(await pool.query(`SELECT COUNT(*) FILTER(WHERE status='no_show' AND start_time>now()-interval '30 days')::int no_shows_30d,COUNT(*) FILTER(WHERE status='cancelled' AND start_time>now()-interval '30 days')::int cancellations_30d,COUNT(*) FILTER(WHERE start_time>now() AND status NOT IN ('cancelled','no_show'))::int future_bookings FROM appointments WHERE tenant_id=$1::uuid`,[t])).rows[0];res.json({ok:true,layer:'revenue_protection_loyalty_v4',automatic_charge:false,automatic_discount:false,capabilities:{deposit_policy_preview:true,loyalty_health:true,save_offer_preview:true},counts:q})});
r.post('/protection/preview',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;const id=n(req.body?.client_id)||null;if(id&&(!UUID.test(id)||!await owns(t,id)))return res.status(403).json({ok:false,error:'client_not_in_tenant'});let hist:any={no_shows:0,cancellations:0,visits:0};if(id)hist=(await pool.query(`SELECT COUNT(*) FILTER(WHERE status='no_show')::int no_shows,COUNT(*) FILTER(WHERE status='cancelled')::int cancellations,COUNT(*) FILTER(WHERE status='completed')::int visits FROM appointments WHERE tenant_id=$1::uuid AND client_id=$2::uuid AND start_time>now()-interval '365 days'`,[t,id])).rows[0];const score=Number(hist.no_shows)*3+Number(hist.cancellations);const rule=score>=6?{deposit_percent:50,cancellation_window_hours:24}:score>=3?{deposit_percent:30,cancellation_window_hours:24}:{deposit_percent:0,cancellation_window_hours:12};res.json({ok:true,model:'revenue_protection_preview_v4',history:hist,recommendation:rule,automatic_charge:false,write_enabled:false,approval_required:true})});
r.get('/loyalty-health/:clientId',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;const id=n(req.params.clientId);if(!UUID.test(id)||!await owns(t,id))return res.status(403).json({ok:false,error:'client_not_in_tenant'});const x=(await pool.query(`SELECT COUNT(*) FILTER(WHERE status='completed' AND start_time>now()-interval '365 days')::int visits_365d,COUNT(*) FILTER(WHERE status='no_show' AND start_time>now()-interval '365 days')::int no_shows_365d,MAX(start_time) FILTER(WHERE start_time<=now()) last_visit,EXISTS(SELECT 1 FROM appointments f WHERE f.tenant_id=$1::uuid AND f.client_id=$2::uuid AND f.start_time>now() AND f.status NOT IN ('cancelled','no_show')) future_booking FROM appointments WHERE tenant_id=$1::uuid AND client_id=$2::uuid`,[t,id])).rows[0];const days=x.last_visit?Math.floor((Date.now()-new Date(x.last_visit).getTime())/86400000):999;const health=Number(x.visits_365d)>=6&&days<90?'LOYAL':days>120?'AT_RISK':'ACTIVE';res.json({ok:true,model:'loyalty_health_v4',health,metrics:{...x,days_since_last_visit:days},automatic_segment_change:false})});
r.post('/save-offer/preview',async(req:AuthRequest,res)=>{const t=await tenant(req,res);if(!t)return;const id=n(req.body?.client_id);if(!UUID.test(id)||!await owns(t,id))return res.status(403).json({ok:false,error:'client_not_in_tenant'});const x=(await pool.query(`SELECT COUNT(*) FILTER(WHERE status='completed')::int visits,MAX(start_time) FILTER(WHERE start_time<=now()) last_visit,COUNT(*) FILTER(WHERE status='no_show' AND start_time>now()-interval '365 days')::int no_shows FROM appointments WHERE tenant_id=$1::uuid AND client_id=$2::uuid`,[t,id])).rows[0];const days=x.last_visit?Math.floor((Date.now()-new Date(x.last_visit).getTime())/86400000):999;const percent=days>180?15:days>120?10:0;res.json({ok:true,model:'save_offer_preview_v4',recommendation:{discount_percent:percent,max_discount_percent:15,reason:percent?`Inaktív vendég: ${days} nap az utolsó látogatás óta.`:'Nincs szükség kedvezményre.'},automatic_discount:false,execution_enabled:false,approval_required:percent>0})});
export default r;
