import {Router,Response} from "express";
import pool from "../db";
import type {AuthRequest} from "../middleware/auth";
import {requireManagement,requireRoles} from "../middleware/requireRoles";
import {findCalendarGaps,matchWaitlist} from "../booking/virWave1Engine";

const router=Router();
const receptionRouter=Router();
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const n=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
type Scope={tenantId:string;locationId:string|null};

async function scope(req:AuthRequest,res:Response):Promise<Scope|undefined>{
  const tenantId=String(req.user?.tenant_id||"").trim();
  if(!tenantId){res.status(403).json({ok:false,error:"A felhasználóhoz nincs tenant rendelve."});return}
  const requested=String(req.query.locationId||req.body?.locationId||req.query.location_id||req.body?.location_id||"").trim();
  if(!requested)return{tenantId,locationId:null};
  if(!UUID.test(requested)){res.status(400).json({ok:false,error:"Érvénytelen telephelyazonosító."});return}
  const owned=(await pool.query(`SELECT id FROM locations WHERE id=$1::uuid AND tenant_id=$2::uuid`,[requested,tenantId])).rows[0];
  if(!owned){res.status(403).json({ok:false,error:"A telephely nem tartozik a tenantjához."});return}
  return{tenantId,locationId:requested};
}

async function ensureSchema(){await pool.query(`
CREATE TABLE IF NOT EXISTS vir_campaigns(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,location_id uuid,name text NOT NULL,objective text,segment_key text,status text NOT NULL DEFAULT 'draft',created_by uuid,approved_by uuid,approved_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS vir_campaign_variants(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),campaign_id uuid NOT NULL REFERENCES vir_campaigns(id) ON DELETE CASCADE,label text NOT NULL,channel text NOT NULL,content text NOT NULL,offer text,cta text,send_window text,weight numeric(6,4) NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS vir_campaign_recipients(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,campaign_id uuid NOT NULL REFERENCES vir_campaigns(id) ON DELETE CASCADE,client_id uuid,variant_id uuid,channel text,action_id uuid,touch_id uuid,status text NOT NULL DEFAULT 'planned',created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE vir_communication_touches ADD COLUMN IF NOT EXISTS campaign_id uuid;
ALTER TABLE vir_communication_touches ADD COLUMN IF NOT EXISTS variant_id uuid;
ALTER TABLE vir_client_channel_identities ADD COLUMN IF NOT EXISTS lawful_basis text;
ALTER TABLE vir_client_channel_identities ADD COLUMN IF NOT EXISTS opted_out_at timestamptz;
ALTER TABLE vir_client_channel_identities ADD COLUMN IF NOT EXISTS communication_blocked boolean NOT NULL DEFAULT false;
ALTER TABLE vir_client_channel_identities ADD COLUMN IF NOT EXISTS block_reason text;
ALTER TABLE vir_client_channel_identities ADD COLUMN IF NOT EXISTS consent_source text;
ALTER TABLE vir_client_channel_identities ADD COLUMN IF NOT EXISTS consent_recorded_at timestamptz;
CREATE INDEX IF NOT EXISTS vir_campaigns_scope_idx ON vir_campaigns(tenant_id,status,created_at DESC);
CREATE INDEX IF NOT EXISTS vir_campaign_recipients_scope_idx ON vir_campaign_recipients(tenant_id,campaign_id,status);
`)}

router.use(requireManagement);

router.get('/campaigns',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const rows=(await pool.query(`SELECT c.*,COUNT(r.id)::int recipients FROM vir_campaigns c LEFT JOIN vir_campaign_recipients r ON r.campaign_id=c.id WHERE c.tenant_id=$1::uuid AND ($2::uuid IS NULL OR c.location_id=$2::uuid) GROUP BY c.id ORDER BY c.created_at DESC LIMIT 200`,[s.tenantId,s.locationId])).rows;res.json({ok:true,approval_flow:'preview_approve_execute',automatic_send:false,items:rows})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'campaign_list_failed'})}});
router.post('/campaigns',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const name=String(req.body?.name||'').trim();if(!name)return res.status(400).json({ok:false,error:'Kampánynév szükséges.'});const row=(await pool.query(`INSERT INTO vir_campaigns(tenant_id,location_id,name,objective,segment_key,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[s.tenantId,s.locationId,name,String(req.body?.objective||''),String(req.body?.segment_key||''),req.user?.id||null])).rows[0];for(const v of Array.isArray(req.body?.variants)?req.body.variants:[]){await pool.query(`INSERT INTO vir_campaign_variants(campaign_id,label,channel,content,offer,cta,send_window,weight) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[row.id,String(v.label||'A'),String(v.channel||'email').toLowerCase(),String(v.content||''),String(v.offer||''),String(v.cta||''),String(v.send_window||''),n(v.weight)||1])}res.status(201).json({ok:true,item:row,automatic_send:false})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'campaign_create_failed'})}});
router.post('/campaigns/:id/preview',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const id=String(req.params.id||'');if(!UUID.test(id))return res.status(400).json({ok:false,error:'Érvénytelen kampányazonosító.'});const c=(await pool.query(`UPDATE vir_campaigns SET status='previewed',updated_at=now() WHERE id=$1 AND tenant_id=$2 RETURNING *`,[id,s.tenantId])).rows[0];if(!c)return res.status(404).json({ok:false,error:'Kampány nem található.'});const variants=(await pool.query(`SELECT * FROM vir_campaign_variants WHERE campaign_id=$1 ORDER BY label`,[id])).rows;res.json({ok:true,preview_only:true,approval_required:true,campaign:c,variants})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'campaign_preview_failed'})}});
router.post('/campaigns/:id/approve',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const id=String(req.params.id||'');const row=(await pool.query(`UPDATE vir_campaigns SET status='approved',approved_by=$3,approved_at=now(),updated_at=now() WHERE id=$1 AND tenant_id=$2 AND status='previewed' RETURNING *`,[id,s.tenantId,req.user?.id||null])).rows[0];if(!row)return res.status(409).json({ok:false,error:'Csak előnézett kampány hagyható jóvá.'});res.json({ok:true,item:row,execute_requires_explicit_call:true})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'campaign_approve_failed'})}});
router.post('/campaigns/:id/execute',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const id=String(req.params.id||'');const campaign=(await pool.query(`SELECT * FROM vir_campaigns WHERE id=$1 AND tenant_id=$2 AND status='approved'`,[id,s.tenantId])).rows[0];if(!campaign)return res.status(409).json({ok:false,error:'Jóváhagyott kampány szükséges.'});const variants=(await pool.query(`SELECT * FROM vir_campaign_variants WHERE campaign_id=$1 ORDER BY label`,[id])).rows;if(!variants.length)return res.status(400).json({ok:false,error:'Legalább egy kampányvariáns szükséges.'});const segment=String(campaign.segment_key||'inactive_60');const days=segment.includes('90')?90:segment.includes('30')?30:60;const clients=(await pool.query(`SELECT c.id::text client_id FROM clients c WHERE EXISTS(SELECT 1 FROM appointments a WHERE a.client_id=c.id AND a.tenant_id=$1::uuid) AND NOT EXISTS(SELECT 1 FROM appointments a2 WHERE a2.client_id=c.id AND a2.tenant_id=$1::uuid AND a2.start_time>=now()-($3::text||' days')::interval) LIMIT 500`,[s.tenantId,s.locationId,days])).rows;let queued=0;for(let i=0;i<clients.length;i++){const clientId=clients[i].client_id;const ids=(await pool.query(`SELECT channel,external_id FROM vir_client_channel_identities WHERE tenant_id=$1 AND client_id=$2 AND active=true AND marketing_consent=true AND opted_out_at IS NULL AND communication_blocked=false ORDER BY CASE channel WHEN 'viber' THEN 1 WHEN 'messenger' THEN 2 WHEN 'push' THEN 3 WHEN 'email' THEN 4 WHEN 'sms' THEN 5 ELSE 9 END LIMIT 1`,[s.tenantId,clientId])).rows[0];if(!ids)continue;const variant=variants.find((v:any)=>v.channel===ids.channel)||variants[i%variants.length];const payload={client_id:clientId,channel:ids.channel,recipient_id:ids.external_id,text:variant.content,campaign_id:id,variant_id:variant.id,purpose:'marketing',campaign_key:`P9:${id}`};const q=(await pool.query(`INSERT INTO vir_guest_action_queue(tenant_id,location_id,kind,status,payload,created_by,approved_by) VALUES($1,$2,'CAMPAIGN_MESSAGE','approved',$3::jsonb,$4,$4) RETURNING id`,[s.tenantId,campaign.location_id,JSON.stringify(payload),req.user?.id||null])).rows[0];await pool.query(`INSERT INTO vir_campaign_recipients(tenant_id,campaign_id,client_id,variant_id,channel,action_id,status) VALUES($1,$2,$3,$4,$5,$6,'approved_queue')`,[s.tenantId,id,clientId,variant.id,ids.channel,q.id]);queued++}await pool.query(`UPDATE vir_campaigns SET status='queued',updated_at=now() WHERE id=$1 AND tenant_id=$2`,[id,s.tenantId]);res.json({ok:true,queued,provider_send_direct:false,p7_guest_action_queue:true,approval_boundary_preserved:true})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'campaign_execute_failed'})}});

router.get('/segments',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const rows=(await pool.query(`WITH v AS(SELECT c.id::text client_id,COALESCE(c.full_name,'Vendég') client_name,MAX(a.start_time) last_visit,COUNT(DISTINCT a.id)::int visits,COALESCE(SUM(wp.amount),0)::numeric paid_revenue FROM clients c JOIN appointments a ON a.client_id=c.id AND a.tenant_id=$1::uuid LEFT JOIN work_orders wo ON wo.appointment_id=a.id LEFT JOIN work_order_payments wp ON wp.work_order_id=wo.id WHERE ($2::uuid IS NULL OR a.location_id=$2::uuid) GROUP BY c.id,c.full_name) SELECT *,EXTRACT(day FROM now()-last_visit)::int days_since_visit FROM v ORDER BY last_visit NULLS FIRST LIMIT 1000`,[s.tenantId,s.locationId])).rows;const items=rows.map((r:any)=>{const d=n(r.days_since_visit),vis=n(r.visits),rev=n(r.paid_revenue);const tags:string[]=[];if(d>=90)tags.push('inactive_90','high_churn_risk');else if(d>=60)tags.push('inactive_60');else if(d>=30)tags.push('inactive_30');if(rev>=300000||vis>=18)tags.push('vip');if(vis>=8&&d<60)tags.push('regular_rebooker');if(vis>=4&&rev/Math.max(vis,1)<12000)tags.push('price_sensitive_proxy');return{...r,segments:tags,price_sensitivity_is_proxy:true}});res.json({ok:true,model:'automatic_guest_segments_v1',items,definitions:{inactive_30:'30+ napja nem járt',inactive_60:'60+ napja nem járt',inactive_90:'90+ napja nem járt',high_churn_risk:'90+ napos recency jelzés',vip:'magas fizetett érték / látogatás',price_sensitive_proxy:'alacsonyabb átlagos fizetett kosár proxy, nem személyiségprofil',regular_rebooker:'gyakori és friss látogató'}})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'segments_failed'})}});

router.get('/channel-optimizer-v2',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const rows=(await pool.query(`SELECT i.client_id::text,i.channel,MAX(i.marketing_consent::int)::int marketing_consent,BOOL_OR(i.communication_blocked) blocked,MAX(i.opted_out_at) opted_out,COUNT(t.id)::int sent,COUNT(t.delivered_at)::int delivered,COUNT(t.read_at)::int read,COUNT(t.clicked_at)::int clicked,COUNT(t.responded_at)::int responded,COALESCE(SUM(t.cost_amount),0)::numeric cost,COUNT(DISTINCT a.id)::int bookings,COALESCE(SUM(wp.amount),0)::numeric paid_revenue FROM vir_client_channel_identities i LEFT JOIN vir_communication_touches t ON t.tenant_id=i.tenant_id AND t.client_id=i.client_id AND t.channel=i.channel AND t.created_at>=now()-interval '180 days' LEFT JOIN appointments a ON a.id=t.booking_id LEFT JOIN work_orders wo ON wo.appointment_id=a.id LEFT JOIN work_order_payments wp ON wp.work_order_id=wo.id WHERE i.tenant_id=$1::uuid AND i.client_id IS NOT NULL AND ($2::uuid IS NULL OR i.location_id=$2::uuid) GROUP BY i.client_id,i.channel ORDER BY i.client_id`,[s.tenantId,s.locationId])).rows;const grouped=new Map<string,any[]>();for(const r of rows){const score=(r.marketing_consent&&!r.blocked&&!r.opted_out)?(n(r.delivered)*2+n(r.read)*3+n(r.clicked)*5+n(r.responded)*8+n(r.bookings)*12+n(r.paid_revenue)/10000-n(r.cost)/10):-999;(grouped.get(r.client_id)||grouped.set(r.client_id,[]).get(r.client_id)!).push({...r,score:Math.round(score*10)/10})}const items=[...grouped.entries()].map(([client_id,channels])=>({client_id,recommended_channel:[...channels].sort((a,b)=>b.score-a.score)[0]?.channel||null,channels:channels.sort((a,b)=>b.score-a.score)}));res.json({ok:true,model:'paid_revenue_engagement_channel_optimizer_v3',signals:['delivery','read','click','response','booking','paid_revenue','cost','consent'],automatic_send:false,items})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'channel_optimizer_failed'})}});

router.get('/conversion-funnel',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const rows=(await pool.query(`SELECT COALESCE(c.name,'Nincs kampány') campaign,COALESCE(t.channel,'unknown') channel,COUNT(t.id)::int messages,COUNT(t.delivered_at)::int delivered,COUNT(t.read_at)::int opened,COUNT(t.clicked_at)::int clicked,COUNT(DISTINCT a.id)::int bookings,COUNT(DISTINCT wo.id)::int work_orders,COALESCE(SUM(wp.amount),0)::numeric paid_revenue FROM vir_communication_touches t LEFT JOIN vir_campaigns c ON c.id=t.campaign_id LEFT JOIN appointments a ON a.id=t.booking_id LEFT JOIN work_orders wo ON wo.appointment_id=a.id LEFT JOIN work_order_payments wp ON wp.work_order_id=wo.id WHERE t.tenant_id=$1::uuid AND ($2::uuid IS NULL OR t.location_id=$2::uuid) GROUP BY c.name,t.channel ORDER BY paid_revenue DESC`,[s.tenantId,s.locationId])).rows;res.json({ok:true,stages:['message','delivered','opened','clicked','booking','work_order','paid'],paid_ledger:true,items:rows})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'funnel_failed'})}});
router.get('/campaign-roi',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const rows=(await pool.query(`SELECT c.id::text campaign_id,c.name,t.channel,COUNT(t.id)::int messages,COALESCE(SUM(t.cost_amount),0)::numeric communication_cost,COUNT(DISTINCT a.id)::int bookings,COALESCE(SUM(wp.amount),0)::numeric paid_revenue FROM vir_campaigns c LEFT JOIN vir_communication_touches t ON t.campaign_id=c.id LEFT JOIN appointments a ON a.id=t.booking_id LEFT JOIN work_orders wo ON wo.appointment_id=a.id LEFT JOIN work_order_payments wp ON wp.work_order_id=wo.id WHERE c.tenant_id=$1::uuid AND ($2::uuid IS NULL OR c.location_id=$2::uuid) GROUP BY c.id,c.name,t.channel ORDER BY paid_revenue DESC`,[s.tenantId,s.locationId])).rows.map((r:any)=>({...r,roi:n(r.communication_cost)>0?Math.round((n(r.paid_revenue)-n(r.communication_cost))/n(r.communication_cost)*1000)/10:null,revenue_per_message:n(r.messages)?Math.round(n(r.paid_revenue)/n(r.messages)):0}));res.json({ok:true,paid_ledger:true,items:rows})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'roi_failed'})}});

router.get('/next-best-actions',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const rows=(await pool.query(`SELECT c.id::text client_id,COALESCE(c.full_name,'Vendég') client_name,MAX(a.start_time) last_visit,COUNT(DISTINCT a.id)::int visits,COALESCE(SUM(wp.amount),0)::numeric paid_revenue FROM clients c JOIN appointments a ON a.client_id=c.id AND a.tenant_id=$1::uuid LEFT JOIN work_orders wo ON wo.appointment_id=a.id LEFT JOIN work_order_payments wp ON wp.work_order_id=wo.id WHERE ($2::uuid IS NULL OR a.location_id=$2::uuid) GROUP BY c.id,c.full_name ORDER BY last_visit ASC LIMIT 300`,[s.tenantId,s.locationId])).rows;const items=[] as any[];for(const r of rows){const identity=(await pool.query(`SELECT channel FROM vir_client_channel_identities WHERE tenant_id=$1 AND client_id=$2 AND active=true AND marketing_consent=true AND opted_out_at IS NULL AND communication_blocked=false ORDER BY last_activity_at DESC NULLS LAST LIMIT 1`,[s.tenantId,r.client_id])).rows[0];const days=Math.floor((Date.now()-new Date(r.last_visit).getTime())/86400000);items.push({...r,recommended_channel:identity?.channel||null,action:days>=90?'WIN_BACK':days>=45?'REBOOK_REMINDER':'SERVICE_RECOMMENDATION',offer:days>=90?'Személyre szabott visszatérő ajánlat':'Következő időpont ajánlása',timing:days>=90?'ma':'következő optimális idősáv',rationale:`${days} nap telt el az utolsó látogatás óta`,approval_required:true,automatic_send:false})}res.json({ok:true,model:'next_best_guest_action_v1',items})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'next_best_action_failed'})}});

router.get('/ab-tests',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const rows=(await pool.query(`SELECT c.name campaign,v.label variant,v.channel,COUNT(t.id)::int messages,COUNT(t.clicked_at)::int clicks,COUNT(DISTINCT a.id)::int bookings,COALESCE(SUM(wp.amount),0)::numeric paid_revenue FROM vir_campaign_variants v JOIN vir_campaigns c ON c.id=v.campaign_id LEFT JOIN vir_communication_touches t ON t.variant_id=v.id LEFT JOIN appointments a ON a.id=t.booking_id LEFT JOIN work_orders wo ON wo.appointment_id=a.id LEFT JOIN work_order_payments wp ON wp.work_order_id=wo.id WHERE c.tenant_id=$1::uuid AND ($2::uuid IS NULL OR c.location_id=$2::uuid) GROUP BY c.name,v.id,v.label,v.channel ORDER BY c.name,paid_revenue DESC`,[s.tenantId,s.locationId])).rows;res.json({ok:true,comparison_basis:'paid_revenue',dimensions:['copy','offer','cta','timing','channel'],items:rows})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'ab_test_failed'})}});

router.get('/attribution-v3',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const rows=(await pool.query(`WITH paid AS(SELECT wo.appointment_id,wp.amount,wp.created_at paid_at,a.client_id FROM work_order_payments wp JOIN work_orders wo ON wo.id=wp.work_order_id JOIN appointments a ON a.id=wo.appointment_id WHERE a.tenant_id=$1::uuid AND ($2::uuid IS NULL OR a.location_id=$2::uuid)), eligible AS(SELECT p.appointment_id,p.amount,p.paid_at,t.id touch_id,t.channel,t.campaign_id,COUNT(*) OVER(PARTITION BY p.appointment_id,p.paid_at) touch_count FROM paid p JOIN vir_communication_touches t ON t.tenant_id=$1::uuid AND t.client_id=p.client_id AND t.created_at BETWEEN p.paid_at-interval '14 days' AND p.paid_at) SELECT channel,campaign_id::text,COUNT(DISTINCT touch_id)::int touches,COALESCE(SUM(amount/NULLIF(touch_count,0)),0)::numeric attributed_paid_revenue FROM eligible GROUP BY channel,campaign_id ORDER BY attributed_paid_revenue DESC`,[s.tenantId,s.locationId])).rows;res.json({ok:true,model:'multi_touch_linear_paid_ledger_attribution_v3',attribution_window_days:14,paid_ledger:true,causality_claim:false,method:'linear_equal_credit',items:rows})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'attribution_v3_failed'})}});

router.get('/suggestions',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;if(!s.locationId)return res.status(400).json({ok:false,error:'Kampányjavaslathoz locationId szükséges.'});await ensureSchema();const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);const date=tomorrow.toISOString().slice(0,10);const gaps=await findCalendarGaps(s.locationId,date,{minMinutes:30});const reachable=(await pool.query(`SELECT channel,COUNT(DISTINCT client_id)::int clients FROM vir_client_channel_identities WHERE tenant_id=$1 AND location_id=$2 AND active=true AND marketing_consent=true AND opted_out_at IS NULL AND communication_blocked=false GROUP BY channel ORDER BY clients DESC`,[s.tenantId,s.locationId])).rows;res.json({ok:true,model:'empty_slot_campaign_suggestion_v1',date,gaps:gaps.slice(0,20),reachable_by_channel:reachable,suggestion:gaps.length?`Holnap ${gaps.length} értékesíthető üres idősáv látszik. A releváns, hozzájárulással rendelkező vendégek csatornánként elérhetők.`:'Nincs jelentős üres idősáv-jelzés.',automatic_send:false,approval_required:true})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'suggestions_failed'})}});

router.get('/compliance',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const rows=(await pool.query(`SELECT i.id::text,i.client_id::text,i.channel,i.display_name,i.transactional_consent,i.marketing_consent,i.lawful_basis,i.opted_out_at,i.communication_blocked,i.block_reason,i.consent_source,i.consent_recorded_at,i.active FROM vir_client_channel_identities i WHERE i.tenant_id=$1::uuid AND ($2::uuid IS NULL OR i.location_id=$2::uuid) ORDER BY i.updated_at DESC LIMIT 1000`,[s.tenantId,s.locationId])).rows;res.json({ok:true,marketing_requires_consent:true,blocked_overrides_consent:true,items:rows})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'compliance_failed'})}});
router.patch('/compliance/:id',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;await ensureSchema();const id=String(req.params.id||'');if(!UUID.test(id))return res.status(400).json({ok:false,error:'Érvénytelen identity id.'});const row=(await pool.query(`UPDATE vir_client_channel_identities SET transactional_consent=COALESCE($3,transactional_consent),marketing_consent=COALESCE($4,marketing_consent),lawful_basis=COALESCE($5,lawful_basis),communication_blocked=COALESCE($6,communication_blocked),block_reason=COALESCE($7,block_reason),opted_out_at=CASE WHEN $8::boolean=true THEN now() WHEN $8::boolean=false THEN NULL ELSE opted_out_at END,consent_source=COALESCE($9,consent_source),consent_recorded_at=CASE WHEN $3 IS NOT NULL OR $4 IS NOT NULL THEN now() ELSE consent_recorded_at END,updated_at=now() WHERE id=$1 AND tenant_id=$2 RETURNING *`,[id,s.tenantId,req.body?.transactional_consent,req.body?.marketing_consent,req.body?.lawful_basis,req.body?.communication_blocked,req.body?.block_reason,req.body?.opted_out,req.body?.consent_source])).rows[0];if(!row)return res.status(404).json({ok:false,error:'Identity nem található.'});res.json({ok:true,item:row})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'compliance_update_failed'})}});

receptionRouter.use(requireRoles('admin','manager','receptionist'));
receptionRouter.get('/guest-actions',async(req:AuthRequest,res:Response)=>{try{const s=await scope(req,res);if(!s)return;if(!s.locationId)return res.status(400).json({ok:false,error:'A recepciós vendégakciókhoz locationId szükséges.'});await ensureSchema();const date=new Date().toISOString().slice(0,10);const gaps=await findCalendarGaps(s.locationId,date,{minMinutes:30});const waitlist=await matchWaitlist(s.locationId,date,{limit:50});const handoffs=(await pool.query(`SELECT c.id::text conversation_id,c.channel,c.subject,c.status,c.updated_at FROM vir_conversations c WHERE c.tenant_id=$1 AND c.location_id=$2 AND c.status IN('human_handoff','open') ORDER BY c.updated_at DESC LIMIT 30`,[s.tenantId,s.locationId])).rows;const approved=(await pool.query(`SELECT id::text,kind,status,payload,created_at FROM vir_guest_action_queue WHERE tenant_id=$1 AND location_id=$2 AND status IN('approved','pending') ORDER BY created_at DESC LIMIT 50`,[s.tenantId,s.locationId])).rows;res.json({ok:true,role_surface:'reception_daily_assist',management_campaign_controls:false,automatic_send:false,summary:{gaps:gaps.length,waitlist_candidates:waitlist.length,handoffs:handoffs.length,approved_or_pending_actions:approved.length},gaps:gaps.slice(0,20),waitlist:waitlist.slice(0,30),handoffs,approved_actions:approved,help:['Üres idősáv visszatöltése','Várólistás vendég ajánlása','Jóváhagyott kommunikáció követése','Emberi handoff átvétele']})}catch(e:any){res.status(500).json({ok:false,error:e?.message||'reception_guest_actions_failed'})}});

export {receptionRouter as virReceptionGuestActionsRouter};
export default router;
