import { Router, Response } from "express";
import pool from "../db";
import type { AuthRequest } from "../middleware/auth";
import { requireManagement } from "../middleware/requireRoles";
import { UUID,actorId,clamp,parseObservationDays,safeRows,tenantId } from "./virP20P22Shared";

const router=Router();
router.use(requireManagement);

async function windowKpis(tenant:string,location:string|null,endAt:string|Date,days:number){
  const row=(await safeRows(`SELECT COUNT(DISTINCT a.id)::int bookings,COALESCE(SUM(CASE WHEN a.status NOT IN ('cancelled','no_show') THEN COALESCE(aps.price,0) ELSE 0 END),0)::numeric revenue,COUNT(DISTINCT a.id) FILTER(WHERE a.status='no_show')::int no_shows,COUNT(DISTINCT a.id) FILTER(WHERE a.status='cancelled')::int cancellations FROM appointments a LEFT JOIN appointment_services aps ON aps.appointment_id=a.id WHERE a.tenant_id::text=$1 AND ($2::uuid IS NULL OR a.location_id=$2::uuid) AND a.start_time<$3::timestamptz AND a.start_time>=$3::timestamptz-($4::text||' days')::interval`,[tenant,location,endAt,String(days)]))[0]||{};
  const bookings=Number(row.bookings||0),noShows=Number(row.no_shows||0);return {days,bookings,revenue:Number(row.revenue||0),no_shows:noShows,cancellations:Number(row.cancellations||0),no_show_percent:bookings?Number((noShows/bookings*100).toFixed(3)):0};
}
function pct(after:number,before:number){if(Math.abs(before)<0.0001)return after>0?100:0;return (after-before)/Math.abs(before)*100;}
function outcomeScore(operationType:string,baseline:any,outcome:any){
  const revenue=pct(outcome.revenue,baseline.revenue),bookings=pct(outcome.bookings,baseline.bookings),noShow=baseline.no_show_percent-outcome.no_show_percent;
  let score=0.45*revenue+0.35*bookings+0.20*noShow*4;
  if(operationType==='customer_retention_review')score=0.25*revenue+0.20*bookings+0.55*noShow*5;
  if(operationType==='staffing_review'||operationType==='capacity_review')score=0.30*revenue+0.50*bookings+0.20*noShow*3;
  return {score:clamp(score,-100,100),revenue_change_percent:revenue,booking_change_percent:bookings,no_show_improvement_points:noShow};
}
async function startCycle(tenant:string,decisionId:string,observationDays:7|14|30,actor:string){
  const decision=(await pool.query(`SELECT d.*,o.status operation_status,o.executed_at,o.verified_at FROM vir_p21_decisions d JOIN vir_p17_operations o ON o.id=d.promoted_operation_id AND o.tenant_id=d.tenant_id WHERE d.id=$1::uuid AND d.tenant_id=$2::bigint AND d.status='promoted'`,[decisionId,tenant])).rows[0];
  if(!decision)return {error:"promoted_decision_not_found"};
  if(!['executed','verified'].includes(String(decision.operation_status)))return {error:"p17_operation_not_executed",operation_status:decision.operation_status};
  const anchor=decision.executed_at||decision.verified_at||new Date().toISOString(),baseline=await windowKpis(tenant,decision.location_id,anchor,observationDays);
  const row=(await pool.query(`INSERT INTO vir_p22_cycles(tenant_id,location_id,decision_id,operation_id,operation_type,objective,observation_days,baseline,created_by) VALUES($1::bigint,$2::uuid,$3::uuid,$4::uuid,$5,$6,$7,$8::jsonb,$9) ON CONFLICT (tenant_id,operation_id) WHERE status='observing' DO UPDATE SET observation_days=EXCLUDED.observation_days,baseline=EXCLUDED.baseline,updated_at=now() RETURNING *`,[tenant,decision.location_id,decision.id,decision.promoted_operation_id,decision.operation_type,'balanced_growth',observationDays,JSON.stringify(baseline),actor])).rows[0];return {row};
}

router.get("/status",async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;try{const counts=(await pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='observing')::int observing,COUNT(*) FILTER(WHERE status='evaluated')::int evaluated,COUNT(*) FILTER(WHERE outcome_class='positive')::int positive FROM vir_p22_cycles WHERE tenant_id=$1::bigint`,[tenant])).rows[0];return res.json({ok:true,model:"closed_loop_governed_optimization_v1",feeds_next_p21_decisions:true,requires_verified_p17_outcomes:true,automatic_external_execution:false,autonomous_policy_mutation:false,counts});}catch(error:any){return res.status(500).json({ok:false,error:error?.message||"p22_status_failed"});}});
router.get("/cycles",async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;try{return res.json({ok:true,items:(await pool.query(`SELECT c.*,d.title decision_title,o.status operation_status,o.executed_at,o.verified_at FROM vir_p22_cycles c JOIN vir_p21_decisions d ON d.id=c.decision_id JOIN vir_p17_operations o ON o.id=c.operation_id WHERE c.tenant_id=$1::bigint ORDER BY c.created_at DESC LIMIT 200`,[tenant])).rows});}catch(error:any){return res.status(500).json({ok:false,error:error?.message||"p22_cycles_failed"});}});
router.post("/cycles/start",async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;const id=String(req.body?.decision_id||"");if(!UUID.test(id))return res.status(400).json({ok:false,error:"invalid_decision_id"});try{const result=await startCycle(tenant,id,parseObservationDays(req.body?.observation_days),actorId(req));if(result.error)return res.status(409).json({ok:false,...result});return res.status(201).json({ok:true,item:result.row,learning_enabled:true,automatic_external_execution:false});}catch(error:any){return res.status(500).json({ok:false,error:error?.message||"p22_start_failed"});}});
router.post("/sync",async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;try{const rows=await safeRows(`SELECT d.id FROM vir_p21_decisions d JOIN vir_p17_operations o ON o.id=d.promoted_operation_id AND o.tenant_id=d.tenant_id LEFT JOIN vir_p22_cycles c ON c.operation_id=o.id AND c.tenant_id=d.tenant_id AND c.status='observing' WHERE d.tenant_id=$1::bigint AND d.status='promoted' AND o.status IN ('executed','verified') AND c.id IS NULL ORDER BY d.decided_at DESC LIMIT 50`,[tenant]),items=[] as any[];for(const x of rows){const r=await startCycle(tenant,String(x.id),7,actorId(req));if(r.row)items.push(r.row);}return res.json({ok:true,created:items.length,items,external_side_effects:false});}catch(error:any){return res.status(500).json({ok:false,error:error?.message||"p22_sync_failed"});}});
router.post("/cycles/:id/evaluate",async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;const id=String(req.params.id||"");if(!UUID.test(id))return res.status(400).json({ok:false,error:"invalid_cycle_id"});try{const cycle=(await pool.query(`SELECT c.*,o.executed_at,o.verified_at,o.status operation_status FROM vir_p22_cycles c JOIN vir_p17_operations o ON o.id=c.operation_id AND o.tenant_id=c.tenant_id WHERE c.id=$1::uuid AND c.tenant_id=$2::bigint`,[id,tenant])).rows[0];if(!cycle)return res.status(404).json({ok:false,error:"cycle_not_found"});if(cycle.status!=='observing')return res.status(409).json({ok:false,error:"cycle_already_closed",status:cycle.status});if(cycle.operation_status!=='verified')return res.status(409).json({ok:false,error:"p17_operation_must_be_verified",operation_status:cycle.operation_status});const anchor=new Date(cycle.executed_at||cycle.created_at).getTime(),elapsed=(Date.now()-anchor)/86400000;if(elapsed<1&&!req.body?.allow_early_evaluation)return res.status(409).json({ok:false,error:"insufficient_observation",elapsed_days:Number(elapsed.toFixed(3)),minimum_days:1});const days=Number(cycle.observation_days||7),outcome=await windowKpis(tenant,cycle.location_id,new Date().toISOString(),days),scored=outcomeScore(String(cycle.operation_type),cycle.baseline||{},outcome),klass=scored.score>=5?'positive':scored.score<=-5?'negative':'neutral',payload={...outcome,...scored,elapsed_days:Number(elapsed.toFixed(3)),evaluation_note:"observational before/after signal; not causal proof"},row=(await pool.query(`UPDATE vir_p22_cycles SET outcome=$3::jsonb,optimization_score=$4,outcome_class=$5,status='evaluated',evaluated_by=$6,evaluated_at=now(),updated_at=now() WHERE id=$1::uuid AND tenant_id=$2::bigint RETURNING *`,[id,tenant,JSON.stringify(payload),scored.score,klass,actorId(req)])).rows[0];return res.json({ok:true,item:row,feedback_to_p21:true,automatic_external_execution:false});}catch(error:any){return res.status(500).json({ok:false,error:error?.message||"p22_evaluate_failed"});}});
router.get("/policy",async(req:AuthRequest,res:Response)=>{const tenant=tenantId(req,res);if(!tenant)return;try{const rows=(await pool.query(`SELECT operation_type,COUNT(*)::int samples,ROUND(AVG(optimization_score)::numeric,3) avg_score,ROUND((COUNT(*) FILTER(WHERE outcome_class='positive')::numeric/NULLIF(COUNT(*),0)),4) positive_rate,MAX(evaluated_at) last_evaluated_at FROM vir_p22_cycles WHERE tenant_id=$1::bigint AND status='evaluated' GROUP BY operation_type ORDER BY avg_score DESC NULLS LAST`,[tenant])).rows;return res.json({ok:true,policy:"evidence_weighted_feedback_v1",items:rows,note:"P22 adjusts P21 recommendation scores only; it does not bypass P17 approval."});}catch(error:any){return res.status(500).json({ok:false,error:error?.message||"p22_policy_failed"});}});

export default router;
