import {Router} from 'express';
import type {AuthRequest} from '../middleware/auth';
import db from '../db';
import {clientBrief,ensureVirWave2Schema,loadRecipes,processWorkflowEvents,profitEngine,replaceRecipe,startVirWorkflowWorker} from '../services/virWave2Engine';

const router=Router();
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const uuid=(v:unknown)=>{const s=String(v||'').trim();return UUID_RE.test(s)?s:null};
const actor=(req:AuthRequest)=>req.user?.email||String(req.user?.id||'management');

router.use(async(_req,res,next)=>{try{await ensureVirWave2Schema();next()}catch(e:any){res.status(500).json({error:'A VIR II. hullám adatmodellje nem inicializálható.',detail:e?.message||String(e)})}});
startVirWorkflowWorker();

router.get('/profit',async(req:AuthRequest,res)=>{try{const locationId=uuid(req.query.location_id);const result=await profitEngine({locationId,from:String(req.query.from||''),to:String(req.query.to||''),targetMargin:Number(req.query.target_margin||35)});res.json({wave:2,engine:'profit',...result})}catch(e:any){res.status(500).json({error:'A Profit Engine számítása sikertelen.',detail:e?.message||String(e)})}});

router.get('/recipes',async(req:AuthRequest,res)=>{try{res.json({recipes:await loadRecipes(uuid(req.query.service_id),uuid(req.query.location_id))})}catch(e:any){res.status(500).json({error:'A szolgáltatás-receptúrák nem tölthetők be.',detail:e?.message||String(e)})}});
router.put('/recipes/:serviceId',async(req:AuthRequest,res)=>{try{const serviceId=String(req.params.serviceId||'');const recipes=await replaceRecipe(serviceId,Array.isArray(req.body?.materials)?req.body.materials:[],actor(req));res.json({ok:true,service_id:serviceId,recipes})}catch(e:any){res.status(e?.status||500).json({error:e?.message||'A receptúra nem menthető.'})}});
router.get('/consumption/:workOrderId',async(req:AuthRequest,res)=>{const id=uuid(req.params.workOrderId);if(!id)return res.status(400).json({error:'Érvénytelen munkalapazonosító.'});try{const {rows}=await db.query(`SELECT m.id,m.product_id::text,p.name product_name,m.quantity::numeric,m.balance_after::numeric,m.unit_cost::numeric,m.stock_value_after::numeric,m.created_at,m.note FROM inventory_movements m JOIN products p ON p.id=m.product_id WHERE m.work_order_id=$1::uuid AND m.movement_type='work_order_consumption' ORDER BY m.created_at,m.id`,[id]);const wo=(await db.query(`SELECT id::text,work_order_number,status,stock_consumed_at FROM work_orders WHERE id=$1::uuid`,[id])).rows[0];res.json({work_order:wo||null,consumption:rows,idempotent:Boolean(wo?.stock_consumed_at)})}catch(e:any){res.status(500).json({error:'A készletfogyási bizonyíték nem tölthető be.',detail:e?.message||String(e)})}});

router.get('/client-brief/:clientId',async(req:AuthRequest,res)=>{try{res.json(await clientBrief(String(req.params.clientId||''),String(req.query.force_ai||'')==='1'))}catch(e:any){res.status(e?.status||500).json({error:e?.message||'A Client Brief nem készíthető el.'})}});

router.get('/workflows',async(req:AuthRequest,res)=>{try{const locationId=uuid(req.query.location_id);const {rows}=await db.query(`SELECT * FROM vir_workflow_rules WHERE ($1::uuid IS NULL OR location_id=$1::uuid OR location_id IS NULL) ORDER BY active DESC,updated_at DESC`,[locationId]);res.json({rules:rows})}catch(e:any){res.status(500).json({error:'A workflow szabályok nem tölthetők be.',detail:e?.message||String(e)})}});
router.post('/workflows',async(req:AuthRequest,res)=>{const b=req.body||{},name=String(b.name||'').trim(),eventKey=String(b.event_key||'').trim();if(!name||!eventKey)return res.status(400).json({error:'Név és event_key szükséges.'});const mode=String(b.mode||'advisory');if(!['advisory','assisted'].includes(mode))return res.status(400).json({error:'A workflow mód advisory vagy assisted lehet.'});try{const row=(await db.query(`INSERT INTO vir_workflow_rules(name,event_key,active,mode,conditions,actions,cooldown_minutes,location_id,created_by,updated_by) VALUES($1,$2,$3,$4,$5::jsonb,$6::jsonb,$7,$8::uuid,$9,$9) RETURNING *`,[name,eventKey,b.active!==false,mode,JSON.stringify(b.conditions&&typeof b.conditions==='object'?b.conditions:{}),JSON.stringify(Array.isArray(b.actions)?b.actions:[]),Math.max(0,Math.min(525600,Math.round(Number(b.cooldown_minutes||0)))),uuid(b.location_id),actor(req)])).rows[0];res.status(201).json({ok:true,rule:row})}catch(e:any){res.status(500).json({error:'A workflow szabály nem hozható létre.',detail:e?.message||String(e)})}});
router.patch('/workflows/:id',async(req:AuthRequest,res)=>{const id=uuid(req.params.id);if(!id)return res.status(400).json({error:'Érvénytelen workflow azonosító.'});try{const before=(await db.query(`SELECT * FROM vir_workflow_rules WHERE id=$1::uuid`,[id])).rows[0];if(!before)return res.status(404).json({error:'A workflow nem található.'});const b=req.body||{};const mode=b.mode===undefined?before.mode:String(b.mode);if(!['advisory','assisted'].includes(mode))return res.status(400).json({error:'Érvénytelen workflow mód.'});const row=(await db.query(`UPDATE vir_workflow_rules SET name=$2,event_key=$3,active=$4,mode=$5,conditions=$6::jsonb,actions=$7::jsonb,cooldown_minutes=$8,location_id=$9::uuid,updated_by=$10,updated_at=now() WHERE id=$1::uuid RETURNING *`,[id,String(b.name??before.name).trim(),String(b.event_key??before.event_key).trim(),b.active===undefined?before.active:Boolean(b.active),mode,JSON.stringify(b.conditions??before.conditions??{}),JSON.stringify(b.actions??before.actions??[]),Math.max(0,Math.min(525600,Math.round(Number(b.cooldown_minutes??before.cooldown_minutes??0)))),b.location_id===undefined?before.location_id:uuid(b.location_id),actor(req)])).rows[0];res.json({ok:true,rule:row})}catch(e:any){res.status(500).json({error:'A workflow nem módosítható.',detail:e?.message||String(e)})}});
router.post('/workflows/process',async(req:AuthRequest,res)=>{try{res.json({ok:true,...await processWorkflowEvents(Number(req.body?.limit||80))})}catch(e:any){res.status(500).json({error:'A workflow események feldolgozása sikertelen.',detail:e?.message||String(e)})}});
router.get('/workflow-events',async(req:AuthRequest,res)=>{try{const status=String(req.query.status||'').trim(),locationId=uuid(req.query.location_id);const {rows}=await db.query(`SELECT * FROM vir_workflow_events WHERE ($1='' OR status=$1) AND ($2::uuid IS NULL OR location_id=$2::uuid) ORDER BY created_at DESC LIMIT 200`,[status,locationId]);res.json({events:rows})}catch(e:any){res.status(500).json({error:'A workflow eseménynapló nem tölthető be.',detail:e?.message||String(e)})}});
router.get('/workflow-actions',async(req:AuthRequest,res)=>{try{const status=String(req.query.status||'').trim(),locationId=uuid(req.query.location_id);const {rows}=await db.query(`SELECT a.*,r.name rule_name,e.event_key FROM vir_workflow_actions a JOIN vir_workflow_rules r ON r.id=a.rule_id JOIN vir_workflow_events e ON e.id=a.event_id WHERE ($1='' OR a.status=$1) AND ($2::uuid IS NULL OR a.location_id=$2::uuid) ORDER BY a.created_at DESC LIMIT 200`,[status,locationId]);res.json({actions:rows})}catch(e:any){res.status(500).json({error:'A workflow akciók nem tölthetők be.',detail:e?.message||String(e)})}});

export default router;
