import {Router} from'express';
import db from'../db';
const router=Router();
const STATUSES=new Set(['waiting','arrived','in_progress','completed','cancelled','no_show']);
const statusOf=(v:any,f='arrived')=>{const s=String(v??f).trim().toLowerCase();return STATUSES.has(s)?s:null};
const NEXT:Record<string,Set<string>>={waiting:new Set(['arrived','in_progress','cancelled','no_show']),arrived:new Set(['in_progress','cancelled','no_show']),in_progress:new Set(['cancelled']),completed:new Set(),cancelled:new Set(),no_show:new Set()};

router.get('/',async(req,res,next)=>{try{const locationId=String(req.query.location_id||'').trim();const hasView=(await db.query(`SELECT to_regclass('public.v_work_orders_list') IS NOT NULL ok`)).rows[0]?.ok;const sql=hasView?`SELECT v.*,w.work_order_number,w.locked_at,w.archived_at,w.archive_hash,w.location_id,w.appointment_id FROM v_work_orders_list v JOIN work_orders w ON w.id=v.id WHERE ($1::text='' OR w.location_id::text=$1) ORDER BY v.created_at DESC`:`SELECT w.* FROM work_orders w WHERE ($1::text='' OR w.location_id::text=$1) ORDER BY w.created_at DESC`;const{rows}=await db.query(sql,[locationId]);res.json(rows)}catch(e){next(e)}});
router.get('/:id/archive',async(req,res,next)=>{try{const{rows}=await db.query(`SELECT id,work_order_id,work_order_number,archived_at,terminal_status,snapshot,snapshot_hash FROM work_order_archive WHERE work_order_id=$1::uuid`,[req.params.id]);if(!rows[0])return res.status(404).json({message:'Ehhez a munkalaphoz még nincs lezárt archív példány.'});res.json(rows[0])}catch(e){next(e)}});
router.get('/:id',async(req,res,next)=>{try{const hasView=(await db.query(`SELECT to_regclass('public.v_work_order_details') IS NOT NULL ok`)).rows[0]?.ok;let header:any;if(hasView)header=(await db.query(`SELECT v.*,w.work_order_number,w.source_created_at,w.source_snapshot,w.locked_at,w.locked_reason,w.archived_at,w.archive_hash,w.location_id,w.appointment_id,w.client_id FROM v_work_order_details v JOIN work_orders w ON w.id=v.id WHERE v.id=$1::uuid`,[req.params.id])).rows[0];else header=(await db.query(`SELECT * FROM work_orders WHERE id=$1::uuid`,[req.params.id])).rows[0];if(!header)return res.status(404).json({message:'A munkalap nem található'});const items=(await db.query(`SELECT * FROM work_order_items WHERE work_order_id=$1::uuid ORDER BY created_at`,[req.params.id])).rows;const payments=(await db.query(`SELECT * FROM work_order_payments WHERE work_order_id=$1::uuid ORDER BY paid_at`,[req.params.id]).catch(()=>({rows:[]} as any))).rows;res.json({...header,items,payments})}catch(e){next(e)}});
router.patch('/:id/lifecycle',async(req,res,next)=>{try{const st=statusOf(req.body?.status,'');if(!st)return res.status(400).json({message:'Érvénytelen munkalap státusz'});const cur=(await db.query(`SELECT id,work_order_number,status,locked_at,financial_closed_at,payment_status FROM work_orders WHERE id=$1::uuid`,[req.params.id])).rows[0];if(!cur)return res.status(404).json({message:'A munkalap nem található'});if(cur.locked_at)return res.status(409).json({message:`A(z) ${cur.work_order_number} munkalap lezárt és archivált; nem módosítható.`});if(st==='completed')return res.status(409).json({message:'A munkalap nem zárható le közvetlen státuszváltással. Előbb rögzítse és zárja le a fizetést a Pénztárban, majd használja a végleges lezárást.'});if(st===cur.status)return res.json(cur);if(!NEXT[String(cur.status||'waiting')]?.has(st))return res.status(409).json({message:`Nem engedélyezett státuszváltás: ${cur.status||'waiting'} → ${st}.`});const now=new Date().toISOString();const{rows}=await db.query(`UPDATE work_orders SET status=$2,started_at=CASE WHEN $2='in_progress' THEN COALESCE(started_at,$3::timestamptz) ELSE started_at END,cancelled_at=CASE WHEN $2='cancelled' THEN COALESCE(cancelled_at,$3::timestamptz) ELSE cancelled_at END,status_updated_at=now(),updated_at=now() WHERE id=$1::uuid RETURNING *`,[req.params.id,st,now]);res.json(rows[0])}catch(e:any){if(e?.code==='55000')return res.status(409).json({message:e.message});next(e)}});
router.post('/',async(req,res,next)=>{const c=await db.connect();try{const b=req.body||{},st=statusOf(b.status);if(!st)return res.status(400).json({message:'Érvénytelen munkalap státusz'});await c.query('BEGIN');if(b.appointment_id){const ex=(await c.query(`SELECT id,work_order_number,locked_at FROM work_orders WHERE appointment_id=$1::uuid LIMIT 1`,[b.appointment_id])).rows[0];if(ex){await c.query('COMMIT');return res.json({...ex,existing:true})}}const number=(await c.query(`SELECT next_official_work_order_number(now()) work_order_number`)).rows[0].work_order_number;const h=(await c.query(`INSERT INTO work_orders(title,notes,status,employee_id,client_id,client_name,client_phone,client_email,location_id,appointment_id,fully_paid,note_for_another_visitor,created_by,status_updated_at,work_order_number,source_created_at,source_snapshot) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,now(),$14,now(),$15::jsonb) RETURNING id,work_order_number`,[b.title||'Munkalap',b.notes||null,st,b.employee_id||null,b.client_id||null,b.client_name||null,b.client_phone||null,b.client_email||null,b.location_id||null,b.appointment_id||null,Boolean(b.fully_paid),Boolean(b.note_for_another_visitor),b.created_by||null,number,JSON.stringify(b.source_snapshot||{})])).rows[0];for(const x of Array.isArray(b.services)?b.services:[]){const s=(await c.query(`SELECT id,name,COALESCE(promo_price,list_price,base_price,0)::numeric price,COALESCE(duration_minutes,30)::int duration FROM services WHERE id=$1::uuid`,[x.service_id])).rows[0];if(s)await c.query(`INSERT INTO work_order_items(work_order_id,item_type,service_id,item_name,quantity,unit_price,discount_amount,line_total,duration_minutes) VALUES($1,'service',$2,$3,$4,$5,$6,$7,$8)`,[h.id,s.id,s.name,Number(x.quantity||1),Number(s.price||0),Number(x.discount_amount||0),Number(x.quantity||1)*Number(s.price||0)-Number(x.discount_amount||0),s.duration])}for(const x of Array.isArray(b.products)?b.products:[]){const p=(await c.query(`SELECT id,name,COALESCE(sale_price,retail_price_gross,0)::numeric price FROM products WHERE id=$1::uuid`,[x.product_id])).rows[0];if(p)await c.query(`INSERT INTO work_order_items(work_order_id,item_type,product_id,item_name,quantity,unit_price,discount_amount,line_total) VALUES($1,'product',$2,$3,$4,$5,$6,$7)`,[h.id,p.id,p.name,Number(x.quantity||1),Number(p.price||0),Number(x.discount_amount||0),Number(x.quantity||1)*Number(p.price||0)-Number(x.discount_amount||0)])}const recalc=(await c.query(`SELECT to_regprocedure('recalc_work_order_totals(uuid)') IS NOT NULL ok`)).rows[0]?.ok;if(recalc)await c.query(`SELECT recalc_work_order_totals($1::uuid)`,[h.id]);if(b.appointment_id)await c.query(`UPDATE appointments SET work_order_id=$2::uuid,work_order_number=$3 WHERE id=$1::uuid`,[b.appointment_id,h.id,number]);await c.query('COMMIT');res.status(201).json(h)}catch(e){await c.query('ROLLBACK');next(e)}finally{c.release()}});
export default router;
