import {Router,Response,NextFunction} from 'express';
import db from '../db';
import {requireAuth,AuthRequest} from '../middleware/auth';
const router=Router();router.use(requireAuth);
const roles=(raw:any)=>{if(Array.isArray(raw))return raw.map(String).map(x=>x.toLowerCase());try{const p=JSON.parse(String(raw||''));if(Array.isArray(p))return p.map(String).map(x=>x.toLowerCase())}catch{}return String(raw||'').split(',').map(x=>x.replace(/[\[\]"]/g,'').trim().toLowerCase()).filter(Boolean)};const anyRole=(r:string[],xs:string[])=>r.some(x=>xs.includes(x));
const ADMIN=['admin','administrator','rendszergazda','superadmin','super_admin'],RECEPTION=['receptionist','recepciós','recepcios','reception'],BUSINESS_MANAGER=['location_manager','üzletvezető','uzletvezeto','store_manager','branch_manager'],SALON_MANAGER=['szalonvezető','szalonvezeto','salon_manager'],CUSTOMER=['customer','client','guest','ügyfél','ugyfel','vendég','vendeg'],STAFF=['employee','staff','munkatárs','munkatars','professional','specialist'];
type Scope={kind:'all'|'location'|'employee'|'customer'|'none';locationId:string|null;employeeId:string|null;customerId:string|null;canEdit:boolean;roleLabel:string};
async function resolveScope(req:AuthRequest):Promise<Scope>{const r=roles(req.user?.role),uid=String(req.user?.id||''),email=String(req.user?.email||'').trim();if(anyRole(r,ADMIN))return{kind:'all',locationId:null,employeeId:null,customerId:null,canEdit:true,roleLabel:'admin'};const locationId=req.user?.location_id?String(req.user.location_id):null;if(anyRole(r,[...RECEPTION,...BUSINESS_MANAGER]))return{kind:'location',locationId,employeeId:null,customerId:null,canEdit:true,roleLabel:anyRole(r,RECEPTION)?'reception':'business_manager'};if(anyRole(r,SALON_MANAGER))return{kind:'location',locationId,employeeId:null,customerId:null,canEdit:false,roleLabel:'salon_manager'};if(anyRole(r,CUSTOMER)){let customerId:string|null=null;try{const q=await db.query(`SELECT id::text FROM clients WHERE ($1<>'' AND lower(COALESCE(email,''))=lower($1)) OR id::text=$2 ORDER BY CASE WHEN $1<>'' AND lower(COALESCE(email,''))=lower($1) THEN 0 ELSE 1 END LIMIT 1`,[email,uid]);customerId=q.rows[0]?.id||null}catch{}return{kind:'customer',locationId:null,employeeId:null,customerId,canEdit:false,roleLabel:'customer'}}let employeeId:string|null=null;let employeeLocation=locationId;try{const q=await db.query(`SELECT id::text,location_id::text FROM employees WHERE ($1<>'' AND (lower(COALESCE(email,''))=lower($1) OR lower(COALESCE(login_name,''))=lower($1))) OR id::text=$2 ORDER BY CASE WHEN $1<>'' AND lower(COALESCE(email,''))=lower($1) THEN 0 ELSE 1 END LIMIT 1`,[email,uid]);employeeId=q.rows[0]?.id||null;employeeLocation=q.rows[0]?.location_id||employeeLocation}catch{}if(anyRole(r,STAFF)||employeeId)return{kind:'employee',locationId:employeeLocation,employeeId,customerId:null,canEdit:false,roleLabel:'employee'};return{kind:'none',locationId:null,employeeId:null,customerId:null,canEdit:false,roleLabel:'none'}}
function where(scope:Scope,alias='w'){switch(scope.kind){case'all':return{sql:'TRUE',params:[] as any[]};case'location':return{sql:`${alias}.location_id=$1::uuid`,params:[scope.locationId]};case'employee':return{sql:`${alias}.employee_id=$1::uuid`,params:[scope.employeeId]};case'customer':return{sql:`(${alias}.client_id=$1::uuid OR ${alias}.client_email=(SELECT email FROM clients WHERE id=$1::uuid))`,params:[scope.customerId]};default:return{sql:'FALSE',params:[] as any[]}}}
async function requireVisible(req:AuthRequest,res:Response,next:NextFunction){try{const scope=await resolveScope(req),f=where(scope);const q=await db.query(`SELECT 1 FROM work_orders w WHERE w.id=$${f.params.length+1}::uuid AND ${f.sql} LIMIT 1`,[...f.params,req.params.id]);if(!q.rows[0])return res.status(404).json({message:'A munkalap nem található vagy nincs hozzá jogosultsága.'});(req as any).workOrderScope=scope;next()}catch(e){next(e)}}async function requireEditor(req:AuthRequest,res:Response,next:NextFunction){try{const scope=await resolveScope(req);if(!scope.canEdit)return res.status(403).json({message:'A munkalapot csak adminisztrátor, recepciós vagy üzletvezető módosíthatja.'});if(scope.kind==='location'&&!scope.locationId)return res.status(403).json({message:'A felhasználóhoz nincs szalon rendelve.'});(req as any).workOrderScope=scope;next()}catch(e){next(e)}}
router.get('/dashboard/summary',async(req:AuthRequest,res,next)=>{try{const scope=await resolveScope(req),f=where(scope);const q=await db.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE w.status IN ('waiting','arrived','in_progress'))::int open,COUNT(*) FILTER(WHERE w.status='completed')::int completed,COUNT(*) FILTER(WHERE w.locked_at IS NOT NULL)::int archived,COALESCE(SUM((SELECT COALESCE(SUM(i.line_total),0) FROM work_order_items i WHERE i.work_order_id=w.id)) FILTER(WHERE w.status='completed'),0)::numeric completed_value FROM work_orders w WHERE ${f.sql}`,f.params);const recent=await db.query(`SELECT w.id,w.work_order_number,w.title,w.status,w.created_at,w.locked_at,w.location_id,l.name location_name,w.client_name,e.full_name employee_name FROM work_orders w LEFT JOIN locations l ON l.id=w.location_id LEFT JOIN employees e ON e.id=w.employee_id WHERE ${f.sql} ORDER BY w.created_at DESC LIMIT 8`,f.params);res.json({scope:{kind:scope.kind,role:scope.roleLabel,can_edit:scope.canEdit,location_id:scope.locationId},stats:q.rows[0],recent:recent.rows})}catch(e){next(e)}});
router.get('/',async(req:AuthRequest,res,next)=>{try{const scope=await resolveScope(req),f=where(scope);const result=await db.query(`SELECT v.*,w.work_order_number,w.locked_at,w.archived_at,w.archive_hash,w.location_id,l.name location_name,w.client_name,e.full_name employee_name,$${f.params.length+1}::boolean can_edit FROM v_work_orders_list v JOIN work_orders w ON w.id=v.id LEFT JOIN locations l ON l.id=w.location_id LEFT JOIN employees e ON e.id=w.employee_id WHERE ${f.sql} ORDER BY v.created_at DESC`,[...f.params,scope.canEdit]);res.json(result.rows)}catch(e){next(e)}});
router.get('/:id',requireVisible,async(req:AuthRequest,res,next)=>{try{const scope=(req as any).workOrderScope as Scope;const header=await db.query(`SELECT v.*,w.work_order_number,w.source_created_at,w.source_snapshot,w.locked_at,w.locked_reason,w.archived_at,w.archive_hash,w.location_id,l.name location_name,w.client_id,$2::boolean can_edit FROM v_work_order_details v JOIN work_orders w ON w.id=v.id LEFT JOIN locations l ON l.id=w.location_id WHERE v.id=$1::uuid`,[req.params.id,scope.canEdit]);if(!header.rows[0])return res.status(404).json({message:'A munkalap nem található.'});const items=await db.query(`SELECT id,item_type,service_id,product_id,item_name,quantity,unit_price,discount_amount,line_total,duration_minutes FROM work_order_items WHERE work_order_id=$1::uuid ORDER BY created_at`,[req.params.id]);const payments=await db.query(`SELECT id,payment_method,amount,paid_at,note FROM work_order_payments WHERE work_order_id=$1::uuid ORDER BY paid_at`,[req.params.id]);res.json({...header.rows[0],items:items.rows,payments:payments.rows})}catch(e){next(e)}});
router.get('/:id/archive',requireVisible,async(req,res,next)=>{try{const q=await db.query(`SELECT id,work_order_id,work_order_number,archived_at,terminal_status,snapshot,snapshot_hash FROM work_order_archive WHERE work_order_id=$1::uuid`,[req.params.id]);if(!q.rows[0])return res.status(404).json({message:'Ehhez a munkalaphoz még nincs lezárt archív példány.'});res.json(q.rows[0])}catch(e){next(e)}});
router.patch('/:id/lifecycle',requireEditor,async(req:AuthRequest,res,next)=>{try{const scope=(req as any).workOrderScope as Scope;if(scope.kind==='location'){const q=await db.query(`SELECT 1 FROM work_orders WHERE id=$1::uuid AND location_id=$2::uuid`,[req.params.id,scope.locationId]);if(!q.rows[0])return res.status(404).json({message:'Másik szalon munkalapja nem módosítható.'})}next()}catch(e){next(e)}});
router.post('/',requireEditor,(req:AuthRequest,res,next)=>{const scope=(req as any).workOrderScope as Scope;if(scope.kind==='location'){if(req.body?.location_id&&String(req.body.location_id)!==String(scope.locationId))return res.status(403).json({message:'Csak a saját szalonhoz hozhat létre munkalapot.'});req.body={...(req.body||{}),location_id:scope.locationId}}next()});export default router;
