import {Router} from'express';
import db from'../db';
import{ensureKioskQueueSchema}from'../services/kioskQueue';
const router=Router();
const STATUSES=new Set(['waiting','arrived','in_progress','completed','cancelled','no_show']);
const statusOf=(v:any,f='arrived')=>{const s=String(v??f).trim().toLowerCase();return STATUSES.has(s)?s:null};
const NEXT:Record<string,Set<string>>={waiting:new Set(['arrived','in_progress','cancelled','no_show']),arrived:new Set(['in_progress','cancelled','no_show']),in_progress:new Set(['cancelled']),completed:new Set(),cancelled:new Set(),no_show:new Set()};

const META_TTL_MS=5*60*1000;
type Timed<T>={value:T;expiresAt:number};
const relationCache=new Map<string,Timed<boolean>>();
let workOrderColumnsCache:Timed<Set<string>>|null=null;
async function relationExists(name:string){const now=Date.now(),cached=relationCache.get(name);if(cached&&cached.expiresAt>now)return cached.value;const q=await db.query(`SELECT to_regclass($1) IS NOT NULL ok`,[`public.${name}`]);const value=Boolean(q.rows[0]?.ok);relationCache.set(name,{value,expiresAt:now+META_TTL_MS});return value}
async function workOrderColumns(){const now=Date.now();if(workOrderColumnsCache&&workOrderColumnsCache.expiresAt>now)return workOrderColumnsCache.value;const q=await db.query(`SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name='work_orders'`);const value=new Set<string>(q.rows.map((r:any)=>String(r.column_name)));workOrderColumnsCache={value,expiresAt:now+META_TTL_MS};return value}
const positiveInt=(raw:any,fallback:number,max:number)=>{const n=Number.parseInt(String(raw??''),10);return Number.isFinite(n)&&n>0?Math.min(n,max):fallback};
type WorkOrderGroup='all'|'new'|'open'|'closed';
const groupOf=(raw:any):WorkOrderGroup=>{const value=String(raw||'all').toLowerCase();return value==='new'||value==='open'||value==='closed'?value:'all'};
const groupSql=(group:WorkOrderGroup,alias='w')=>group==='new'?`${alias}.status='waiting'`:group==='open'?`${alias}.status IN ('arrived','in_progress')`:group==='closed'?`COALESCE(${alias}.status,'') NOT IN ('waiting','arrived','in_progress')`:'TRUE';

router.get('/',async(req,res,next)=>{try{
  await ensureKioskQueueSchema();
  const locationId=String(req.query.location_id||'').trim();
  const paginated=String(req.query.paginated||'')==='1';
  const hasView=await relationExists('v_work_orders_list');
  const baseWhere=`($1::text='' OR w.location_id::text=$1)`;
  const selectSql=hasView
    ?`SELECT v.*,w.work_order_number,w.locked_at,w.archived_at,w.archive_hash,w.location_id,w.appointment_id,w.kiosk_queue_no,w.kiosk_queue_date,w.kiosk_queue_code,w.source_snapshot FROM v_work_orders_list v JOIN work_orders w ON w.id=v.id WHERE ${baseWhere}`
    :`SELECT w.* FROM work_orders w WHERE ${baseWhere}`;
  if(!paginated){const{rows}=await db.query(`${selectSql} ORDER BY ${hasView?'v':'w'}.created_at DESC`,[locationId]);return res.json(rows)}
  const group=groupOf(req.query.group),page=positiveInt(req.query.page,1,1000000),limit=positiveInt(req.query.limit,50,200),offset=(page-1)*limit;
  const countRow=(await db.query(`SELECT COUNT(*)::int all_count,COUNT(*) FILTER(WHERE w.status='waiting')::int new_count,COUNT(*) FILTER(WHERE w.status IN ('arrived','in_progress'))::int open_count,COUNT(*) FILTER(WHERE COALESCE(w.status,'') NOT IN ('waiting','arrived','in_progress'))::int closed_count FROM work_orders w WHERE ${baseWhere}`,[locationId])).rows[0]||{};
  const counts={all:Number(countRow.all_count||0),new:Number(countRow.new_count||0),open:Number(countRow.open_count||0),closed:Number(countRow.closed_count||0)};
  const total=counts[group];
  const{rows}=await db.query(`${selectSql} AND ${groupSql(group)} ORDER BY ${hasView?'v':'w'}.created_at DESC LIMIT $2 OFFSET $3`,[locationId,limit,offset]);
  res.json({items:rows,page,limit,total,total_pages:Math.max(1,Math.ceil(total/limit)),group,counts})
}catch(e){next(e)}});
router.get('/:id/archive',async(req,res,next)=>{try{const{rows}=await db.query(`SELECT id,work_order_id,work_order_number,archived_at,terminal_status,snapshot,snapshot_hash FROM work_order_archive WHERE work_order_id=$1::uuid`,[req.params.id]);if(!rows[0])return res.status(404).json({message:'Ehhez a munkalaphoz még nincs lezárt archív példány.'});res.json(rows[0])}catch(e){next(e)}});
router.get('/:id',async(req,res,next)=>{try{await ensureKioskQueueSchema();const hasView=await relationExists('v_work_order_details');let header:any;if(hasView)header=(await db.query(`SELECT v.*,w.work_order_number,w.source_created_at,w.source_snapshot,w.locked_at,w.locked_reason,w.archived_at,w.archive_hash,w.location_id,w.appointment_id,w.client_id,w.kiosk_queue_no,w.kiosk_queue_date,w.kiosk_queue_code FROM v_work_order_details v JOIN work_orders w ON w.id=v.id WHERE v.id=$1::uuid`,[req.params.id])).rows[0];else header=(await db.query(`SELECT * FROM work_orders WHERE id=$1::uuid`,[req.params.id])).rows[0];if(!header)return res.status(404).json({message:'A munkalap nem található'});const items=(await db.query(`SELECT * FROM work_order_items WHERE work_order_id=$1::uuid ORDER BY created_at`,[req.params.id])).rows;const payments=(await db.query(`SELECT * FROM work_order_payments WHERE work_order_id=$1::uuid ORDER BY paid_at`,[req.params.id]).catch(()=>({rows:[]} as any))).rows;res.json({...header,items,payments})}catch(e){next(e)}});
router.patch('/:id/lifecycle',async(req,res,next)=>{try{await ensureKioskQueueSchema();const st=statusOf(req.body?.status,'');if(!st)return res.status(400).json({message:'Érvénytelen munkalap státusz'});const cur=(await db.query(`SELECT w.id,w.work_order_number,w.status,w.employee_id,w.kiosk_queue_code,COALESCE(w.source_snapshot->>'source','') source,NULLIF(to_jsonb(w)->>'locked_at','')::timestamptz locked_at,NULLIF(to_jsonb(w)->>'archived_at','')::timestamptz archived_at FROM work_orders w WHERE w.id=$1::uuid`,[req.params.id])).rows[0];if(!cur)return res.status(404).json({message:'A munkalap nem található'});if(cur.locked_at||cur.archived_at)return res.status(409).json({message:`A(z) ${cur.work_order_number||'munkalap'} munkalap lezárt és archivált; nem módosítható.`});if(st==='completed')return res.status(409).json({message:'A munkalap nem zárható le közvetlen státuszváltással. Előbb rögzítse és zárja le a fizetést a Pénztárban, majd használja a végleges lezárást.'});if(cur.source==='kiosk'&&st==='arrived'&&!cur.employee_id)return res.status(409).json({message:'A kioskos vendég csak kijelölt szakemberrel küldhető tovább. Előbb válasszon munkatársat a munkalapon.'});if(st===cur.status)return res.json(cur);if(!NEXT[String(cur.status||'waiting')]?.has(st))return res.status(409).json({message:`Nem engedélyezett státuszváltás: ${cur.status||'waiting'} → ${st}.`});const cols=await workOrderColumns();const sets:string[]=['status=$2'];if(cols.has('started_at'))sets.push(`started_at=CASE WHEN $2='in_progress' THEN COALESCE(started_at,now()) ELSE started_at END`);if(cols.has('work_started_at'))sets.push(`work_started_at=CASE WHEN $2='in_progress' THEN COALESCE(work_started_at,now()) ELSE work_started_at END`);if(cols.has('arrival_at'))sets.push(`arrival_at=CASE WHEN $2='arrived' THEN COALESCE(arrival_at,now()) ELSE arrival_at END`);if(cols.has('cancelled_at'))sets.push(`cancelled_at=CASE WHEN $2 IN ('cancelled','no_show') THEN COALESCE(cancelled_at,now()) ELSE cancelled_at END`);if(cols.has('status_updated_at'))sets.push('status_updated_at=now()');if(cols.has('updated_at'))sets.push('updated_at=now()');if(cols.has('document_status'))sets.push(`document_status=CASE WHEN $2 IN ('cancelled','no_show') THEN 'cancelled' WHEN $2='in_progress' THEN 'open' ELSE COALESCE(document_status,'draft') END`);const{rows}=await db.query(`UPDATE work_orders SET ${sets.join(',')} WHERE id=$1::uuid RETURNING *`,[req.params.id,st]);res.json(rows[0])}catch(e:any){if(e?.code==='55000'||e?.code==='23514')return res.status(409).json({message:e.message});if(e?.code==='22P02')return res.status(400).json({message:'Érvénytelen munkalapazonosító.'});next(e)}});
router.post('/',async(req,res,next)=>{const c=await db.connect();try{await ensureKioskQueueSchema();const b=req.body||{},st=statusOf(b.status);if(!st)return res.status(400).json({message:'Érvénytelen munkalap státusz'});await c.query('BEGIN');if(b.appointment_id){const ex=(await c.query(`SELECT id,work_order_number,locked_at FROM work_orders WHERE appointment_id=$1::uuid LIMIT 1`,[b.appointment_id])).rows[0];if(ex){await c.query('COMMIT');return res.json({...ex,existing:true})}}const number=(await c.query(`SELECT next_official_work_order_number(now()) work_order_number`)).rows[0].work_order_number;const h=(await c.query(`INSERT INTO work_orders(title,notes,status,employee_id,client_id,client_name,client_phone,client_email,location_id,appointment_id,fully_paid,note_for_another_visitor,created_by,status_updated_at,work_order_number,source_created_at,source_snapshot) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,now(),$14,now(),$15::jsonb) RETURNING id,work_order_number,kiosk_queue_no,kiosk_queue_date,kiosk_queue_code`,[b.title||'Munkalap',b.notes||null,st,b.employee_id||null,b.client_id||null,b.client_name||null,b.client_phone||null,b.client_email||null,b.location_id||null,b.appointment_id||null,Boolean(b.fully_paid),Boolean(b.note_for_another_visitor),b.created_by||null,number,JSON.stringify(b.source_snapshot||{})])).rows[0];for(const x of Array.isArray(b.services)?b.services:[]){const s=(await c.query(`SELECT id,name,COALESCE(promo_price,list_price,base_price,0)::numeric price,COALESCE(duration_minutes,30)::int duration FROM services WHERE id=$1::uuid`,[x.service_id])).rows[0];if(s)await c.query(`INSERT INTO work_order_items(work_order_id,item_type,service_id,item_name,quantity,unit_price,discount_amount,line_total,duration_minutes) VALUES($1,'service',$2,$3,$4,$5,$6,$7,$8)`,[h.id,s.id,s.name,Number(x.quantity||1),Number(s.price||0),Number(x.discount_amount||0),Number(x.quantity||1)*Number(s.price||0)-Number(x.discount_amount||0),s.duration])}for(const x of Array.isArray(b.products)?b.products:[]){const p=(await c.query(`SELECT id,name,COALESCE(sale_price,retail_price_gross,0)::numeric price FROM products WHERE id=$1::uuid`,[x.product_id])).rows[0];if(p)await c.query(`INSERT INTO work_order_items(work_order_id,item_type,product_id,item_name,quantity,unit_price,discount_amount,line_total) VALUES($1,'product',$2,$3,$4,$5,$6,$7)`,[h.id,p.id,p.name,Number(x.quantity||1),Number(p.price||0),Number(x.discount_amount||0),Number(x.quantity||1)*Number(p.price||0)-Number(x.discount_amount||0)])}const recalc=(await c.query(`SELECT to_regprocedure('recalc_work_order_totals(uuid)') IS NOT NULL ok`)).rows[0]?.ok;if(recalc)await c.query(`SELECT recalc_work_order_totals($1::uuid)`,[h.id]);if(b.appointment_id)await c.query(`UPDATE appointments SET work_order_id=$2::uuid,work_order_number=$3 WHERE id=$1::uuid`,[b.appointment_id,h.id,number]);await c.query('COMMIT');res.status(201).json(h)}catch(e){await c.query('ROLLBACK');next(e)}finally{c.release()}});
export default router;