import {Router} from 'express';
import PDFDocument from 'pdfkit';
import nodemailer from 'nodemailer';
import db from '../db';
import {requireAuth,AuthRequest} from '../middleware/auth';
const router=Router();router.use(requireAuth);
const actor=(r:AuthRequest)=>r.user?.email||String(r.user?.id||'');
const money=(v:any)=>Math.round(Number(v||0)*100)/100;

async function ensureDraft(c:any,workOrderId:string,req:AuthRequest){
 const existing=(await c.query(`SELECT * FROM finance_invoices WHERE work_order_id=$1 AND direction='outgoing' ORDER BY created_at DESC LIMIT 1`,[workOrderId])).rows[0];if(existing)return existing;
 const wo=(await c.query(`SELECT * FROM work_orders WHERE id=$1`,[workOrderId])).rows[0];if(!wo)throw new Error('A munkalap nem található.');
 if(String(wo.payment_status||'')!=='paid')throw new Error('Számlatervezet csak teljesen kifizetett munkalaphoz készíthető.');
 const gross=money(wo.amount_due||wo.gross_total||0);const vatRate=27;const net=money(gross/(1+vatRate/100));const vat=money(gross-net);const invoiceNo=(await c.query(`SELECT next_internal_invoice_number() invoice_no`)).rows[0].invoice_no;
 return (await c.query(`INSERT INTO finance_invoices(location_id,direction,invoice_no,partner_name,issue_date,performance_date,due_date,currency,net_total,vat_total,gross_total,status,work_order_id,note,created_by,document_kind) VALUES($1,'outgoing',$2,$3,CURRENT_DATE,CURRENT_DATE,CURRENT_DATE,'HUF',$4,$5,$6,'draft',$7,$8,$9,'internal_draft') RETURNING *`,[wo.location_id||null,invoiceNo,wo.client_name||'Magánszemély',net,vat,gross,wo.id,`Belső számlatervezet a ${wo.work_order_number||wo.id} munkalaphoz. Nem NAV-adatszolgáltatásra kiállított számla.`,actor(req)])).rows[0];
}

router.post('/workorders/:id/draft',async(req:AuthRequest,res,next)=>{const c=await db.connect();try{await c.query('BEGIN');const inv=await ensureDraft(c,req.params.id,req);await c.query('COMMIT');res.json(inv)}catch(e:any){await c.query('ROLLBACK');if(/munkalap|kifizetett/i.test(String(e.message)))return res.status(409).json({message:e.message});next(e)}finally{c.release()}});
router.get('/workorders/:id',async(req,res,next)=>{try{const {rows}=await db.query(`SELECT i.*,wo.work_order_number,wo.client_email FROM finance_invoices i JOIN work_orders wo ON wo.id=i.work_order_id WHERE i.work_order_id=$1 AND i.direction='outgoing' ORDER BY i.created_at DESC LIMIT 1`,[req.params.id]);res.json(rows[0]||null)}catch(e){next(e)}});
router.post('/invoices/:id/post-accounting',async(req:AuthRequest,res,next)=>{const c=await db.connect();try{await c.query('BEGIN');const inv=(await c.query(`SELECT * FROM finance_invoices WHERE id=$1::uuid FOR UPDATE`,[req.params.id])).rows[0];if(!inv){await c.query('ROLLBACK');return res.status(404).json({message:'A számlatervezet nem található.'})}if(inv.accounting_entry_id){await c.query('COMMIT');return res.json({idempotent:true,accounting_entry_id:inv.accounting_entry_id})}const entryNo=`KLEO-KV-${new Date().getFullYear()}-${String(Date.now()).slice(-8)}`;const entry=(await c.query(`INSERT INTO accounting_journal_entries(location_id,entry_date,document_no,source_type,source_id,description,status,created_by) VALUES($1,$2,$3,'finance_invoice',$4,$5,'posted',$6) RETURNING *`,[inv.location_id,inv.performance_date||inv.issue_date,entryNo,inv.id,`Kimenő számlatervezet ${inv.invoice_no}`,actor(req)])).rows[0];const net=money(inv.net_total),vat=money(inv.vat_total),gross=money(inv.gross_total);await c.query(`INSERT INTO accounting_journal_lines(journal_entry_id,account_code,account_name,debit,credit) VALUES($1,'311','Vevők',$2,0),($1,'91','Értékesítés nettó árbevétele',0,$3),($1,'467','Fizetendő ÁFA',0,$4)`,[entry.id,gross,net,vat]);await c.query(`UPDATE finance_invoices SET accounting_entry_id=$2,accounting_posted_at=now(),updated_at=now() WHERE id=$1`,[inv.id,entry.id]);await c.query('COMMIT');res.json({entry})}catch(e){await c.query('ROLLBACK');next(e)}finally{c.release()}});

router.get('/invoices/:id/pdf',async(req,res,next)=>{try{const q=await db.query(`SELECT i.*,wo.work_order_number,wo.client_name,wo.client_email,wo.client_phone,wo.created_at work_order_created_at FROM finance_invoices i JOIN work_orders wo ON wo.id=i.work_order_id WHERE i.id=$1::uuid`,[req.params.id]);const inv=q.rows[0];if(!inv)return res.status(404).json({message:'A számlatervezet nem található.'});const items=(await db.query(`SELECT item_name,quantity,unit_price,line_total FROM work_order_items WHERE work_order_id=$1 ORDER BY created_at`,[inv.work_order_id])).rows;res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`inline; filename="${inv.invoice_no}.pdf"`);const doc=new PDFDocument({size:'A4',margin:48});doc.pipe(res);doc.fontSize(9).text('KLEOPÁTRA SZÉPSÉGSZALONOK',{align:'center'});doc.moveDown(.3).fontSize(20).text('SZÁMLATERVEZET',{align:'center'});doc.fontSize(9).fillColor('#a00000').text('Belső bizonylat – nem minősül NAV Online Számla rendszerbe beküldött adóügyi számlának.',{align:'center'}).fillColor('black');doc.moveDown();doc.fontSize(11).text(`Bizonylatszám: ${inv.invoice_no}`);doc.text(`Munkalap: ${inv.work_order_number}`);doc.text(`Kiállítás: ${String(inv.issue_date).slice(0,10)}`);doc.text(`Teljesítés: ${String(inv.performance_date).slice(0,10)}`);doc.moveDown();doc.fontSize(12).text('Vevő',{underline:true});doc.fontSize(10).text(inv.partner_name||inv.client_name||'Magánszemély');if(inv.client_email)doc.text(inv.client_email);if(inv.client_phone)doc.text(inv.client_phone);doc.moveDown();doc.fontSize(12).text('Tételek',{underline:true});items.forEach((x:any)=>doc.fontSize(9).text(`${x.item_name} · ${Number(x.quantity)} × ${money(x.unit_price).toLocaleString('hu-HU')} Ft = ${money(x.line_total).toLocaleString('hu-HU')} Ft`));doc.moveDown();doc.fontSize(11).text(`Nettó: ${money(inv.net_total).toLocaleString('hu-HU')} Ft`,{align:'right'});doc.text(`ÁFA: ${money(inv.vat_total).toLocaleString('hu-HU')} Ft`,{align:'right'});doc.fontSize(14).text(`Bruttó: ${money(inv.gross_total).toLocaleString('hu-HU')} Ft`,{align:'right'});doc.moveDown(2);doc.fontSize(8).fillColor('#666').text(`Kapcsolódó hivatalos munkalap: ${inv.work_order_number}`);doc.end();await db.query(`UPDATE finance_invoices SET pdf_generated_at=now(),updated_at=now() WHERE id=$1::uuid`,[inv.id]).catch(()=>undefined)}catch(e){next(e)}});

router.post('/invoices/:id/email',async(req:AuthRequest,res,next)=>{try{const q=await db.query(`SELECT i.*,wo.client_email,wo.work_order_number FROM finance_invoices i JOIN work_orders wo ON wo.id=i.work_order_id WHERE i.id=$1::uuid`,[req.params.id]);const inv=q.rows[0];if(!inv)return res.status(404).json({message:'A számlatervezet nem található.'});const to=String(req.body?.to||inv.client_email||'').trim();if(!to)return res.status(400).json({message:'A címzett e-mail címe hiányzik.'});const host=process.env.SMTP_HOST,user=process.env.SMTP_USER,pass=process.env.SMTP_PASS,from=process.env.SMTP_FROM||user;if(!host||!user||!pass||!from)return res.status(409).json({message:'Az SMTP nincs konfigurálva. Állítsd be az SMTP_HOST, SMTP_USER, SMTP_PASS és SMTP_FROM változókat.'});const tr=nodemailer.createTransport({host,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE||'false')==='true',auth:{user,pass}});const info=await tr.sendMail({from,to,subject:`Kleopátra – ${inv.invoice_no} számlatervezet`,text:`Tisztelt Vendég!\n\nA ${inv.work_order_number} munkalaphoz tartozó ${inv.invoice_no} belső számlatervezet elkészült.\n\nEz az üzenet jelenleg belső VIR bizonylatot jelez; hivatalos adóügyi számlához NAV-kompatibilis számlázási integráció szükséges.\n\nKleopátra Szépségszalonok`});await db.query(`UPDATE finance_invoices SET emailed_at=now(),emailed_to=$2,updated_at=now() WHERE id=$1::uuid`,[inv.id,to]);await db.query(`INSERT INTO invoice_delivery_log(invoice_id,recipient,status,provider_message_id,created_by) VALUES($1,$2,'sent',$3,$4)`,[inv.id,to,String(info.messageId||''),actor(req)]);res.json({sent:true,to,message_id:info.messageId})}catch(e:any){await db.query(`INSERT INTO invoice_delivery_log(invoice_id,recipient,status,error_message,created_by) VALUES($1::uuid,$2,'failed',$3,$4)`,[req.params.id,String(req.body?.to||''),String(e.message||e),actor(req)]).catch(()=>undefined);next(e)}});
export default router;
