import db from'../db';
export type LoyaltyNotification={key:string;type:'loyalty';severity:'info'|'warning'|'critical';title:string;detail:string;route:string;created_at:string};
async function count(sql:string,params:any[]=[]){try{return (await db.query(sql,params)).rows[0]||{}}catch{return{}}}
export async function getLoyaltyNotifications():Promise<LoyaltyNotification[]>{const now=new Date().toISOString();const items:LoyaltyNotification[]=[];const s=(await count(`SELECT * FROM loyalty_automation_settings WHERE active=true ORDER BY location_id NULLS FIRST LIMIT 1`)) as any;const passDays=Number(s.pass_expiry_days||14),voucherDays=Number(s.voucher_expiry_days||14),inactiveDays=Number(s.inactive_guest_days||90);
 const p:any=await count(`SELECT COUNT(*)::int count FROM loyalty_passes WHERE status='active' AND valid_until BETWEEN CURRENT_DATE AND CURRENT_DATE+$1::int`,[passDays]);if(Number(p.count)>0)items.push({key:'loyalty:pass-expiry',type:'loyalty',severity:'warning',title:`${p.count} hamarosan lejáró bérlet`,detail:`A következő ${passDays} napban lejáró bérletekhez hosszabbítási ajánlat javasolt.`,route:'/loyalty/automation',created_at:now});
 const v:any=await count(`SELECT COUNT(*)::int count,COALESCE(SUM(remaining_value),0)::numeric value FROM loyalty_vouchers WHERE status='active' AND remaining_value>0 AND valid_until BETWEEN CURRENT_DATE AND CURRENT_DATE+$1::int`,[voucherDays]);if(Number(v.count)>0)items.push({key:'loyalty:voucher-expiry',type:'loyalty',severity:'warning',title:`${v.count} hamarosan lejáró utalvány`,detail:`Fennmaradó érték: ${Math.round(Number(v.value||0)).toLocaleString('hu-HU')} Ft.`,route:'/loyalty/automation',created_at:now});
 const pts:any=await count(`SELECT COUNT(*)::int count,COALESCE(SUM(points),0)::numeric points FROM loyalty_accounts WHERE status='active' AND points>0 AND points_expires_at BETWEEN CURRENT_DATE AND CURRENT_DATE+30`);if(Number(pts.count)>0)items.push({key:'loyalty:points-expiry',type:'loyalty',severity:'warning',title:`${pts.count} vendégnél pontlejárat közeleg`,detail:`Összesen ${Number(pts.points||0).toLocaleString('hu-HU')} pont érintett.`,route:'/loyalty/automation',created_at:now});
 const ina:any=await count(`SELECT COUNT(*)::int count FROM crm_guest_profiles WHERE COALESCE(last_visit_at,first_visit_at,updated_at)<now()-($1::text||' days')::interval`,[inactiveDays]);if(Number(ina.count)>0)items.push({key:'loyalty:inactive',type:'loyalty',severity:'info',title:`${ina.count} inaktív vendég`,detail:`Legalább ${inactiveDays} napja nem jártak a szalonban; visszacsábító kampány javasolt.`,route:'/loyalty/automation',created_at:now});
 const sug:any=await count(`SELECT COUNT(*)::int count FROM loyalty_campaign_suggestions WHERE status='suggested'`);if(Number(sug.count)>0)items.push({key:'loyalty:suggestions',type:'loyalty',severity:'info',title:`${sug.count} hűségkampány-javaslat vár`,detail:'Nézd át és hagyd jóvá vagy vesd el a javaslatokat.',route:'/loyalty/automation',created_at:now});return items}
