import cron from "node-cron";
import db from "../db";
import {ensureExceptionCommandCenterSchema} from "./exceptionCommandCenter";
import {ensureOperationalRiskControlSchema} from "./operationalRiskControlRegister";

const TZ="Europe/Budapest";let started=false;const ACTIVE=["open","acknowledged","in_progress","waiting","snoozed"];
type Item={key:string;sourceKey:string;severity:"critical"|"high";title:string;detail:string;location_id?:string|null;entity_type:string;entity_id:string;payload:any};
async function event(caseId:string,type:string,message:string,from?:string|null,to?:string|null,evidence:any={}){await db.query(`INSERT INTO exception_case_events(case_id,event_type,actor_key,from_status,to_status,message,evidence) VALUES($1::uuid,$2,'system-risk-bridge',$3,$4,$5,$6::jsonb)`,[caseId,type,message,from||null,to||null,JSON.stringify(evidence||{})])}

export async function syncOperationalRiskExceptions(){await ensureOperationalRiskControlSchema();await ensureExceptionCommandCenterSchema();await db.query(`INSERT INTO exception_routing_rules(category,team_key,critical_sla_minutes,high_sla_minutes,medium_sla_minutes,low_sla_minutes,auto_resolve) VALUES('risk','management',30,120,480,1440,true) ON CONFLICT(category) DO UPDATE SET team_key='management',auto_resolve=true`);
 const items:Item[]=[];
 const risks=(await db.query(`SELECT id::text,risk_no,title,description,location_id,residual_score,residual_band,appetite_threshold,next_review_at FROM operational_risks WHERE status NOT IN('accepted','closed') AND appetite_state='outside' AND residual_band IN('critical','high') ORDER BY residual_score DESC LIMIT 300`)).rows;
 for(const r of risks)items.push({key:`risk:outside-appetite:${r.id}`,sourceKey:r.risk_no,severity:r.residual_band==='critical'?'critical':'high',title:`Risk appetite túllépés · ${r.risk_no}`,detail:`${r.title}. Residual risk ${r.residual_score}/25, appetite ${r.appetite_threshold}/25. ${r.description}`,location_id:r.location_id,entity_type:'operational_risk',entity_id:r.id,payload:{risk_no:r.risk_no,residual_score:r.residual_score,residual_band:r.residual_band,appetite_threshold:r.appetite_threshold,next_review_at:r.next_review_at}});
 const kris=(await db.query(`SELECT k.id::text,k.code,k.name,k.last_value,k.unit,k.breach_threshold,k.last_measured_at,r.id::text risk_id,r.risk_no,r.title,r.location_id FROM operational_kris k JOIN operational_risks r ON r.id=k.risk_id WHERE k.enabled=true AND k.last_state='breached' AND r.status<>'closed' ORDER BY k.last_measured_at DESC LIMIT 300`)).rows;
 for(const k of kris)items.push({key:`risk:kri-breached:${k.id}`,sourceKey:k.code,severity:'critical',title:`KRI breach · ${k.name}`,detail:`${k.risk_no} · ${k.title}. Mért érték: ${k.last_value}${k.unit?` ${k.unit}`:''}; breach küszöb: ${k.breach_threshold}.`,location_id:k.location_id,entity_type:'operational_risk',entity_id:k.risk_id,payload:{kri_id:k.id,kri_code:k.code,value:k.last_value,breach_threshold:k.breach_threshold,last_measured_at:k.last_measured_at}});
 const controls=(await db.query(`SELECT c.id::text,c.control_no,c.name,c.effectiveness_score,c.last_test_at,c.next_test_at,(SELECT result FROM operational_control_tests t WHERE t.control_id=c.id ORDER BY t.tested_at DESC LIMIT 1) last_result FROM operational_controls c WHERE c.enabled=true AND c.is_key_control=true AND (c.next_test_at<now() OR c.effectiveness_score<60 OR EXISTS(SELECT 1 FROM operational_control_tests t WHERE t.control_id=c.id AND t.result='fail' AND t.tested_at=(SELECT MAX(t2.tested_at) FROM operational_control_tests t2 WHERE t2.control_id=c.id))) ORDER BY c.next_test_at NULLS FIRST LIMIT 100`)).rows;
 for(const c of controls){const critical=String(c.last_result)==='fail'||Number(c.effectiveness_score)<40;items.push({key:`risk:key-control:${c.id}`,sourceKey:c.control_no,severity:critical?'critical':'high',title:`Key control action needed · ${c.name}`,detail:`Hatékonyság: ${Number(c.effectiveness_score||0).toFixed(1)}%. Utolsó teszt: ${c.last_test_at||'nincs'}; következő esedékesség: ${c.next_test_at||'nincs'}; eredmény: ${c.last_result||'nincs'}.`,entity_type:'operational_control',entity_id:c.id,payload:{control_no:c.control_no,effectiveness_score:c.effectiveness_score,last_test_at:c.last_test_at,next_test_at:c.next_test_at,last_result:c.last_result}})}
 const seen=new Set(items.map(x=>x.key));let created=0,reopened=0,resolved=0;
 for(const x of items){const existing=(await db.query(`SELECT * FROM exception_cases WHERE exception_key=$1`,[x.key])).rows[0];const sla=x.severity==='critical'?30:120;if(!existing){const row=(await db.query(`INSERT INTO exception_cases(exception_key,source_type,source_key,category,severity,priority_score,status,sla_state,sla_minutes,title,detail,location_id,entity_type,entity_id,source_route,team_key,first_detected_at,last_detected_at,last_scanned_at,due_at,source_payload,auto_resolve) VALUES($1,'operational-risk',$2,'risk',$3,$4,'open','on_track',$5,$6,$7,$8,$9,$10,'/finance/exception-command-center/risk-register','management',now(),now(),now(),now()+make_interval(mins=>$5),$11::jsonb,true) RETURNING id::text`,[x.key,x.sourceKey,x.severity,x.severity==='critical'?100:75,sla,x.title,x.detail,x.location_id||null,x.entity_type,x.entity_id,JSON.stringify(x.payload)])).rows[0];await event(row.id,'detected','Operational Risk & Control Register eltérés automatikusan Exception case-szé emelve.',null,'open',{source:'operational-risk'});created++}else{const wasClosed=['resolved','dismissed'].includes(String(existing.status));await db.query(`UPDATE exception_cases SET severity=$2,priority_score=$3,status=CASE WHEN status='resolved' THEN 'open' ELSE status END,sla_state=CASE WHEN status='resolved' THEN 'on_track' ELSE sla_state END,title=$4,detail=$5,location_id=COALESCE($6,location_id),entity_type=$7,entity_id=$8,source_payload=$9::jsonb,last_detected_at=now(),last_scanned_at=now(),due_at=CASE WHEN status='resolved' THEN now()+make_interval(mins=>$10) ELSE due_at END,resolved_at=CASE WHEN status='resolved' THEN NULL ELSE resolved_at END,updated_at=now() WHERE id=$1::uuid`,[existing.id,x.severity,x.severity==='critical'?100:75,x.title,x.detail,x.location_id||null,x.entity_type,x.entity_id,JSON.stringify(x.payload),sla]);if(wasClosed){await event(existing.id,'reopened','A risk/control eltérés ismét aktív.',existing.status,'open',{source:'operational-risk'});reopened++}}}
 const old=(await db.query(`SELECT id::text,exception_key,status FROM exception_cases WHERE source_type='operational-risk' AND status=ANY($1::text[])`,[ACTIVE])).rows;for(const c of old){if(seen.has(String(c.exception_key)))continue;await db.query(`UPDATE exception_cases SET status='resolved',sla_state='closed',resolved_at=now(),resolution_note='A Risk Register következő ellenőrzése már nem jelezte az eltérést.',resolution_evidence='{"auto_resolved":true,"source":"operational-risk"}'::jsonb,updated_at=now() WHERE id=$1::uuid`,[c.id]);await event(c.id,'auto_resolved','A risk/control eltérés megszűnt.',c.status,'resolved',{source:'operational-risk'});resolved++}
 return{detected:items.length,created,reopened,auto_resolved:resolved,generated_at:new Date().toISOString()}}

export function startOperationalRiskExceptionBridge(){if(started||process.env.NODE_ENV==='test')return;started=true;cron.schedule('*/5 * * * *',()=>void syncOperationalRiskExceptions().catch(e=>console.error('[operational-risk] exception bridge failed',e)),{timezone:TZ});const t=setTimeout(()=>void syncOperationalRiskExceptions().catch(e=>console.error('[operational-risk] initial exception bridge failed',e)),135_000);t.unref?.()}
