'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const read=p=>fs.readFileSync(path.join(process.cwd(),p),'utf8');

test('operational risk register persists scores controls KRI sources and immutable evidence',()=>{const s=read('src/services/operationalRiskControlRegister.ts');for(const marker of ['operational_risks','operational_risk_sources','operational_controls','operational_risk_controls','operational_control_tests','operational_kris','operational_kri_measurements','operational_risk_events','kleo_operational_immutable','append-only','inherent_score','residual_score','appetite_threshold','effectiveness_score'])assert.ok(s.includes(marker),marker)});

test('risk governance requires independent acceptance evidence and safe closure',()=>{const s=read('src/services/operationalRiskControlRegister.ts');for(const marker of ['Risk acceptance requires independent approver','Risk acceptance note and evidence are required','Accepted risk requires review within 90 days','Risk cannot close outside appetite','Risk closure blocked: unresolved source, breached KRI or stale key control remains','Key control test requires independent tester','Control test note and evidence are required'])assert.ok(s.includes(marker),marker)});

test('source sync closes enterprise control loop from CAPA incidents resilience and GameDay',()=>{const s=read('src/services/operationalRiskControlRegister.ts');for(const marker of ['exception_capa_candidates','major_incidents','resilience_recovery_sessions','continuity_drills','gameday:','resilience:','major:','capa:','linkDefaultControls','07'])assert.ok(s.includes(marker),marker);assert.match(s,/cron\.schedule\("25 7 \* \* \*"/)});

test('operational risk API is management mounted with risk controls tests and KRI endpoints',()=>{const r=read('src/routes/operationalRiskControlRegister.ts'),n=read('src/routes/notifications.ts');for(const marker of ["'/summary'","'/sync'","'/governance-cycle'","'/risks'","'/controls'","'/controls/:id/tests'","'/kri/:id/measurements'",'startOperationalRiskExceptionBridge'])assert.ok(r.includes(marker),marker);assert.ok(n.includes('router.use("/risk-register",requireManagement,operationalRiskControlRegisterRouter)'))});

test('risk exception bridge raises appetite KRI and key-control failures back to Exception Center',()=>{const s=read('src/services/operationalRiskExceptionBridge.ts');for(const marker of ['risk:outside-appetite:','risk:kri-breached:','risk:key-control:','source_type=\'operational-risk\'','exception_routing_rules','auto_resolved','*/5 * * * *'])assert.ok(s.includes(marker),marker)});

test('executive menu exposes operational risk register only to management roles',()=>{const s=read('src/services/executiveAiMenu.ts');for(const marker of ['analytics.operational_risk','Operational Risk & Control Register','/finance/exception-command-center/risk-register'])assert.ok(s.includes(marker),marker);assert.match(s,/VALUES\('admin'\),\('manager'\)/)});
