const fs=require('fs');
const assert=require('assert');
const p4=fs.readFileSync('src/routes/virP4.ts','utf8');
const adv=fs.readFileSync('src/routes/virP4Advanced.ts','utf8');
assert(p4.includes('router.use(virP4AdvancedRouter)'), 'advanced P4 router not mounted');
assert(adv.includes('router.use(requireManagement)'), 'management guard missing');
for(const route of ['/smart-shift-generator','/employee-revenue-coach','/service-portfolio','/cannibalization']) assert(adv.includes(`router.get("${route}"`),`${route} missing`);
assert(adv.includes('resolveTenantIdentity'),'advanced P4 must resolve canonical SaaS tenant identity');
assert(adv.includes('locationBelongsToTenant'),'advanced P4 location scope must use canonical tenant ownership');
assert(adv.includes('tenant_id::text=$1::text'),'tenant scoping evidence missing');
assert(!/tenant_id\s*=\s*\$\d+::uuid/.test(adv),'tenant UUID comparison must not return to advanced P4');
assert(/automatic_scheduling\s*:\s*false/.test(adv)&&/approval_required\s*:\s*true/.test(adv)&&/automatic_write\s*:\s*false/.test(adv),'smart shift must stay approval-only');
assert(/non_punitive\s*:\s*true/.test(adv)&&/no_automatic_hr_action\s*:\s*true/.test(adv),'coach must be non-punitive');
assert(/automatic_catalog_changes\s*:\s*false/.test(adv),'portfolio must not mutate catalog');
assert(/causality_claim\s*:\s*false/.test(adv),'cannibalization must not claim causality');
console.log('VIR P4 advanced contract OK');
