const fs=require('fs');
const assert=require('assert');
const route=fs.readFileSync('src/routes/virP4.ts','utf8');
const vir=fs.readFileSync('src/routes/vir.ts','utf8');
assert(route.includes('router.use(requireManagement)'),'P4 must be management-only');
assert(route.includes('/workforce-optimizer'),'workforce optimizer route missing');
assert(route.includes('resolveTenantIdentity'),'P4 must resolve canonical SaaS tenant identity');
assert(route.includes('locationBelongsToTenant'),'P4 location scope must use canonical tenant ownership');
assert(route.includes('tenant_id::text=$1::text')||route.includes('tenant_id::text=$3::text'),'tenant scope missing');
assert(!/tenant_id\s*=\s*\$\d+::uuid/.test(route),'tenant UUID comparison must not return to P4');
assert(route.includes('work_shifts'),'published shifts must drive scheduled capacity');
assert(route.includes("status='published'"),'only published shifts may count');
assert(route.includes('employee_service_overrides'),'skill matrix must be reused');
assert(route.includes('historical_daily_minutes'),'historical demand baseline missing');
assert(route.includes('forecast_capacity_workforce_optimizer_v1'),'model label missing');
assert(/automatic_scheduling\s*:\s*false/.test(route),'optimizer must not schedule autonomously');
assert(/decision_support_only\s*:\s*true/.test(route),'decision-support boundary missing');
assert(vir.includes('router.use("/p4", virP4Router)'),'P4 router mount missing');
console.log('VIR P4 workforce optimizer contract: PASS');
