BEGIN;

-- A meglévő UAT esetek kanonikus KLEO → AC → TC hozzárendelése.
UPDATE uat_test_cases SET catalog_requirement_id='KLEO-FUN-BOOK-002',acceptance_criteria_id='KLEO-FUN-BOOK-002-AC-02',external_test_case_id='TC-KLEO-FUN-BOOK-002-AC-02',requirement_lifecycle_status='approved',source_reference='SRS v2 / 9. oldal',owner_role='Product Owner',priority='P0',verification_method='integration' WHERE code='UAT-BOOK-001';
UPDATE uat_test_cases SET catalog_requirement_id='KLEO-FUN-BOOK-004',acceptance_criteria_id='KLEO-FUN-BOOK-004-AC-02',external_test_case_id='TC-KLEO-FUN-BOOK-004-AC-02',requirement_lifecycle_status='approved',source_reference='Operational supplement 2026-08-16',owner_role='Product Owner',priority='P1',verification_method='integration' WHERE code='UAT-BOOK-002';
UPDATE uat_test_cases SET catalog_requirement_id='KLEO-FUN-WO-003',acceptance_criteria_id='KLEO-FUN-WO-003-AC-02',external_test_case_id='TC-KLEO-FUN-WO-003-AC-02',requirement_lifecycle_status='approved',source_reference='Operational supplement 2026-08-16',owner_role='Product Owner',priority='P0',verification_method='integration' WHERE code='UAT-WO-001';
UPDATE uat_test_cases SET catalog_requirement_id='KLEO-FUN-FIN-003',acceptance_criteria_id='KLEO-FUN-FIN-003-AC-01',external_test_case_id='TC-KLEO-FUN-FIN-003-AC-01',requirement_lifecycle_status='approved',source_reference='Operational supplement 2026-08-16',owner_role='Finance Owner',priority='P0',verification_method='integration' WHERE code='UAT-FIN-001';
UPDATE uat_test_cases SET catalog_requirement_id='KLEO-FUN-FIN-004',acceptance_criteria_id='KLEO-FUN-FIN-004-AC-01',external_test_case_id='TC-KLEO-FUN-FIN-004-AC-01',requirement_lifecycle_status='approved',source_reference='Operational supplement 2026-08-16',owner_role='Finance Owner',priority='P0',verification_method='integration' WHERE code='UAT-FIN-002';
UPDATE uat_test_cases SET catalog_requirement_id='KLEO-FUN-PROC-001',acceptance_criteria_id='KLEO-FUN-PROC-001-AC-01',external_test_case_id='TC-KLEO-FUN-PROC-001-AC-01',requirement_lifecycle_status='approved',source_reference='Operational supplement 2026-08-16',owner_role='Procurement Owner',priority='P0',verification_method='security' WHERE code='UAT-PROC-001';
UPDATE uat_test_cases SET catalog_requirement_id='KLEO-FUN-PROC-002',acceptance_criteria_id='KLEO-FUN-PROC-002-AC-01',external_test_case_id='TC-KLEO-FUN-PROC-002-AC-01',requirement_lifecycle_status='approved',source_reference='Operational supplement 2026-08-16',owner_role='Procurement Owner',priority='P0',verification_method='integration' WHERE code='UAT-PROC-002';
UPDATE uat_test_cases SET catalog_requirement_id='KLEO-FUN-PAY-001',acceptance_criteria_id='KLEO-FUN-PAY-001-AC-01',external_test_case_id='TC-KLEO-FUN-PAY-001-AC-01',requirement_lifecycle_status='approved',source_reference='Operational supplement 2026-08-16',owner_role='Payroll Owner',priority='P0',verification_method='integration' WHERE code='UAT-PAY-001';
UPDATE uat_test_cases SET catalog_requirement_id='KLEO-FUN-PAY-002',acceptance_criteria_id='KLEO-FUN-PAY-002-AC-01',external_test_case_id='TC-KLEO-FUN-PAY-002-AC-01',requirement_lifecycle_status='approved',source_reference='Operational supplement 2026-08-16',owner_role='Payroll Owner',priority='P1',verification_method='integration' WHERE code='UAT-PAY-002';
UPDATE uat_test_cases SET catalog_requirement_id='KLEO-FUN-ACC-001',acceptance_criteria_id='KLEO-FUN-ACC-001-AC-01',external_test_case_id='TC-KLEO-FUN-ACC-001-AC-01',requirement_lifecycle_status='approved',source_reference='Operational supplement 2026-08-16',owner_role='Finance Owner',priority='P0',verification_method='integration' WHERE code='UAT-ACC-001';
UPDATE uat_test_cases SET catalog_requirement_id='KLEO-NFR-SEC-004',acceptance_criteria_id='KLEO-NFR-SEC-004-AC-01',external_test_case_id='TC-KLEO-NFR-SEC-004-AC-01',requirement_lifecycle_status='approved',source_reference='Operational supplement 2026-08-16',owner_role='Security Owner',priority='P0',verification_method='security' WHERE code='UAT-RBAC-001';
UPDATE uat_test_cases SET catalog_requirement_id='KLEO-GEN-AUD-001',acceptance_criteria_id='KLEO-GEN-AUD-001-AC-01',external_test_case_id='TC-KLEO-GEN-AUD-001-AC-01',requirement_lifecycle_status='approved',source_reference='SRS v2 / 41. oldal',owner_role='Product Owner',priority='P1',verification_method='integration' WHERE code='UAT-AUDIT-001';
UPDATE uat_test_cases SET catalog_requirement_id='KLEO-FUN-NOT-001',acceptance_criteria_id='KLEO-FUN-NOT-001-AC-01',external_test_case_id='TC-KLEO-FUN-NOT-001-AC-01',requirement_lifecycle_status='approved',source_reference='Operational supplement 2026-08-16',owner_role='Platform Owner',priority='P1',verification_method='integration' WHERE code='UAT-NOTIF-001';
UPDATE uat_test_cases SET catalog_requirement_id='KLEO-NFR-OPS-001',acceptance_criteria_id='KLEO-NFR-OPS-001-AC-01',external_test_case_id='TC-KLEO-NFR-OPS-001-AC-01',requirement_lifecycle_status='approved',source_reference='Operational supplement 2026-08-16',owner_role='Platform Owner',priority='P0',verification_method='resilience' WHERE code='UAT-SYS-001';

-- Új UAT esetek azokhoz a kötelező operatív követelményekhez, amelyekhez korábban nem volt runtime UAT.
INSERT INTO uat_test_cases(code,module_key,title,description,expected_result,route,order_index,critical,active,requirement_id,requirement_text,acceptance_criteria,source_reference,owner_role,priority,verification_method,catalog_requirement_id,acceptance_criteria_id,external_test_case_id,evidence_required,requirement_lifecycle_status)
VALUES
('UAT-COMM-001','complaints','Panasz e-mail automatikus rekordképzés','Dedikált panaszpostafiók új levelének és csatolmányának idempotens feldolgozása.','Pontosan egy panaszrekord és csatolmánylánc jön létre; újrafeldolgozás nem duplikál.','/marketing/complaints',150,true,true,'KLEO-FUN-COMM-001','A panasz e-mail pontosan egyszer válik panaszrekorddá.','KLEO-FUN-COMM-001-AC-01','Operational supplement 2026-08-16','Quality Owner','P0','integration','KLEO-FUN-COMM-001','KLEO-FUN-COMM-001-AC-01','TC-KLEO-FUN-COMM-001-AC-01',true,'approved'),
('UAT-GDPR-001','gdpr','GDPR érintetti kérelem','Hozzáférési/hordozhatósági/törlési kérelem teljes folyamatának ellenőrzése.','A kérelem határidővel, döntéssel és bizonyítékkal lezárható; megőrzési kivétel auditálható.','/admin/gdpr',160,true,true,'KLEO-NFR-PRV-001','Az érintetti jogok végrehajtása bizonyítható.','KLEO-NFR-PRV-001-AC-01','Operational supplement 2026-08-16','Data Protection Owner','P0','inspection','KLEO-NFR-PRV-001','KLEO-NFR-PRV-001-AC-01','TC-KLEO-NFR-PRV-001-AC-01',true,'approved'),
('UAT-GDPR-002','gdpr','Adatmegőrzés és hozzájárulás','Retention és marketing-hozzájárulás visszavonásának ellenőrzése.','Lejárt adat törlődik/anonimizálódik, visszavont hozzájárulás után nincs opcionális marketingküldés.','/admin/gdpr',170,true,true,'KLEO-NFR-PRV-002','A retention és consent szabályok érvényesülnek.','KLEO-NFR-PRV-002-AC-02','Operational supplement 2026-08-16','Data Protection Owner','P0','integration','KLEO-NFR-PRV-002','KLEO-NFR-PRV-002-AC-02','TC-KLEO-NFR-PRV-002-AC-02',true,'approved'),
('UAT-BACKUP-001','system','Backup és visszaállítás próba','Legutóbbi mentésből izolált próbavisszaállítás és konzisztencia-ellenőrzés.','A visszaállítás sikeres, RTO/RPO mérhető és bizonyíték készül.','/admin/system-health',180,true,true,'KLEO-NFR-BCK-001','A mentésből bizonyíthatóan visszaállítható az üzemi adat.','KLEO-NFR-BCK-001-AC-01','Operational supplement 2026-08-16','Platform Owner','P0','resilience','KLEO-NFR-BCK-001','KLEO-NFR-BCK-001-AC-01','TC-KLEO-NFR-BCK-001-AC-01',true,'approved'),
('UAT-PERF-001','system','Kritikus teljesítménykapu','Naptár, pénztár és dashboard normál üzemi terhelési profilja.','Olvasási p95 <=800 ms, írási p95 <=1500 ms, 5xx hibaarány <1%.','/admin/system-health',190,true,true,'KLEO-NFR-PERF-001','A kritikus felületek mérhető teljesítményküszöböt teljesítenek.','KLEO-NFR-PERF-001-AC-01','Operational supplement 2026-08-16','Platform Owner','P0','performance','KLEO-NFR-PERF-001','KLEO-NFR-PERF-001-AC-01','TC-KLEO-NFR-PERF-001-AC-01',true,'approved'),
('UAT-IDEM-001','system','Kritikus írások idempotenciája','Párhuzamos/ismételt fizetési, számlázási vagy foglalási kérés.','Legfeljebb egy üzleti mellékhatás keletkezik azonos idempotenciakulcs mellett.','/admin/uat',200,true,true,'KLEO-NFR-IDEM-001','A kritikus írások újrapróbálása nem duplikál.','KLEO-NFR-IDEM-001-AC-01','Operational supplement 2026-08-16','Platform Owner','P0','integration','KLEO-NFR-IDEM-001','KLEO-NFR-IDEM-001-AC-01','TC-KLEO-NFR-IDEM-001-AC-01',true,'approved'),
('UAT-REL-001','system','Migráció és deploy visszaállíthatóság','Adatbázis-migráció ismételt staging futtatása és hibás deploy rollback/forward-fix próbája.','Nincs adatvesztés, a migráció konzisztens és a szolgáltatás dokumentált eljárással helyreáll.','/admin/system-health',210,true,true,'KLEO-NFR-REL-001','Az éles release adatvesztés nélkül visszaállítható vagy javítható.','KLEO-NFR-REL-001-AC-01','Operational supplement 2026-08-16','Platform Owner','P0','resilience','KLEO-NFR-REL-001','KLEO-NFR-REL-001-AC-01','TC-KLEO-NFR-REL-001-AC-01',true,'approved')
ON CONFLICT(code) DO UPDATE SET module_key=EXCLUDED.module_key,title=EXCLUDED.title,description=EXCLUDED.description,expected_result=EXCLUDED.expected_result,route=EXCLUDED.route,order_index=EXCLUDED.order_index,critical=EXCLUDED.critical,active=true,requirement_id=EXCLUDED.requirement_id,requirement_text=EXCLUDED.requirement_text,acceptance_criteria=EXCLUDED.acceptance_criteria,source_reference=EXCLUDED.source_reference,owner_role=EXCLUDED.owner_role,priority=EXCLUDED.priority,verification_method=EXCLUDED.verification_method,catalog_requirement_id=EXCLUDED.catalog_requirement_id,acceptance_criteria_id=EXCLUDED.acceptance_criteria_id,external_test_case_id=EXCLUDED.external_test_case_id,evidence_required=true,requirement_lifecycle_status='approved',updated_at=now();

COMMIT;
