import type{KnowledgeMaterial,KnowledgeSource,QuizQuestion}from'./catalog';

const ALL=['all'];
const HAIR=['fodrász','fodrasz','borbély','borbely'];
const COS=['kozmetikus','kozmetikus technikus'];
const NAIL=['kéz- és lábápoló','kez- es labapolo','kézápoló','kezapolo','lábápoló','labapolo','körmös','kormos','pedikűrös','pedikuros'];
const REC=['recepciós','recepcios','receptionist','reception','front desk','ügyfélszolgálat','ugyfelszolgalat'];
const MGR=['üzletvezető','uzletvezeto','szalonvezető','szalonvezeto','salon_manager','location_manager','manager','vezető','vezeto'];
const CASH=['pénztáros','penztaros','cashier',...REC,...MGR];
const WH=['raktáros','raktaros','beszerző','beszerzo','warehouse','procurement',...MGR];
const MKT=['marketing','marketinges','marketing manager','kampánymenedzser','kampanymenedzser'];
const HR=['hr','hr manager','humán erőforrás','human resources','személyügy','szemelyugy'];

export const roleKnowledgeSources2026:KnowledgeSource[]=[
 {code:'SRC-IKK-HAIR-2026',name:'IKK – Fodrász KKK 2024.09.01. v5',url:'https://api.ikk.hu/v1/media/documents/10562?filename=Fodr%C3%A1sz-2024.09.01.-v5.pdf',authority:'IKK Nonprofit Zrt.',reviewed_at:'2026-08-17'},
 {code:'SRC-IKK-COS-2026',name:'IKK – Kozmetikus technikus KKK 2024.01.16. v4',url:'https://api.ikk.hu/v1/media/documents/10311?filename=Kozmetikus-technikus-2024.01.16.-v4.pdf',authority:'IKK Nonprofit Zrt.',reviewed_at:'2026-08-17'},
 {code:'SRC-IKK-NAIL-2026',name:'IKK – Kéz- és lábápoló technikus KKK 2026.02.11. v4',url:'https://api.ikk.hu/v1/media/documents/13437?filename=K%C3%A9z-%C3%A9s-l%C3%A1b%C3%A1pol%C3%B3-technikus-2026.02.11.-v4.pdf',authority:'IKK Nonprofit Zrt.',reviewed_at:'2026-08-17'},
 {code:'SRC-NAV-ENYUGTA-2026',name:'NAV – Nyugtaadat-szolgáltatás 2026',url:'https://nav.gov.hu/ado/enyugta/nyugtaadat-szolgaltatas',authority:'NAV',reviewed_at:'2026-08-17'},
 {code:'SRC-NAIH-GDPR-2026',name:'NAIH – Adatvédelmi incidensek (GDPR)',url:'https://www.naih.hu/adatvedelmi-incidensek-gdpr',authority:'NAIH',reviewed_at:'2026-08-17'},
];

export const roleKnowledgeMaterials2026:KnowledgeMaterial[]=[
 {code:'KB-HAIR-2026',title:'Fodrász diagnózis, szolgáltatástervezés és utóápolás',roles:HAIR,category:'Fodrászat',summary:'A hatályos KKK szerinti vendégfogadás, haj- és fejbőrdiagnózis, technológiai döntés és otthoni tanácsadás.',learning_points:['Egyéniség, fejbőr és haj állapotának felmérése','Kívánt eredmény és technológiai korlátok egyeztetése','Termék és technológia szakmai kiválasztása','Minden szolgáltatás után otthoni hajápolási és formázási tanács'],source_code:'SRC-IKK-HAIR-2026'},
 {code:'KB-COS-2026',title:'Kozmetikai higiénia, kezelési terv és készülékbiztonság',roles:COS,category:'Kozmetika',summary:'Állapotfelmérésre épülő kezelés, következetes fertőtlenítés és az elektrokozmetikai készülékek állapothoz illesztett használata.',learning_points:['Kezelést befolyásoló és kizáró körülmények értékelése','Tisztítás és fertőtlenítés következetes végrehajtása','Készülék alkalmazásának illesztése a bőrállapothoz','Rendellenes reakciónál a kezelés megszakítása és újraértékelése'],source_code:'SRC-IKK-COS-2026'},
 {code:'KB-NAIL-2026',title:'Kéz- és lábápolás: diagnózis, higiénia és speciális lábápolási határok',roles:NAIL,category:'Kéz- és lábápolás',summary:'A 2026-os KKK szerinti felület-előkészítés, kizáró állapotok felismerése, fertőtlenítés és speciális lábápolási kompetenciahatár.',learning_points:['Kezelendő felület előkészítése és állapotfelmérése','Egészségestől eltérő bőr- és körömállapot felismerése','Fertőtlenítés és tisztítás szakszerű alkalmazása','Diabeteses vagy kóros lábállapotnál kompetenciahatár felismerése'],source_code:'SRC-IKK-NAIL-2026'},
 {code:'KB-CASH-2026',title:'Pénztár és 2026-os nyugtaadat-szolgáltatás',roles:CASH,category:'Pénzügy',summary:'Bizonylati fegyelem és a 2026. szeptember 1-jétől alkalmazandó kézi/számítógépes nyugtaadat-szolgáltatás alapjai.',learning_points:['Egy ügyletről egy bizonylat elve','Kézi és számítógépes nyugták napi összesítése','Adómértékek szerinti bontás','2026.09.01-től beküldés a kibocsátást követő 3 naptári napon belül'],source_code:'SRC-NAV-ENYUGTA-2026'},
 {code:'KB-REC-2026',title:'Recepció: adatbiztonság és hibamentes vendégérkeztetés',roles:REC,category:'Recepció',summary:'Vendég, telephely, szolgáltatás, szakember és időpont pontos egyeztetése, minimális adatkezeléssel.',learning_points:['Teljes foglalási kontextus egyeztetése','Csak szükséges vendégadat megnyitása','Téves címzés vagy adatkiszivárgás azonnali eszkalációja','Eltérés tényszerű dokumentálása'],source_code:'SRC-NAIH-GDPR-2026'},
 {code:'KB-MGR-2026',title:'Vezetői incidens-, higiéniai és pénzügyi kontroll',roles:MGR,category:'Vezetés',summary:'Ismétlődő eltérések okfeltárása, felelős intézkedés, visszaellenőrzés és auditálható műszakátadás.',learning_points:['Eltéréshez felelős és határidő rendelése','Intézkedés után visszaellenőrzés','Adatvédelmi incidensnél azonnali belső folyamatindítás','Nyitott pénzügyi és munkalap tételek rendezése napzárás előtt'],source_code:'SRC-NAIH-GDPR-2026'},
 {code:'KB-MKT-2026',title:'Marketing és hírlevél: vendégadatok kontrollált kezelése',roles:MKT,category:'Marketing',summary:'Célcsoportképzés és kampányküldés adatminimalizálással, címzett-ellenőrzéssel és incidensmegelőzéssel.',learning_points:['Csak a kampányhoz szükséges adatok használata','Címzettlista és kommunikációs preferenciák ellenőrzése','Téves címzés azonnali megfékezése','Exportok és hozzáférések minimalizálása'],source_code:'SRC-NAIH-GDPR-2026'},
 {code:'KB-HR-2026',title:'HR-adatkezelés és belépési dokumentáció',roles:HR,category:'HR',summary:'Munkatársi adatok jogosultságalapú kezelése, státuszkövetés és adatvédelmi incidensreakció.',learning_points:['Csak feladathoz szükséges HR-adat megnyitása','Dokumentumok hozzáférésének korlátozása','Belépési státusz és felelős visszakövethető kezelése','Téves címzett HR-dokumentum incidensként kezelendő'],source_code:'SRC-NAIH-GDPR-2026'},
];

export const roleQuizQuestions2026:QuizQuestion[]=[
 {id:'all-2026-1',roles:ALL,topic:'Munkavédelem',q:'Kiömlött vagy rendellenesen reagáló vegyi anyagnál mi az első helyes lépés?',answers:['Folytatni a munkát','Az expozíciót megszüntetni, a területet biztonságossá tenni és az előírt eljárást követni','Minden esetben másik flakonba áttölteni'],correct:1,explanation:'Veszélyes anyagnál az expozíciókontroll és a vészhelyzeti eljárás követése elsődleges.',source_code:'SRC-OSHA-CHEM'},
 {id:'all-2026-2',roles:ALL,topic:'Dokumentáció',q:'Melyik a helyes dokumentációs gyakorlat?',answers:['Utólag emlékezetből kitölteni','Az eseményhez közel, tényszerűen és visszakövethetően rögzíteni','Csak szóban továbbadni'],correct:1,explanation:'A szépészeti szolgáltatások adminisztratív tevékenységét pontosan és szabálykövetően kell végezni.',source_code:'SRC-IKK-SZEP'},
 {id:'all-2026-3',roles:ALL,topic:'Adatvédelem',q:'Az adatvédelmi incidens belső kezelésével szabad 72 órát várni?',answers:['Igen','Nem, a hatáskorlátozás és belső eszkaláció azonnal indul','Csak hétvégén'],correct:1,explanation:'A 72 óra a kockázatos incidens felügyeleti hatósági bejelentésének felső célhatárideje; a belső kezelés nem várhat.',source_code:'SRC-NAIH-GDPR-2026'},
 {id:'hair-2026-1',roles:HAIR,topic:'Fodrászat',q:'A KKK szerint melyik része a fodrász munkájának?',answers:['Csak a hajvágás','Vendégfogadás, diagnózis, szolgáltatástervezés és utóápolási tanácsadás is','Kizárólag termékértékesítés'],correct:1,explanation:'A Fodrász KKK a vendégfogadástól a diagnózison és technológián át az otthoni tanácsadásig írja le a munkaterületet.',source_code:'SRC-IKK-HAIR-2026'},
 {id:'hair-2026-2',roles:HAIR,topic:'Ergonómia',q:'Melyik csökkenti a fodrászati mozgásszervi terhelést?',answers:['Állítható szék és ergonomikus munkahely','Minden feladat azonos testhelyzetben','A szünetek elhagyása'],correct:0,explanation:'Az EU-OSHA ergonomikus berendezést és a terhelés csökkentését javasolja.',source_code:'SRC-OSHA-HAIR'},
 {id:'hair-2026-3',roles:HAIR,topic:'Vegyi szolgáltatás',q:'Hajszínváltoztatás előtt mi a szakmailag helyes alap?',answers:['A legerősebb hatóanyag kiválasztása','Haj- és fejbőrállapot felmérése, majd megfelelő termék és technológia választása','A foglalás alapján automatikus végrehajtás'],correct:1,explanation:'A KKK a diagnózisra épülő technológiai döntést követeli meg.',source_code:'SRC-IKK-HAIR-2026'},
 {id:'hair-2026-4',roles:HAIR,topic:'Vendégkommunikáció',q:'Mi tartozik a fodrász szolgáltatás befejezéséhez?',answers:['Csak a fizetés','Otthoni hajápolási és hajformázási tanácsadás','A vendégadatok törlése'],correct:1,explanation:'A KKK szerint minden szolgáltatást követően tanácsot kell adni az otthoni hajápoláshoz és formázáshoz.',source_code:'SRC-IKK-HAIR-2026'},
 {id:'cos-2026-1',roles:COS,topic:'Kozmetika',q:'Mi előzi meg a kezelési terv véglegesítését?',answers:['Termékértékesítés','Állapotfelmérés és a kezelést befolyásoló/kizáró körülmények vizsgálata','Fizetés'],correct:1,explanation:'A kezelésnek az aktuális bőrállapotra és releváns vendéginformációkra kell épülnie.',source_code:'SRC-IKK-COS-2026'},
 {id:'cos-2026-2',roles:COS,topic:'Higiénia',q:'Melyik kijelentés helyes a kozmetikai tisztításra és fertőtlenítésre?',answers:['Csak látható szennyeződésnél szükséges','A munkafolyamat részeként, következetesen és az előírt módon kell elvégezni','Illatosító kiváltja'],correct:1,explanation:'A KKK önálló, higiénikus tisztítási és fertőtlenítési munkafolyamatot ír le.',source_code:'SRC-IKK-COS-2026'},
 {id:'cos-2026-3',roles:COS,topic:'Készülékbiztonság',q:'Elektrokozmetikai készüléknél mi az egyik alapvető szakmai döntés?',answers:['Mindig maximális intenzitás','Az alkalmazás illesztése az adott bőrállapothoz és a készülék működési elvéhez','Minden vendégnél azonos beállítás'],correct:1,explanation:'A KKK az adott bőrállapothoz illesztett szakszerű készülékalkalmazást értékeli.',source_code:'SRC-IKK-COS-2026'},
 {id:'cos-2026-4',roles:COS,topic:'Vendégbiztonság',q:'Rendellenes bőrreakció jelentkezik kezelés közben. Mi a helyes lépés?',answers:['Folytatni kisebb intenzitással','Megszakítani, állapotot felmérni és szükség szerint segítséget kérni','Csak lefotózni'],correct:1,explanation:'A vendégbiztonság elsőbbséget élvez.',source_code:'SRC-NNGYK'},
 {id:'nail-2026-1',roles:NAIL,topic:'Kéz- és lábápolás',q:'Fertőzésgyanús vagy szolgáltatást kizáró állapotnál mi a helyes elv?',answers:['Mindenképp elvégezni','A kockázatot értékelni, szükség esetén elutasítani vagy halasztani','Kesztyű nélkül vizsgálni'],correct:1,explanation:'A 2026-os KKK előírja a szolgáltatást kizáró körülmény felismerését.',source_code:'SRC-IKK-NAIL-2026'},
 {id:'nail-2026-2',roles:NAIL,topic:'Diagnózis',q:'Mit kell ellenőrizni a kéz- vagy lábkezelés megkezdése előtt?',answers:['Csak a választott színt','A kezelendő felület állapotát és a kizáró körülményeket','Csak a fizetési módot'],correct:1,explanation:'A KKK előkészítést, állapotfelmérést és kizáró körülmény vizsgálatát írja le.',source_code:'SRC-IKK-NAIL-2026'},
 {id:'nail-2026-3',roles:NAIL,topic:'Higiénia',q:'Melyik tartozik a 2026-os KKK vizsgatémái közé?',answers:['Higiénia és fertőtlenítés a körömszalonban','Csak közösségi média trendek','Kizárólag értékesítés'],correct:0,explanation:'A KKK vizsgatémái között hangsúlyos a higiénia, fertőtlenítés, anyag- és eszközismeret.',source_code:'SRC-IKK-NAIL-2026'},
 {id:'nail-2026-4',roles:NAIL,topic:'Speciális lábápolás',q:'Diabeteses vagy kóros lábállapotnál mi a szakmailag helyes hozzáállás?',answers:['Mindig rutinpedikűr','A kompetenciahatár, kizáró/befolyásoló állapot és szükséges továbbirányítás mérlegelése','A tünet figyelmen kívül hagyása'],correct:1,explanation:'A 2026-os KKK külön kezeli a diabeteses lábat, kóros állapotokat és a határterületi lehetőségeket.',source_code:'SRC-IKK-NAIL-2026'},
 {id:'rec-2026-1',roles:REC,topic:'Recepció',q:'Foglalási eltérésnél mi a helyes eljárás?',answers:['Figyelmen kívül hagyni','Tisztázni, szükség esetén felelőshöz eszkalálni és dokumentálni','Törölni a vendéget'],correct:1,explanation:'A pontos vendégút és visszakövethetőség érdekében az eltérést kezelni kell.',source_code:'SRC-NNGYK'},
 {id:'rec-2026-2',roles:REC,topic:'Adatvédelem',q:'Vendéglista exportálása mikor indokolt?',answers:['Bármikor kényelmi okból','Csak indokolt feladathoz, megfelelő jogosultsággal és szükséges adatkörrel','Saját e-mailre mindig'],correct:1,explanation:'Az adatminimalizálás és jogosultságalapú hozzáférés csökkenti az incidenskockázatot.',source_code:'SRC-NAIH-GDPR-2026'},
 {id:'rec-2026-3',roles:REC,topic:'Pénztár',q:'Egy ügyletről mi a NAV által hangsúlyozott bizonylati alapelv?',answers:['Mindig két bizonylat','Egy ügyletet egyszer kell megfelelő bizonylattal bizonylatolni','Nem kell bizonylat'],correct:1,explanation:'A NAV szerint egy ügyletről egyetlen bizonylatot kell kibocsátani.',source_code:'SRC-NAV-ENYUGTA-2026'},
 {id:'mgr-2026-1',roles:MGR,topic:'Vezetés',q:'Ismétlődő higiéniai eltérésnél mi a helyes vezetői intézkedés?',answers:['Elfogadni, ha nincs panasz','Okot feltárni, intézkedést és felelőst kijelölni, majd visszaellenőrizni','Csak szóban figyelmeztetni'],correct:1,explanation:'A kockázatkezelés intézkedést és visszaellenőrzést igényel.',source_code:'SRC-NNGYK'},
 {id:'mgr-2026-2',roles:MGR,topic:'Adatvédelmi incidens',q:'Adatvédelmi incidens gyanújánál melyik vezetői lépés helyes?',answers:['Kivárni 72 órát','Azonnal korlátozni a hatást, dokumentálni és elindítani a belső incidenskezelést','Törölni minden nyomot'],correct:1,explanation:'A 72 órás hatósági határidő nem belső várakozási idő.',source_code:'SRC-NAIH-GDPR-2026'},
 {id:'mgr-2026-3',roles:MGR,topic:'Pénzügy',q:'2026. szeptember 1-jétől a kézi/számítógépes nyugták adat-szolgáltatásánál mi a NAV határideje?',answers:['30 nap','A kibocsátást követő 3 naptári nap','Évente egyszer'],correct:1,explanation:'A NAV 2026.09.01-től 3 naptári napos határidőt ír le, napi összesítéssel.',source_code:'SRC-NAV-ENYUGTA-2026'},
 {id:'cash-2026-1',roles:CASH,topic:'Nyugtaadat',q:'Melyik dátumtól indul az általános nyugtaadat-szolgáltatás a kézi és számítógépes nyugtákra?',answers:['2026. január 1.','2026. szeptember 1.','2028. július 1.'],correct:1,explanation:'A NAV tájékoztatója szerint 2026. szeptember 1-jétől.',source_code:'SRC-NAV-ENYUGTA-2026'},
 {id:'cash-2026-2',roles:CASH,topic:'Nyugtaadat',q:'Milyen bontásban kell a NAV szerint a kézi/számítógépes nyugták adatait napi szinten összesíteni?',answers:['Adómértékek szerint','Munkatárs életkora szerint','Szalon színe szerint'],correct:0,explanation:'A NAV adómértékek szerinti bontást ír le.',source_code:'SRC-NAV-ENYUGTA-2026'},
 {id:'cash-2026-3',roles:CASH,topic:'Pénztár',q:'Pénztáreltérésnél mi a helyes gyakorlat?',answers:['Csendben korrigálni','Dokumentálni, okot tisztázni és a jogosult felelőshöz eszkalálni','A következő műszakra hagyni'],correct:1,explanation:'A pénzügyi visszakövethetőség dokumentált eltéréskezelést igényel.',source_code:'SRC-NAV-ENYUGTA-2026'},
 {id:'wh-2026-1',roles:WH,topic:'Készlet',q:'Lejárt vagy sérült tétellel mi a helyes eljárás?',answers:['Normál készletben hagyni','Felhasználásból kizárni/blokkolni és dokumentálni','Akciósan felhasználni'],correct:1,explanation:'A nem megfelelő tételt el kell különíteni a felhasználható készlettől.',source_code:'SRC-NNGYK'},
 {id:'wh-2026-2',roles:WH,topic:'Bevételezés',q:'Mi a visszakövethető bevételezés kulcsadata lejáratos terméknél?',answers:['Tétel és lejárat','A polc színe','A dolgozó kedvenc márkája'],correct:0,explanation:'A tétel- és lejáratkezelés teszi lehetővé a FEFO-t és visszakeresést.',source_code:'SRC-NNGYK'},
 {id:'wh-2026-3',roles:WH,topic:'Vegyi biztonság',q:'Irritatív termék raktári sérülésénél mi az elsődleges?',answers:['Kézzel összeszedni','Az expozíciót korlátozni és a termék biztonsági előírása szerint eljárni','Jelölés nélkül áttölteni'],correct:1,explanation:'Veszélyes anyagnál az expozíciókontroll és a biztonsági információ követése alapvető.',source_code:'SRC-OSHA-CHEM'},
 {id:'mkt-2026-1',roles:MKT,topic:'Marketing',q:'Kampánylista készítésekor melyik adatkezelési elv helyes?',answers:['Minden elérhető adat exportálása','Csak a kampányhoz szükséges adatok használata megfelelő jogosultsággal','Vendégadatok magáneszközre másolása'],correct:1,explanation:'Az adatminimalizálás és hozzáférés-korlátozás csökkenti a kockázatot.',source_code:'SRC-NAIH-GDPR-2026'},
 {id:'mkt-2026-2',roles:MKT,topic:'Marketing',q:'Téves címzettlistára személyes adatot felfedő kampány megy ki. Mi a helyes reakció?',answers:['Figyelmen kívül hagyni','Azonnal megfékezni, dokumentálni és incidensként eszkalálni','Újabb levelet küldeni ellenőrzés nélkül'],correct:1,explanation:'A téves címzés tipikus adatvédelmi incidenstípus.',source_code:'SRC-NAIH-GDPR-2026'},
 {id:'hr-2026-1',roles:HR,topic:'HR',q:'Munkatársi dokumentumhoz ki férjen hozzá?',answers:['Minden dolgozó','Csak akinek a feladata és jogosultsága indokolja','Minden külső partner'],correct:1,explanation:'A hozzáférést a szükséges feladathoz kell korlátozni.',source_code:'SRC-NAIH-GDPR-2026'},
 {id:'hr-2026-2',roles:HR,topic:'HR',q:'Téves címzettnek küldött HR-dokumentum esetén mi a helyes reakció?',answers:['Semmi','A terjedés megállítása, dokumentálás és incidens-eszkaláció','A fájl átnevezése'],correct:1,explanation:'A jogosulatlan közlés adatvédelmi incidens lehet.',source_code:'SRC-NAIH-GDPR-2026'},
];

const norm=(value:unknown)=>String(value??'').trim().toLocaleLowerCase('hu-HU');
export function roleMatches2026(roles:string[],role:string){const r=norm(role);return roles.includes('all')||roles.some(x=>r.includes(norm(x)))}
export function extraMaterialsForRole2026(role:string){return roleKnowledgeMaterials2026.filter(x=>roleMatches2026(x.roles,role))}
export function extraQuestionsForRole2026(role:string){return roleQuizQuestions2026.filter(x=>roleMatches2026(x.roles,role))}
