export type KnowledgeSource={code:string;name:string;url:string;authority:string;reviewed_at:string};
export type KnowledgeMaterial={code:string;title:string;roles:string[];category:string;summary:string;learning_points:string[];source_code:string};
export type QuizQuestion={id:string;roles:string[];topic:string;q:string;answers:string[];correct:number;explanation:string;source_code:string};

export const knowledgeSources:KnowledgeSource[]=[
 {code:'SRC-IKK-SZEP',name:'IKK – Szépészet ágazat, KKK/PTT',url:'https://akkreditaltvizsgaztatas.ikk.hu/kkk-ptt',authority:'IKK Nonprofit Zrt.',reviewed_at:'2026-08-17'},
 {code:'SRC-IKK-COS',name:'IKK – Kozmetikus technikus szakmakártya',url:'https://ikk.hu/szakmakartyak/szakmak/kozmetikus-technikus',authority:'IKK Nonprofit Zrt.',reviewed_at:'2026-08-17'},
 {code:'SRC-IKK-HAIR',name:'IKK – Fodrász szakmakártya',url:'https://ikk.hu/szakmakartyak/szakmak/fodrasz',authority:'IKK Nonprofit Zrt.',reviewed_at:'2026-08-17'},
 {code:'SRC-NNGYK',name:'NNGYK – Szépségápolási szolgáltatási tevékenységek',url:'https://nngyk.gov.hu/hu/?id=671&view=category',authority:'NNGYK',reviewed_at:'2026-08-17'},
 {code:'SRC-OSHA-HAIR',name:'EU-OSHA – Non-binding Guidelines for the Hairdressing Sector',url:'https://osha.europa.eu/en/legislation/guidelines/non-binding-guidelines-hairdressing-sector',authority:'EU-OSHA / European Commission',reviewed_at:'2026-08-17'},
 {code:'SRC-OSHA-CHEM',name:'EU-OSHA – Veszélyes anyagok kezelése',url:'https://osha.europa.eu/hu/themes/dangerous-substances',authority:'EU-OSHA',reviewed_at:'2026-08-17'},
 {code:'SRC-NAIH',name:'NAIH – Adatvédelmi incidensek kezelése',url:'https://www.naih.hu/tudnivalok-az-adatvedelmi-incidensek-kezeleserol',authority:'NAIH',reviewed_at:'2026-08-17'},
 {code:'SRC-NAV',name:'NAV – Bizonylatolási és Online Számla tájékoztatók',url:'https://nav.gov.hu/',authority:'NAV',reviewed_at:'2026-08-17'},
];

const ALL=['all'];
export const knowledgeMaterials:KnowledgeMaterial[]=[
 {code:'KB-ALL-001',title:'Szalonhigiénia, kézhigiénia és fertőzésmegelőzés',roles:ALL,category:'Higiénia',summary:'A kezelőhely, eszközök, textíliák és kéz higiénés kockázatainak kontrollja.',learning_points:['Tiszta és szennyezett eszközút elkülönítése','Kézhigiénia a vendégváltások között','Gyártói fertőtlenítési behatási idő betartása','Egyszer használatos eszközök újrahasználatának tiltása'],source_code:'SRC-NNGYK'},
 {code:'KB-ALL-002',title:'Vegyi anyagok, címkék és biztonsági adatlapok',roles:ALL,category:'Munkavédelem',summary:'Kozmetikumok, hajfestékek, fertőtlenítők és tisztítószerek biztonságos kezelése.',learning_points:['Címke és használati előírás ellenőrzése','Biztonsági adatlap hozzáférhetősége','Bőr- és légúti expozíció csökkentése','Kiömlés és rendellenes reakció jelentése'],source_code:'SRC-OSHA-CHEM'},
 {code:'KB-ALL-003',title:'Vendégadatok és adatvédelmi incidensek',roles:ALL,category:'Adatvédelem',summary:'Szükséges adatkezelés, jogosultság és incidens esetén azonnali eszkaláció.',learning_points:['Csak feladathoz szükséges adat megnyitása','Téves címzett vagy elveszett adat incidens lehet','Incidens terjedésének azonnali megállítása','Időpont, érintett adatkör és körülmények dokumentálása'],source_code:'SRC-NAIH'},
 {code:'KB-HAIR-001',title:'Fodrászati munkavédelem: bőr, légút és ergonómia',roles:['fodrász','fodrasz','borbély','borbely'],category:'Fodrászat',summary:'Wet-work, vegyszerek, por/aeroszol és ismétlődő testhelyzetek kockázatának csökkentése.',learning_points:['Megfelelő kesztyű vegyszeres munkánál','Bőr kiszáradásának és irritációjának megelőzése','Szellőzés és porképződés csökkentése','Állítható szék és ergonomikus munkahely használata'],source_code:'SRC-OSHA-HAIR'},
 {code:'KB-HAIR-002',title:'Fodrász szakmai kompetenciák és vendégkonzultáció',roles:['fodrász','fodrasz','borbély','borbely'],category:'Fodrászat',summary:'Szakmai diagnózis, vendégigény felmérése, technológiai döntés és dokumentálás.',learning_points:['Haj és fejbőr állapotának felmérése','Kívánt eredmény és korlátok egyeztetése','Technológia és termék kiválasztása','Utóápolási tanács dokumentált átadása'],source_code:'SRC-IKK-HAIR'},
 {code:'KB-COS-001',title:'Kozmetikai diagnózis és kezelési terv',roles:['kozmetikus','kozmetikus technikus'],category:'Kozmetika',summary:'Állapotfelmérésből felépített, kontraindikációkat figyelembe vevő kezelési terv.',learning_points:['Bőr állapotának megfigyelése és anamnézis','Kontraindikáció felismerése','Kezelési cél és módszer meghatározása','Vendégtájékoztatás és otthoni ápolási javaslat'],source_code:'SRC-IKK-COS'},
 {code:'KB-COS-002',title:'Kozmetikumok biztonságos szalonhasználata',roles:['kozmetikus','kozmetikus technikus'],category:'Kozmetika',summary:'Termékazonosítás, higiénikus adagolás és rendellenes reakció kezelése.',learning_points:['Lejárat és csomagolás sértetlenségének ellenőrzése','Keresztkontamináció kerülése','Gyártói alkalmazási korlátozások betartása','Rendellenes reakciónál kezelés megszakítása'],source_code:'SRC-NNGYK'},
 {code:'KB-NAIL-001',title:'Kéz- és lábápolás: higiénia és eszközbiztonság',roles:['kéz- és lábápoló','kez- es labapolo','körmös','kormos','pedikűrös','pedikuros'],category:'Kéz- és lábápolás',summary:'Eszközút, bőrsérülés, fertőzésgyanú és egyszer használatos anyagok kezelése.',learning_points:['Vendég előtti eszközállapot-ellenőrzés','Sérült vagy fertőzésgyanús terület kockázatértékelése','Egyszer használatos fogyóeszköz elkülönítése','Vérrel/szövetnedvvel szennyezett felület azonnali protokollja'],source_code:'SRC-NNGYK'},
 {code:'KB-NAIL-002',title:'Kéz- és lábápoló szakmai követelmények',roles:['kéz- és lábápoló','kez- es labapolo','körmös','kormos','pedikűrös','pedikuros'],category:'Kéz- és lábápolás',summary:'A szépészeti KKK/PTT szerinti szakmai alapok, vendégkommunikáció és dokumentáció.',learning_points:['Munkafolyamat megtervezése','Eszköz és anyag kiválasztása','Higiénés és munkavédelmi kontroll','Eredmény és utóápolás értékelése'],source_code:'SRC-IKK-SZEP'},
 {code:'KB-REC-001',title:'Recepció: foglalástól az érkeztetésig',roles:['recepciós','recepcios','front desk','ügyfélszolgálat'],category:'Recepció',summary:'Vendégazonosítás, foglalásellenőrzés, hozzájárulások és munkalapindítás.',learning_points:['Foglalás és vendégadat egyeztetése','Telephely, szolgáltatás és szakember ellenőrzése','Adatkezelési preferenciák tiszteletben tartása','Eltérés azonnali eszkalációja'],source_code:'SRC-NAIH'},
 {code:'KB-REC-002',title:'Panasz fogadása és szolgáltatás-helyreállítás',roles:['recepciós','recepcios','front desk','üzletvezető','uzletvezeto','manager'],category:'Vendégélmény',summary:'Tényszerű rögzítés, felelős, SLA, visszajelzés és zárási bizonyíték.',learning_points:['Vendég megszakítás nélküli meghallgatása','Tény és vélemény elkülönítése','Felelős és határidő kijelölése','Lezárás csak dokumentált eredménnyel'],source_code:'SRC-NNGYK'},
 {code:'KB-MGR-001',title:'Szalonvezetői napi kontroll és műszakátadás',roles:['üzletvezető','uzletvezeto','szalonvezető','szalonvezeto','manager','location_manager'],category:'Vezetés',summary:'Pénztár, nyitott munkalapok, készlet, higiénia, panasz és beosztás kontrollja.',learning_points:['Nyitó és záró checklist ellenőrzése','Nyitott pénzügyi és munkalap tételek rendezése','Kritikus készlethiány és lejárat kezelése','Eltérések felelőssel és határidővel történő átadása'],source_code:'SRC-NNGYK'},
 {code:'KB-CASH-001',title:'Pénztár és bizonylatolás alapjai',roles:['pénztáros','penztaros','recepciós','recepcios','üzletvezető','uzletvezeto'],category:'Pénzügy',summary:'Fizetés, bizonylati fegyelem, pénztármozgás és zárás visszakövethető végrehajtása.',learning_points:['Fizetési mód pontos rögzítése','Bizonylat kapcsolása az üzleti eseményhez','Készpénzmozgás csak nyitott műszakban','Eltérés dokumentált kezelése'],source_code:'SRC-NAV'},
 {code:'KB-WH-001',title:'Készlet, FEFO és szavatossági kontroll',roles:['raktáros','raktaros','beszerző','beszerzo','üzletvezető','uzletvezeto'],category:'Készlet',summary:'Bevételezés, lejárati tételkezelés, FEFO, korrekció és visszakövethetőség.',learning_points:['Tétel és lejárat rögzítése bevételezéskor','Leghamarabb lejáró használható tétel elsőbbsége','Lejárt vagy blokkolt készlet kizárása','Korrekció csak dokumentált indokkal'],source_code:'SRC-NNGYK'},
];

const QALL=['all'];
export const quizQuestions:QuizQuestion[]=[
 {id:'all-1',roles:QALL,topic:'Higiénia',q:'Mi a helyes eljárás két vendég között a többször használatos eszközzel?',answers:['Azonnal visszatenni a fiókba','A meghatározott tisztítási/fertőtlenítési folyamatot végrehajtani','Csak száraz kendővel áttörölni'],correct:1,explanation:'A keresztszennyeződés megelőzéséhez validált tisztítási és fertőtlenítési folyamat szükséges.',source_code:'SRC-NNGYK'},
 {id:'all-2',roles:QALL,topic:'Vegyi biztonság',q:'Mit kell tenni ismeretlen vagy sérült címkéjű vegyi termékkel?',answers:['Használni kis mennyiségben','Nem használni, amíg azonosítása és biztonságos alkalmazása nem tisztázott','Áttölteni jelöletlen flakonba'],correct:1,explanation:'Ismeretlen veszélyességű anyag használata nem kontrollálható kockázat.',source_code:'SRC-OSHA-CHEM'},
 {id:'all-3',roles:QALL,topic:'Adatvédelem',q:'Téves címzettnek elküldött vendégadat esetén mi az elsődleges teendő?',answers:['Eltitkolni','A további terjedést megállítani és az incidensfolyamatot azonnal indítani','Csak a vendéget felhívni'],correct:1,explanation:'Az incidens hatásának korlátozása és azonnali belső jelentése szükséges.',source_code:'SRC-NAIH'},
 {id:'hair-1',roles:['fodrász','fodrasz','borbély','borbely'],topic:'Fodrászat',q:'Mi csökkenti legjobban a wet-work és hajfesték okozta bőrterhelést?',answers:['Gyakori forró vizes kézmosás','Megfelelő kesztyű és bőrvédelmi gyakorlat','Parfümös kézkrém kezelés közben'],correct:1,explanation:'Az EU-OSHA fodrászati útmutató kiemeli a wet-work és veszélyes anyagok expozíciójának csökkentését.',source_code:'SRC-OSHA-HAIR'},
 {id:'hair-2',roles:['fodrász','fodrasz','borbély','borbely'],topic:'Fodrászat',q:'Mikor kell a tervezett kémiai szolgáltatást újraértékelni?',answers:['Ha a haj/fejbőr állapota vagy az előzmény kockázatot jelez','Csak ha a vendég kéri','Soha, ha már van foglalás'],correct:0,explanation:'A szakmai döntésnek a diagnózisra és az aktuális állapotra kell épülnie.',source_code:'SRC-IKK-HAIR'},
 {id:'cos-1',roles:['kozmetikus','kozmetikus technikus'],topic:'Kozmetika',q:'Mi előzi meg a kezelési terv véglegesítését?',answers:['Termékértékesítés','Anamnézis, állapotfelmérés és kontraindikációk vizsgálata','Fizetés'],correct:1,explanation:'A kozmetikus technikus kompetenciája a diagnózis és az erre épülő kezelési terv.',source_code:'SRC-IKK-COS'},
 {id:'cos-2',roles:['kozmetikus','kozmetikus technikus'],topic:'Kozmetika',q:'Rendellenes bőrreakció jelentkezik kezelés közben. Mi a helyes lépés?',answers:['Folytatni kisebb intenzitással','Megszakítani, állapotot felmérni és szükség szerint segítséget kérni','Lefotózni és folytatni'],correct:1,explanation:'A vendégbiztonság elsőbbséget élvez; rendellenes reakciónál a kockázatot újra kell értékelni.',source_code:'SRC-NNGYK'},
 {id:'nail-1',roles:['kéz- és lábápoló','kez- es labapolo','körmös','kormos','pedikűrös','pedikuros'],topic:'Kéz- és lábápolás',q:'Fertőzésgyanús bőrelváltozásnál mi a helyes döntési elv?',answers:['Mindenképp elvégezni a szolgáltatást','A kockázatot értékelni, szükség esetén a szolgáltatást elutasítani/halasztani','Csak kesztyű nélkül jobban megvizsgálni'],correct:1,explanation:'A fertőzés terjedésének megelőzése elsődleges higiénés követelmény.',source_code:'SRC-NNGYK'},
 {id:'nail-2',roles:['kéz- és lábápoló','kez- es labapolo','körmös','kormos','pedikűrös','pedikuros'],topic:'Kéz- és lábápolás',q:'Egyszer használatos fogyóeszközzel mi történik használat után?',answers:['Fertőtlenítve újra használható','A kijelölt hulladékút szerint el kell távolítani','A következő vendégnek félretehető'],correct:1,explanation:'Az egyszer használatos eszköz újrahasználata keresztszennyezési kockázat.',source_code:'SRC-NNGYK'},
 {id:'rec-1',roles:['recepciós','recepcios','front desk','ügyfélszolgálat'],topic:'Recepció',q:'Érkeztetés előtt melyik adatcsoportot kell elsőként egyeztetni?',answers:['Vendég, telephely, szolgáltatás és időpont','Csak a telefonszámot','Csak a kedvezményt'],correct:0,explanation:'A helyes vendégút alapja az üzleti esemény teljes azonosítása.',source_code:'SRC-NAIH'},
 {id:'rec-2',roles:['recepciós','recepcios','front desk','ügyfélszolgálat'],topic:'Panasz',q:'Panasz rögzítésekor melyik a helyes gyakorlat?',answers:['Csak a vendég minősítését felírni','Tényeket, felelőst, határidőt és visszajelzési lépést rögzíteni','Szóban továbbadni és törölni'],correct:1,explanation:'A visszakövethető panaszkezelés objektív eseményadatot és felelős folyamatot igényel.',source_code:'SRC-NNGYK'},
 {id:'mgr-1',roles:['üzletvezető','uzletvezeto','szalonvezető','szalonvezeto','manager','location_manager'],topic:'Vezetés',q:'Mi blokkolja a biztonságos napzárást?',answers:['Nyitott, rendezetlen munkalap vagy pénzügyi esemény','Ha kevés vendég volt','Ha nincs marketingkampány'],correct:0,explanation:'A napzárás előtt minden üzleti eseménynek rendezett állapotba kell kerülnie.',source_code:'SRC-NAV'},
 {id:'mgr-2',roles:['üzletvezető','uzletvezeto','szalonvezető','szalonvezeto','manager','location_manager'],topic:'Vezetés',q:'Műszakátadásnál melyik eltérés kezelése megfelelő?',answers:['Csak szóban megemlíteni','Rögzíteni az eltérést, felelőst és határidőt','A következő műszakra hagyni információ nélkül'],correct:1,explanation:'A vezetői kontroll alapja a visszakövethetőség és egyértelmű felelősség.',source_code:'SRC-NNGYK'},
 {id:'cash-1',roles:['pénztáros','penztaros','recepciós','recepcios','üzletvezető','uzletvezeto'],topic:'Pénztár',q:'Mikor rögzíthető pénztármozgás szabályosan?',answers:['Nyitott pénztári műszakban, az eseményhez kapcsolva','Bármikor utólag','Csak hónap végén'],correct:0,explanation:'A pénztár és a bizonylati lánc visszakövethetősége nyitott műszakot és eseménykapcsolatot igényel.',source_code:'SRC-NAV'},
 {id:'wh-1',roles:['raktáros','raktaros','beszerző','beszerzo','üzletvezető','uzletvezeto'],topic:'Készlet',q:'Mit jelent a FEFO elv?',answers:['A legdrágább termék fogy először','A leghamarabb lejáró használható tétel fogy először','A legutóbb érkezett tétel fogy először'],correct:1,explanation:'FEFO: First Expired, First Out; a lejárati kockázatot csökkenti.',source_code:'SRC-NNGYK'},
];

export function normalizedRole(value:unknown){return String(value??'').trim().toLocaleLowerCase('hu-HU')}
export function isForRole(roles:string[],role:string){const r=normalizedRole(role);return roles.includes('all')||roles.some(x=>r.includes(normalizedRole(x)))}
export function materialsForRole(role:string){return knowledgeMaterials.filter(x=>isForRole(x.roles,role))}
export function questionsForRole(role:string){const specific=quizQuestions.filter(x=>isForRole(x.roles,role));return specific.length?specific:quizQuestions.filter(x=>x.roles.includes('all'))}
export function sourceMap(){return new Map(knowledgeSources.map(s=>[s.code,s]))}
